### ISSUE TITLE
the 5th assignment is due date

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#100]
the 5th assignment is due tomorrow not tonight right????
please say tomorrow

**Comment by willccoates** [comment]
i just see alot of pull request so its freaking me out

**Comment by DanTheTingler** [comment]
yep, it's due thursday, don't worry

**Comment by willccoates** [comment]
omg thank goodness lol i had a panic attack for a second haha

**Comment by rgosh001** [comment]
Hey guys, I sent my pull request like 15 minutes ago, did you guys get an email for that? I'm just trying to make sure I sent the pull request correctly instead of last minute lol

**Comment by willccoates** [comment]
it looks like its in the pull requests tab so i think its fine

**Comment by DanTheTingler** [comment]
I got the email, you're good bro

**Comment by rgosh001** [comment]
thanks homies (insert thumbs up sign here) lol
