### ISSUE TITLE
Running valgrind in script

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1008]
In our script should we do all our tests while running valgrind?
For example, calling "valgrind bin/rshell" and then doing all our tests with valgrind displaying the memory leak report at the end?

**Comment by M-Evans** [comment]
I believe the TAs will run valgrind and cppcheck on their own, so you do not need to put it in your script. That just clutters the script file.

**Comment by mikeizbicki** [comment]
@M-Evans is correct.
