### ISSUE TITLE
Spam?

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#101]
![screen shot 2014-08-27 at 9 41 25 pm](https://cloud.githubusercontent.com/assets/5942410/4071285/d1be4666-2e6d-11e4-937a-b55450c41e9e.png)
I'm assuming this is spam?... @mikeizbicki  @bmars003

**Comment by DanTheTingler** [comment]
SOMEONE'S TRYING TO INFILTRATE OUR CLASS!!!!

**Comment by rgosh001** [comment]
LOLOLOL all he did was erase everything in the README.md file and updated it with links. DEFINATELY spam, DONT OPEN IT! -___-

**Comment by willccoates** [comment]
thats so weird haha

**Comment by mikeizbicki** [comment]
You playing a practical joke on us Rashid?!

:)

**Comment by DanTheTingler** [comment]
All I can think of is the scene in The Walking Dead season finale where Rick says "They messed with the wrong people" right before the episode ends. If someone was trying to spam us, Mike would totally destroy him/her lol, no competition.

**Comment by rgosh001** [comment]
I would "neeeevvvveerr" haha

**Comment by kryne001** [comment]
YOOOO HAHAHA THIS WAS ME. I was doing this for the video I was making for doing pull requests on forked repositories

**Comment by mikeizbicki** [comment]
@kryne001 I like that you're trying to be fun with the username, but the name crosses the border of what's appropriate in a professional context.  If your submitted videos have this username in them, you will not get full points on the submissions.

**Comment by kryne001** [comment]
Yeah honestly it was not smart. It was only one video, and I'll redo that video.
