### ISSUE TITLE
question regarding grading script

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1010]
I think this is the correct place this time.

I noticed a while ago that even though some of these things can fail and take information from members of `struct stat` as arguments, they aren't included in the grading script. How do you typically figure what is a system call vs what isn't, especially when they use the results of system calls and require specific libraries?

Also is it appropriate to use `std::cerr` for things where `errno` is not set, as it doesn't seem to write to the same stream/buffer as `perror`.

In this case it was `asctime` and `local time`, both of which have documented behavior on failure.

`file: [lsnewcopy2.cpp]`
`lines with syscalls:`

`029: stat(name.c_str()`
`031: perror();`
`037: stat(name.c_str()`
`039: perror();`
`064: getgrgid(file.st_gid)`
`066: perror();`
`070: getpwuid(file.st_uid)`
`072: perror();`
`078: perror();`
`083: perror();`
`131: readdir(dir);`
`133: perror();`
`141: opendir(dir.c_str()`
`143: perror();`
`189: close = closedir(dirp)`
`191: perror();`

**Comment by mikeizbicki** [comment]
There are 10 different "sections" of the man pages, and each section refers to something different.  Section 2 corresponds to syscalls.  So, one way to check if a function `foo` is a syscall is to run the terminal command `man 2 foo`.  If it shows you the information about the function, then it was a syscall; if you get an error, then it wasn't a syscall.

`perror` and `cerr` both write to stderr, and are both appropriate ways to display error messages to the user.  You're correct that `perror` should only be used on functions that set the global `errno` variable.  For other functions, using `cerr` is one of many acceptable solutions.

**Comment by mikeizbicki** [comment]
Also, this was a good question that I'd like to give you some extra credit for.  But in order to get the credit you'll need to reformat the post using markdown syntax.
