### ISSUE TITLE
hw1 "LS" not graded

### ISSUE THREAD

**Issue by oribix** [mikeizbicki/ucr-cs100#1019]
I checked my grade and there is no number in the grade. calcgrade.sh does not show a grade for LS. I already talked to Busra but she was not in charge of my LS assignment.

**Comment by mikeizbicki** [comment]
@benavidz Can you look at this?

**Comment by ghost** [comment]
I graded your assignment at the same time as everyone else, but I was unable to upload your grade (I get a 403 error). Have you added me as a contributor to your repository?

**Comment by oribix** [comment]
It looks like I never did. I added you.
