### ISSUE TITLE
Hw4 submission

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1025]
If you are doing documentation the specs says to put your stuff in a folder called /textbook/yoursubject but in my case I am doing a cheatsheet and there is a folder in textbook that contains cheatsheets already so should I put my file in a new "yoursubject" folder or in the existing cheatsheet folder when I make my pull request?

Basically, should we put our documentation in a pre-existing folder if topics are related or regardless we should make a new "yoursubject" folder in textbook?

**Comment by mikeizbicki** [comment]
Please try to put your writeup in whatever subfolder of `textbook` is appropriate.  So in your case, it should be under `textbook/cheatsheet`.

**Comment by NisreenFarhoud** [comment]
Okay, thanks!

**Comment by svtanthony** [comment]
What if our hw4 is not related to the class materials but rather a standalone project?

**Comment by mikeizbicki** [comment]
@svtanthony then submit a github issue with a link to what I should be looking at.
