### ISSUE TITLE
A matter of a meeting

### ISSUE THREAD

**Issue by GitHubbubble** [mikeizbicki/ucr-cs100#1027]
Hey Mike, I'd like to talk about some of my goals for the class, and I'd like your help with my plan of action for the remainder. Do you have a time other than this Tuesday you could meet with me?

**Comment by mikeizbicki** [comment]
Would Friday morning at 9 work in WCH315?

**Comment by mikeizbicki** [comment]
Closing just because it's not relevant for everyone else to see.

**Comment by GitHubbubble** [comment]
30 minutes before the meetings? Sounds great! Thanks Mike.
