### ISSUE TITLE
Git Problems: Squashing Commits

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#1036]
I followed the tutorial in the textbook section of this repo for squashing commits. This is the second time I've tried to squash commits following the tutorial, and both times have ended poorly.

I can't seem to squash my commits, and now I get errors when I try any sort of squashing.

Do you have time after class Wednesday(today) to help me fix this so I can squash to one commit?

And would you still like me to create the pull request before class? I was planning on waiting until I get this all figured out.

Thanks!

**Comment by mikeizbicki** [comment]
Waiting until this gets fixed is fine.

I should have time to meet after class, although there are a couple of students already in line before you.
