### ISSUE TITLE
REDDIT POST AND STARRED 20 GIT REPOS

### ISSUE THREAD

**Issue by MichaelUy** [mikeizbicki/ucr-cs100#1046]
![Image of My Glory](http://i.imgur.com/b0z8SBx.png)

Hoho! I have starred 20 other githubs!

By the ancient rights of ucr-cs100 tradition, I have won +10 Extra Credit!
- I starred some C/C++ repos on r/coolgithubprojects mainly terminal games and C/C++ based utilities
- Shout out to @tristanzickovich , I found your slot machine game and starred it. 

Also, I got on the front page of r/programming with over 200 upvotes! 

![Image of My Other Glory](http://i.imgur.com/j0un2LC.png?1)

http://www.reddit.com/r/programming/comments/2x38gs/high_school_hackers_trick_men_on_tinder_into/
By the ancient rights of ucr-cs100 tradition, I have yet again, +10 Extra Credit!
- I mentored a High School Hackathon called HackGenY so I decided to post a article about the winners
- At the moment, I now have 497 upvotes and I'm a winner. Yeah

**Comment by mikeizbicki** [comment]
Ancient rites of ucr-cs100 tradition activated!  Unfortunately the rite of github stars only awards 5 pts extra credit, not 10, so you get +15 pts extra credit in total.
