### ISSUE TITLE
How to squash commits

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#1055]
I've gotten to the point where I know how to squash my commits for my fork, but how do I exit out of interactive?

**Comment by nevarez-emil** [comment]
Once you've picked the commit you're going to squash into, you can save it with ^O then exit with ^X. After you exit, the process will continue and you should be forced to choose a commit message to keep. Save your message and exit and your rebase should be done.

**Comment by mchu011** [comment]
It's still not exiting

**Comment by tristanzickovich** [comment]
git rebase --abort will exit interactive mode.  I don't know if it has other effects.  You should look it up

**Comment by mchu011** [comment]
gives out this:

Trailing garbage following expression

**Comment by nevarez-emil** [comment]
I can't see it for myself so I'm not sure what the issue is.

Are you getting the error after picking which commit to squash into? Or does the error come up after you select your commit message?

**Comment by nevarez-emil** [comment]
Either way, you can always abort and try again.

**Comment by mchu011** [comment]
every time I call git rebase  -i HEAD
the terminal changes to a format similar to when you just put 'git commit' into the commands

-it has the two black bars, one on top of the file and the other at the bottom file as it is automatically in insert mode
-pressing [Esc] and then :wq or any one of those kinds of commands leads to some type of call of Eval:, which just returns messages of debug

ps. I've already tried it again several times

**Comment by nevarez-emil** [comment]
You should be using 'bit rebase -i HEAD~x' where x is the number of commits
you want to squash. You can also use the log number instead of 'HEAD~x'

**Comment by mchu011** [comment]
Okay i got it now:
-"git rebase -i Head~x"
- change commits calls to pick, squash, etc.
- if can't exit through normal, open another terminal and type "git rebase --abort"
- check "git log" if files have squashed
- make a new "git commit -m "message" " for the squashed file
- git push and merge
