### ISSUE TITLE
Do you have time to meet this week?

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#1057]
Mike, 

I was not able to successfully squash my commits.  Do you have time Thursday between 12:35 and 5:00 or Friday between 1:00 and 2:00, or after 3:00 to meet up?

Thanks

**Comment by mikeizbicki** [comment]
Sorry I didn't see this earlier.  The only time I have available tomorrow is 8:30-9:00 AM.  If that doesn't work for you I can do Monday after/before class.

**Comment by tristanzickovich** [comment]
I'd prefer Monday. I can do before or after class, whichever works better
for you.

**Comment by mikeizbicki** [comment]
Let's do after class.  That'll be easier.
