### ISSUE TITLE
Feedback on HW5 README.md?

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#106]
Good Morning Mike, Bryan, and classmates,
I was wondering if you could give me feedback on my README.md file.(https://github.com/rgosh001/ucr-cs100/tree/master/assignments/hw/hw5-oss/tutorials/githubvim#11-learning-the-terminal-scripting)
It isn't 100% complete and I haven't inserted excerpts from Shawn's word document, BUT I want to know if I should change it to be 100% professional unlike my introduction statements or keep it appealing to those who are going to take cs100 (and other similar classes) in the future.
Also, if you have any idea's that'll really help it pop out more, i'd greatly appreciate it.
Thank you!

**Comment by mikeizbicki** [comment]
My comments:
- What you have so far is very _professional_; it's not _formal_, but it is professional.  Informal things are good.  I'd try to be a little less wordy though in the intro.
- If this is all comes together, I suspect you'll have a large audience (much bigger than future cs100 students) for this work.  You can mention this was put together to help people in cs100 at ucr, but don't spend more than a sentence on it.  Focus on the larger audience.
- Your titles are way off right now.  You should have one title using `#`, then under that, you should have a title for vim, git, and the terminal, each at level `##`; Under that will be each of your video/writeup titles with heading `###`.   Don't repeat the words vim/git in the subtitles; only provide new information in there.
- I think it would look nicer if titles are not numbered, but maybe not.
- VIM is never capitalized.  It is always written vim.  I don't care whether it's within backticks or not, but stay consistent everywhere.

**Comment by rgosh001** [comment]
Thank you Mike. I'll be making these changes in the morning.
Can you expand more on what you mean with our titles? because I don't understand what the `#` character does.
Thank you though, this is great stuff for us to use to improve our project!

**Comment by bmars003** [comment]
@rgosh001 What Mike is referring to with `#` is how to do header in the Markdown language. 

Here is a link you should take a look at https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers.

Hope this helps.

**Comment by rgosh001** [comment]
Ohhhh, got it. I looked at something similar to that on wiki but it said to use something else that didn't work. Thanks for the help!
