### ISSUE TITLE
question on ls assignment revision

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1066]
When printing text a certain color, how do we determine what to regard as "hidden"? Obviously hidden files begin with a dot, and even . and .. are normally hidden. What if something is within a hidden folder? Also would it be normal to print something as hidden if the path itself begins with a dot?

For example 

`./folder`  or `.afolder/anotherfolder:`

The colon is there because bash always prints a colon in its headings before displaying the folder contents with the exception of . and no -R flag.

**Comment by scohe001** [comment]
From the man page:
-    a_, *--all_
            do not ignore entries starting with .

**Comment by kavj** [comment]
Thanks but that doesn't actually indicate what should be printed on a grey background. There are a number of cases that seem strange, such as `ls -R .`   or  `ls -R .folder/folder`  . I was trying to figure out when things should actually be printed against a grey background.

**Comment by mikeizbicki** [comment]
A file should be colored as hidden only if the "base name" of the file begins with a `.`.  The base name is the filename without any leading directories.  See `man basename` for more details.

**Comment by kavj** [comment]
Thank you.
