### ISSUE TITLE
assignment 3 directory list

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1069]
Okay so I broke up the path list by colon separators. This list is returned.

`/usr/csshare/cs100/bin:/usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts:/opt/rh/devtoolset-2/root/usr/bin:/home/csmajs/kkamg001/bin:/usr/csshare/bin:/usr/csshare/sbin:/usr/bin/:/bin:/usr/local/bin:/usr/ucb:/sbin:/usr/sbin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:/usr/local/X11:/usr/local/bin/X11:/usr/openwin/bin:.`

Some work, but I thought these were all searchable. This is the full output with everything printed to screen. The ones that could not be opened are followed by an `opendir` error indicating they do not exist, yet they seem to be local to hammer. Using `cd` from the terminal to get to higher directories, `ls` with no arguments gives

`csmajs`
`bin  boot  cgroup  class  C:\nppdf32Log\debuglog.txt  dev  etc extra  home  lib  lib64  lost+found  media  misc  mnt  net  opt  proc  root  sbin  selinux  srv  sys  tmp  usr  var`

I don't have permission to search some of these such as `csmajs`, yet the subdirectories are there. The error returned also doesn't suggest it failed due to inadequate permissions,

`/usr/csshare/cs100/bin`
`/usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts`
`/opt/rh/devtoolset-2/root/usr/bin`
`/home/csmajs/kkamg001/bin`
`opendir: No such file or directory`
`/home/csmajs/kkamg001/bin`
`/usr/csshare/bin`
`/usr/csshare/sbin`
`opendir: No such file or directory`
`/usr/csshare/sbin`
`/usr/bin/`
`/bin`
`/usr/local/bin`
`/usr/ucb`
`opendir: No such file or directory`
`/usr/ucb`

Can anyone explain the reason for this? The man pages haven't been very helpful. I found a couple articles on the path variable, but they were also unhelpful with this specific issue.

This one appears later in the list, and also fails. Some of

**Comment by mikeizbicki** [comment]
I don't quite follow what you're asking.  It might help if you used codeblocks for the longer code segments (surround the whole thing by three backticks on each side; not each individual line).

I can tell you, however, that it is wrong to be calling `opendir` for any part of this assignment.  You are supposed to just construct the path, then call `execv` on the result.  Nothing else.
