### ISSUE TITLE
HW3 path lengths

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1071]
There is a defined limit in `limits.h` for maximum path length, but it doesn't seem to be entirely advisable. There is also a way to look up the required length via http://linux.die.net/man/3/realpath . Is this necessary here or can we assume a fixed limit? I've been using `std::string` as it dynamically allocates its own memory. It negates the use of a simple solution like `strtok` though. I normally hate `strtok`, but since the folders are only separated by colons, this alleviates having to use logic like `while(myString(index) < myString.length() && myString(index+1) != ':'){++index};`

Anyway I was wondering if this is feasible with statically allocated char arrays.

**Comment by mikeizbicki** [comment]
> There is a defined limit in limits.h for maximum path length, but it doesn't seem to be entirely advisable. 

Why do you say it is not advisable to use the predefined limit?

> There is also a way to look up the required length via http://linux.die.net/man/3/realpath 

I don't think `realpath` would help with this assignment.

> It negates the use of a simple solution like strtok though.

The naive use of `strtok` is almost certainly incorrect for this assignment.  Remember that the string returned by `getenv` is the actual string used to store the environment variable.  If you change that string, you change the value of the environment variable.  `strtok` will change this string on you while it parses, which will probably introduce hard to find bugs.
