### ISSUE TITLE
HW3 Part 3 Current Working Directory 

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#1072]
For part 3 we are asked to change our prompt to display the current working directory. 
Do you want this to replace our user and host name info before the "$" of the prompt, or can we output it above that as bash does?

**Comment by M-Evans** [comment]
I believe it's safe to assume that if the user can see the path after the execution of a command, that's all that is needed. Where it is actually printed is up to you.

**Comment by tristanzickovich** [comment]
@M-Evans  You're probably right. Thanks!

**Comment by mikeizbicki** [comment]
@M-Evans is correct.
