### ISSUE TITLE
HW3 and HW2 interaction

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1078]
Okay so do we need to handle the case of multiple processes with signal handling? If so is it a good idea to keep track of all child pids to kill them individually upon receiving `^C` or should I be looking for a way to kill all? I have most of assignment 3 written at this point, but I'm not sure what to do in that case.

**Comment by mikeizbicki** [comment]
This is a great edge case that you've thought of!  +3 pts extra credit.  

I believe that there's actually no need to do anything special to get `^C` to kill all of the processes.  It should automatically get sent to them all.  That said, there's no need to get this feature to work, and it won't be graded.
