### ISSUE TITLE
Showing ec hacker news post and starred repos

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1083]
![screen shot 2015-03-03 at 9 28 36 pm](https://cloud.githubusercontent.com/assets/5578936/6478706/b2bfc050-c1ed-11e4-87e2-21392ea9a949.png)
I starred over 20 repos that I found interesting in the explore section of github.

![screen shot 2015-03-03 at 9 26 20 pm](https://cloud.githubusercontent.com/assets/5578936/6478707/b2c18a0c-c1ed-11e4-932b-99659480be0d.png)
I submitted a post that received over 30 upvotes on hacker news.

**Comment by mikeizbicki** [comment]
Screenshots aren't proof because they're so easily faked :)  A link would be proof.  Give me the link and I'll give you the points.

**Comment by NisreenFarhoud** [comment]
Hacker News: https://news.ycombinator.com/item?id=9139307
Github profile: https://github.com/NisreenFarhoud

**Comment by NisreenFarhoud** [comment]
Unless I am logged in to the hacker news page, the link takes you to a `[dead]` page for that post for some reason but when I am logged in it takes me to the post. If that link doesn't work when you try it I will show it to you before/after class today.

**Comment by NisreenFarhoud** [comment]
If it's easier, I can also show you before/after lecture today.
