### ISSUE TITLE
getcwd vs. $PWD?

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#1088]
It seems to me that to find the current working directory for the prompt we could either call `getcwd` or use `getenv` to fetch the `PWD` environment variable storing the same information...is there any obvious reason to use one over the other?

I'm tempted to use `getenv` only because the memory for the string has already been allocated and we don't have to worry about the deallocation, whereas with `getcwd` to ensure we can handle any path length, we'll have to ask `getcwd` to allocate new memory for us.

Am I missing anything?

**Comment by mikeizbicki** [comment]
According to the [POSIX standard chapter 8](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html), the `PWD` environment variable always contains a valid absolute path to the present working directory.  This means that for most purposes, you can read from this environment variable instead of calling `getcwd`.  For situations where `PWD` and `getcwd` will behave differently, see [this stackoverflow post](http://stackoverflow.com/questions/10795014/pwd-vs-pwd-regarding-portability).

**Comment by mikeizbicki** [comment]
+3 points extra credit for a good question

**Comment by scohe001** [comment]
From the standard you linked:

> PWD
>    This variable shall represent an absolute pathname of the current working directory. It shall not contain any filename components of dot or dot-dot. **_The value is set by the cd utility.**_

After a quick test with this code:

```
char path[256];
getcwd(path, 256);
cout << path << endl;
cout << getenv("PWD") << endl;

cout << GREEN << uname << "@" << YELLOW << hostname << RESET << "$ ";
```

I get this output:

```
/Users/aricohen/Desktop/Dev/CS100/rshell
/Users/aricohen/Desktop/Dev/CS100/rshell
aricohen@Ace.local$ cd bin
/Users/aricohen/Desktop/Dev/CS100/rshell/bin
/Users/aricohen/Desktop/Dev/CS100/rshell
```

Suggesting that if we do end up using the `PWD` environment variable we'll have to be updating it in our `cd` function since the system will only help us on initialization. On the other hand, it seems `getcwd` requires no help from us.

If we do use `getcwd`, should we still update `PWD` for the assignment?

**Comment by mikeizbicki** [comment]
Whoops!  I misinterpreted the documentation I linked you.  I thought it was saying that a compliant version of `chdir` would automatically update `PWD`, but it was actually saying that a compliant shell must update `PWD`.  So if you want your shell to be POSIX compatible (not required for the assignment) then you have to update `PWD`.  Either way you do it, you must be printing out the value of whatever `getcwd` would give.  But it's fine to never explicitly call `getcwd` and only update the value of `PWD`.

**Comment by scohe001** [comment]
Cool, thank you so much!

**Comment by nevarez-emil** [comment]
PWD doesn't reflect any chdir calls you may make

Thanks,

Emil Nevarez
