### ISSUE TITLE
Reshow

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1091]
If we plan to reshow assignment 0, should we keep a version of our rshell that uses the system call `execvp` since the specs for that assignment say to use it? Or is it okay to show our updated rshell for assignment 3 that doesn't use `execvp`?

**Comment by mikeizbicki** [comment]
I just want to see your final shell and see that it has all the features of hw0.  No need to do any special refactoring.

**Comment by NisreenFarhoud** [comment]
Should we also make a new script for the reshow assignments or is there no need since we will be running the commands for you?

**Comment by mikeizbicki** [comment]
You should have a script file for me to look at.
