### ISSUE TITLE
Ascii escape char for cs100-utility

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#1093]
I seem to be an having issue with ctrl C. I can kill cat in normal rshell run with this, but not in the script. I'm using ctrl v, ctrl c right now.

**Comment by Fire3galaxy** [comment]
This is more info to help solve problem. I think that the end of text char isn't translating well from vim to execution. I executed ^C in a script without the utility and got this as an error:

```
./runTests/ctrlC.sh: line 3: : command not found
```

```
The shell script:
#! /bin/bash
#basic control C
^C
```

**Comment by M-Evans** [comment]
are you running `cs100-runtests` with `bin/rshell`?

e.g.

`cs100-runtests bin/rshell ./runTests/ctrlC.sh`

**Comment by Fire3galaxy** [comment]
Yes, but without the .sh extension. I added .sh and changed the file to see if it would work without the utility.

**Comment by M-Evans** [comment]
the end-of-text character must be on its own line. Is it?

**Comment by Fire3galaxy** [comment]
It is

**Comment by Fire3galaxy** [comment]
New update. Used it on bash, with no problem. Could be a problem with signals, but ctrl+c works in rshell when manual.

**Comment by M-Evans** [comment]
if you're redirecting, you'll get the `./runTests/ctrlC.sh: line 3: : command not found` error.
`cs100-runtests` does not send the end-of-text character to your executable. rather, it sees that the line in your test file only contains the end-of-text character and sends `SIGINT` to your executable. 

I suggest deleting all the end-of-text characters in your test file, and retyping them. Remember: they must be on their own line with nothing else. make sure you're in insert mode, then press `Ctrl+V` and `Ctrl+C`.

**Comment by M-Evans** [comment]
`cs100-runtests` doesn't work with bash... I think you're doing something wrong.

a good test case would be as follows:

``` bash
# cat will not stop until stdin is closed or it receives a
# signal to tell it to finish
cat
^C
# prints a message if it succeeded.
echo it worked
# if it didn't work, you'd be seeing double of everything.
```

**Comment by Fire3galaxy** [comment]
Your tutorial says that bash can be specified in place of bin/rshell. (hw0)
I copied your test case to a file and ran it in `cs100-runtests`, it did an infinite loop. Maybe the issue is sending the signal to my rshell? I set the child process to have the default signal handler, but maybe the new process in execv isn't getting the signal?

**Comment by M-Evans** [comment]
`bash` can be specified, but it may not do what you want it to. In its current state, `cs100-runtests` is able to send signals to `bash`, which it chooses to ignore. I'll be fixing this issue in the future.

If your test file is compliant with the standard I specified, I guarantee that `SIGINT` gets sent to `bin/rshell` when you tell it to get sent. 

Read the section for [hw0](https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/scripts/cs100-runtests#hw0) so you fully understand why your `rshell` did an infinite loop.

**Comment by Fire3galaxy** [comment]
I added `exit` to the end of my file, but it didn't see it because of `cat`. I added `cin.fail()` to my code though to stop it and that worked, but it shows that cat stopped the code from entering. Check this out:

```
/home/csmajs/dhand002/CS100/firstrepo/rshell $ cat

^C


echo it worked
echo it worked
exit
exit
/home/csmajs/dhand002/CS100/firstrepo/rshell $ 
```

Now that I think about it, if `cat` was still intercepting input, then `cin.fail()` couldn't have been reached because of `waitpid`. This is crazy weird.

**Comment by M-Evans** [comment]
did you run that yourself? not using `cs100-runtests`? In any case, it appears as if you don't have `SIGINT` handling finished.

**Comment by Fire3galaxy** [comment]
I used cs100-runtests. This works if I do it manually though.

**Comment by M-Evans** [comment]
what happens if you do this:

```
bin/rshell
cat
^C
exit
```

**Comment by Fire3galaxy** [comment]
Manually, this:

```
dhand002@cs100:~/CS100/firstrepo/rshell (path) $ bin/rshell
/home/csmajs/dhand002/CS100/firstrepo/rshell $ cat
^C
/home/csmajs/dhand002/CS100/firstrepo/rshell $ exit
dhand002@cs100:~/CS100/firstrepo/rshell (path) $ 
```

With cs100-runtests, this:

```
dhand002@cs100:~/CS100/firstrepo/rshell (path) $ cs100-runtests bin/rshell runTests/test 
*****************
* runTests/test *
*****************
================================================================================
/home/csmajs/dhand002/CS100/firstrepo/rshell $ cat

^C
exit
exit
/home/csmajs/dhand002/CS100/firstrepo/rshell $ 
================================================================================
dhand002@cs100:~/CS100/firstrepo/rshell (path) $ 
```

**Comment by M-Evans** [comment]
I just cloned the code from a previous student who got credit for properly handling `SIGINT`, and his `rshell` works perfectly for that case. I am convinced that it is a problem with your code.

**Comment by Fire3galaxy** [comment]
unfortunately, same here. I'm telling `SIGINT` to be handled with `SIG_DFL`, but...thanks though, man.
