### ISSUE TITLE
why cat ends with piping: theory

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#1096]
I think I get it now. When cat reads from stdin, it stops after getting a sigquit signal. So when piping, I should enter sigquit manually as the last char entered, maybe clear the write pipe before writing subequently, unless you like the idea of ps | a.out with a cin | a.out with another cin

**Comment by mikeizbicki** [comment]
There is no need to use signals to get piping to work correctly.
