### ISSUE TITLE
Install Linux

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1099]
How do we show you that we have Linux installed on a home computer(that can't be physically brought in) for the points?

**Comment by mikeizbicki** [comment]
You'll log in to a lab machine and ssh into your home computer.  So you have to setup ssh on it and (probably) adjust your internet router's settings to forward ssh connections to your desktop.

**Comment by NisreenFarhoud** [comment]
When is the latest we can show you this?

**Comment by mikeizbicki** [comment]
I'll have some office hours during finals week that you could show me.
