### ISSUE TITLE
Forked Repo is Bad?

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#110]
Hey guys,
My forked repo of the ucr-cs100 class is apparently 179 commits ahead of Mikes. Is there a way I can just overwrite everything in my forked repo to match @mikeizbicki 's repo? Thanks guys

**Comment by rgosh001** [comment]
FIXED IT :D
http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

**Comment by rgosh001** [comment]
oh no, it got rid of my grades Mike... Do you guys have a backup of them hopefully? I know my grades as of today too if that helps to correct them...

**Comment by mikeizbicki** [comment]
I've reset your grades from the backups I was keeping.  In the future, the correct git command to merge commits together is called `git rebase`.

**Comment by rgosh001** [comment]
Thank you so much Mike! You are the best, I was seriously about to cry if it came to the worst. Thank you!
