### ISSUE TITLE
Homework 4 deadline

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1102]
Your hw 4 is scheduled to be due this Friday.  I'm okay with granting extensions to the deadline in order to make the submissions as high quality as possible.  If you would like an extension, then you must: reply to this post with the reason you want the extension and the date that you will be submitting your assignment.  It's important that you reply here so that I can keep track of everyone's submissions.

**Comment by GitHubbubble** [comment]
I can garuntee a working solution for one parameter, but that doesn't seem very useful. I may have more but I'm not willing to make a claim. I would like to request an extension to expand what paramters my solution looks at. 

I'd really like to keep mining data until the last second possible, so it's hard to decide when to finish. I would like to ask what a reasonable deadline might be for my situation.

**Comment by mikeizbicki** [comment]
@wfink001 For your project, I'd probably need to meet with you sometime this week to see where exactly you're at to give you a good recommendation.

**Comment by ahvino** [comment]
Hello Mike,
I'd like an extension on my GDB video tutorial...I'm attaching a link to my first rough draft and would like feedback as to whether or not this is good. This is 1 of 4 videos. Each video will go more in depth and explore more features and tools and each will be about 4-5 minutes. I noticed a few mistakes in narration and will correct them as I go but I'd like to know if you had any suggestions/  recommendations in the mean time.

Thanks,
https://www.youtube.com/watch?v=JsOwAFf-cRM&feature=youtu.be

**Comment by ahvino** [comment]
I edited the recursive factorial function but other than that, is this heading in the right direction?

**Comment by tristanzickovich** [comment]
I would like an extension to Wednesday the 18th. I have some fixing up to do on my tutorial, and I have a quiz and early finals upcoming that I would like to study for.

I plan on submitting another draft soon to make sure my revisions are heading in the right direction. I have some more squashing problems to figure out before I can do so.

**Comment by plusEight** [comment]
cfan002
muy003
yli006
wlee001

Our group would like an extension for our Sensors project to Tuesday the 18th.

So far we have been able to successfully read from a temperature sensor and send that data to the internet and get it graphed. Now we are working on getting multiple sensors(at least two) to display their data. 

I discussed the documentation with you during the assignment reshow and we both agreed that our documentation needed to be two-fold, a step-by-step intuitive guide for those who want to follow along our project and through in-depth explanation of what we did and its applications. 

Documenting all that we have done is probably the biggest reason for our need of an extension. Reading from sensors and uploading data (and analyzing/graphing) has been a "learn-as-we-go" experience for all of us. Since our documentation includes a step-by-step procedure on how to recreate our project, we want to make sure we can explain the coding process (which is done with Squirrel) as clearly as we can. We ourselves have spent a lot of time familiarizing our self with Squirrel and we still feel we need a better understanding of it to explain ourselves to anyone recreating our project.

Here is our current schedule for the upcoming days
`Thurs '12` -- Be able to get two live-updating graphs of our sensors
`Friday '12` -- Feature these graphs on our own website(we have already found a method to embed these graphs)
`Saturday` -- Troubleshoot any extra issues regarding webhosting or the actual sensor
`Sunday thru Monday` -- Finish documentation.

**Comment by Laviness** [comment]
group: yliu127
           jwang096
I would like an extension to Thursday 19th for the following reasons: 
1. I need to take an IELTS test this weekend so I will spend most time on that until Sunday. Besides, I have a final on Wednesday.
2.We didn't write a lot of documents in English of this style before, so we may need more time to get several reviews and discuss the writing style with you.
For the progress now, we have done about  3/4 of the content and are going to add more examples.

**Comment by admiralakbar** [comment]
I would like to request an extension to Wednesday the 18th. I have finals on Friday, Monday, and Tuesday morning. I'd like to use the extra time to include a more extensive look into bash functions and how to save them rather than just aliases.

**Comment by M-Evans** [comment]
I'm requesting an extension to finish `cs100-runtests` after my finals on Saturday and Monday. I'll turn it in by Wednesday the 18th.

**Comment by mchu011** [comment]
I'm requesting to extend my deadline to Friday, March 20, because I will be making a new draft, recording commentary with a friend, making my remaining videos and double checking their timings, and doing the extra credit webpage between studying for finals

**Comment by mikeizbicki** [comment]
@antonvinod You pacing and tone is good.  I like the layout of your windows in the screen and how you're using them.  Your font is too small though for people to read.  You'll need to make it bigger.  You have a lot of blank space on the screen that's being wasted.  There's also a lot of static in the sound that makes it hard to hear you.  That will definitely need to be fixed somehow.

Don't spell out the gdb website website.  Anytime you are saying verbatim text out loud, you should be typing it as well.  For example, when you say "compile using g++ with the -g flag", you should be typing in the actual command so that people can see it.   Overall, your intro takes a bit too long.  It should be no more than 15 seconds before you start showing people code/commands that they can use.  

You don't "enable the gdb debugger" when you compile.  The -g flag adds DWARF symbols into the executable file (you should look this up, but probably shouldn't go into detail on it).  All debugging tools use these symbols, not just gdb.  

You should always be talking when you're typing.  If it's too much for the viewer, they can always pause/rewind.  But if the viewer gets bored for even a split second, they'll switch to a different tab and you've lost them forever.

Never say "right here".  The view doesn't know what you're talking about.  Instead, say "Look at my cursor in the middle of the right hand terminal" to give the viewer context.

You mention the `l` command, but then you don't mention that the `1` shows the code at line 1.  You mention breakpoints without explaining what they are.  

`n` does not "go to the next function"; it goes to the next line.

You can't have any mistakes where you type something like `w` instead of `watch`.  Your final video must be perfect.  You need to explicitly mention that all of these single letter commands are explicitly shortcuts for their longer versions.

`watch` is a relatively advanced command, and so probably shouldn't be in the intro video.  I recommend the first video be about tracking down segfaults in gdb.  This is obviously useful without any explaining context, and you don't have to introduce too many commands to do it.  You also need to have a bit more focus to your video.  In this video, you just used a bunch of gdb commands together, but you should have an explicit purpose.  For example: "In this video, we'll learn how to use gdb to find the causes of segfaults."  Or "In this video, we'll learn how to use the step, next, and print commands to track down a logic error in a simple factorial function".  Or "In this video, we'll learn how to use the breakpoint and continue commands to speed up the process of tracking down a logic error.

@tristanzickovich approved

@plusEight approved, but I highly recommend you have some progress to show me on Friday so that I can give you feedback

@Laviness approved

@admiralakbar approved

@M-Evans approved

@mchu011 I will need to see a draft video by Friday, similar to the one @antonvinod posted, so that I can give you feedback first

**Comment by svtanthony** [comment]
I would like to request an extension of homework 4 due this Friday to next
Wednesday. The writing center staff will be at Orbach Library this Sunday
from 5:00 pm till 9:00 pm to help students with their writing. This would
help making my project more readable and hopefully more popular.

**Comment by shawnjzlee** [comment]
[slee208](http://github.com/shawnjzlee), [athio001](http://github.com/AndyThio)

[BrightTime project](https://github.com/Team-Unguided/unguided_packages_apps_brighttime)

We would like an extension to Friday, March 20th. 

We have finished a prototype that does the function we set out to do - to set a custom brightness level automatically by a user-preset time-of-day. But, our UI and code is messy and does not meet up to [Google's design guidelines](http://www.google.com/design/spec/material-design/introduction.html). 

We would like to use the extra time to:
- create a finer UI, following the [Material design guidelines](http://www.google.com/design/spec/material-design/introduction.html)
- Documentation overhaul that includes demo and analysis of `Adaptive Brightness` vs. our `Timed Brightness`.
- Implement feature that allows editing existing "points".
- Send through Gerrit Code Review, either with [AOSP](https://android-review.googlesource.com/#/q/status:open), [AOSPA](https://gerrit.paranoidandroid.co/#/q/status:open), or [CM](http://review.cyanogenmod.org/#/q/status:open,n,z).
- Become more familiarized with Android SDK and JDK

We also hope to meet with you in person to show you the prototype, talk about documentation, etc. 

Thank you.

**Comment by SpaceCowboy100** [comment]
I'd like an extension to after my finals are over. I can turn in my final Makefile tutorial by Wednesday the 18th

**Comment by ahvino** [comment]
I didn't explicitly state a date for completion but I would like to have an extension up until March 20th. I will use this time to redo the previos video and implement and design new cases. I will have have 2-3 videos ready for review by Sunday March 15th. From here on, I am going to be using github for submitting the videos instead of youtube until I get a final ok from you. Then I'll publish on youtube. I am providing a link to the project folder below.  Most of the video files will be in .OGV but I believe you will have no problem viewing them. When they are ready to publish, I'll convert to .AVI in order to publish to youtube.

https://github.com/antonvinod/hw4

**Comment by NisreenFarhoud** [comment]
I will have a new complete draft to submit this Monday for my cheatsheet, but I will like to extend the deadline for my final submission to Friday which will allow time for us to go back and forth enough on the draft to perfect it.

**Comment by Dongdongshe** [comment]
dshe001
rapache
I would like to extend the deadline for next Monday, right now I am working on fix the bug we have talked about and more time is needed to write the document.

**Comment by nevarez-emil** [comment]
Hi Mike,

I'd like to request an extension until Monday,   because I  have my final project due tomorrow for a separate class and I won't have time to work  on this project.

**Comment by vgarc018** [comment]
Hello,
We (Virgilio and Chelsey) would like an extension for our hw4 so we can work on the feedback you gave us today. And so we can take our write up to the writing center stuff that is going to be at the Orbach Library Sunday. We can have everything done and ready by Tuesday 3/17/15.

Thank you Very much

**Comment by MiaoXiao** [comment]
Hello, we would like to extend it to next Friday, March 20th.

Stanley, Sherina, and I are working on the music game, which you can play here:
https://github.com/MiaoXiao/CS100-Music-Game-

We want to make the web page look nicer with better visual indicators on how well the player is doing. We are also working on a statistics page that will track the player's progress. We can also implement different instruments and different scales that the player can use.

Thanks!

**Comment by shinray** [comment]
ok, so we have most of the work done for our project, but we're reviewing it for correctness and quality. It's possible this may take longer than we have, and I have finals tomorrow. If the worst comes, may we be considered for an extension?

https://www.youtube.com/watch?v=tDMjNPKQJP8
https://www.youtube.com/watch?v=GFo1Oo42Rv0
https://www.youtube.com/watch?v=2-pIsY7iq10
some of the videos we're making

https://github.com/shinray/UNIX-Signals/

We can finish by wednesday at the latest, most likely today or sunday though. the extra time would really help us improve the quality of our submission

**Comment by mchu011** [comment]
Here's one of the videos I have so far:

https://www.youtube.com/watch?v=eq835QBxN4o

And my project goals would be to focused on stirring interest in the topic in people with short attention spans by first, showing a short, engaging video that will stir up the viewer's interest and then providing relevant information for the user to delve into the details on the topic.

**Comment by oribix** [comment]
Considering that I was never able to show you a draft due to not knowing how to squash, I hope its fine with you that i continue to work with you.

**Comment by jduga002** [comment]
Hello,

I would like a homework extension like we discussed at office hours last Tuesday. I have already pushed what I've made so far to `gitlearn` for you to take a look at.

I would like to use the extra time to:
1. Add more formatting to the website, via a css page.
2. Add support for creating a password and signing in to see your grade
3. Perhaps, if I have time, add a page for instructors to sign into to view all students' grades and perhaps even grade assignments.

Since I have finals coming up next week, I would like an extension to Friday to finish the website.

**Comment by Fire3galaxy** [comment]
Hi Mike, would it be possible to ask for an extension for the syscall cheatsheet? I need more time to finish the latex formatting and look over the tool you mentioned to ensure I have all the necessary syscalls. I can reasonably finish by Sunday at the latest

**Comment by kavj** [comment]
Hi Mike, I could just use more time. I've put some work into getting it together. I worked on it earlier today, and I'll post something preliminary by tomorrow.

**Comment by mikeizbicki** [comment]
@svtanthony Please send me an issue as you complete each video so I can make sure they're progressing in the right direction.

@shawnjzlee You have until Wednesday.  I'll give you some feedback at that point, and then you'll have until Friday to respond to the feedback.  I don't want you to wait until Friday and then have no time to respond to whatever feedback I have.

@SpaceCowboy100 approved

@eneva002 approved

@vgarc018 approved

@MiaoXiao Have a preliminary submission ready for me by Wednesday so I can give you feedback.  Also, you'll probably be in the realm of extra credit possibilities, and I'll want to see that you've contacted people in the music department in order to be eligible for any extra credit.

@NisreenFarhoud approved

@shinray There's feedback on your pull request

@mchu011 In your first pull request #1068, I had some comments on your video idea that it doesn't look like you took into account.  I'm still not clear on exactly what your video ideas are, so maybe we should talk in person about it.

@oribix Yes, that's fine.  There's feedback on your pull request.

@jduga002 Try to have at least some of the pull requests in by Wednesday if possible.  Break it up into whatever seems like logical chunks to you.

@Fire3galaxy I've left comments on your pull request.

@kavj Can you get me a rough draft (very rough is okay) by Monday night?

**Comment by shawnjzlee** [comment]
Hi @mikeizbicki , 
 Thank you for the response, [@AndyThio](http://github.com/AndyThio) and I plan to meet with you tomorrow during your office hours for initial feedback for our project. We will follow your timeline according to your comment above as well. Thank you.

**Comment by nevarez-emil** [comment]
Hi @mikeizbicki,

I'd like to request another extension until this Friday.

I'm having a hard time debugging the socket communication with the daemon and I'm spread thin on time  between work and studying for finals.

**Comment by mikeizbicki** [comment]
@eneva002 Let's do Wednesday instead.  You haven't shown me anything yet, so I'm pretty sure I'm going to have a lot of changes you'll need to fix.  And then you'll have until Friday to make those changes.

**Comment by ahvino** [comment]
Hello Mike,
I've done 3 videos so far. I would like feedback on the content specifically. I plan on still redoing them once I get the ok on the content and presentation. I still have a few things i need to fix(currently, keyboard strokes are pretty loud). I would also like any other feedback/recommendations you might have and to inform you that I believe there will be a total of 5 videos.  I will have the other 2 videos by Wednesday and can make edits and until Friday. 
I am providing a link to the videos below. They need to be downloaded but once I get the ok, I will publish them to youtube and add the links described in the video...I'd also like to know what's the best score I can get for the videos...Thank you.

Intro
https://github.com/antonvinod/hw4/blob/master/gdb_intro.ogv

Breakpoints
https://github.com/antonvinod/hw4/blob/master/gdb_breakpoint.ogv

Segfaults
https://github.com/antonvinod/hw4/blob/master/gdb_segfault.ogv

**Comment by jsun031** [comment]
Hi Mike,

I have my draft here under my repository forked from our class https://github.com/jsun031/ucr-cs100/tree/hwk4/textbook/assignment-help/sort. And I have not pull request to your repository. Could you give me some advice to improve my work?

Thank you!

**Comment by mchu011** [comment]
Hey Mike, 

you said you wanted to see what the other videos are like:

https://www.youtube.com/watch?v=Y3Iky0GF1y0

I'm currently trying to complete the last parts of my final video, but it seems that I would exceed my estimated deadline by 6 hours or so...

Could I change my extension to Saturday? Also, do I get the extra credit for going to the writing center for my 2nd draft paper? (I cut out the excess information after the final office hour, but the corrections are still there)

**Comment by mikeizbicki** [comment]
@mchu011 Yes, you can extend to tomorrow.  And yes, you will get the
writing center extra credit.
