### ISSUE TITLE
HW3 Grade Incorrect

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#1116]
I believe my `rshell` has been misgraded. Zachary Benavides authored my grade file.

My grade file: [link](https://github.com/M-Evans/ucr-cs100/blob/grades/assignments/hw/hw3-signals/grade)

My test file: [link](https://github.com/M-Evans/rshell/blob/signals/tests/signals.script)

Things I believe are incorrect:

1) the total doesn't reflect the extra credit I earned
2) I executed a program in the current working directory (test file lines [13](https://github.com/M-Evans/rshell/blob/signals/tests/signals.script#L13), [122](https://github.com/M-Evans/rshell/blob/signals/tests/signals.script#L122), [226](https://github.com/M-Evans/rshell/blob/signals/tests/signals.script#L226), and [241](https://github.com/M-Evans/rshell/blob/signals/tests/signals.script#L241)) (grade file issue [line 4](https://github.com/M-Evans/ucr-cs100/blob/grades/assignments/hw/hw3-signals/grade#L4))

**Comment by ghost** [comment]
The first error was an oversight, I've adjusted your grade accordingly.

As for the second point you mentioned, at each of those lines you are entering the command "bin/rshell". This is not executing a program in the current directory, it is executing a program in the bin subdirectory of the current directory. I was looking for a command of the form "rshell" or "./rshell" when inside the bin directory, for instance.

**Comment by M-Evans** [comment]
what's the difference? It's still a relative path to an executable.

**Comment by ghost** [comment]
The item on the rubric reads:
    "Execute a program in the working directory."
The program that you executed on each of those lines does not reside in what was at that point the working directory. It was not a test of your shell's ability to handle relative paths. Specifying the absolute path to an executable in the current working directory would have been acceptable as well.
