### ISSUE TITLE
HW3 graded incorrect

### ISSUE THREAD

**Issue by Laviness** [mikeizbicki/ucr-cs100#1117]
What I believe are incorrect:
1.

grade file:
[5/10] Execute a program not in the working directory.
        Running ps works, but running ls gives an error when it shouldn't.

```
    [rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell$ ls
    error in execv: No such file or directory
[0/10] Execute a program using an absolute path.
```

test file:
[rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell$ which ls
[rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell$ ls
error in execv: No such file or directory
[rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell$ cd bin
[rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell/bin$ ls
ls          rshell
[rshell]Elvis@Lius-MacBook-Air.local:~/Documents/UCR/CS-100/rshell/bin$ ./ls
ls          rshell

1) I use 'which' ls to show I have already deleted 'ls' in /bin to show that my rshell can work well on 'ls' in the current directory.
2) I use './ls' to test the absolute route for a program. In my program, if a path start with '.' ,it runs directly the argument I passed with out add $PATH in front.
1. I want to know the details about the segmentation fault, if it comes with ^z which I didn't finish, I believe that shouldn't be counted.

**Comment by Laviness** [comment]
@benavidz

**Comment by ghost** [comment]
Your intention with that series of commands was unclear to me when I graded your assignment, but makes perfect sense now. I've adjusted your grade appropriately in that respect.

As for the segmentation fault, it came first when I tried to run your program under Valgrind. I also tried running it uninstrumented (not under Valgrind), and it still throws the segmentation fault. I was not attempting to use ^Z, only to start your shell. The last thing I tried was running your shell on hammer, but I couldn't clone your repository onto the server (disk space concerns, I think). If your shell does not do this in your testing environment, please come demonstrate that for me in office hours this week.

**Comment by Laviness** [comment]
Thanks! It works when I ssh to hammer and see you in the office hour.
