### ISSUE TITLE
Linux system + EC opportunities

### ISSUE THREAD

**Issue by linuxmotion** [mikeizbicki/ucr-cs100#1121]
I have my linux system to show as well as the website ec. My website thelinuxmotion.org is hosted on my personal linux server at my house. This website was not designed as a portfolio website but originally as a place for guides and information about linux related things. My personal information in te website is here <a href="http://www.thelinuxmotion.org/?q=John">John</a>

**Comment by mikeizbicki** [comment]
We should talk in person after class tomorrow.  As is, the site doesn't meet the requirements for the extra credit.
