### ISSUE TITLE
starring repos

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1126]
I was looking for repositories that should to star, yet I'm not sure of a reliable way to tell when I've located the "master" repository rather than someone else's fork. Sometimes it's obvious, but that isn't always the case. Is there a good way to identify this?

**Comment by jduga002** [comment]
If the repository has been forked, then under the name of the repo, it will say "forked from such-and-such." You can then click that link to see the "master" repo.
