### ISSUE TITLE
I'd like to change my hw4 topic

### ISSUE THREAD

**Issue by admiralakbar** [mikeizbicki/ucr-cs100#1136]
I was going to do write up on cool things you can do with fbcmd, but it has stopped working because facebook updated their site, and the owner of the repo is no longer updating it. I have been trying to update it myself, but it is in php and I don't know much php. I'd like to change topics to aliases and bash functions, because I found them very useful this quarter and I think many other students would also find them useful.

This is little bit of my first paragraph:
Have you ever opened up your terminal and typed in `cd /home/user/Desktop/folder/yawn/omg/this_is_way_too_long_an_address`? Well what if I told you `$open_it` could do the same thing? Now before you call me crazy and ship me off to the loony bin, let me introduce you to the magical world of alias and shell functions. Bash allows us to create custom shortcuts through the use of aliases and shell functions Aliases are by far the easier, yet more limited method, so we will go over them first. Simply enter `$ alias open_it=cd /home/user/Desktop/folder/like_a_boss/never_again` and all we will have to do to execute this long command again is `$open_it`

**Comment by mikeizbicki** [comment]
This is a fine topic to write about.  I don't want you to do your own writeup though, I would rather you add to this existing one: https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/using-bash/shell-scripts  You are free to make any modifications you think would be helpful to the content that is already there, and you should build off that content to discuss functions.  For this topic, you will also need to discus POSIX compliance.  Bash has a number of features in functions that are not available in other shells, and you should point out what those features are (e.g. local variables and certain syntaxes).

I also have a comment on the writing style of your paragraph.  It's too fluffy.  You need to get to the point fast.
