### ISSUE TITLE
Writing Style Checker

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#1137]
Hello everyone! Are you having difficulty writing well? Check out [this writing style checker](http://www.hemingwayapp.com/)! It's free, and does a remarkable job. I recommend it if you'd like people to better understand what you're trying to explain to them.

**Comment by mikeizbicki** [comment]
This looks like a great tool!  +3 pts extra credit.

This would make an excellent vim plugin.  It would get tons of users (as in possibly tens of thousands), and I'll offer 200 points of extra credit if anyone can make it (smaller amounts for partial progress).  You'll have to find the library this program uses or a similar library.  They're called natural language processing (NLP) libraries.  Then connect it to vim.  Depending on how the library works, you might require the latest version of vim called neovim (http://neovim.org) to make it work.

If anyone can find similar vim plugins, then I'll offer some small amount of extra credit depending on how useful they would be for writing documentation.

**Comment by M-Evans** [comment]
I'm interested in attempting to make it. I've never made a vim plugin before, and have never done natural language processing. I would like to learn those things, however. I'll need until the weekend before I commit to this project. Until then, I'm too busy to figure out precisely how much work this project will need. (of course I'd work on it after finishing `cs100-runtests`)

I took a look at the javascript used to make the magic happen on the site, and it's been **heavily** obfuscated. It seems that any solution to the NLP problem like theirs would have to be created from scratch and without help from that site.

**Comment by mikeizbicki** [comment]
It is standard practice to compress the html/css/javascript on websites so that it looks obfuscated.  The purpose is to compress the files to conserve bandwidth, not to make it harder for people to read.  I'll bet they have a technical description somewhere.  If you can't find it, send an email to the webmasters and you'll probably get a response.  Beginning programmers are usually much more shy about contacting other developers than you need to be.  People like it when you ask about their creations!

**Comment by M-Evans** [comment]
The javascript file ends in "-obf.js" :smile: 

[Link to the file](http://www.hemingwayapp.com/js/hemingway-doubleup-obf.js). Doesn't even look like real javascript to me! I think their tool is free to use, but not free as in freedom. 

I'll definitely send an email their way, though!

**Comment by Anthony1234567** [comment]
I too would like a crack at this vim plugin challenge. That is if I am not already too late to call.

**Comment by mikeizbicki** [comment]
No calling dibs on this one.  This seems like it'll be a pretty hard task, so it'll be best to work together and pool ideas.

**Comment by GitHubbubble** [comment]
Sounds fun! I could start a repo (or someone else could) so anyone intrested in the project could fork it up.
