### ISSUE TITLE
Calcgrade.sh

### ISSUE THREAD

**Issue by vgarc018** [mikeizbicki/ucr-cs100#1140]
I spoke to you about how the calcgrade script is taking my score of hw2 and putting it in the total portion of that assignment. I wanted to remind you, as you told me on monday, see if this can be fixed or what the problem could be?

Thank you Very much.

**Comment by mikeizbicki** [comment]
I'm sorry I haven't had a chance to look into this yet.  I should have time tomorrow.

**Comment by mikeizbicki** [comment]
I spent a while trying to figure out the underlying problem, but couldn't figure it out.  I gave up with that.  Just now, I regraded the assignment manually so that it shows up correctly now.
