### ISSUE TITLE
Hw #4,

### ISSUE THREAD

**Issue by ikim025** [mikeizbicki/ucr-cs100#1143]
My group's first draft was full of errors and we have fixed our information on it;
We added 
- general overview of the signals such as ^C ^Z etc
- signal handler functions signal() and sigaction()
- kill()

Is there any suggestion that we should add further?

**Comment by mikeizbicki** [comment]
I would need to see an actual draft to provide feedback.

**Comment by shinray** [comment]
would you like us to talk about sigaction()? We haven't really used it much, but according to the man page signal() is deprecated and we should use sigaction instead.

**Comment by mikeizbicki** [comment]
I can't say without seeing everything else you have.
