### ISSUE TITLE
Zachary Office Hours

### ISSUE THREAD

**Issue by admiralakbar** [mikeizbicki/ucr-cs100#1150]
Hey I wanted to come by your office hours to demo lab, but I have class from 1-2 today. Are you free any other time today, or should I show it to the other TA?

**Comment by ghost** [comment]
You can come after your class. 

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by admiralakbar** [comment]
yeah i can be there at 2:10.
