### ISSUE TITLE
Git Errors

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#1151]
I ran into a bunch of the same problems as last time when trying to squash.
The TA's were not able to help me fix these problems during office hours. 

I want to submit another draft for my HW4 for review.  
I tried similar things to what you walked me through last time for fixing my git issues but had no luck, everything seems to be messed up (even tried the hard reset a couple times).
Is there another way I can submit a draft in the meanwhile?
And can I meet up with you to get this figured out?
I'll be heading out of town late afternoon on Tuesday. I want to get it resolved before I head home so I can submit my final submission correctly. 

Thanks

**Comment by mikeizbicki** [comment]
There's no other way I can easily give you feedback.  Do office hours tomorrow work?
