### ISSUE TITLE
assignment 4 ctrl z

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#116]
can anyone give me some hints as to how that could be done?
@kryne001 could you send me our lab that we did on signal handling? i cant seen to find the email 
thank you!

**Comment by bmars003** [comment]
Try looking at these along with going over lab 6 again http://www.yolinux.com/TUTORIALS/C++Signals.html this one too http://www.cs.kent.edu/~farrell/sp/lectures/signals.html .

**Comment by kryne001** [comment]
look up my email address in your inbox: kylerrynear@gmail.com

**Comment by kryne001** [comment]
if you can't find it i'll look it up again

**Comment by willccoates** [comment]
Oh I was looking for your ucr one lol, il look tomorrow! Thanks! And thank you Bryan Il look into it tomorrow!

**Comment by willccoates** [comment]
@kryne001 im sorry to bug but i can not find the email :/

**Comment by kryne001** [comment]
damn i'm sorry i just saw this. hold on lemme email it to you

**Comment by kryne001** [comment]
#include <iostream>
#include <sys/types.h>
#include <stdio.h>
#include <unistd.h>
#include <signal.h>
using namespace std;

int one = 0;
int two = 0;
int three = 0;
void printC(int x) {

   cout << "c" << endl;
   ++one;
   cout << flush;
}

void printBackslash(int x) {
   string temp = "\";
   cout << temp << endl;
   ++two;
   cout << flush;
}

void printS (int signum) {
   cout << "s" << endl;
   ++three;
   if (three == 3) {
      cout << "^C: " << one << endl;
      cout << "^\:" << two << endl;
      cout << "^Z:" << three << endl;
      exit(0);
   }  
   pid_t x;
   x = getpid();
   kill(x, SIGSTOP);
}
void handle_signals() {

   while(1) {
      cout << "x" << endl;
      sleep(1);
      if (SIG_ERR == signal(SIGINT, printC)) 
         perror("sigint failed");

```
  if (SIG_ERR == signal(SIGQUIT, printBackslash))
     perror("sigterm failed");

  if (SIG_ERR == signal(SIGTSTP, printS)) 
     perror("sigstop failed");
```

   }   

}

int main() {

   handle_signals();
   return 0;
}

**Comment by willccoates** [comment]
No worries, thanks!
