### ISSUE TITLE
HW4: Sensor Project **update**

### ISSUE THREAD

**Issue by plusEight** [mikeizbicki/ucr-cs100#1170]
@mikeizbicki 
cfan002
muy003
yli066
wlee030

We apologies for the unresponsiveness of our updates.  Our progress has stagnated over the course of the last several days as many of our core members had finals or 120b projects due. Since then we have resumed production on project and we have much to show and recieve criticism on.

Firstly we have updated our Github repository with a bare-bone README.md. Our group differed greatly on writing style and we had much debate over the proper style of documentation. Either way, we will gratefully accept suggestions.
https://github.com/MichaelUy627/SensorsToInternet

Secondly, we successfuly read readings from two sensors on the same board. We are planning to fill out our Squirrel code with comments to guide the reader with the coding process that we struggled with so much.

Lastly, we have a demo website running, with embedded graphs to show that we have succesfully uploaded and are able to present this data on the internet.
http://cpingfan.wix.com/cs100sensors

On a side note, we would ask you to graciously give us just a little bit more time to work on this project. We would like an extension on to Friday to finish up Documentation and Coding and act accordingly to your feedback.

**Comment by mikeizbicki** [comment]
Looking at your README, I honestly have no idea what, exactly, your repo does.  There's a lot of words, and I'm sure it says it there somewhere, but I can't find it.  You need to simplify that down a LOT.  I issued a pull request with some comments.

Try to have another draft for me to look at some time tomorrow.  I suspect it will help a lot if we talk in person during office hours as well.
