### ISSUE TITLE
HW4 Update: BrightTime App Development

### ISSUE THREAD

**Issue by shawnjzlee** [mikeizbicki/ucr-cs100#1172]
Hi @mikeizbicki,
 Thank you for the valuable feedback yesterday afternoon. We have completed a preliminary update on our repository [here](https://github.com/Team-Unguided/unguided_packages_apps_brighttime). Before we visit on Wednesday, we'd like to know if there's more we should add or polish up. 

Thank you,
[@shawnjzlee](http://github.com/shawnjzlee), [@AndyThio](http://github.com/AndyThio)

**Comment by mikeizbicki** [comment]
I REALLY like that gif!  Awesome job!  

I've created a pull request that cleans up your README file a bit.  There's still some work to do on it.  For example: 
1. Those screenshots you have would be better if they were just the screen, without all of the other stuff in it.
2. You need to change the name of your repo.
3. There's a lot of files in your repo's root folder that don't seem like they should be there.
4. The writing could use some more editing still.
5. You'll want to make sure the download link is in a place where you can easily track the number of downloads.

**Comment by shawnjzlee** [comment]
Hi @mikeizbicki,
 After visiting you at your office hours on Thursday, we have updated the readme for better readability. Please let us know how it is now. Thank you.

[@shawnjzlee](http://github.com/shawnjzlee), [@AndyThio](http://github.com/AndyThio)
