### ISSUE TITLE
Hwk4 draft

### ISSUE THREAD

**Issue by jsun031** [mikeizbicki/ucr-cs100#1176]
Hi Mike,

I have my draft here under my repository forked from our class https://github.com/jsun031/ucr-cs100/tree/hwk4/textbook/assignment-help/sort. And I have not pull request to your repository. Could you give me some advice to improve my work?

Thank you!

**Comment by mikeizbicki** [comment]
You'll need to issue a pull request for me to give detailed feedback.  Make sure you review issue #1028 first.
