### ISSUE TITLE
Hw4: Sensors Project Update

### ISSUE THREAD

**Issue by plusEight** [mikeizbicki/ucr-cs100#1181]
@mikeizbicki 
Our README and repository underwent many changes. We would like your feedback.

https://github.com/MichaelUy627/SensorsToInternet

**Comment by mikeizbicki** [comment]
It's a good improvement, but it still needs better focus and cohesion.  It strikes me as several unrelated projects that have been strapped together.  I think we should talk in person.  Can everyone from your group meet tomorrow during office hours?
