### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#1193]
My goal was to show you my Linux installation tomorrow at office hours but I haven't been able to get it to work. I have been working on it all week but it still doesn't seem to want to cooperate. Is there any other way that I can make up these Linux points? My overall grade is currently borderline so any points will be helpful. Thanks!

**Comment by tristanzickovich** [comment]
20 / 25 points for a virtual machine Linux installation.

Virtual Machine is much easier.

Virtual Box:
https://www.virtualbox.org/wiki/Downloads

Walk through for Virtual Box on Windows:
http://www.instructables.com/id/How-to-make-a-virtual-machine-of-Linux-on-Windows--2/
