### ISSUE TITLE
hw 4 gdb tutorial

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#1221]
https://github.com/antonvinod/GDB_videos

I am not sure if you had time to look at the repo I posted along with the links but I included the cpp file there as well (I hope that's ok). I'd also like any recommendations on the repo itself but I am still working on the videos and making the changes you suggested. I am hoping the complete repo with new videos will be ready by 4pm today. I will have the videos available on youtube as well as on my repo but I'm a little unclear as to whether I submit a link to my repo or am I just submitting the videos. Any clarification would help

**Comment by mikeizbicki** [comment]
When you're ready to submit it, it won't be able to be in its own repo.  It'll have to be as a pull request to this repo.  Also, you don't need to put the Author section.  The git repo tracks that for us automatically.  Otherwise, it looks good.
