### ISSUE TITLE
pull requests

### ISSUE THREAD

**Issue by kavj** [mikeizbicki/ucr-cs100#1226]
For whatever reason I can't seem to make a pull request from my repository. Any ideas?

**Comment by mikeizbicki** [comment]
You'll have to give me a better description of the error messages you're getting for me to help.

**Comment by kavj** [comment]
I'm not getting an error message. I think it worked just now. Before it either tried to merge to my forked repo or it just didn't bring up any highlighted "create pull request" option on the site.
