### ISSUE TITLE
EC 

### ISSUE THREAD

**Issue by Wurmie** [mikeizbicki/ucr-cs100#1228]
I have starred 20 repos: https://github.com/Wurmie
and I have made my own website. I'm not sure what I was suppose to put on there so any feedback would be appreciated.

website: wurmie.webs.com

**Comment by mikeizbicki** [comment]
To be eligible for extra credit, you'll need to:
- have your own domain
- remove the chart at the bottom of the main page
- include titles of your projects
- remove pages that don't have content
- make your writing a bit less verbose

This will be worth a very small amount of extra credit, so there are probably more time efficient ways of getting last minute points.  Of course, you should do all the things I mentioned above at some point to help your career get started.
