### ISSUE TITLE
test cases

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#123]
anyone have any idea on how to come up with over a hundred test cases? do we just redo commands we have already done but with different files or what? I am confused by this

**Comment by bmars003** [comment]
First thing of some obvious test cases, do those. Then try to test the extreme bounds, then try to think of test cases that might break your code.

**Comment by willccoates** [comment]
so should we include the test cases that break our code or no? because i have some cases that break my code but i do not know how to fix them

**Comment by willccoates** [comment]
like for the LS part of rshell, i cant think of anymore test cases besides the obvious simple ones and putting files as the argument
