### ISSUE TITLE
Assignment 5 Due Date

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#124]
Hello Mike,

Does Kyler and I have to schedule a time to meet with you tomorrow or do we just have to have it in before midnight tomorrow?

Thank you

**Comment by rgosh001** [comment]
Actually, can we schedule a time tomorrow? Anytime will do. I just need to show you that my unix install is complete and working.

**Comment by mikeizbicki** [comment]
Let's do 12:30 tomorrow.  Make sure you have your final pull request done before then.

**Comment by rgosh001** [comment]
Understood. Thank you Mike.
