### ISSUE TITLE
video sample (remade)

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#1246]
Adjusted volume output on the video, no guarantees that it would work, but couldn't you have just turned up your computer volume settings? 

https://www.youtube.com/watch?v=kwTZVAnKfFg&feature=youtu.be

**Comment by mikeizbicki** [comment]
I had my volume turned as loud as it would go :)
- I don't think you actually say anywhere what getcwd does.  You just describe how to use it.  The descriptions of the functions would be better if you showed actual code examples.  
- The video's volume gets really quiet again towards the end.
- I like the fun ending :)
