### ISSUE TITLE
Nyphai Hw4 

### ISSUE THREAD

**Issue by MichaelUy** [mikeizbicki/ucr-cs100#1247]
This is our final product with all the problems you pointed out yesterday, and more revising.
In accord with your suggested revisions, we made edits to our README and our three Guides regarding markdown, style, grammar, and spelling. 

Our Net IDs are: wlee030, cfan002, muy003, yli066.

Our final product: https://github.com/MichaelUy627/NYMPHAI

**Comment by mikeizbicki** [comment]
I've updated your grades.  

I still think you're going to have trouble sharing this as-is, but that with a little bit of work on the presentation you could make it top notch.
