### ISSUE TITLE
hw 4 gdb tutorial

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#1257]
Here is a link to the updated segfault video. If it's ok, I'll go ahead and add it.

https://www.youtube.com/watch?v=vcVmWbYEIsk&feature=youtu.be

This is 1 of 3 videos all of which will be about the same length(7-8 mins). 
The second video will go over a few other commands and the third will be debugging with fork.
Is there anything in particular that you are looking for in the other two videos?

**Comment by mikeizbicki** [comment]
I've accepted and commented on your pull request.
