### ISSUE TITLE
Extra Credit - Quine-McCluskey-Gui

### ISSUE THREAD

**Issue by svtanthony** [mikeizbicki/ucr-cs100#1262]
Hello again.

Here is a link to a Boolean Expression optimization tool I created. The README now incorporates your suggested changes. The imagemagick program helped a lot with creating a readable gif. Thanks

https://github.com/svtanthony/Quine-McCluskey-gui

**Comment by mikeizbicki** [comment]
You need more text in your intro section besides just one sentence.  For example, what does it mean to minimize a boolean function?  Why would we want to do that?  You should also link to the relevant wikipedia articles.  This is also where you say what platform it runs on.

Your examples section can't just be a gif.  It needs a brief sentence explaining why that gif is relevant.

Your installation instructions need to be the exact commands I need to run, not a description of those commands.

**Comment by svtanthony** [comment]
Added brief description of minimization with a link to Wikipedia with in depth details, Also added a description of the gif to add clarity. Added table to help visualize the difference between an minimized vs non-minimized function. Finally added clear installation instructions. 

Thanks for the input.
