### ISSUE TITLE
Broken links to ESR's book

### ISSUE THREAD

**Issue by srufe001** [mikeizbicki/ucr-cs100#1289]
The links in ucr-cs100/README.md for ESR's book do not take you to the book. However, if I change the "ESR" in the url to "esr" it take me to the correct page.
Example: "http://www.catb.org/ESR/writings/taoup/html/context.html" to "http://www.catb.org/esr/writings/taoup/html/context.html"

EDIT: I submitted a pull request that changes the links

**Comment by mikeizbicki** [comment]
Thanks again.  Awesome job!  

In the future, just make either an issue or pull request but never both.
