### ISSUE TITLE
Gitlearn and cs100 grade calculating

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1376]
When I ssh into hammer and type in cs100 it states that calcgrade.sh should print my grade. When I type this I get the following error:

running installed gitlearn: /usr/csshare/cs100/src/ucr-cs100/
user=jdixo001
$1=
awk: cmd. line:1: fatal: cannot open file `people/students/jdixo001' for reading (No such file or directory)
 ERROR: student jdixo001 does not have attribute name in their studentinfo file
finding grade for  (jdixo001)

Is this because I don't have grades in or does it have to do with the following git learn commands and me having not running them yet:
$ git clone https://github.com/mikeizbicki/gitlearn
$ export PATH=$(pwd)/scripts:$PATH

Also what is meant by PATH, and when I run this command do I run it when I am ssh into hammer or not? Thanks.

**Comment by mikeizbicki** [comment]
Everything should work now.  There were a few students who hadn't yet finished lab1, and this was breaking things.

**Comment by ColdNightHour** [comment]
Alright I tried running it now and it says access denied. Is this normal?

**Comment by mikeizbicki** [comment]
I need you to report the exact error message in order for me to fix it.  Please put the message in backticks so that it gets displayed correctly using markdown.

**Comment by ColdNightHour** [comment]
This is the error message that is processed:
`bash: /usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: Permission denied`

**Comment by mikeizbicki** [comment]
Should be fixed now.

Thanks for reporting this.  I've given you +5 pts extra credit.

**Comment by ColdNightHour** [comment]
Thanks a lot!

**Comment by ColdNightHour** [comment]
I apologize for bothering, but another error like thing occurred. I'll post it in markdown but it's really really long.

**Comment by ColdNightHour** [comment]
```
/usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: line 55: pad: command not found
fatal: Not a git repository (or any parent up to mount point /home/csmajs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
fatal: Not a git repository (or any parent up to mount point /home/csmajs)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: line 60: isGraded: command not found
/usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: line 63: getOutOf: command not found
```

But the error is far larger and seems to be repeating itself

**Comment by ColdNightHour** [comment]
And it now worked properly. Though none of the grades are up for me.

**Comment by mikeizbicki** [comment]
I've fixed the issue.  In the future, please report the whole error message (even if it's thousands of lines; by computer science standards, that's still not long).  Also, it's better to use verbatim blocks (three backticks).  I've edited your message above so you can see exactly what it looks like.  Click the edit button to see the source.

**Comment by ColdNightHour** [comment]
Thank you very much.

**Comment by mikeizbicki** [comment]
This is a known bug.  Run it one more time and it should work.

Once we've covered a bit more about how these scripts work, you'll be able to earn extra credit for fixing bugs like this in them.
