### ISSUE TITLE
g++ version, c++11, and cs100 command

### ISSUE THREAD

**Issue by avere001** [mikeizbicki/ucr-cs100#1378]
1) Which version of g++ of the compiler will be used to compile our code? Will it be 4.4.7 (before typing cs100) or 4.8.2 (after typing cs100). 

2) Are we allowed to use c++11?

3) Should we use the cs100 command even while working from home? Or is this command only for use in lab?

**Comment by mikeizbicki** [comment]
1. We will do everything after running the cs100 command.
2. You may use any version of C++ you want as long as it is supported.
3. You should run `cs100` every time you login to hammer.

**Comment by avere001** [comment]
Thanks!

**Comment by mikeizbicki** [comment]
I'm reopening this so that everyone can easily see the answers.
