### ISSUE TITLE
Your quiz grades are all updated and posted

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1379]
Also, if you've gotten extra credit for submitting pull requests to the class repo, that's been posted too.

Login to hammer and run the `calcgrade.sh` command to view your grades.  You may have to run it twice for the grades to refresh.  We'll talk about how your grades are stored in more detail on Monday.

**Comment by ColdNightHour** [comment]
There is a permission denied warning when I run it.
`bash: /usr/csshare/cs100/src/ucr-cs100/gitlearn/scripts/calcgrade.sh: Permission denied`
