### ISSUE TITLE
HW0 bash commands

### ISSUE THREAD

**Issue by tortas** [mikeizbicki/ucr-cs100#1380]
In our shell, do we need to be responsible for all of the commands available in /bin? Or, only the ones we have been using so far in class (i.e. `pwd, ls, echo`)? Also, should input redirection be supported?

In the hw README it says we should be able to handle the command `$ ls -a; echo hello && mkdir test || echo world; cd test` but then later it says that we will be implementing cd in a later homework.

**Comment by mikeizbicki** [comment]
Your shell should be able to handle any command in `/bin`.  I could even create my own program that you don't know about and put it in `/bin` to test your code.

Including `cd` in that example was an error.  I've updated the example.
