### ISSUE TITLE
Handling errno

### ISSUE THREAD

**Issue by avere001** [mikeizbicki/ucr-cs100#1382]
What types of errors from exec are we expected to handle? When I `man errno` there's a huge list of possible errors to handle. Are we expected to handle all of them?

**Comment by mikeizbicki** [comment]
Yes, you must be able to handle all of them.  But if you use the `perror` function to print your error message (as you're required to), this will happen for you automatically.

**Comment by avere001** [comment]
Thank you. I must have missed that part.
