### ISSUE TITLE
Connectors

### ISSUE THREAD

**Issue by ykamo001** [mikeizbicki/ucr-cs100#1385]
Lets say the user enters in the command: A && B && C || X && Y where each letter is some command like "ls -a" or "mkdir folder". Suppose A and B are both successful, but C fails. I was wondering whether X or Y would be executed or not, and under what circumstances. I tried to break up the command as such: (A && B && C) || (X && Y), but I'm not sure if this is the right way to group/order them, or how the success/failure of A, B, or C would affect the rest.

**Comment by mikeizbicki** [comment]
This is something not in the specifications, so you get to decide how to handle it.  The way you suggest sounds fine.  But there are other alternatives (like left to right order) that would be equally fine.  Just make sure that whatever you choose, you document it in your README.

Also, in the future you should put all code in backticks so it displays like: `A && B && C || X && Y`.
