### ISSUE TITLE
hw0-rshell: gibberish code popping up

### ISSUE THREAD

**Issue by mchen046** [mikeizbicki/ucr-cs100#1387]
I accidentally ran `make` while in the a.out executable. Now every time execvp successfully runs, a block of gibberish code shows. How can I fix this? I restarted my computer and ran `reset` in the terminal, to no avail.

**Comment by mikeizbicki** [comment]
Sorry, but I don't understand what you're asking.  Can you post the exact sequence of commands you run and their output?

**Comment by mchen046** [comment]
![gibberish](https://cloud.githubusercontent.com/assets/5588203/7152748/2536d528-e2f6-11e4-833f-72726ac2d4d0.png)

I first run `ls -a; echo hello`, then `exit`. `cmdArray` and `cmdLine` are just variables I outputted. The gibberish code seems to appear when execvp is run

**Comment by mikeizbicki** [comment]
I suspect that the gibberish is not actually related to calling `execvp`.  For example, you shouldn't be calling `execvp` when you run the `exit` command.

**Comment by mchen046** [comment]
It's actually a problem with new code that I added. Thanks!
