### ISSUE TITLE
compiling in C++ 11 with all the flags

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1389]
I used the tokenizer method and when ever I try to compile, I get errors saying that I can't use auto as an iterator to iterate through the command prompt, is there a reason why, c++ 11 is suppose to support auto.

**Comment by Kilenaitor** [comment]
-ansi tag means no C++11

**Comment by hkwan003** [comment]
~~so then i'm not suppose to use c++ 11?~~

**Comment by Kilenaitor** [comment]
~~Correct.~~

**Comment by mikeizbicki** [comment]
You can replace the `-ansi` flag with a language standard of your choice.  C++11 is fine.
