### ISSUE TITLE
git cloning on well

### ISSUE THREAD

**Issue by tglen002** [mikeizbicki/ucr-cs100#139]
I am trying to clone my rshell git project onto well and it responds to the command with:
tglen002@well $ git clone  http://github.com/tglen002/rshell.git
Cloning into 'rshell'...

And then nothing. I am able to control c and end the command. On both my laptop and desktop (one unix and one linux) they were both able to clone my git directory. This is the first technical difficulty I have had with the CS computers, who should I contact (systems@cs.ucr.edu)?

**Comment by mikeizbicki** [comment]
We will be covering git in detail in class today. I recommend you wait until afterward and see if your question gets answered.

**Comment by tkimva** [comment]
You can come to my office hour next Tuesday or Prof. Izbicki office hour today. Or you can also ask this after our lab on Monday
