### ISSUE TITLE
ssh issue

### ISSUE THREAD

**Issue by Renee7547** [mikeizbicki/ucr-cs100#1393]
I ran ssh dlei004@hammer.cs.ucr.edu as usual,
But then the prompt is -bash-4.1$ rather than hammer$
I don't know why this happened.
![screenshot from 2015-04-15 21 39 59](https://cloud.githubusercontent.com/assets/9004759/7174172/11a4fc52-e3b8-11e4-92f1-4f21b9419475.png)

**Comment by mikeizbicki** [comment]
Sorry, but I don't understand what the problem is.  Can you elaborate?

**Comment by Renee7547** [comment]
When I ssh dlei004@hammer.cs.ucr.edu, I cannot login to hammer. The prompt is -bash-4.1$, while it is supposed to be hammer$. And in this case, I cannot run "cs100" command.

**Comment by busrac** [comment]
Did you recently change anything on your account settings? You can email systems@cs.ucr.edu and ask them about your problem.

**Comment by Renee7547** [comment]
Thank you. This issue happened after the last lab "fork" while I don't know what I did.
Because I cannot ssh to my own account, I used the account of my friend with which I pushed my files. Is that OK?
