### ISSUE TITLE
Leaking memory

### ISSUE THREAD

**Issue by divyanshch** [mikeizbicki/ucr-cs100#1396]
When running valgrind should we be trying to fix the memory leaking that is listed as "possibly lost" or "still reachable"? If yes, what would be the best method to find and free that memory. 

I have been reading some articles and they have said that "still reachable" memory is okay since those pointers don't cause any problem that a actual memory leak would cause.

**Comment by mikeizbicki** [comment]
We haven't discussed valgrind in class yet, so there is no need to use it for this assignment.  In future assignments it's only the `definitely lost` category that we'll care about.
