### ISSUE TITLE
getlogin() returns NULL while running script

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1397]
`getlogin()` works fine when I do `./a.out` by itself, but when I run `script` and then `./a.out`,  `getlogin()` fails to return the login name until I exit the script in which case it works fine again.

**Comment by mikeizbicki** [comment]
In order for me to help, you need to provide enough information for me to reproduce the problem.  In this case, that means giving the specific set of instructions that you run.

**Comment by mikeizbicki** [comment]
Also, it is always wrong to be using `a.out` to run your code.  Why aren't you calling `make` and then running `bin/rshell`?

**Comment by kevdev158** [comment]
I didn't really understand how to compile it with the makefile and the flags until just now. I got it working now though, but I have to use `getpwuid()` instead of `getlogin()`.

**Comment by Renee7547** [comment]
I have encountered the same problem as yours!!! And then I switched to use other's computer, it just went well. It seems that script can make many things different from the real running process!
