### ISSUE TITLE
Pushing issue

### ISSUE THREAD

**Issue by dtran049** [mikeizbicki/ucr-cs100#1409]
When I tried to push my exec branch or master branch to my rshell repository I get errors saying : 
error: src refspec exec matches more than one.
error: failed to push some refs to 'https://github.com/dtran049/rshell/'

What does this mean and what should I do to fix this?

**Comment by mikeizbicki** [comment]
In order to get help, you need to provide the exact sequence of commands you typed in and the exact output.
