### ISSUE TITLE
hw0-rshell: a failed successful execution

### ISSUE THREAD

**Issue by mchen046** [mikeizbicki/ucr-cs100#1410]
Let's say I have a directory where `test` does not exist, and I call `execvp` with the commands `rmdir test`. `execvp` succeeds, but `rmdir test` should be considered a failure in this scenario. I found this page on stackoverflow: http://stackoverflow.com/questions/13710003/execvp-fork-how-to-catch-unsuccessful-executions that describes my problem. I've tried tinkering with pipes but I am still confused on how to utilize pipes correctly. Could someone please elaborate on this?

**Comment by mikeizbicki** [comment]
Using `pipe` is actually incorrect in this case.  You want to use the `wait` syscall and the `status` parameter.  In particular, take a look at the `WIFEXITED` macro.

**Comment by mikeizbicki** [comment]
In case it wasn't clear, all the information is in `wait`'s manpage.
