### ISSUE TITLE
in script, I can not compile -std=c++ 11

### ISSUE THREAD

**Issue by ycao006** [mikeizbicki/ucr-cs100#1424]
Hello, guys: when I run script, I can not compile -std=c++11 it says it is not recognized

it works nor. sorry for the disturb

**Comment by mikeizbicki** [comment]
You should not be compiling from within your script.  Only test your program.

**Comment by ghost** [comment]
How do I run script before I run my program? I compile first, run my program, then type in script exec.script , it seems to take me out of my program and runs script by bash? I see my hostname change from cs100 to hammer.cs.ucr.edu. If I exit my script, my program will continue.
On second thought, do you start script, cd into your rshell folder then run bash/rshell and then do tests?

**Comment by busrac** [comment]
You should start the script on rshell folder (the main folder) and then run bin/shell, then do the tests.
