### ISSUE TITLE
Script issue

### ISSUE THREAD

**Issue by yyao007** [mikeizbicki/ucr-cs100#1426]
Hi all,
I have a question about script. Can I add comments by vim to my exec.script because I haven't added any comments when I run script. After that, my script will look like this:

 30 # this is the test for ls
 31 yyao007@hammer.cs.ucr.edu $ ls^M
 32 bin  LICENSE  Makefile  README.md  src  tests^M
 33 yyao007@hammer.cs.ucr.edu $ pwd^M
 34 /home/csmajs/yyao007/cs100/rshell^M

I wrote line 30 by myself. Am I allowed to do that?

Another question, there are many garbage messages in the script file, and sometimes my commands aren't recorded correctly. Does it matter?

Thanks!

**Comment by mikeizbicki** [comment]
You should not be editing your script file after you create it.  If you forgot to include comments, you need to rerun script from the beginning and include the comments that way.  Editing manually, you are very likely to introduce bugs that will get you minus points.
