### ISSUE TITLE
Uploading to GitHub

### ISSUE THREAD

**Issue by donei003** [mikeizbicki/ucr-cs100#1427]
Hello, I have been searching everywhere and haven't gotten any answer. How do I post a local repository to GitHub. As in GitHub has nothing named rshell prior to uploading. 

This is what I've tried:
git remote add origin https://github.com/donei003/rshell.git
git push origin master

That doesn't work and I get an error saying:
To https://github.com/donei003/rshell.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/donei003/rshell.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by kluu006** [comment]
Hello, you should try creating a new repository on github itself. Then clone the repository onto your computer after initializing a directory. For the same directory, move all your folders/files you want to push onto git into the directory. At this point, all you have is a master branch. You could create a new branch for exec itself. Aside from that, git push origin master will put everything onto git.

**Comment by busrac** [comment]
Did you make multiple commits before pushing? You can take a look at the suggestions here:
http://stackoverflow.com/questions/11696295/rejected-master-master-non-fast-forward

**Comment by ghost** [comment]
Even though its not recommended you can use the following command: git push -f origin to update your repo.
