### ISSUE TITLE
Openning hbhairy-utils.tar.xz on mac

### ISSUE THREAD

**Issue by isadoramariamendes** [mikeizbicki/ucr-cs100#1440]
Hello,
I am trying to download the lab from yesterday to take a look again and I just can't extract the file. I downloaded the xz-utils and still not working. I use mac os x. Any idea on how to solve it?
It always say "unxz: hbhairy-utils.tar.xz: File format not recognized"
Thanks.

**Comment by avere001** [comment]
Did you download it from the fall 2014 branch? The file in this quarters branch appears to be some kind of HTML document.

**Comment by isadoramariamendes** [comment]
Yes, I downloaded from fall 2014. It's really weird. =/

**Comment by mikeizbicki** [comment]
It's possible that MacOS just doesn't come with the necessary decompression software.  But since you didn't actually tell us the command you used or the output, it's impossible for me to tell.

**Comment by isadoramariamendes** [comment]
I tried this:

```
mobilenet3-4-240-177:Desktop isadoramaria$ unxz hbhairy-utils.tar.xz
unxz: hbhairy-utils.tar.xz: File format not recognized
mobilenet3-4-240-177:Desktop isadoramaria$ 
```

**Comment by mikeizbicki** [comment]
The correct command is `tar -xf filename` to decompress a tar archive.
Internally, `tar` is going to use the `xz` decompression algorithm.  It
looks like based on your error message, however, that you did not properly
install the `xz-utils` package.  I'm not sure how to do that on a mac, so I
can't help you with that.  I recommend going to stackoverflow and asking
there for more help.

**Comment by isadoramariamendes** [comment]
I tried this command and didn't work, happened this...

```
mobilenet3-4-240-177:~ isadoramaria$ tar -xf hbhairy-utils.tar.xz
tar: Error opening archive: Failed to open 'hbhairy-utils.tar.xz'
```

So I installed the xz... I nothing...

```
mobilenet3-4-240-177:Desktop isadoramaria$ xz --help
Usage: xz [OPTION]... [FILE]...
Compress or decompress FILEs in the .xz format.

  -z, --compress      force compression
  -d, --decompress    force decompression
  -t, --test          test compressed file integrity
  -l, --list          list information about .xz files
  -k, --keep          keep (don't delete) input files
  -f, --force         force overwrite of output file and (de)compress links
  -c, --stdout        write to standard output and don't delete input files
  -0 ... -9           compression preset; default is 6; take compressor *and*
                      decompressor memory usage into account before using 7-9!
  -e, --extreme       try to improve compression ratio by using more CPU time;
                      does not affect decompressor memory requirements
  -q, --quiet         suppress warnings; specify twice to suppress errors too
  -v, --verbose       be verbose; specify twice for even more verbose
  -h, --help          display this short help and exit
  -H, --long-help     display the long help (lists also the advanced options)
  -V, --version       display the version number and exit

With no FILE, or when FILE is -, read standard input.

Report bugs to <lasse.collin@tukaani.org> (in English or Finnish).
XZ Utils home page: <http://tukaani.org/xz/>
mobilenet3-4-240-177:Desktop isadoramaria$ xz -d hbhairy-utils.tar.xz
xz: hbhairy-utils.tar.xz: File format not recognized
```

I'll post there so. Thank you!
