### ISSUE TITLE
Reading EC

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1445]
Hi, I was planning on doing a reading for some EC and I've found a pretty interesting book - "Paradigms of Artificial Intelligence Programming: Case Studies in Common Lisp." I've ordered the book already, but from some of the reviews that I've read, some said it was complicated whereas others said it was a good introduction to LISP, AI, and provides a new approach to programming. Are there any other simpler (if this is too difficult) recommended readings for similar topics and would this be considered for EC?

**Comment by mikeizbicki** [comment]
I doubt I would offer extra credit for that book in particular, but we would have to talk in person about it.

**Comment by zzhou007** [comment]
Can I get extra credit for reading "Structure and Interpretation of Computer Programs" or "Intellectual Property and Open Source: A Practical Guide to Protecting Code"

**Comment by mikeizbicki** [comment]
No for SICP.  Possibly for the other if you show it to me in person.
