### ISSUE TITLE
Hw 1

### ISSUE THREAD

**Issue by zzhou007** [mikeizbicki/ucr-cs100#1448]
Do we combine the ls program with rshell so when you call ls in rshell it calls your ls program or is it a seperate program called ls where you only test the ls command?
Also for the ls program will ls be part of the input of just the flags?

**Comment by mikeizbicki** [comment]
> Do we combine the ls program with rshell so when you call ls in rshell it calls your ls program or is it a seperate program called ls where you only test the ls command?

You do not have to make any changes to the rshell executable for this assignment.  Your ls program is completely separate.  It just happens to be in the same repository and created with the same Makefile.

> Also for the ls program will ls be part of the input of just the flags?

Your ls program should behave exactly like the built-in GNU ls program.
