### ISSUE TITLE
hw0 grade

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1450]
I received a 0/100 on my hw0 because it did not compile, but I've been able to git clone - git checkout - make hundreds of times without issue.

**Comment by mikeizbicki** [comment]
It's certainly possible we made a mistake while grading.  You should visit @busrac during her office hours to work this out.  We'll also be discussing the grades in class tomorrow.

**Comment by htang014** [comment]
Upon closer inspection it appears im missing unistd.h, and asking around everyone else cant compile my code either.  As it turns out I had forgotten to enable cs100 settings whenever I logged into hammer, so it compiled fine without unistd.h.  Adding unistd.h fixes everything.  Am I screwed for the course?
