### ISSUE TITLE
hw0 update

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1452]
Upon closer inspection it appears im missing unistd.h, and asking around everyone else cant compile my code either. As it turns out I had forgotten to enable cs100 settings whenever I logged into hammer, so it compiled fine without unistd.h. Adding unistd.h fixes everything. Am I screwed for the course?

**Comment by mikeizbicki** [comment]
There's no need to panic.  Just wait until tomorrow when we discuss the grades in class.  If you have questions after that, then talk to me after class.
