### ISSUE TITLE
Executing ls

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1454]
How should ls be executed? 
`./ls [parameters]` ( or `bin/ls [parameters]` ) where the parameters are taken in as command line arguments

or...

`./ls`  ( or `bin/ls` ) then get input for `ls [parameters]` where we run the executable and then do the `ls` stuff

**Comment by mikeizbicki** [comment]
I don't understand the difference between the two cases... but your ls program should behave exactly like the built-in GNU ls.
