### ISSUE TITLE
HW1 Exceptions 

### ISSUE THREAD

**Issue by fvera002** [mikeizbicki/ucr-cs100#1458]
When running this command `ls -l -a cmd.h test1 abc` on lab, I get this return: 

```
ls: cannot access abc: No such file or directory
-rw-r--r-- 1 fvera002 csmajs 4558 Apr 24 17:38 cmd.h

test1:
total 0
drwxr-xr-x 3 fvera002 csmajs  80 Apr 27 21:11 .
drwxr-xr-x 4 fvera002 csmajs 300 Apr 28 16:34 ..
-rw-r--r-- 1 fvera002 csmajs   0 Apr 27 21:11 t1.cpp
drwxr-xr-x 2 fvera002 csmajs  60 Apr 27 21:12 test1-1
```

But when using my ls program, I get this: 
`There was an error with stat(): No such file or directory`

It happens because I always call `exit(1)` after any `perror`. Is this correct? Or should I keep running even after a syscall fails?

**Comment by mikeizbicki** [comment]
You do not have to call `exit` after `perror`.  You should only do it in situations where the error means you actually _cannot_ keep going no matter what.  That is often the case with syscalls, but you've pointed out a great counterexample.  It's actually _wrong_ to call `exit` in this case.

**Comment by kevdev158** [comment]
Would there be a test case for using `-laR ~`? When I try running it, I'm unable to open some directories (permission denied for `.dbus`) or some weird files like `SingletonLock`, but I can access normal files/directories. In cases like these, should I simply skip them or stop the program altogether?

**Comment by mikeizbicki** [comment]
@ktang012 
1.  `~` is not a feature I'm expecting your shell to handle.  This is something that bash does automatically called "globbing" that we'll talk about in more detail later.
2.  You ls should behave similarly to the built-in ls on those files with weird permissions.
