### ISSUE TITLE
HW1 Permissions

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1461]
Besides the IFDIR permission, what other permissions were we supposed to account for again?
Also for time, are we supposed to use time like it is used here in the stat man page? http://linux.die.net/man/3/stat

**Comment by mikeizbicki** [comment]
1.  You do not need to check FIFOs or sockets.  It's not any harder, we just haven't gone over what those types of files are or where to find them.
2. I don't understand your question about time.  You're free to use whatever libraries you want, you just need to get the output into a human readable form.

**Comment by ghost** [comment]
1. Then the only ones we need to account for are: DIR, CHR, BLK, LNK?

**Comment by mikeizbicki** [comment]
Yes, plus of course regular files.

**Comment by mikeizbicki** [comment]
Reopening so that it's easier for everyone else to see.
