### ISSUE TITLE
Formatting ls output

### ISSUE THREAD

**Issue by avere001** [mikeizbicki/ucr-cs100#1462]
Does our output need to look exactly like ls does? ls does a very good job of keeping columns as small as possible and I am having a hard time replicating it. Is it sufficient for each column to have the same width as determined by the longest file name, or must we make sure each column is as small as possible?

**Comment by ghost** [comment]
I believe Mike told us to get the ls program as similar to the regular ls output on the lab terminal.

**Comment by mikeizbicki** [comment]
Your program does not have to exactly match the GNU ls's formatting.  You just have to make it reasonably close.  When we inspect it, it shouldn't "look weird" to us.  About the columns for ls with no parameters, your specific suggestion sounds reasonable.
