### ISSUE TITLE
Undefined ls flags

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1464]
When I run the bash's ls on a random flag lets say, ls -f, bash will still run ls. When I run, ls -k, bash will run as if I typed ls -a. There doesn't seem to be a pattern to this behaviour. In our ls, for unsupported flags, are we supposed to output an error or just let it run ls?

**Comment by fundamelon** [comment]
From the ls help page:
ls -f: do not sort, enable -aU, disable -ls --color
ls -k: use 1024-byte blocks
These weren't random flags!  They just didn't modify the output you saw.

Try ls -z for an option that isn't implemented.

**Comment by mikeizbicki** [comment]
There are at least two reasonable ways to handle flags like `-z` that don't do anything.  One is to print an error message that `-z` is a bad flag.  Another is to assume that `-z` is actually the name of a file.  You cannot, however, just silently ignore these cases.  Remember that one of the principles of unix programs is to fail early and fail LOUDLY.

**Comment by mikeizbicki** [comment]
Reopening so that it's easier for everyone else to see.
