### ISSUE TITLE
ls total

### ISSUE THREAD

**Issue by glaceeeee** [mikeizbicki/ucr-cs100#1467]
From the GNU documentation, I read that [the block size used for display is independent of any file system block size](https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html#Block-size) and that for ls, [the block size currently defaults to 1024 bytes](https://www.gnu.org/software/coreutils/manual/html_node/What-information-is-listed.html#What-information-is-listed). This affects the number after "total". Are we only responsible for the default 1024 byte block size for the number after "total" or do we need to deal with other cases?

**Comment by mikeizbicki** [comment]
BSD ls uses the value 512 bytes, GNU ls uses the value 1024 bytes.  The programs never adjust this value to match what the underlying filesystems actually use.  I don't care whether you follow the BSD or GNU convention for this number.
