### ISSUE TITLE
Extension for Hw1

### ISSUE THREAD

**Issue by IgneousToast** [mikeizbicki/ucr-cs100#1468]
Is there any possible way of getting the homework extended until Monday? I have consulted with many students in the class and they have said that if we receive more time, they would be able to turn in 100% work. I personally have worked more than 50+ hours on the assignment and I still continue to get major bugs and I know multiple students have the same problem. At this rate, we will not be able to turn in a completed assignment. I, along with my classmates, politely ask and would greatly appreciate and extension for Sunday. Thank you in advance.

**Comment by laurenB93** [comment]
Very true. The longer I work on it, the more I see wrong with it. :(

**Comment by ghost** [comment]
Well Mike was pretty solid on his statement in class today. Chances of an extentions are really low. I know that there are a few people completely done and a lot more getting done with 3 more hours of work. I would try to get as much done tonight and push out and tagged. If we're lucky then Mike might consider up to Saturday night. If Mike were to push back the dates, then he would have to put more strain on Busrac in grading the assignments. So not fair on her when she could get most of the grading done on the weekend. I would try on the next assignment hw2, which is due on the 15th, push the due day 3 days earlier before the due date and if you pass that date, get as much help from either peers, Mike or Busrac to get the assignment done.
Anyways, I wish for the people who are still working on the assignment good luck and keep on coding. Who knows Mike might have a change of heart.

**Comment by Renee7547** [comment]
I have implemented -l, -a, -la, and filenames. But when I came to do with -R, it seemed I need to change my structure of code! But time is up, I feel so sad now.

**Comment by mikeizbicki** [comment]
Sorry, but I can't give an extension on this assignment.

**Comment by alvtdev** [comment]
I've been having the same problem with -R. With every bug I fix, I find 2 others. It's like a hydra.
Oh well, I'll take the point deductions for not having it working and continue to fix it after the deadline.

In hindsight, coding ls such that it works recursively first then altering it to work without recursion would have been much easier than coding such that it doesn't work recursively, then attempting to restructure all of the code for recursion..

**Comment by cdixi001** [comment]
ʰᵃᶦᶫ ʰʸᵈʳᵃ
