### ISSUE TITLE
Recursive method

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1469]
My ls -R works similar to the GNU implementation, but instead of traversing in-order, it does it in a level-order fashion meaning it prints out all the folders/files in the current directory before going into any other directories in the current directory. Is this acceptable?

**Comment by mikeizbicki** [comment]
This is not correct and will lose points.  Your breadth first traversal isn't super useful in practice, whereas the standard depth first is.
