### ISSUE TITLE
resource not available

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1472]
I keep getting that message on hammer right now trying to test my code

**Comment by mikeizbicki** [comment]
I can't help you unless you show the exact commands you typed in and the exact response.

**Comment by hkwan003** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6343774/7439833/7ebe73a8-f043-11e4-814c-580cc26bbfe3.png)

**Comment by hkwan003** [comment]
i start the script and when I just do my normal cd commands and try to execute, i exit and it just exits out of hammer.
