### ISSUE TITLE
SCRIPT ERROR

### ISSUE THREAD

**Issue by jpatu001** [mikeizbicki/ucr-cs100#1473]
I uploaded my ls.script. But github couldn't display it since the file was too big. But when I git clone my repo, and open up the tests folder and open the ls.script, it opens. Downloading the ls.script and using cat also works. In guthub, it is only possible to see as RAW, which looks really bad. Should I redo my testing and use -R less to make it smaller? or is it ok as is? 
(For Prof Mike or Busra: It's up in my github acct if you need to see)

---EDIT----
I've decided to shrink the test file.

My only question left is, when I do cat ls.script it outputs in the terminal all the tests that I did. But the file on github shows file as RAW(and this shows the color formatting) is this alright?

**Comment by mikeizbicki** [comment]
I haven't looked at your actual file, but what you describe is correct.
