### ISSUE TITLE
errno=operation not permitted and segfaults

### ISSUE THREAD

**Issue by cbarb005** [mikeizbicki/ucr-cs100#1474]
I was working on formatting the time correctly for the -l flag, test ran it, and decided to adjust with getw. The next time I compiled and ran, these messages appear. They've appeared before but not to this extent. I'm not sure if the segfault is related, but I highly doubt that using setw suddenly is causing this. Any ideas on how to continue?

**Comment by mikeizbicki** [comment]
It's probably too late, but you should always be using gdb to track down segfaults.  That should be your first instinct.
