### ISSUE TITLE
Can't Push onto Git

### ISSUE THREAD

**Issue by kzhen002** [mikeizbicki/ucr-cs100#1475]
To https://github.com/kzhen002/rshell.git
 ! [rejected]        ls -> ls (non-fast-forward)
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/kzhen002/rshell.git'

whenever I try to submit my assignment onto github I get this error and It won upload. I'm not really sure how to fix this.

**Comment by mikeizbicki** [comment]
This means that your repo on github has commits that the repo on your computer does not.  Run `git pull` to update your computer's repo.
