### ISSUE TITLE
Fell asleep, mostly done.

### ISSUE THREAD

**Issue by ChannelJuanNews** [mikeizbicki/ucr-cs100#1478]
Hey I have a quick question. So yesterday (like 6 hours ago) I finished my ls assignment around 9:30pm. I just needed to redo my ls.script file because hammer kept giving me the `do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted` error within my script session and I needed to update my README.  But unfortunately I had been up for more than 48 hours working on this and other classes. When I saw my bed I just told myself I would lay on it for a couple minutes before I would finalize my work and go to sleep. I dozed off and now I am here at 4:37 in the morning wondering if I will get docked off points for turning in those a bit late. I didn't make any changes to my source code just FYI.

**Comment by ghost** [comment]
Another note when I was testing my code, when I did my test for ls, I named the output script 'test.script' would I still be able to change the file name.

**Comment by mikeizbicki** [comment]
For both of you, please go back to your repo and fix these mistakes before we look at it.  If you fix the mistakes before we actually download the repo then you won't lose any credit.

**Comment by ghost** [comment]
We change it as long as we don't touch the src files. Right?

**Comment by ghost** [comment]
Because wouldn't it mean that we have the change our tags as well?

**Comment by mikeizbicki** [comment]
We will only look at whatever is tagged as `hw1` on github.  So yes, you must delete the old tag and upload a new one.
