### ISSUE TITLE
Flags for compiling for hw1

### ISSUE THREAD

**Issue by jtran071** [mikeizbicki/ucr-cs100#1481]
Do we need to compile with the flags -Werror -Wall -ansi -pedantic for hw1? 

When I added the target in my Makefile for ls, I had a typo in my variable where my flags are suppose to be. So, when I was compiling it didn't include all the -Werror and -Wall flags, and unfortunately, I did not notice until now. Am I allowed to change my Makefile and fix the errors in my code that the compiler gives when these flags are used? It was only a couple of errors regarding the use of unsigned and int.

**Comment by mikeizbicki** [comment]
Don't worry about it for hw1.  You shouldn't lose any points for it.  But please fix it for hw2.

**Comment by jtran071** [comment]
Will do, thanks!
