### ISSUE TITLE
Combining two class projects.

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1482]
Hello, I am wondering if it is possible to combine our final project with the final project for another class? The other class is embedded systems and involves a lot of coding as well, and we have a final project in that class as well. The program for the embedded system itself will be written in C, and the coded posted on github, along with other specifications the user would need to use the code and change it.

**Comment by mikeizbicki** [comment]
You can definitely do that!  Of course, I would still have to approve your project and make sure it's appropriate for this class.
