### ISSUE TITLE
Homework 4 Contribution Idea

### ISSUE THREAD

**Issue by alvtdev** [mikeizbicki/ucr-cs100#1484]
I'd like to add documentation to Michael Evans' cs100 runtests script to ensure that future students are able to use it without any misunderstanding.

**Comment by mikeizbicki** [comment]
This sounds like it would probably be a good topic.  But before I approve it I'll want to see a more detailed description of what exactly your documentation will include.  Also, do you already know Michael so it would be easy for you to ask him questions?

**Comment by alvtdev** [comment]
My documentation will include information about specific commands and their arguments, as well as how to use them. I plan on doing this by creating a step-by-step walkthrough showing the reader how to use cs100 runtests by having them use it on examplestudent's rshell. 
I do already know Michael, so it would be fairly easy to ask him questions.

**Comment by mikeizbicki** [comment]
Awesome!  Sounds like a great project.  You should assume the reader has no Unix experience and walk them through everything.  There'll probably need to be a number of screenshots in the final presentation.

**Comment by alvtdev** [comment]
I'm currently working on the draft for my documentation. Any and all progress can be found here:
https://github.com/M-Evans/runtests/tree/documentation/docs

There will be frequent commits and pushes as I've been unable to get markdown preview working on my linux machine, and this is my only way of checking how the readme looks.
