### ISSUE TITLE
HW4 idea

### ISSUE THREAD

**Issue by Renee7547** [mikeizbicki/ucr-cs100#1485]
If we choose to do a project, chould the project be like a demo involving computer graphics, i.e. I did a very rough ray-tracing project before. Can I just develop it and make it run well, write comments in details and create a document for the project.
As for writing doc to an existing project, what kind of the project should be? Is there any suggested method for us to search for the appropriate project?

**Comment by mikeizbicki** [comment]
I don't think the ray-tracing project will work.  It doesn't meet the criteria of giving the community something that doesn't already exist.  There's already lots of ray tracers out there.

The project you document should be a Linux related somehow.  A good place to search is for ideas is the [GNU coreutils](http://www.gnu.org/software/coreutils/manual/html_node/index.html) library.  Most of the programs we've covered in class (e.g. `ls`) come from this library.  The existing documentation is good for experts, but is not very beginner friendly.  You could provide examples making it more beginner friendly.
