### ISSUE TITLE
HW 4 Idea

### ISSUE THREAD

**Issue by isadoramariamendes** [mikeizbicki/ucr-cs100#1487]
Hello Mike,
First of all, I would like to know if my partner and I need to post the idea or I just need to mention his name here.
Secondly, we were discussing about some ideas... and the one the we liked the most was basically to implement the Huffman Code using binary tree and dynamic heap. This is an interesting application of trees and discussing with some students I notice that most of them never heard about this method of lossless data compression... Researching in the internet I could not find the code implemented like this with heap and well documented. We believe this can be a nice project because most of new students in CS sometimes have the feeling that they are learning things that are not applicable (I heard things like "Why should I struct my project if I can put everything in the main file?" or "Why should I learn trees? I will never use it"... and this can be one example that will show them the opposite. Finally, my friend and I never implemented a dynamic heap and I can tell that I have some "good issues" implementing trees in general, so it's gonna be a challenge and at the final we will have learned a lot, as well. 

So at the final of the project we would have:
- BinaryTree.c and BinaryTree.h;
- DynamicHeap.c and DynamicHeap.h
- Huffman.c and Huffman.h
- Examples.c
- Documentation
- Explanations 

What do you think?

**Comment by mikeizbicki** [comment]
You only need to post the issue once including both names.

About the idea, this would be a good project for a data structures class, but not for this class.  Huffman codes are a classic data structures problem and included in the standard libraries for most programming languages.  See the [boost library implementation](http://www.boost.org/doc/libs/1_35_0/libs/iostreams/doc/classes/zlib.html).  These existing implementations are already fully featured and highly optimized, so no one will want to use your library.

**Comment by mikeizbicki** [comment]
There are a number of ideas related to this idea that might work.  But you'll need to emphasize: why does the world _need_ what you're making?

**Comment by isadoramariamendes** [comment]
Can you give me one example that is related to this idea that might work? hahaha, now all ideas that I can think sounds "too data structures class" for me hahaha... =/

**Comment by mikeizbicki** [comment]
You could create a short tutorial/lab that would teach people how to use
the existing zlib library and why it's useful.  This would help the same
group of people you were targeting with your initial proposal (i.e. people
who want to add compression to their programs), but it would do so in an
even better way by building upon existing work.

**Comment by isadoramariamendes** [comment]
Hmmm, I took a look in this project here in Github and it is pretty well documented :( I don't think it would really help somebody...
So we discussed about making a tutorial to help future students using LateX to create their history graphs of repositories...I guess it's gonna make all students have an introduction to LateX and at the same time they can use it in that lab that we need to draw our own history tree, for example.  What do you think?

**Comment by mikeizbicki** [comment]
That's the start of a great idea!  I think there's two ways you could go with it:
1.  Do a tutorial on latex.  You would want to cover combining latex and git and how this lets you version control your documents.  You could use creating a file representing the git repo as an example.
2. Create a utility that converts a git repo into a picture using latex.  Your utility would be a simple bash script people would download, and when you run it in a repo it generates a pdf (or some other format).

Both options seem like about the same amount of work to me.  I'd recommend you do the second option.  I think it has a good chance of attracting a lot of attention because it combines two different but cool utilities.  But you should do whichever sounds more fun to you.

**Comment by isadoramariamendes** [comment]
The second way sounds amazing; however, it does not look like a project to be done in a few weeks having all assignments that we have, unfortunately. But it is definitely something to work on soon as a personal project (I will post here if I do finish, haha). 

Regarding the first way that we could go with... Let me see if I get it right:
My tutorial should be about LaTeX. It's gonna provide information enough for users understand how to write a LaTeX code and how it can help with the documentation -- more specifically, using LaTeX to create history graphs of repositories on git. Is that right?

**Comment by isadoramariamendes** [comment]
By the way, my partner is @fvera002.

**Comment by mikeizbicki** [comment]
The emphasis should be on how to combine lots of unix tools together.  Use git to version control the file, use vim to edit the file, make to build the file (a book, for example, might have hundreds of files that need to be built in the right order), and finally pdflatex to output the pdf.  Whatever example contents for the latex file you decide on are fine.

**Comment by isadoramariamendes** [comment]
Ok, we can do it! Thank you!
