### ISSUE TITLE
HW4 Project idea

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1490]
@dtran049, @jtran071 and I want to make a web crawler/spider that scrapes the web, or a certain domains that are popular food sites, for food recipes and based on those recipes the user can enter what ingredients they currently have and the program spits back out what recipe can be made with the ingredients on hand. I'm not sure if this is too much work, and if C++ is a good language to write this in, also there might be some legal areas we are messing with too while doing this.

**Comment by mikeizbicki** [comment]
This sounds like a great project for another class, but not for this one.  A service like this would require a number of servers constantly running, which is not something that an open source project can provide.  It also sounds like it would be too much work for this class.

A related idea is a tutorial on how to do web scraping with bash scripts.  This is something we'd probably have to talk about in person a bit though.
