### ISSUE TITLE
HW 4 idea

### ISSUE THREAD

**Issue by ChannelJuanNews** [mikeizbicki/ucr-cs100#1491]
My partners (John and Kevin) and I want to build an open source game that will serve as a stepping stone for future cs100 students who don't know how to build apps. This game will be documented every step of the way which will serve as a tutorial and teach all aspects of developing an android app to anyone who wants to know how to. It is a fun way to learn/teach so it will be awesome. The game will be a small scale version of whack-a-mole, except instead of moles we will have little piggies. This will contribute to the open source community by making the game open source and customizable. Is this idea okay?

**Comment by mikeizbicki** [comment]
I might approve this if we talk about it in person a bit more.  But I _strongly_ discourage you from developing an android app.  Everyone makes these and they usually don't attract very much attention.  So you'll probably put in a lot of work and not see anyone actually benefit from it.
