### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1494]
My partners (Chirag Dixit and Peter Hung) and I plan to make a workout app.

The app will have a picture of the human body that will allow a user to select which muscle they wish to target for a workout.  It will also have a customizable workout list where users can add exercises and customize the number of reps and sets. 

Example scenario: Given a picture of the body, if the user clicks on the chest, the app will provide an extensive list of workouts for the chest (filters can be added for exercises with free-weights, machines, or body weight). If the user wants to do one of these workouts, they can add the workout to a workout queue.  Later, the user can change the order of their chosen exercises and can customize the number of reps and set. 

We aim to make this a mobile app for Android where we would learn java.

**Comment by mikeizbicki** [comment]
This sounds like a good project for another class, but not for this class.  In general, apps and open source don't mix very well together.  So I recommend staying away from apps.
