### ISSUE TITLE
HW4 ideas

### ISSUE THREAD

**Issue by sandiexie-UCR** [mikeizbicki/ucr-cs100#1495]
Hi, my partner,kenny luu, and I want to make a tutorial video on one of the two following topic:
1. Github: this will cover init, push, pull, merge, tags, branch, and others. we also consider add why using Github is good for a project, and demonstrate what can Github be use for. we think this tutorial project is useful because new user of github can visualize how github and github commands work. 
2. fork() and exec() on coding: there is a video on fork() showing the idea of what fork() is, but when i watched it, i was very confuse of how to use fork(). so i am thinking to have a video showing how fork() is used with exec().

**Comment by mikeizbicki** [comment]
1. There are already lots of these videos on youtube, so I doubt your videos would get too many views.  You'd have to have some really clever presentation for me to approve a video like this.
2. This has potential, but I'd need a bit more description about what exactly you'll cover first.  The video should also somehow build off of the material from the video that already exists.

For a group of 2, I would expect 4 _extremely_ good videos to get a 100 on the assignment.  So you'd need to think of some more options as well.

**Comment by sandiexie-UCR** [comment]
We are planning to do videos on
1. fork() and exec(). We will have dual terminals open, one for how to use the functions in code and the other for compiling and showing what the functions do. There will be different examples touching on, for example, what happens if the parent does not wait on the child and what happens if the child does not end correctly. We will also talk about wait(), waitpid(), and exit().
2. ps. How to understand the output of ps, along with the various flags people might use (the more important flags). Why ps is useful when working with fork(). Why you need it for the bash command kill.
3. kill. How to understand the different kinds of kill such as kill and killall. Why kill is a useful bash command when processes go wrong. We will talk about the different flags and what they mean. How to use kill and when to use kill. Have various examples of what happens when you kill a certain process, such as killing bash or killing vim.
4．In the works.

**Comment by mikeizbicki** [comment]
Okay.  For the next submission I'll expect a rough draft of one of your videos and a script of everything else.  Just so you know, most students have to remake the videos 3-5 times before they're at A quality.

Also, the kill command is (despite the name) not just for killing processes.  It's for sending signals to processes.  The last rshell assignment deals with signals, so we'll be covering that in more detail then.  A possible good idea for the forth video is this more advanced use of kill.
