### ISSUE TITLE
Project 4 Idea

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1497]
So my idea is to work with @CompKev824 John Dixon and Juan Ruelas would like to make a chrome extension that would help people learn git. My idea is to make a chrome extension would only work when  the user is on the Github page. When I mouse over an option lets say to make a new repository, our extension would output a box which will output the terminal command equivalent of the mouse click which is currently on. This will teach people how to use Git and break away from always using the web application.

**Comment by mikeizbicki** [comment]
This has a LOT of potential.  If you can pull it off, I think it'd be huge.

I'm a little doubtful though.  It seems to me like there's very clear mapping between GitHub's options and the terminal git commands.  If you can show me a good list of these commands then I'd approve this.  But again, I'm skeptical this is possible.
