### ISSUE TITLE
HW4 Ideas

### ISSUE THREAD

**Issue by yyao007** [mikeizbicki/ucr-cs100#1498]
I will work with my partner @ycao006 yujie cao to create a Android Project. We have two ideas:
1. Smart Home Control system user interface for Android: 
   We want to write a control system user interface template. To be specific, our project is an app that provides people a user interface to control home devices. For example, people can use our app to control their air conditioners anywhere.
2.  An Android App: Guid to assemble a desktop:
   We will use Android app to write a toolbox about assembling a desktop. this app tells users what components are still needed based on the list that user provided. In addition, this app will recommend users a list of proper components to buy.

Which of these two ideas sounds good for this class? If you are confused about our description, we can provide you more details after class tomorrow.

**Comment by mikeizbicki** [comment]
Both of those sound like good projects for another class, but not so much for this class.  In general, phone apps and open source don't mix very well.  So I recommend looking in another direction.

**Comment by yyao007** [comment]
Alright, so we come up with this idea.
My partner @ycao006 yujie cao and I found that there were few documents teaching people how to properly use g++ flags. For example, if I installed a library in a different directory rather than the default one, then when I compile my code which includes that library there will be several error messages saying "undefined reference <function name>". This is because g++ will always look into its default library folder to look for the library which is included. If it can't find the library, the functions in that library won't be declared in the beginning and will become an undefined reference. Can we write documents about this and teach beginners to use g++ wisely?

**Comment by mikeizbicki** [comment]
One good related topic would be the difference between dynamic and static linking of libraries.  This is a very controversial issue among programmers, and I'd be very excited for a writeup about it.

As for just talking about g++ flags, it's hard for me to imagine what value you could add that the man page/existing documentation doesn't already cover.  I'd approve this topic if you can: give me a list of the options you would cover and explain how your tutorial would improve existing documentation.

**Comment by yyao007** [comment]
Is it possible that we talk to you about our topic tomorrow between 9:30am
and 2:00pm whenever you are free? Thank you very much.

Mike Izbicki notifications@github.com于2015年5月6日星期三写道：

**Comment by mikeizbicki** [comment]
Sorry, tomorrow is a bad day for me.  Would Friday right after class work?

**Comment by yyao007** [comment]
OK, that's fine.

Mike Izbicki notifications@github.com于2015年5月6日星期三写道：
