### ISSUE TITLE
git commit problem

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#15]
Hey everyone:

When working at home, I've been getting this problem when trying to run:

git commit -m "added the first code"

This is what I get:

**\* Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

However, when I try to run git config followed by my info, I get an error that says invalid key. Any ideas? Thanks!

**Comment by DanTheTingler** [comment]
Never mind, solved it by using this link, sorry for the amateur question!

https://help.github.com/articles/set-up-git

**Comment by mikeizbicki** [comment]
It was a good question.  And thanks for following up with your answer!
