### ISSUE TITLE
Hw4 Idea

### ISSUE THREAD

**Issue by TheBoop** [mikeizbicki/ucr-cs100#1503]
Hello,
I would like to actually provide a documentation on the differences between several coding languages, such as: Java, C, C++, Python, Javascript. 
Even web-based languages: Ruby, PHP, HTML, SQL
### The document would include each languages:
- strengths & flaws
  -  with small explanation
- common uses
- different variations of commonly used commands, such as:
  - cout, str(s), System.out.println
- common used functions such as arrays

_All included with code and picture examples._

This is because I'm interested myself, and I thought it would be an excellent place for beginning programmers to see which languages they should learn. There are many sites with lists of popular languages, but I have not found one that contained good documentations on how they are different with examples of each language.

**Comment by mikeizbicki** [comment]
This sounds too ambitious.  http://learnxinyminutes.com/ is a pretty good reference that already does a lot of this.

A related topic that I think is more doable would be a C tutorial for people who already know C++.  But this would be an extremely hard writeup to do well.  You should talk to me in person if this sounds interesting.
