### ISSUE TITLE
Hw 4 Idea

### ISSUE THREAD

**Issue by glaceeeee** [mikeizbicki/ucr-cs100#1504]
For homework 4, I would like to expand the [existing Boost Tokenizer tutorial](https://github.com/mikeizbicki/ucr-cs100/blob/2015spring/textbook/assignment-help/BoostTokenizer/README.md). I would like to edit parts of it to clarify some points. Also, the existing tutorial only goes over the char_seperator TokenizerFunction model, so I would like to write about the other two models, escaped_list_seperator and offset_seperator.

**Comment by mikeizbicki** [comment]
> I would like to edit parts of it to clarify some points.

Which parts do you plan to clarify?

**Comment by glaceeeee** [comment]
The way I was planning on organizing this was to make 3 markdown files. The first one would be the existing tutorial, along with some edits, and the other two would be the other TokenizerFunctions. My plan is to use the existing tutorial (along with some edits) as a general Boost Tokenizer tutorial and to use the existing char_seperator examples to supplement the general tutorial.

So by "clarifying" I meant that I would add a few topics and edit the introduction/conclusion to make the existing tutorial more of a general Boost Tokenizer tutorial. The main addition I was planning is a section on what a TokenizerFunction is and what it does. I was also considering adding sections on the constructor (might not do this because I think the constructor is pretty self explanatory in the documentation) or the member functions of tokenizer (there's only assign() but with different parameters).

**Comment by glaceeeee** [comment]
Another way I was thinking about organizing this would be to make 4 files: 1 as a general tutorial and the other 3 for each of the TokenizerFunctions. In this case, the existing tutorial would be split up into the general tutorial and the char_seperator tutorial.

**Comment by mikeizbicki** [comment]
Sounds good.  Just so you know, I'm going to be extra picky about the writing quality of this project since it'll be something that most future students will want to work through.
