### ISSUE TITLE
HW 4 Proposal

### ISSUE THREAD

**Issue by vinkert** [mikeizbicki/ucr-cs100#1505]
I was thinking of writing a tutorial on using awk, as it seems like a very powerful and useful tool. I think I would focus mainly on its uses for data extraction. Is this ok?

**Comment by mikeizbicki** [comment]
Sounds great!  A few other students are working on web scraping (see#1490) .  I'd expect you to coordinate with them to ensure that you're not duplicating material.  

For the next deadline, I'd like to see the specific data you'll be working with, the specific features of awk you'll cover, and a short motivating example.

**Comment by htang014** [comment]
Sorry for replying so late, but I have been working with Vincent on the AWK tutorial, mostly so far as a research partner. I thought I should notify you just to make sure I'm not screwing myself.  Is this OK with you Mike?

**Comment by mikeizbicki** [comment]
@htang014 You're working on AWK as your actual homework assignment, or just to help out?

**Comment by htang014** [comment]
as the actual assignment

**Comment by mikeizbicki** [comment]
that's fine

**Comment by htang014** [comment]
OK great
