### ISSUE TITLE
HW4 idea

### ISSUE THREAD

**Issue by kkita004** [mikeizbicki/ucr-cs100#1506]
I'd like to write a more in depth tutorial about the .vimrc file and how to modify it., and The current lab 0 doesn't have much information on the actual vimrc, and the PacVim only goes over commands on movement.

**Comment by mikeizbicki** [comment]
I forge, but was it you that I talked with in person about this topic?

**Comment by kkita004** [comment]
Yeah, after we moved to the TA office we talked about this. You suggested that I come up with a more concrete outline and discuss with you about it before it would be confirmed.
