### ISSUE TITLE
Hw4 Idea

### ISSUE THREAD

**Issue by Kilenaitor** [mikeizbicki/ucr-cs100#1507]
Started working on an open source library for C++ that would help with teaching/debugging code with data structures.

Was going to call it something like "DataViz" or something like that, but basically it would use an existing library called GraphViz which can be used for drawing graphs and charts and things like that to basically draw out and render data structures. It would use template metaprogramming to cover a lot of the data structures but it would allow you to, for example, add a function call into a for loop and it would create a series of pictures of your data structure as it gets modified. Could significantly help with debugging and also for teaching so students could actually visualize the data structures that they're working with. 

Array/Vector would look like a ![grid](https://cloud.githubusercontent.com/assets/4632233/7500567/43684aec-f3e3-11e4-94e8-726b652c6bec.png)
Trees would be drawn like how trees look from top down. 
Dictionarys would be key/value grids.
Trying to add support for some custom data structures, too
![out 113200](https://cloud.githubusercontent.com/assets/4632233/7500626/8bba0998-f3e3-11e4-9dec-aa06ba653fca.png)
etc.
It's not super pretty yet, and it works on a small amount of structures now, but I hope to make it a little prettier and hope to add a lot more functionality to be able to handle a lot of data structures.

It renders out .PNG images, so they are actual pictures not just text, and it makes it so that instructors/devs don't have to write their own printing function for data structures in awkward ASCII text and take up a bunch of space in the terminal.

**Comment by mikeizbicki** [comment]
This looks nice!  I'll probably approve this, but we'll have to talk a bit more in person about how it works and the scope of the project.  In particular, it depends on how much modification the original program requires.  The best way to create a project like this would actually be as a plugin to gdb.  That way, it would work on any program ever created without any source code modifications.  Something like that would gain a LOT of traction real quick.

**Comment by Kilenaitor** [comment]
Hey Mike! 

Here's what I have so far
https://github.com/kyleminshall/GraphData/

It's not QUITE 75% done in terms of the programming itself, since I need to add the other data structures manually, but that really isn't too bad. So time-wise, it should be about 75% done.

I'm free tomorrow if you want to talk about the project scope. What I envisioned was more of a teaching instrument than a debugging instrument, but it could easily be used for both. So it's going to mostly tailor to the common data structures taught in a class. I don't actually know how to add plugins to gdb so if that is what you think would be best I would need some help with that.

I plan on meeting with Prof. Shelton this week to discuss the implementation of the template-metaprogramming since he's the one who gave me the project idea in the first place. 

See you in a few hours!

**Comment by Kilenaitor** [comment]
Hey Mike,

We talked about changing the purpose of the project away from being a standalone library to a plugin for gdb.

I looked around for a while to see if I could find any documentation on creating plugins for gdb and my google results turned up pretty empty. Looked for python, gdb extensions, plugins, etc and couldn't find anything that went over how to create or write plugins.

If you wouldn't mind pointing me in the right direction for this whenever you get a chance I'd really appreciate it. I can't seem to really find anything. 

Thanks, Mike!

Have a great weekend.

**Comment by Kilenaitor** [comment]
Is this a better question for in-person?

**Comment by mikeizbicki** [comment]
I don't personally have any experience writing these gdb plugins, so I can't help you too much.  The thing to google for is the "gdb python api".

Does that help?

**Comment by Kilenaitor** [comment]
Here is the (WIP) plugin for GDB:
https://github.com/kyleminshall/GraphData2

And here is the original repo:
https://github.com/kyleminshall/GraphData

Thanks for a great year, Mike!
