### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by jpatu001** [mikeizbicki/ucr-cs100#1508]
My idea for homework 4 is to create a side by side comparison of how to use strtok and boost tokenizer in the same tutorial. In this way the user/ reader can see the pros and cons of using each other. I will also add a short program that has a paragraph in it, and the user can enter whatever delimiters they want, and the program will output the tokenized paragraph using the delimiters provided. This way, the user can reuse the program(by slightly modifying it) to fit to their needs instead of having to rewrite everything for themselves. This might help to cut time experimenting when parsing inputs. Plus the reader has an overview of what they think is easier for them to implement and which will fit better in their code implementation instead of reading two separate tutorials.

**Comment by mikeizbicki** [comment]
I'm just replying to let you know that I've read this, but I'm waiting to hear back based on what we talked about after class.

**Comment by jpatu001** [comment]
Yes, I just posted it because I might forget to post later. What should I go over again? I reread the strtok and tokenizer from hw0, and what I wanted was to merge both of them(in my own terms) and show a comparison of doing the same thing but using the two methods.

**Comment by mikeizbicki** [comment]
Right now I don't see how the tutorials could be improved in this way, so I'm very hesitant to approve the project.  My recommendation is that you try to think of something else.

**Comment by jpatu001** [comment]
I just thought that maybe having a tutorial using both of them(doing the same thing) instead of reading two long tutorials would be beneficial for future users of tokenizer/ strtok since they can see how to use both in the same page. Plus the small program can be used as visual help, and probably as a code incase it fits the user's parsing needs(like in hw0 rshell, with the program, there would be less tinkering of how to parse an input). Anyway, is there a place where I can look for more potential topic to write about? because I  can't think of another thing to write about. I saw someone who will do this too(tokenizer) but with getopt, and thats kind of what I was intending to do minus the getopt part. Any suggestion will be greatly appreciated.

**Comment by mikeizbicki** [comment]
Would you be interested in partnering with @knels012 on #1509 creating a cheatsheet for the coreutils commands?

**Comment by jpatu001** [comment]
That would be great if its cool with her.

**Comment by jpatu001** [comment]
So are we going to work on it already as partners, or should I ask her first if she wants one?

**Comment by jpatu001** [comment]
I had another idea and I dont know if I should create a new issue so I'll just add it here. I would like to implement a wheel of fortune like game that will help user get use to bash commands. The players will guess which bash command is being asked with a help of a single hint. The user can either check a character or go guess the whole command. It can be played by multiple players where they accumulate points per correct guess, or played by single player. In single player the user will be timed, and the question that are not answered correctly or took too much time too answer will be asked again to improve the user's memory of the bash commands.

**Comment by mikeizbicki** [comment]
I don't think the wheel of fortune game would work, but if you really want to do it we can talk in person.

**Comment by jpatu001** [comment]
Its not like 100% wof, kind of. Anyway I'll discuss it in more detail after class on  Friday. Thanks

**Comment by jpatu001** [comment]
Hi Mike, I'm now doing a documentation for some of coreutils as you suggested before for my hw4. This is just a plan of what I want to cover. I've read the list below, but haven't had an actual writeup since hw2 took more time than I expected. I'm assuming that I need to explain what each of them do, and probably an example of its use. So that's what will be in the write up. I opened up the gnu coreutils manual online and selected the commands below(I'm not sure if these were the ones you were referring to when we talked last time. If it's not, can you please point me to the right list and I'll revise this asap). Here's the list that I'm planning to do so far:
- Formatting file contents(fmt, numfmt, pr, fold)
- Operating on Sorted Files(sort, shuf, uniq, comm, ptx, tsort)
- Operating on Fields(cut, paste, join)

**Comment by mikeizbicki** [comment]
Okay.  Your focus now should be on coming up with good examples that demonstrate the use of those commands.
