### ISSUE TITLE
hw4 potential ideas

### ISSUE THREAD

**Issue by knels012** [mikeizbicki/ucr-cs100#1509]
I was considering one of two following things.
1. In your reply to [another hw4 idea](https://github.com/mikeizbicki/ucr-cs100/issues/1485), you mentioned the [GNU coreutils](http://www.gnu.org/software/coreutils/manual/html_node/index.html), and said providing samples to make it more beginner friendly would be a possible hw4. I was wondering if I should do several commands or pages, and how many would be a good amount for this assignment. Also, should it be more like separate beginner pages, or would I expand the pages already there?
2. Tutorial for file moment/transfer from your own computer to github or remote machines, such as ssh, and vice versa. I wasn't sure if this would would be big enough though, or if existing documentation would make this rather unneeded.

**Comment by mikeizbicki** [comment]
1.  For this topic, you should pick between 3-5 programs that are closely related somehow and write about them.  The key will be to provide lots of good examples.
2. This has some good potential.  You'd want to cover the `scp` and `rsync` commands.  The hard part about this writeup would be finding some good examples that relate back to the course somehow.  I can't think of any off the top of my head.  But if you can think of some, then I'd approve it.

**Comment by knels012** [comment]
Would [these six](http://www.gnu.org/software/coreutils/manual/html_node/User-information.html#User-information) work for 1?

**Comment by mikeizbicki** [comment]
I don't think so.  I'm not sure what you would do with those other than give a one sentence description of what it does.

**Comment by knels012** [comment]
How about [these four](http://www.gnu.org/software/coreutils/manual/html_node/Working-context.html#Working-context), including all the [subtopics for stty](http://www.gnu.org/software/coreutils/manual/html_node/stty-invocation.html#stty-invocation)?

**Comment by mikeizbicki** [comment]
Hmm... these look too simple too.  How about making a cheat sheet where you give a short description and an example or two of each of the commands?  It wouldn't have to be all the commands, just the most useful ones.

**Comment by knels012** [comment]
So this would be roughly 20-30 commands then?

**Comment by mikeizbicki** [comment]
Yes.

**Comment by knels012** [comment]
Do I still need to write up 2 paragraphs explaining my hw4?

**Comment by mikeizbicki** [comment]
You're done.
