### ISSUE TITLE
Lab 1 Compiler Error

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#151]
I'm trying to follow the steps for lab 1, and I encounter this error when trying to compile my main.cpp.

"fatal error: iostream.h: No Such file or directory #include <iostream.h>"

What steps can I take to fix this issue? Thanks!

**Comment by 2c2c** [comment]
#150 fixes the documentation for this

**Comment by tkimva** [comment]
It's already fixed and please use `iostream` header

**Comment by jesuscreyes** [comment]
Thanks for the quick response!
