### ISSUE TITLE
HW 4 Topic

### ISSUE THREAD

**Issue by jmeji011** [mikeizbicki/ucr-cs100#1512]
Hello, I talked to you after class about what I could do for a possible HW4 project, and you said that I should make improvements on some of the tutorials. You told me to compare the tutorials with one of the better ones, so I can get an idea on how to improve them. I was looking through the tutorials, but I can't determine which one you thought was a better tutorial. Can you link me to the tutorials you were talking to me about? Thanks.

**Comment by mikeizbicki** [comment]
See #1512.  The two of you don't have to work together on the assignment if you don't want, but you should split up the work roughly in half.  I'm going to close this issue, and you should reply to the other issue.  That way all the communication about this one topic is in one place.

**Comment by jmeji011** [comment]
Did you mean to link me to #1511 ?

**Comment by mikeizbicki** [comment]
Whoops!  You're right!
