### ISSUE TITLE
HW 4 Proposal

### ISSUE THREAD

**Issue by sthak004** [mikeizbicki/ucr-cs100#1513]
Hey Mike,

We came to the conclusion that adding documentation for advanced features of vim would work for this project. However, I don't quite remember what concrete features you said you'd be looking for, although you mentioned something like vim having macros that could serve as a replacement for the C++ macros we used. What sort of features would you think are worthy? I understand I have to do the research but if I have a narrowed scope, it would be helpful in my proposal. 

Thanks.

**Comment by mikeizbicki** [comment]
This website: http://vim.wikia.com/wiki/Vim_Tips_Wiki is the definitive source on vim tips.  So you should browse this a bit.  I specifically don't want is just a rehash of some of the tips already found on the vim wiki.  Before I approve this project, you'll need to come up with a plan of how to avoid that trap.

One way to proceed would be to find 3-5 cool vim features that can be tied back to this course somehow.  Then you would add small sections to each of the relevant files that explain how to use vim in that situation.  You'll have to get creative though about how those vim shortcuts would apply.

**Comment by sthak004** [comment]
So for example, if I find a command that is useful, it's let's say a homework or lab assignment, shall I explain how that command works first and then relate it that particular part in the homework or lab? Or will the explanation be essentially rehashing the tip?

**Comment by sthak004** [comment]
So from what I understand, my proposal is that I will find a couple of vim commands that will serve as shortcuts in clever ways for the class assignments. I will not rehash those commands from a website, rather I will explain the significance of using the command in that particular situation and how it serves as a shortcut. These can be extremely beneficial to students in certain cases. However, I have yet to find the exact set of commands I will use.

**Comment by mikeizbicki** [comment]
Your last description sounds good to me.  I'd try to come up with the set of commands you're going to use by next week.  That way if it turns out you can't find any, you'll have plenty of time to pick a new project.

**Comment by sthak004** [comment]
Will do! Thanks!

**Comment by sthak004** [comment]
Hey Mike,

I've starred 20 repos. 

Thanks!
