### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by donei003** [mikeizbicki/ucr-cs100#1514]
Hello,

Data structures are a very important concept in CS14 and I think it's something everyone in computer science should know. However, in CS14, learning these data structures and different types of trees was very difficult and finding help was not very easy. What I propose as my hw4 project is to make a neat document demonstrating the different types of data structures and make it easy to read. I'll include some advantages and disadvantages with each structure as well as some tips in implementing them in c++.

**Comment by mikeizbicki** [comment]
This is probably not a good project.  There are already hundreds of tutorials about these data structures.  Why would your tutorial be better?  You have to answer that question before I could approve the project.

**Comment by donei003** [comment]
Ok, I have a better idea. I would like to create a cheatsheet for gdb commands, similar to the ones we have for syscalls and for vim. The two cheatsheets that we have are extremely useful and I carry them with me all of the time and I find myself referring to them constantly. Gdb has a pretty good learning curve and I find myself resorting to cout statements because of it. I think creating a cheatsheet would greatly help incoming students and I think I could benefit from it as well.

**Comment by mikeizbicki** [comment]
That cheatsheet already exists: https://github.com/mikeizbicki/ucr-cs100/blob/2015spring/cheatsheets/gdb-cheatsheet.md

It probably has room for improvement, but you'd have to tell me exactly how you'll improve it first.

**Comment by donei003** [comment]
Ok, I see what you mean. What I was proposing was something like a LaTex document  that could be given out to the class so that the could keep it with them. But I could also improve on the cheatsheet on github.

**Comment by donei003** [comment]
For instance, adding some advanced commands such as examining memory and list (displays the next few lines) which are some commands I only have learned about which would have been useful earlier on.

**Comment by mikeizbicki** [comment]
I'd need to see a detailed list of which commands you plan to add before I approve the topic.  You would also probably have to modify the existing lab a bit to teach some of these commands.  At the very least, the lab should be linking to the cheatsheet if it doesn't already.

**Comment by donei003** [comment]
I think revising the gdb lab is a good idea either way since there is already a disconnect between the cheatsheet and the lab. I'll list three commands I think are would be useful to beginners. If you would like more I can do so but it would probably be better to meet in person if you want a better list.
1. list ( l ) command. This should be on the cheatsheet as well as in the lab. Knowing this command would save a load of time when beginning to use gdb. I found myself quitting gdb numerous times in order to find the right line of code to set a breakpoint.
2. backtrace ( bt ) command. This, like valgrind is useful for finding things like seg faults, and the bt command can tell you where the seg fault occurred and in what function. Extremely useful.
3. set args command. This isn't going to streamline gdb but it would allow the user to rerun their program in gdb without having to set the arguments everytime. It could save some time and frustration.

**Comment by mikeizbicki** [comment]
This sounds like a good project.

As an aside, why did you have to close gdb?  Why didn't you just have vim open in one terminal and gdb in another?

**Comment by donei003** [comment]
I never bothered to ssh into hammer for each terminal. But to be honest we shouldn't have to. I also have yet to find an operating system that handles multiple windows in a way that is intuitive and is not clunky. Especially on CentOS. multiple windows are way too clunky. Mini rant I guess.

**Comment by mikeizbicki** [comment]
You should get a tiling window manager like xmonad.  Plus, it's extra credit if you install it on linux :)

**Comment by donei003** [comment]
Sounds like I'll be installing it soon, it looks very powerful with multiple tiles and multiple workstations.
