### ISSUE TITLE
HW 4 Idea

### ISSUE THREAD

**Issue by kzhen002** [mikeizbicki/ucr-cs100#1516]
Hey Mike,

For hw 4 I was thinking of making a tutorial(like the tokenizer and strtok already written) on using getopt, argp, and getsubopt to parse command line arguments. I've had trouble with parsing arguments before and getopt made it very simple for me, in particular with the ls hw we had. So I thought this could be helpful. I'm not sure if this is enough work though, this is just the only thing I could think of so far.

**Comment by mikeizbicki** [comment]
Great idea!  You should pick a simple command line program (not one that gets implemented in hw or lab) and use that as an example.
