### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1517]
Hello Mr. Izbicki, 

I have several ideas for this assignment.  I would appreciate it to know your opinion about each of these and which would be best for the open source community. 
1. Create an Emacs cheatsheet for quick reference if we ever encounter an Emacs editor.
2. Extend PacVim to PacEmacs so that users can also learn Emacs the same way they would learn Vim with this game.  
3. Write a tutorial on grep that includes how it works and flag usage. 

Thank you, 
Mark

**Comment by mikeizbicki** [comment]
I think talking about emacs would just be too confusing.  Vim's already confusing enough without throwing in something else that's really weird.  If you want to do something vim related, no one has done anything with vimscript yet.

Another student is already doing grep this quarter.

**Comment by markasfour** [comment]
Vimscript sounds very interesting.  I'd like to make a tutorial for it.  Thanks for the suggestion. 

How far in depth should I go explaining it? From my quick research on the topic, I can include instructions on how to execute Vim commands, how to make variables, data types, if/else statements, for/while loops, try/catch statements, functions, and classes, and how to use Vim's built in functions.

**Comment by mikeizbicki** [comment]
The key is to pick a good example of a task where it makes sense to use vimscript, and you can't do it without vimscript.  Then, your tutorial would explain how to go about making something that does that.  You just explain the syntax for each feature as you use it.  There's no need to cover everything.  You just want to get the reader motivated to look at the deeper documentation for themselves.

**Comment by markasfour** [comment]
Sounds good.  I'll have a draft of this ready by the next deadline. Thanks again!
