### ISSUE TITLE
HW 4 Proposal

### ISSUE THREAD

**Issue by avere001** [mikeizbicki/ucr-cs100#1518]
I was considering making a tutorial on using ANSI escape codes, including the codes for moving the cursor around and more. I wrote some code about a year ago wrapping some of this functionality (e.g. `setCursor`, `setFG`, `clearScreen`, etc) that I could expand on and include with this so that people don't have to remember seemingly random sequences of characters when writing code for controlling the terminal.

**Comment by mikeizbicki** [comment]
I don't think this will work.  There's already a tutorial on ANSI escape codes: https://github.com/mikeizbicki/ucr-cs100/tree/2015spring/textbook/assignment-help/output-formatting-in-c%2B%2B And creating  set of functions like that is simple enough that most people would either: prefer to do it themselves on small projects; use a standard library like ncurses on larger projects.

**Comment by avere001** [comment]
Mr. Izbicki

Perhaps I could expand gitlearn to give more information about assignments. In particular I think it would be nice to view comments about our grades from gitlearn itself without having to check on github or in the ucr-cs100 repository. This could also include information like when the homework was officially graded. I could also expand gitlearn to show the assignment requirements without having to go on github. I'm not sure if this would enough to write about, or if it would take very long, unfortunately. I'm having trouble thinking of much else to do. If you don't like this idea, do you think there's anything similar to either this or the ANSI proposal that I could work on? 

Thanks,
Adam Veres

**Comment by mikeizbicki** [comment]
What I'm most interested with respect to gitlearn is getting a good tutorial written on how to use it.  In particular, it would go through the steps for how to setup a new class.  Does that sound interesting?

Once that's done, it would be very easy for you to write a script that displays the contents of the grade file for any particular assignment.

If you did both of those things, I'd give up to 25 pts extra credit.  I don't think the assignment would be too hard, I just really want to have these things implemented well.

**Comment by avere001** [comment]
Yes, that sounds interesting. Though, didn't you already assign gitlearn documentation to #1486? Or is that just documentation for the individual files?

**Comment by mikeizbicki** [comment]
I think @aso001 was more interested in working on the website aspect, but there's enough documentation that needs doing that I'd be happy having multiple people working on it.

**Comment by avere001** [comment]
Okay. In that case I shall work on those. Would it be all right if I came to your office hours to get a demonstration of how to set up a class? Or would you prefer I try to figure that out on my own by looking through the code?

**Comment by mikeizbicki** [comment]
I can definitely give you an overview of everything during office hours.

**Comment by avere001** [comment]
Okay. Thank you!
