### ISSUE TITLE
hw4-contributing proposal

### ISSUE THREAD

**Issue by mchen046** [mikeizbicki/ucr-cs100#1519]
@ykamo001 @ttruo018 and I, @mchen046, would like to create a utility that takes a git repo as a command line argument and outputs the structure of branches and respective commit history for each file in a pdf or PNG format. This will be done using LaTeX.

**Comment by mikeizbicki** [comment]
Sounds good.  I'll want your program to be written as a bash shell script.  I suspect it'll be a fairly easy program to write.  The key will be to provide really excellent documentation for it.  That's what's going to make people want to use the project.  There's also a number of pictures of repositories in the various writeups inside this repo.  They're all in slightly different formats though, so I'll want you to recreate all these pictures using your tool.

**Comment by mchen046** [comment]
Hey Mike, we currently have our project hosted on a github repository, hope that's fine: `https://github.com/ykamo001/GitMap`

So far, our project extracts all the information of all branches in a repository and stores the information into separate files. We are still working on implementing repository specification in the command line arguments. We also need to utilize the necessary information from the files to convert into a graph in LaTeX.

Currently we are implementing the tool in C++, though we still plan to implement the code in a bash shell script as per your request.
