### ISSUE TITLE
HW 4 Proposal

### ISSUE THREAD

**Issue by vhall415** [mikeizbicki/ucr-cs100#1520]
Bailey Herms and I would like to make a trivia type game based on the game snake. The snake would be moved with the vim direction (h,j,k,l). A prompt would display at the top that would be a description of a command for vim or bash and two objects would appear in the game area. One object would be a command and the other would say "no" that the command provided is not correct. We'd have a few commands pulled from the entire list, one of which is correct, and the game would change the prompt after the correct command has appeared on the screen and is picked up by the snake. The game ends when the snake hits itself, a wall, or chooses the incorrect object.

**Comment by mikeizbicki** [comment]
Sounds good, with the caveat that we talked about before that I think this will be a relatively hard project to do well.

**Comment by baileyherms** [comment]
“We looked at what we wanted to get done for this project and we realized that we wouldn’t have enough time to do this assignment along with our individual projects for CS 120B. Would we be able to do a written tutorial with code examples on the different ways to parse in C++ instead? We will be able to complete a rough draft of the tutorial by the Wednesday deadline.”

**Comment by mikeizbicki** [comment]
I doubt it.  There's already tutorials on two methods for tokenization.
What would you be adding?

**Comment by vhall415** [comment]
We haven't been able to think of what we could add to the tokenization so could we instead add to the boost tutorials. I was thinking we could explain the useful data structures in the boost library, specifically boost.any, boost.variant, and boost.optional. They're similar to templates or the auto keyword, but have some additional features that could be useful. We would describe each type and compare and contrast them with each other since they can be used in similar ways, but one version might be more useful than another depending on the situation.

**Comment by mikeizbicki** [comment]
I'll approve this topic, but I suspect it's going to be hard to do well.
To get an A on the assignment, you'll need to come up with examples somehow
related to system calls and the other material we've covered in the class.
If you can specifically relate it to one of the assignments, that would be
even better.
