### ISSUE TITLE
HW 4 Idea

### ISSUE THREAD

**Issue by hzhu007** [mikeizbicki/ucr-cs100#1521]
Hi Mike,

I just come up with two ideas.
1. I can write a tutorial about how to install and how to use Tor relay.
2. I am using open source program ZXing and QRCode.net to do my senior design. It took me great effort to figure out how to use them. Then I wrote a small C# program to render customized QR Code. Can I share my program with some tutorials as a sample of how to use those third party library?

Thank you

**Comment by mikeizbicki** [comment]
As for 1, I think there's already a number of good tutorials on tor, so I doubt that's a good topic.

I just quickly looked through the documentation of ZXing.  It's looks really good.  What, specifically, would you improve about the documentation?

**Comment by hzhu007** [comment]
We finally followed your advice to make a tutorial about function pointer in which typedef will be mentioned. It will be an detailed explanation as well as an extension of your lecture on Mon..

**Comment by mikeizbicki** [comment]
Sounds great :)
