### ISSUE TITLE
Hw #4 Alternate Idea

### ISSUE THREAD

**Issue by aesgu001** [mikeizbicki/ucr-cs100#1522]
So, unfortunately, the idea of contributing to runtests script didn't work out, so here's a new suggestion:

I was thinking my partner (nchun003) and I would create a lab for implementing the echo command. Say, this lab would require future students to handle at least one flag (-e seems to be a good candidate) and to be able to redirect them into a file using the '>' or the '>>' character. It could help teach them a thing or two about piping, preferably before having them start hw2.

**Comment by mikeizbicki** [comment]
Piping and io redirection is handled in the shell, not within individual commands.  The echo command has no built in support for this.  I'm very interested in ideas for new labs though, so I'd encourage you to keep thinking about this.

**Comment by aesgu001** [comment]
Hmm... What if we have them implement all three flags and work on at least two backslash escape characters? Maybe handle quotes as well? Should suffice for lab time as well as teaching parsing, in my opinion...

**Comment by mikeizbicki** [comment]
The shell handles all of those things (except the flags), not the program.

**Comment by aesgu001** [comment]
I'm pooped. I'll see if I couldn't find a way to help make #1486 work.
