### ISSUE TITLE
HW4 draft submission: quiz-game-tutorial (edited)

### ISSUE THREAD

**Issue by fundamelon** [mikeizbicki/ucr-cs100#1523]
@fundamelon @UrielNaranjo @kkimb003 
Due to the volume of existing tutorials and instructional games, the group has decided to combine the best of both worlds - we propose to create a command-line quiz game.

The game will be based around a "flash card" style of learning - a simple, one to two sentence explanation of a task, and one or several possible commands that implement it correctly.  

These questions would be assigned difficulty (or obscurity) scores.  For example, an easy (or well-known) question would say, "Go up one directory", to which the answer is simply "cd .." - a more difficult question would ask, "Print the calendar for December of 1789", to which the answer is "cal 12 1789".  The content of questions would be entirely customizable, and available to create using simple plaintext files, thus allowing the game to serve as an open-ended backbone for user-created content.  It would come prepared with several question sets, such as bash and vim commands, to demonstrate this.  

Some ideas for fun game modes:  there may be several types of quiz, including a race against the clock, multiple-choice versus free-type input, and a non-timed test for correctness.  Scoring and a performance breakdown would be available afterwards, if the user chooses to see it.  There will hopefully be a stylish ASCII interface to boot.

Starting a quiz would be a very simple process - either have the user start the executable and use a simple menu, or start a quiz outright using a single command (with quiz name and difficulty as parameters).  Again, it should be as non-intrusive as possible, with the "game" itself serving only as a slim interface and backbone for question sets.  

We fully realize that most of these ideas will change form or be thrown out, and that we may not be able to fully realize the project before the deadline - but feel that as a whole it mirrors the programming philosophy and goals of this course.

**Comment by mikeizbicki** [comment]
Possibly.  We'll have to talk about this more in person.  Can you meet Friday after class?

**Comment by fundamelon** [comment]
https://github.com/fundamelon/quiz-game-tutorial

Not quite at 50% yet, but the group now has solid footing.  Please let us know if this is headed in the right direction.  Also note that none of us are available for office hours on Tuesday, since we all are in a class during those hours.

**Comment by mikeizbicki** [comment]
We should probably talk Friday after class.  Your project doesn't seem to be going in the direction I remember talking about.  In particular:
1. You quiz questions seem bad.  For the ones I looked at I could easily think of alternative answers that are just as valid.
2. I can't tell what exactly your repo is supposed to be.  Is it a quiz game or a tutorial on how to write a quiz game?  These are _very_ different things, and you can't do both.
