### ISSUE TITLE
HW4 Proposal

### ISSUE THREAD

**Issue by cdixi001** [mikeizbicki/ucr-cs100#1524]
Inf. Peter Hung and I would like to do a project to help people become more familiar with piping and input/output redirection. We want to create an tutorial that asks the user to use one-line bash commands composed of combinations of piping and redirection to perform an increasingly difficult series of tasks. Those tasks, if performed correctly, would result in a file containing a fun story or perhaps some further information on piping and redirection.
For example, one of the tasks could be "use grep to put into 'mikenike.txt' the names of all files in the current directory that contain the phrase 'magic mike (izbicki)'".
"grep -r "magic mike" .  > ike.txt" would be an acceptable answer.
At each step, we would check if their answer works or not.
Any feedback would be appreciated.

**Comment by mikeizbicki** [comment]
Possibly.  We'll have to talk more about this in person.  Can we meet Friday after class?

**Comment by phung001** [comment]
I should be able to meet with you instead
