### ISSUE TITLE
HW4: Wiki for a javascript game OR C++ data structures visualizer

### ISSUE THREAD

**Issue by DoranCals** [mikeizbicki/ucr-cs100#1525]
Curvytron (https://github.com/Elao/curvytron) is a Tron-like game where players move around a 2D field avoiding each other's damaging trails. The game's documentation explains how to set up the game, but provides no info on its mechanics or customization options. I plan to study the game and document its gameplay, including movement speeds, collision behavior, and the various powerups whose effects are often unclear. I'll put my documentation either in Markdown pages or GitHub wiki entries, whichever people pay attention to more.

---

Alternatively, I'll create a visualizer in C++ for contiguous arrays, linked lists, and other commonly-used data structures. It'll allow the user to insert, delete, and rearrange the elements of the data structure and print its contents in an appropriate manner. It'll help CS014 students most, but CS012 and CS013 students will probably get some use out of it as well.

**Comment by mikeizbicki** [comment]
We'll have to talk more in person about the curvytron idea.  Can you meet with me Friday after class?

I think the other idea is too ambitious for the amount of time you'd have.

**Comment by DoranCals** [comment]
Sure, I'll stay in Friday.
