### ISSUE TITLE
HW 4 idea

### ISSUE THREAD

**Issue by Renee7547** [mikeizbicki/ucr-cs100#1526]
I noticed that there is not enough materials to refer to when we use git command. i.e. in recent two labs, we should fork our partner's repository, git push the changed files, and make pull request. But what we should do is very different from the "fork-a-repo" tutorial given in lab. And also, about the assignment, we always need to delete tags and assign new one, but when it's about the due, time is very limited to search for appropriate process, a structured tutorial would be helpful.

So I am considering if we could write a detailed tutorial about git, which would cover the commands that are likely to be used during this class.

partner: @hzhu007

**Comment by mikeizbicki** [comment]
> But what we should do is very different from the "fork-a-repo" tutorial given in lab.

How so?  It seems the same to me.

> So I am considering if we could write a detailed tutorial about git,

There are already lots of git tutorials, and I'm not sure how yours would be different.  One possible thing you could do related to git is to organize all of these tutorials better so that the material is more accessible.
