### ISSUE TITLE
HW4 proposal

### ISSUE THREAD

**Issue by echan031** [mikeizbicki/ucr-cs100#1527]
I have a few ideas that I may want to do, I'm not sure which, if any, are appropriate or will be approved. One is adding documentation on topics on how to submit assignments on git, such as cloning a repository, forking, issuing a pull request, pushing and pulling onto git. I was confused on how to do many of these things early in the class. Another idea is improving the makefile tutorial, as reading it, I believe it did not have all the information needed for me to make the makefile for all the assignments.

**Comment by mikeizbicki** [comment]
> One is adding documentation on topics on how to submit assignments on git, such as cloning a repository, forking, issuing a pull request, pushing and pulling onto git. I was confused on how to do many of these things early in the class.

If there's something wrong/lacking in the current documentation, then I'd greatly appreciate a fix!  But I don't want you to just repeat what's already there.

> Another idea is improving the makefile tutorial, as reading it, I believe it did not have all the information needed for me to make the makefile for all the assignments.

I agree that the Makefile tutorial could be improved a lot.  It's very dense right now and could use some more explanation with the examples.

---

Before I approve either of these topics, I would want to see a _detailed_ breakdown of how _exactly_ you would improve the existing documentation.
