### ISSUE TITLE
Question about open syscall

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1531]
In the open man 2 page it says you can either use open like this
`int open(const char *pathname, int flags);` or `int open(const char *pathname, int flags, mode_t mode);`
When would you use one or the other?

**Comment by markasfour** [comment]
[This](https://www.ibm.com/developerworks/community/blogs/58e72888-6340-46ac-b488-d31aa4058e9c/entry/understanding_linux_open_system_call?lang=en) page gives a good straightforward explanation to when to include the `mode` argument with examples.

Essentially, you would only pass in the `mode` argument when a new file is created by `open` to define [file permissions](https://en.wikipedia.org/wiki/File_system_permissions) (like the `read` and `write` permissions).  If a new file is not being created, the `mode` argument is ignored.
