### ISSUE TITLE
HW2 Testing

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1533]
While testing I came across a testcase for redirection: >filename ls -al  
I was wondering if we have to handle a case like this or we can ignore it.

**Comment by mikeizbicki** [comment]
I don't understand what you mean by "can we ignore it?"  The specs don't say what to do, so you're free to do anything reasonable as long as you document it and test it.

**Comment by mikeizbicki** [comment]
Reopening so that others can see.
