### ISSUE TITLE
HW2 I/O Redirection

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1539]
When doing input and output on one line like, cat < infile > outfile, how should i approach this?  When i test this, it acts strangely and tries to do one and then the other

**Comment by mikeizbicki** [comment]
This question is far too vague for me to help you.  Can you be more specific about your question other than just "how do I approach this?"

**Comment by htang014** [comment]
Err sorry.  I wasn't sure what I was asking either.  So in the end I managed to get input redirection working by performing it before output redirection.  You can close this now
