### ISSUE TITLE
Set up meeting time

### ISSUE THREAD

**Issue by TheBoop** [mikeizbicki/ucr-cs100#1540]
Hi Mike, I couldn't follow you to ask questions about hw2 and hw4 after lecture today.
Is it possible to set a meeting time? It won't take long just some questions that's better discussed in person. I'm free after 3 pm today.

David

**Comment by mikeizbicki** [comment]
Would Thursday at 12:40 in WCH110 work?

I'm closing this issue just so it's not on the main page.  I'll still be checking for your response.

**Comment by TheBoop** [comment]
Yes that would be fine

**Comment by mikeizbicki** [comment]
Ok, see you then.
