### ISSUE TITLE
Capturing ctrl+c

### ISSUE THREAD

**Issue by ykamo001** [mikeizbicki/ucr-cs100#1541]
Hey Mike, 
I noticed that in bash if you enter in a command like: `cat > file1`, then it would allow you to keep entering whatever you wanted until you pressed `ctrl+c` to exit it. I implemented this features into my rshell, but if the user enters `ctrl+c`, it ends my entire rshell program. I was wondering if there's a way to properly catch this input from the user instead of ending the entire program. I know you can use `sigaction` or `signal`, but I'm still not sure how to implement them or how they work. Any help would be appreciated it.

**Comment by mikeizbicki** [comment]
This is part of your next assignment.  We'll be going over how to do it Friday and Monday next week.  I don't expect you to have it working for this assignment.

**Comment by ykamo001** [comment]
ohhh alright, thanks!

**Comment by mikeizbicki** [comment]
Reopening so that others can see the question.
