### ISSUE TITLE
Testing with gdb

### ISSUE THREAD

**Issue by tortas** [mikeizbicki/ucr-cs100#1542]
I tried to use what I learned in lab on gdb for this homework and its giving me some grief in hammer. I'm ssh-ing from home and when I compile my code with the `-g` flag and then run the executable with gdb I get the following error message:

`Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.7.x86_64 libgcc-4.4.7-11.el6.x86_64 libstdc++-4.4.7-11.el6.x86_64`

So I tried installing the package but I do not have permission. Should I avoid gdb right now while in hammer?

**Comment by mikeizbicki** [comment]
I can't help you unless you provide the exact sequence of steps you used to recreate the problem.

**Comment by avere001** [comment]
It only displays that after your program has exited. I think that message is for when trying to debug programs like `/bin/ls`([more info here](https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html)). gdb should still work just fine, and it does for me.
