### ISSUE TITLE
I/O testing

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1543]
Are the only possible ways to use I/O
command > outfile
command >> outfile
command < infile
command < infile > outfile
command < infile >> outfile
If so, are those the only cases I need to have working?

**Comment by mikeizbicki** [comment]
First, the correct term is I/O _redirection_.  Second, I don't know what you mean by "working."  There are dozens more test cases that would involve IO redirection somehow.

**Comment by mikeizbicki** [comment]
For example, what about the following test cases that you did not list:

```
command >
```

```
> outfile
```

```
>
```

You must be able to handle all of these as well.

**Comment by ghost** [comment]
I mean what are valid ways of using I/O without piping yet. Like you wouldn't do command > outfile < infile or command > outfile > outfile. I'm not too sure under what other cases I/O redirection we need working.

**Comment by kevdev158** [comment]
Should we be able to handle cases like `command > file1 flag > file2` (just cases where the flags come in between the redirection) or is it up to us to define those cases?

**Comment by mikeizbicki** [comment]
Your choice of words in not very clear.  Of course you must "handle" that case.  You must "handle" all possible cases.  But since the specifications don't explicitly state _how_ to "handle" it, you are free to do whatever you want as long as you document the behavior.
