### ISSUE TITLE
The <<< operator

### ISSUE THREAD

**Issue by donei003** [mikeizbicki/ucr-cs100#1544]
So I'm trying to do input redirection with a string. But, with the < operator we are opening a file. So how do we then pass the string as input if we cannot open it, since it's a string and not a file?

To do this do I need to call echo and pipe that into something like cat if the command is something like 
"cat <<< hello world"?

**Comment by mikeizbicki** [comment]
There are many correct ways to handle the `<<<` extra credit.  The way you propose seems fine, but other ways would work as well.
