### ISSUE TITLE
The  <<< operator

### ISSUE THREAD

**Issue by ChannelJuanNews** [mikeizbicki/ucr-cs100#1552]
For the extra credit, does it matter if it just works as a standalone command or do we need it to support chaining with other commands as well. 

So if we do `cat <<<  "this is a string"` and it works, do we need to do implement that with piping and the other input/output redirection in order to get the full 20 points?
(i.e. `cat <<< "this is a string" > file.txt` or `cat <<< "ls -a" | grep ls)`

**Comment by mikeizbicki** [comment]
It can't work just by itself.  You need to support both of the examples you listed.
