### ISSUE TITLE
Valgrind possible memory leak

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1555]
Valgrind is reporting a possible memory leak on the line in which i call getline(cin, mystr).  Is there any reason that this could happen?  I don't remember getline ever calling the heap.

Further, the possible leak does not seem to expand as the program loops, its always 29 bytes in 1 block

**Comment by srufe001** [comment]
You don't lose points for "possibly" and "reachable" memory leaks.

**Comment by mchen046** [comment]
We are only being graded on the 'definitely lost' section.

**Comment by srufe001** [comment]
#1547
