### ISSUE TITLE
hw 4

### ISSUE THREAD

**Issue by kchan049** [mikeizbicki/ucr-cs100#1556]
hw4 draft is due soon and how do i submit the draft? we are doing videos and documentation about inodes data blocks and linking

**Comment by kchan049** [comment]
hw4 draft is due soon and how do i submit the draft? we are doing videos and documentation about inodes data blocks and linking

**Comment by mikeizbicki** [comment]
Just reply to your previous issue with your progress.  You can attach/link any files you need me to look at.
