### ISSUE TITLE
bizarre tee piping issue

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1559]
When I pipe output to "tee outfile" and I attempt to pipe that output to another command, it creates an empty file

However, if I do the same thing with the --append flag, it works correctly.  Could this more likely be a permissions issue or an issue with my I/O redirection?

**Comment by mikeizbicki** [comment]
You need to be much more detailed with your question.  In particular, you need to show the exact sequence of commands you're running and their output.  There are literally millions of possible things that could be wrong and we can't narrow down the search without more information.

**Comment by htang014** [comment]
Well, when I run `cat outfile | tee newoutfile | sort`,  i get an empty newoutfile.  However if i run `cat outfile | sort | tee newoutfile` or `cat outfile | tee -a newoutfile | sort` I end up with proper outputs

**Comment by mikeizbicki** [comment]
You're still not giving us enough information.  What are the contents of the files before running the commands?  What is the overall output of the command?  Are you running on hammer or your own computer?

**Comment by htang014** [comment]
On hammer, in my rshell directory, there is one file called outfile.  Its contents are
G
A
C
D
E
F
B
When performing the command `cat outfile | tee newoutfile | sort` or anything in which the output of tee is piped into another command, it creates(or overwrites) newoutfile with emptiness.

**Comment by mikeizbicki** [comment]
You still haven't told me the output of the command to stdout?

**Comment by htang014** [comment]
sorry, the command above will output
A
B
C
D
E
F
G
to the screen.

![capture](https://cloud.githubusercontent.com/assets/7118443/7669471/bd3e41ca-fc29-11e4-975a-05b32d6f0dda.PNG)

**Comment by mikeizbicki** [comment]
If I understand correctly, the following two commands will give the same output:

```
cat outfile | tee newoutfile | sort
```

and

```
cat outfile | sort
```

So one possible problem is that you're not actually piping through the middle commands.  You're just sending the output of the first program directly to the last program.  You need to design some tests to check if this is happening.

**Comment by htang014** [comment]
no, actually it will run tee, and create this "newoutfile", but the file will be blank unless i pass the -append flag to tee, or unless tee is the last piped command.  As far as my testing goes, this only happens with tee, all other commands that I have tested pipe fine

**Comment by mikeizbicki** [comment]
Just because you run `tee` doesn't mean you're piping things to it.

**Comment by htang014** [comment]
So further testing in ~/rshell:
`ls | cat | tr A-Z a-z | grep l` outputs:
license  #tr converts correctly
makefile
outfile

When a files "out" contains:
G
A
C
B
D
E
F
`cat < out | tr A-Z a-z | sort | tee newout > newout2` sends to newout and newout2 correctly:
a
b
c
d
e
f
g

However `cat < out | tr A-Z a-z | sort | tee newout | grep A` will correctly send 'a' to stdout but newout is blank.  Im considering the possibility that it simply isnt piping, but Im not sure why rshell pipes properly to any other command

**Comment by mikeizbicki** [comment]
The test cases you list aren't particularly good because they change too many factors.  Better is to just replace the `tee` in the original command with something else that would actually affect the output.  For example, instead of

```
cat outfile | tee newoutfile | sort
```

use `tr` to change the uppercase letters to lowercase

```
cat outfile | tr A-Z a-z | sort
```

Notice that I'm not using quotes in the above example because your rshell doesn't support them.  If this correctly converts the text to lowercase, then you know that you are piping through the middle command.

**Comment by htang014** [comment]
yes it does indeed convert to lowercase properly

**Comment by mikeizbicki** [comment]
Then it sounds like your piping works with everything you've tried except `tee`.  If that's really the case, just document this bug in your README and you won't lose any points.

**Comment by htang014** [comment]
Ok, good to know. Thanks for checking up on this so late at night Mike.
