### ISSUE TITLE
Hammer Issues?

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1563]
I'm probably gonna speak for a few people here. I've noticed that hammer is currently down for some people. We can switch over to 'well.cs.ucr.edu' to finish the assignment. The only difference is that it will be a 32bit system and we do not have cs100 command. Hopefully hammer will be up soon.

On a side note, if this is going on and off, it might be because you have too many background process running. Hammer is preset to only handle 23 process.
#1551

**Comment by avere001** [comment]
I am also unable to log in since last night.

**Comment by mikeizbicki** [comment]
In the future, these issues should be reported to `systems@cs.ucr.edu` who will be able to respond to the incident right away.
