### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1564]
So have allocated memory like this: `char** argv = new char*[size]` and then I do this

```
for(int i =0; argv[i] != NULL; i++)
{
    if (conditon)
       argv[i] = NULL
}
```

That results in a memory leak. But I have no idea how to deallocated it. I've tried this:

```
for(int i =0; argv[i] != NULL; i++)
{
    if (conditon)
        for(i = i +1; argv[i] != NULL; i++)
              delete argv[i]
       argv[i] = NULL
}
```

But I still have a bit of memory leak left

**Comment by yyao007** [comment]
Actually, when you do `char** argv = new  char *[size];`, you allocate an array of pointers and that array  has a size of "size". After that, each element of this array, in other words, `argv[i]`, has one allocated memory in the heap. Because of that, when you do `if (condition) argv[i] = NULL;`, you will lose access to some of the allocated memories in the heap and that is a memory leak, even though you delete the other `argv[i]`s after. You should never change a pointer after you allocated memory for it until you deallocate it. So, you need to do `delete argv[i]` before you change it to a NULL pointer `argv[i] = NULL`.

However, I think you may actually want to allocate memory for `argv[i]` so that you can store a cstring in that. To do that, you only need to declare an array of pointers and then allocate memory for each pointer in the array in a loop. Something like:

```
char *argv[size];
for (int i = 0; i < size; ++i) {
    argv[i] = new char[size];
}
```

and then use `delete[] argv[i];` in a loop to delete every allocated array.

**Comment by ghost** [comment]
Hmm, even with this method, I'm still getting a definite memory leak from running valgrind.
after the for loop ends and i reach the end of my function I do:

```
for(int i = 0; i < size; i++)
{
    delete[] argv[i];
}
```

**Comment by yyao007** [comment]
I didn't notice that you use a if statement to deallocate memory, I don't
know why you are doing that. All you need to do is the for loop to
deallocate the memory.

ZhuLeon notifications@github.com于2015年5月17日星期日写道：

**Comment by ghost** [comment]
Oh no, I'm not using it to deallocate memory, that if statement is just the condition under which I want to set `argv[i] = NULL`. I've tried allocating before I set `argv[i] = NULL` and I've tried deallocating at the end of my function. Either way, valgrind says I have definitely lost a bit of memory.

**Comment by yyao007** [comment]
I mean, all you need is:

```
char **argv = new char *[size];
for(int i =0; argv[i] != NULL; i++)
{
    if (conditon) {
        delete argv[i];
        argv[i] = NULL
}
```

and in the end of you program, deallocate like:

```
for(int i =0; argv[i] != NULL; i++)
{
       delete argv[i]
       argv[i] = NULL
}
```

hope this can help you avoid memory leak.

**Comment by yyao007** [comment]
sorry I lost semicolons.

**Comment by nchun003** [comment]
I was having this same problem as well, I just switched to using `std::vector<char *>` instead of using `char **`. Then there's no memory leaks to worry about since you can just use `push_back` rather than dynamically allocating more memory.

**Comment by yyao007** [comment]
Hmm, I find I lost something in the deallocate part, which should be:

```
for(int i =0; i < size; i++)
{
   if (argv[i] != NULL) {
       delete argv[i];
       argv[i] = NULL;
    }
}
```

**Comment by avere001** [comment]
You should be able to use `std::vector<std::string>` and convert to c style strings using `string_name.c_str()`

**Comment by ghost** [comment]
@nchun003, @avere001  I could try those methods but i'm not sure if it'll work for me because the only reason why i want a `char**` in the first place is so i can pass it into `execvp`
why have a `delete argv[i]` before setting `argv[i]=NULL`? 

```
char **argv = new char *[size];
for(int i =0; argv[i] != NULL; i++)
{
    if (conditon) {
        delete argv[i];
        argv[i] = NULL
}
```

Also using that exact method, my memory leak is worse.
maybe this will help describle my problem more.
I have a `vector<string> argv`. I want to convert it to `char**` so i can use execvp on it. So i do

```
char** argv = new char*[vector.size()+1];
for(int i = 0; i <vector.size(); i++)
{
    argv[i] = new char[vector.size()+1];
    //copy things i vector to argv[i];
    argv[vector.size()] = NULL;
}
```

then I have

```
for(int i =0; argv[i] != NULL; i++)
{
    if (conditon)
       argv[i] = NULL
}
```

Then i try to deallocate at the end of my function

```
for(int i =0; i < size; i++)
{
   if (argv[i] != NULL) {
       delete argv[i];
       argv[i] = NULL;
    }
}
```

However, valgrind is still saying I have memory leaks. 
Also i'm pretty sure the leak is because of `argv[i] = NULL`. If i comment that out, no more leaks.

**Comment by nchun003** [comment]
So if right now you're using `execvp(argv[0], argv)`, and if you switch to using `std::vector<char *>argv` then you just use `execvp(argv[0], &argv[0)`. 
Here's a link to the question I asked on stackoverflow along with the answer i received: http://stackoverflow.com/questions/30291444/valgrind-memory-leak-pointer?noredirect=1#comment48680167_30291444

**Comment by yyao007** [comment]
I got it. When you do `char **argv = new char *[vector.size() + 1];`, you have a vector.size()+1 array of pointers. Then in the for loop below it, you set `argv[vector.size()] = NULL;`, this will exactly cause a memory leak because you didn't delete it first. And because of you allocate a dynamic 2-D array, you should use `delete[] argv[i];` to delete the whole array.

```
char** argv = new char*[vector.size()+1];
for(int i = 0; i <vector.size(); i++)
{
    argv[i] = new char[vector.size()+1];
    //copy things i vector to argv[i];
}
delete argv[vector.size()];
argv[vector.size()] = NULL;
```

and in the end, you do:

```
for(int i =0; i < size; i++)
{
   if (argv[i] != NULL) {
       delete[] argv[i];
       argv[i] = NULL;
    }
}
delete argv;
```

**Comment by ghost** [comment]
Hmmm I tried that but it seems theres a conflict with `delete argv[vector.size()];` and `argv[vector.size()] == NULL;`  If I delete, ill error, if not i wont error
Ive also tried the `vector<char*>` method but its gonna take me a while to convert everything
Thanks a lot btw!!!

**Comment by yyao007** [comment]
Sorry but that's my understand. But why are you need to allocate memory for argv? You can just do

```
char *argv[vector.size() + 1] = {0}; // initialize each element to a NULL pointer
for(int i = 0; i <vector.size(); i++)
{
    argv[i] = new char[vector.size()+1];
    //copy things i vector to argv[i];
}
```

and you do not to `delete argv[vector.size()]` because you didn't dynamically allocate it.
In the end, you do not need to `delete argv;`

**Comment by ghost** [comment]
@nchun003 So im trying to use the method of `vector<char*> argv` but when i pass it into execvp as you described, it doesnt seem to work. Did i miss any steps?

**Comment by nchun003** [comment]
Hmm, as long as values are getting pushed into argv correctly and it's passed into execvp like i described it should work.

**Comment by ghost** [comment]
I couldn't fix it but thanks everyone!
