### ISSUE TITLE
Deleting files

### ISSUE THREAD

**Issue by laurenB93** [mikeizbicki/ucr-cs100#1568]
Before the deadline and before I made the hw2 tag, I deleted a lot of files and my executables from my repository. I made a pull request and made sure everything was up to date. But when I made my hw2 tag, it did not have any of the deletions on there. So the executables are in my bin directory in my repo. I made these commits on master way before I made the hw2 tag and I was not able to fix it in time and I still cannot figure out how. I was wondering if there is any way I will not get marked down for having executables in my repo on the hw2 tag because they are not located on my master branch? I do not want to change my tag because then it will look like I turned it in late.

**Comment by ghost** [comment]
Just fix it before they grade it ... it would be a lot worse if you kept the mistake on there than change it. They can check your git log to see what you changed as well. #1478

**Comment by laurenB93** [comment]
You're right. I changed it. I guess I'll be getting that -10, better than a -50 though! Ha.

**Comment by ghost** [comment]
Quote from Mike:"For both of you, please go back to your repo and fix these mistakes before we look at it. If you fix the mistakes before we actually download the repo then you won't lose any credit."

**Comment by laurenB93** [comment]
Awesome! Thank you.
