### ISSUE TITLE
error checking syscalls

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1571]
So I have never used the check syscalls command in hammer until now to check if I am error checking properly. It turns out I have alot of unchecked syscalls. should I fix them or leave it?

**Comment by mikeizbicki** [comment]
Please fix them.  Your grades for hw0 and hw1 will reflect the negative points, but you can still update hw2 so you don't lose the points.

**Comment by glaceeeee** [comment]
I found that a few of my labs have some unchecked syscalls. Does the syscalls script check labs as well? And should I update hw2 to fix these errors?

**Comment by mikeizbicki** [comment]
Everything within the rshell project needs to have proper error checking on the syscalls.

Yes, you can update your project to perform the error checking.

**Comment by hkwan003** [comment]
so I just checked my grade for my piping assignment and I saw that I got 10 points marked for being late. I recall that you said you would give us an extension to fix all our syscalls.
