### ISSUE TITLE
appointment?

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1572]
Hi Mike

Can I meet with you today if you have time. I am free for the rest of the day. Please let me know?

**Comment by mikeizbicki** [comment]
Yes, I can meet with you at 2PM in WCH110.

**Comment by mikeizbicki** [comment]
I'm here right now.  I'll have to leave in about 5 minutes if you don't show up.

**Comment by hkwan003** [comment]
i am on my way. had to run home real quick

**Comment by mikeizbicki** [comment]
ok, I'll wait
