### ISSUE TITLE
Partial extension for hw2 and error checking

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1573]
A number of students have noticed that they were not doing error checking properly in their hw2 submissions (see #1571).  If this applies to you, I will give you until midnight tonight to update your rshell `hw2` tag to include proper error checking.  Remember that every file in your repo must have this error checking, even if the file is not directly related to the homework submission.

**Comment by hzhu007** [comment]
Gee I was working on the report for my senior design last night and didn't notice this post. In my src some labs' cpp was not checked. Is it possible to make it up today?

**Comment by mikeizbicki** [comment]
@hzhu007 You have until 2PM today.

**Comment by Renee7547** [comment]
I didn't notice this post either, and some of my lab programs were not checked. Can I have a late ddl until 2:30?

**Comment by mikeizbicki** [comment]
@Renee7547 Yes.

**Comment by jpatu001** [comment]
Just a question, I fixed the perrors from the labs we had. Do I need to have it under the hw2 tag? I fixed the errors and all that but pushed it on the master.

**Comment by mikeizbicki** [comment]
@jpatu001  We're not going to grade master.  We're going to grade hw2.  So
it must be under hw2.  Please fix it ASAP.
