### ISSUE TITLE
Extra credit for watching a movie

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1574]
The documentary Citizenfour covers how and why Edward Snowden released government documents showing that the National Security Administration illegally spies on American citizens.  This will be related to some of the material we'll be covering over the next few weeks.

I'd like to arrange a public showing of Citizenfour at UCR (maybe in conjunction with ACM).  I'd need one or two students to volunteer to take care of some of the administrative issues.  Everyone who attends the showing (volunteer or not) would get +5 pts extra credit.

Is anyone interested in volunteering?

**Comment by ghost** [comment]
At what time would this event occur? If we volunteer what time and where would you need us to show up?

**Comment by hkwan003** [comment]
I can talk to them. I am one of the officers for ACM

**Comment by mikeizbicki** [comment]
@ZhuLeon The volunteers would need to decide and arrange all of those details.  Ideally, they would just tell me a time to show up and I'd bring the movie.

**Comment by hkwan003** [comment]
@mikeizbicki so can the movie be in the ACM clubroom. because we can literally do it anytime. all we need to do is grab a projector from bcoe.

**Comment by mikeizbicki** [comment]
The ACM room would be acceptable, but not ideal.  I don't think there's a sound system, and I doubt it would be very comfortable to watch a full movie there.  I think someplace more like our current classroom would be more comfortable.

But yeah, it shouldn't take all that much organization.  Just picking a time and making some announcements.

**Comment by hkwan003** [comment]
ok. i'll ask the other officers how fast we could grab a classroom to show the movie.

**Comment by hkwan003** [comment]
so ACM recently purchased some speakers. Would you be ok with that because it would be super convenient on our part to put this on while bringing more exposure to the ACM club room.

**Comment by mikeizbicki** [comment]
In that case, the ACM room is fine.  Next week either Wednesday or Friday evening works for me.  Pick whichever one of those you think is better.
