### ISSUE TITLE
HW4 rough draft submission

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1579]
Hello Mr. Izbicki,

I am unsure about how to turn in my hw4 rough draft.

Should I be creating a pull request (merge request) to this class's repository directly or should I be pushing to my fork of this class's repository _and then_ submit a pull request (or do they do the same thing?). 

I cloned my fork of this class, added my own directory under the `/textbook/` directory, and have my README.md in that directory.

Also, I have noticed that you ask us to squash our commits before merging when we pull request for extra credit. Should we squash all of our commits into one for this rough draft? I don't understand why if we should.

Thank you,
Mark Asfour

**Comment by glaceeeee** [comment]
Where does it say that we get extra credit for squashing our commits?

**Comment by mikeizbicki** [comment]
The easiest way for you to get good feedback is by submitting a pull request.  But anyway where you can show me your work is fine.

> Also, I have noticed that you ask us to squash our commits before merging when we pull request for extra credit. Should we squash all of our commits into one for this rough draft? I don't understand why if we should.

Yes, all commits should be squashed.  I will discus this in class.

@pockymons  I do not accept pull requests to this repo if the commits are not logically arranged.
