### ISSUE TITLE
Submitting the HW4 draft

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1585]
We did our draft on google doc, and it is far from being ready to be in a pull request due to the formatting and lack of pictures/code. Also we've yet to make the script work all together but we do plan on finishing it up as soon as possible. 

https://docs.google.com/a/ucr.edu/document/d/1YwiilwVdlmdjnu7NqO_a2zK-R_pxqlAvMZ72LsoBBac/edit?usp=sharing

It's a very rough rough draft.

Written by: Dang Tran, Jacky Tran, and Kevin Tang

**Comment by mikeizbicki** [comment]
Please resubmit it as a pull request so I can provide direct feedback.  I won't be accepting the pull request, but it'll be easier for you to get feedback that way.
