### ISSUE TITLE
Draft Submission

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1603]
I was wondering would we send you an new issues page because my group was not working on a cs100 fork but on another repository that we created locally to simulate gitlearn.

**Comment by mikeizbicki** [comment]
Your group's goal is to get everything setup so that you can successfully run all the scripts in the repo.  Don't worry about writing anything until you can run the scripts.

You should just let me know (via an issue) when you're at that point.  Your goal should be there by Monday next week.
