### ISSUE TITLE
HW3 Grading

### ISSUE THREAD

**Issue by donei003** [mikeizbicki/ucr-cs100#1615]
Assignment 3 is due next Friday and we still have not yet received our grades for hw1 or hw2. As far as grading goes, what if there was some sort of bug or lack of error checking or anything else on hw2. Since we still have not gotten our grades back, then that problem is likely to still exist without feedback. Will we still be losing points on our assignment for the persistent bugs? Personally, it doesn't seem fair, to keep losing points without any feedback. How is this going to work?

**Comment by mikeizbicki** [comment]
You will not lose points multiple times for the same mistakes.  So if you missed something on hw1, you will not lose points for missing it again on hw2.  

We will discuss grades more in class on Wednesday.  I'm sorry your grades are taking so long.
