### ISSUE TITLE
Star Repos EC

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1617]
Hello Mr. Izbicki,

I have starred 20+ github repos that I have found cool and interesting, enough for the extra credit.

[Here is my github page](https://github.com/markasfour).

Thank you,
Mark Asfour

**Comment by ghost** [comment]
Same, I have 20+ star repos that I found interesting.

Andrew So

**Comment by laurenB93** [comment]
I also did this. :)

On Sunday, May 24, 2015, Andrew So notifications@github.com wrote:

> Same, I have 20+ star repos that I found interesting.
> 
> Andrew So
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikeizbicki/ucr-cs100/issues/1617#issuecomment-105092846
> .

## 

Lauren Boyd
861018398

**Comment by mikeizbicki** [comment]
Awesome!  +5 pts extra credit for everyone!
