### ISSUE TITLE
hw4 video script 

### ISSUE THREAD

**Issue by zzhou007** [mikeizbicki/ucr-cs100#1619]
Can you read over the script for the two video for hw4 and give me some feedback?
https://github.com/zzhou007/links/tree/master/script

**Comment by mikeizbicki** [comment]
Didn't I already give you feedback on this from your previous pull request?

**Comment by zzhou007** [comment]
Can you go into detail about how i should format the video so i don't confuse the viewers?
for the links video i formatted it so it something like:
links link file names to inode (watch inode video to learn more)
making a hard link
using ls -i to show both share the same inode
writing to one file to show changing one changes the other 
using the touch command to change the time to show the time changes for both 
deleting the original file to show the new hard link i just created still works 
using the ls -l command on an empty folder to show the . and .. are hard links

making a soft link
using ls -i to show the inode numbers are different 
change one file and showing it changes the other file 
using the touch command to show changing the time for one does not change the time for the other 
deleting the original file and showing the soft link i created no longer works.

can you please recommend some changes to make the videos better and less confusing? Is the format for the videos wrong? Am I missing something I should talk about? thank you

**Comment by zzhou007** [comment]
For the inode video I plan on cutting out any coding and just making a power point 
the format for the power points is:
What are inodes and the info it stores 
show a picture of directory entries pointing to inodes and the data stored in the inode points to other inodes 
go over data blocks and how data is stored in them 
go over fragmentation and what defraging does 

can you please comment on the format and tell me if im missing any important information or if i should removing anything?

**Comment by mikeizbicki** [comment]
I won't approve videos based on powerpoints.  Those convey less information than a written article and take longer to watch than the article would to read.

The examples you list don't talk about the "why I should care" aspect at all.  They seem like they cover the "how" aspect, but without the "why", no one will watch them.

You can still do the videos if you want, but my recommendation is to just do a writeup.  If you choose to do videos, plan on spending about 20 more hours working on it than you would just the writeup.

**Comment by zzhou007** [comment]
How about the video on how to use links a write up of examples on using links and a write up on inodes and data blocks instead of a video for anyone interested to learn about it.

**Comment by mikeizbicki** [comment]
I answered this question in your other comment.  Let's keep all the discussion in #1618 to make things easier to follow.
