### ISSUE TITLE
Hw3 Extra credit clarification

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1621]
I was wondering in order to to get the second part of the extra credit, it would have to give the following output if we are in the user's home directory: `aso001@cs100:~/CS100 $` ... not something like this right: `aso001@hammer.cs.ucr.edu :  /home/csmajs/aso001/CS100/$`?

**Comment by mikeizbicki** [comment]
Correct.

PS. I've updated your question to what I think you were asking.

**Comment by ghost** [comment]
Our code  also has to realize that we are in `cs100` ... not just hammer? Right? Or is `hammer` still acceptable?

**Comment by mikeizbicki** [comment]
@aso001  I don't understand your question.  Calling `cs100` doesn't affect `$HOME`, so your rshell will behave the same whether you've run `cs100` first or not.

**Comment by ghost** [comment]
ok nevermind ... I wasn't thinking my question clearly.
