### ISSUE TITLE
movie showing

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1627]
So the room scheduling is completely packed for Wednesday. Is there any way that we can do it on Thursday?

**Comment by mikeizbicki** [comment]
I'm not available on Thursday.  I think I should to be there in order to take attendance and answer questions.

**Comment by cdixi001** [comment]
I couldn't make the movie due to timing conflicts. Could I watch it on my own and discuss it with you to receive the extra credit?

**Comment by mikeizbicki** [comment]
@cdixi001 Sorry, but no.

**Comment by isadoramariamendes** [comment]
Is there anything that can be done to students who lost it?
I had class at the extension center during the same time...

**Comment by mikeizbicki** [comment]
No.  We might have been able to work something out if you contacted me
beforehand.  But I can't do anything when I'm told about these things
afterward.
