### ISSUE TITLE
Setting up SSH server

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#1631]
So I need to show that I've installed linux but I have a desktop computer so I can't bring it to show Mike. I think I have to setup a SSH server but I'm having trouble getting it to work. Is there another way to show that we've installed linux? or
Has anyone using ubuntu 14.04 managed to setup a SSH server and can help?

**Comment by mikeizbicki** [comment]
Yes, that's how you should demo linux.  You should contact the mailing list for your distribution or unix.stackexchange.com for help.

**Comment by ghost** [comment]
If I brought in a laptop tomorrow that I installed Linux on, would I get full credit?

**Comment by mikeizbicki** [comment]
yes
