### ISSUE TITLE
Appointment 

### ISSUE THREAD

**Issue by markasfour** [mikeizbicki/ucr-cs100#1634]
Hello Mr. Izbicki,

If it is possible, may I schedule an appointment with you sometime between 2 - 5 tomorrow (Thursday)?

I would like to discuss some things class and non-class related. 

Thank you,
Mark Asfour

**Comment by mikeizbicki** [comment]
I can meet with you at 3:30 in WCH 110.

**Comment by markasfour** [comment]
I will see you then.
