### ISSUE TITLE
Can't Sign into Hammer

### ISSUE THREAD

**Issue by laurenB93** [mikeizbicki/ucr-cs100#1638]
Is anyone else having trouble signing into hammer? I try to sign in and logs me out right away. I got signed in one time and I turned on the cs100 settings and the command prompt printed out "'I have no name!'@hammer:"  I don't understand what is going on...

**Comment by laurenB93** [comment]
Now it works on cs100 settings but I am still getting that "I have no name!@hammer"..

**Comment by mikeizbicki** [comment]
You should contact `systems@cs.ucr.edu` about issues like this.  They're the ones in charge of the server and can help you out.
