### ISSUE TITLE
Extra credit question

### ISSUE THREAD

**Issue by ChannelJuanNews** [mikeizbicki/ucr-cs100#1643]
Just a question about [the extra credit reading](https://github.com/jruel006/ucr-cs100/tree/2015spring/assignments/ec/ec-reading)

Is it 10 points extra credit PER book or is there only a 1 book limit of 10 extra credit points?

**Comment by mikeizbicki** [comment]
It states at the bottom: "In addition, you may only read one of these books for extra credit during the quarter."
