### ISSUE TITLE
Hw3 ^C result not constant

### ISSUE THREAD

**Issue by knels012** [mikeizbicki/ucr-cs100#1648]
When I run rshell, any of these 3 things can happen, and they aren't consistent on which one happens.
1. ^C seems to work fine the first time, but pressing ^C again quits rshell. If I press ^C the first time in the middle of running a program, `wait: Interrupted system call` is outputted, before return to rshell prompt.
2. ^C works perfectly every time, interrupting the child process being run if one is being run, and not exiting shell ^C while waiting for the user to input something after the prompt.
3. The prompt is infinitely outputted, without stopping to wait for the user to input anything.
If 1 or 3 kept happening consistently I might be able to fix it, but because it's so inconstant, I'm not sure what's wrong.

**Comment by hzhu007** [comment]
Do you use `sigaction` correctly at the beginning of your main?
#1626 This may be helpful.

**Comment by mikeizbicki** [comment]
Closing due to @hzhu007's reference to another post.
