### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by laurenB93** [mikeizbicki/ucr-cs100#1649]
I have been trying to figure out how to fix a memory leak in my cd implementation, but I cannot find it. It is only when I use 'cd -'. Would I lose a lot of points on the assignment if I can't find where the memory leak comes from? I have been trying to fix it but I can't find it anywhere. Is there any way I can get help fixing it before it is graded?

**Comment by hkwan003** [comment]
yea I just found one also. should I fix it right now too and submit?

**Comment by mikeizbicki** [comment]
Sorry, it's past the deadline.  These questions need to be asked much sooner to get detailed help with them.

If you're still interested for curiosity's sake, I can help you during office hours.

**Comment by hkwan003** [comment]
so since I fixed it the next morning and I retagged it at that time. Am I going to get like a zero on the assn?

**Comment by mikeizbicki** [comment]
@hkwan003 You will not get a zero.

**Comment by hkwan003** [comment]
but will i get docked for being late though?

**Comment by mikeizbicki** [comment]
Possibly.  We can discuss your grade after it's graded, but there's no point in discussing it before then.

**Comment by laurenB93** [comment]
Would I be able to discuss my grade with you as well? I wasn't able to fix
my memory leak but I retagged it Saturday morning. Could I get it graded on
the commit/tag where I submitted it on Friday night?

On Sunday, May 31, 2015, Mike Izbicki notifications@github.com wrote:

> Possibly. We can discuss your grade after it's graded, but there's no
> point in discussing it before then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikeizbicki/ucr-cs100/issues/1649#issuecomment-107314500
> .

## 

Lauren Boyd
861018398

**Comment by mikeizbicki** [comment]
@lboyd002 Of course we can discuss your grade, but let's wait until after the assignment is actually graded to do so.  I think you'll find that more useful.

**Comment by laurenB93** [comment]
Okay, but I can come to office hours to see if we can find my memory leak ?

On Sunday, May 31, 2015, Mike Izbicki notifications@github.com wrote:

> @lboyd002 https://github.com/lboyd002 Of course we can discuss your
> grade, but let's wait until after the assignment is actually graded to do
> so. I think you'll find that more useful.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikeizbicki/ucr-cs100/issues/1649#issuecomment-107315458
> .

## 

Lauren Boyd
861018398

**Comment by mikeizbicki** [comment]
Certainly.
