### ISSUE TITLE
Concern over HW2 grading

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1650]
I am concerned over how HW2 was graded. Number one, I got -10 points for late submission, though the reason why my last commit was Monday was because you (Izbicki) said we have until Midnight to fix our error checking. Another concern I have was that my grading feedback says piping with one and multiple commands doesn't work. I demonstrated in my test script that it does and I actually tested about 10 minutes ago and multiple pipes as well as one pipe works.

**Comment by ghost** [comment]
I noticed the same thing because I went back and check for the the extra credit ... I did show in the test script.

**Comment by mikeizbicki** [comment]
It's very easy to make mistakes while grading.  The easiest way to get the mistakes fixed is to come to office hours.  If we made a mistake like you say, you'll definitely get the points back.
