### ISSUE TITLE
grading on HW2 and fixed memory leak after deadline on HW3

### ISSUE THREAD

**Issue by hkwan003** [mikeizbicki/ucr-cs100#1651]
So I just saw my grade for HW2 and i recall you said you would give an extension to fix the non perror syscalls for HW2. I fixed them within the extension deadline and I got a minus 10 point deduction on my piping grade. can this please be resolved.

Also I check for memory leaks after the Friday deadline sometime Saturday morning. I pushed the commit and retagged. Am I going dock like crazy amount of points for a late submission?

**Comment by laurenB93** [comment]
I also did the same on both accounts. -10 for last assignment and I tried
fixing a memory leak on the last assignment and it didn't work. But I also
pushed a commit and retagged.

On Saturday, May 30, 2015, Calvin Kwan notifications@github.com wrote:

> So I just saw my grade for HW2 and i recall you said you would give an
> extension to fix the non perror syscalls for HW2. I fixed them within the
> extension deadline and I got a minus 10 point deduction on my piping grade.
> can this please be resolved.
> 
> Also I check for memory leaks after the Friday deadline sometime Saturday
> morning. I pushed the commit and retagged. Am I going dock like crazy
> amount of points for a late submission?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikeizbicki/ucr-cs100/issues/1651.

## 

Lauren Boyd
861018398

**Comment by ghost** [comment]
I too have this issue

**Comment by mikeizbicki** [comment]
We can resolve all grading mistakes during office hours.
