### ISSUE TITLE
Hw2 grading

### ISSUE THREAD

**Issue by kchan049** [mikeizbicki/ucr-cs100#1652]
Hi Mike, 
I asked you in office hours if I could fix my makefile and you allowed me to. I scored a 120 on hw2 but Busra gave me 0 points because she said it was late.

**Comment by mikeizbicki** [comment]
Grading mistakes are best resolved in person during office hours.  Can you make it to my office hours?

**Comment by mikeizbicki** [comment]
Closing the issue so it doesn't spam everyone.
