### ISSUE TITLE
Assignment regrade details

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1657]
Regrades for hw0, hw1, and hw2 will happen during our regularly scheduled finals time: Tuesday Jun 9th from 8-11AM.  We will meet in WCH110, and you must arrive on time.  If you are late, your assignments will NOT be regraded.

You may ask for any/all assignments to get regraded.  For each assignment, there will be a -40 point penalty for getting the regrade.  Your final grade on the assignment will be the regrade I give you during the finals period, even if this is lower than your original grade.  My expectation is that everything will be perfect on these regraded submissions.  I will be grading very strictly.

If there was a mistake in your grade, we will of course correct the mistake without giving you any regrade penalty.

There will be no regrades for hw3.

**Comment by jtran071** [comment]
Just making sure, did you mean Tuesday? Our final is on June 9th and it is a Tuesday.

**Comment by mikeizbicki** [comment]
Yes, thanks.  I've updated the announcement.

**Comment by kevdev158** [comment]
Hi,
I know this is asking a bit too much, but is it possible to get HW3 reevaluated for compilation errors? It was my mistake for not running it on hammer first before submitting. I opted for `secure_getenv` instead of `getenv` and it so happened to not work on hammer.
Thanks.

**Comment by mikeizbicki** [comment]
@ktang012 If there is time on Tuesday, I will regrade your hw3 submission.

**Comment by alvtdev** [comment]
Would we be able to show you any extra credit things (e.g. xmonad, tor, etc) during the scheduled final time?

**Comment by mikeizbicki** [comment]
@athai005 Yes, the finals time is for anything grade related that needs updating.

**Comment by knels012** [comment]
If we forgot to commit the signals script for hw3, would it still be possible to at least get a regrade for it?
