### ISSUE TITLE
Optional hw4 extension

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1658]
Your hw4 is due Friday this week.  The last time I will be able to review your work before your final submission is Tuesday during office hours.  So if you want feedback, you must get it to me your draft before then.

Everyone is eligible to have the deadline extended until up to Wednesday Jun 10th.  To get this extension, please reply to this post with the time/date you will submit your project and a one sentence description of why the deadline extension will help you.

Remember to review issue #1632 carefully before submitting your assignment.

**Comment by dtran049** [comment]
Our group would like to extend our deadline date until Tuesday  Jun 9th at 11:59 PM.  Two of us have a final on Saturday Jun 6th and another has a final on Mon Jun 8th along with a final project due on Jun 5th.

**Comment by hkwan003** [comment]
Hi Mike

The Git Game group would like to have our due date extended until Tuesday 2pm. The reason is that the majority of our group have multiple final projects to finish on top of the git game as well as multiple finals on Saturday.

Thank You
Git game 2.0

**Comment by kluu006** [comment]
Hi Mike
Can my partner (Sandie Xie) and I get an extension on homework 4 until Monday June 8th at 11:59 PM? We both have projects due on Friday June 5th and finals on Saturday June 6th. Thank you.

**Comment by nchun003** [comment]
Mike, 

Our group requests to have an extension untill Tuesday June 9th at 11:59 PM. One of us has a project due on June 5th and a final on Monday June 8th, another has a final on Monday and the third person has a final Saturday June 7th.

Thank You.

**Comment by kchan049** [comment]
Hi Mike,
My partner and I would like to get an extension for homework 4 until Tuesday 9th at 11:59 PM. My partner and I both have two finals on Saturday and a final on Monday as well. I also have a final project for another class due on Friday. 
Thanks,
kchan049 and zzhou007

**Comment by jle034** [comment]
Hi Mike,
I would like to get an extension until Tuesday 06/09 at 11:59pm. I have a final project due Friday and finals on Saturday and Monday that I need to focus on in addition to the hw4 for this class.
Thank you.

**Comment by amah001** [comment]
My partner, ecarr007, and I would like to have an extension until Monday, June 8th, 11:59 pm. I have a final project due on Friday as well as a final on Saturday while my partner has an essay to do.

**Comment by avere001** [comment]
I would like an extension until the end of Tuesday the 9th. I have a midterm early saturday morning that I would like to study for and an essay due Monday that I will be working on this weekend. 

Thank you

**Comment by jkinc002** [comment]
I would like an extension until Tuesday, June 9th. I can show up at 12:00-12:30 and wait until you're open to review my work. I'd like to use my time this week to study for a final I have this Saturday.

**Comment by sthak004** [comment]
Hi Mike,
I would like an extension till Tuesday the 9th at 11:59 pm as I have an essay due Friday as well as a final on Saturday.

Thank you.

**Comment by tortas** [comment]
Mike, 
I would like an extension to Monday 11:59pm. I have a very scary final Saturday morning and I will need all the time I can have this week to study for it. Thank you.
Cheers.

**Comment by laurenB93** [comment]
Hi Mike,
My partner (Leon Zhu) and I would like an extension until Tuesday, June 9th at 11:59pm. We both have finals on Saturday at different times and we would like to study for them as much as we can this week. We also have other class homework assignments due Thursday.
Thank you.

**Comment by phung001** [comment]
Shalom Mike,
My partner Chirag Dixit (cdixi001) and I are requesting an extension until Tuesday, June 9th at 11:59pm. We have a project for CS120B due on Friday, 2 finals on Saturday, and a final Monday morning. An extension would give us adequate time to prepare some more examples and give more detailed explanations in our tutorial. Thank you for your consideration.

**Comment by markasfour** [comment]
Hello Mr. Izbicki,
I would like to request an extension for hw4 until Tuesday, June 9th at 11:59 pm.  My final project for CS120B is due this Friday, I have a HIST109 final and CS120B final on Saturday, and I have an EE20 final on Monday.  I would use this additional time to give my documentation on vimscripting the time it deserves with adequate examples.  
Thank you,
Mark Asfour

**Comment by jmeji011** [comment]
Hi Mike,
I would like an extension until Tuesday, June 9th at 11:59 PM. I have a final project due on Friday and two finals on Saturday, so an extension would be great.
Thank you.

**Comment by glaceeeee** [comment]
Hi, 
I'd like an extension until Tuesday, June 9th at 11:59 PM. I have a final on Saturday as well as projects and homework to submit this week. Also, my project, the Boost Tokenizer tutorial expansion, will probably used a lot by future cs100 students, so I would like to make it as high quality as possible.

**Comment by divyanshch** [comment]
Hi,
We (Hannes, Siddu, and Divyansh) would like to request for a extension until Tuesday, June 9th at 11:59 PM. As everyone in my group has final on Saturday and my other two partners have a final on Monday, the extension would be helpful for us as we have had to change some of the documentation we are working on, and as you pointed out it needs to be redone. Thank you for the consideration.

**Comment by cbarb005** [comment]
Hi, I'd like an extension since I have a final paper due Monday morning, as well as a final I need to extensively study for (on thursday, but the passing rates for the final are dismal, so I'd like to avoid failing). I can probably have it done before Monday at 11:59, as the extension is more or less for polish and for the FAQ sections. I would prefer to have it done by this Friday, but if and when something goes wrong, the extra time would really help!

**Comment by TheBoop** [comment]
Me and my partner (Jerome Barbero) would like an extension to Monday night at 11:59 pm. For me it was a very late midterm this week and would like to to study for finals, and my partner has final Monday. 
Thank you

**Comment by Kilenaitor** [comment]
Hey Mike, I'd love an extension to Wednesday, June 10th to finish up the work on the project now that I have all of the gdb stuff sorted out and have the ball rolling on that implementation! Thank you.

**Comment by jpatu001** [comment]
Hey Mike, Can I have an extension for hw4 to Monday (june 8). The reason is I have a final project due by Friday and two finals on Saturday. Thanks

**Comment by fvera002** [comment]
Hi Mike,
Isadora (@isadoramariamendes) and I would like an extension to Wednesday (June 10th) night at 11:59 pm since we have a huge project due this week for the certification class we are attending on UCR Extension and this extra time to finish up and reorganize our hw4 would be great.

**Comment by UrielNaranjo** [comment]
Hi Mike, 
My group (Igi and Korbin) would like an extension to Tuesday Jan 9th at 11:59 PM as we all have finals coming up early in the week. We would be able to present a stronger project if we are given this extra time. Thank you.

**Comment by mchen046** [comment]
Hey Mike, 
@ykamo001, @ttruo018, and I, @mchen046, would like an extension on our project until **11:59 pm @ Wednesday, June 10.** We all have multiple projects/finals over the course of the weekend + Monday, and this extra time will allow us to submit a much better Gitmap project.

**Comment by laurenB93** [comment]
So if we comment on here, do we automatically get the extension?

**Comment by mikeizbicki** [comment]
Everyone who has commented got the extension you requested.

**Comment by kkita004** [comment]
In order to complete the changes to my hw4 assignment, I would like an extension until Wednesday June 10th. I thought my submission was complete but it turns out that there still needs to be some changes made.

**Comment by cbarb005** [comment]
Would it be possible to amend my extension to the latest possible on Wednesday? I'd like to submit a few pull requests for feedback, starting with one tonight.

**Comment by amah001** [comment]
i would like to amend my extension til Tuesday June 9th, 2015 12:00 pm to deal with unexpected problems with video rendering.
