### ISSUE TITLE
Star and Stackoverflow EC

### ISSUE THREAD

**Issue by cdixi001** [mikeizbicki/ucr-cs100#1674]
Dear Sir and/or Ma'am,
I am writing to you today to inform you that I have painstakingly, but lovingly selected 20 repositories to adorn with a star. I feel as if there is a part of me in each of those repositories now, as you can see [here](https://github.com/stars/cdixi001).

In addition, I have graced the halls of Stackoverflow with my presence, answering the desperate calls of new programmers. My efforts, as you may witness [here](http://stackoverflow.com/users/4747961/cdixit2), have been rewarded with slightly over 100 points.

I humbly request you to bequeath me with 15 extra credit points for these thoroughly enjoyable experiences.

Yours Truly,
Chirag Dixit (@cdixi001)

**Comment by mikeizbicki** [comment]
And so it came to pass that 15 points extra credit were bequeathed.
