### ISSUE TITLE
git push

### ISSUE THREAD

**Issue by kryne001** [mikeizbicki/ucr-cs100#17]
i'm trying to do the part of the lab where i type the following command:

$ git push origin master

it has me put my username and password for github, then says:

remote: Permission to mikeizbicki/ucr-cs100.git denied to kryne001.
fatal: unable to access 'https://github.com/mikeizbicki/ucr-cs100/': The requested URL returned error: 403

**Comment by bmars003** [comment]
@kryne001 The problem that you are trying to push to 'https://github.com/mikeizbicki/ucr-cs100/, which is a repository you don't have permissions to edit. Instead you should be pushing to the forked repository you did in Lab 2 on your own github account https://github.com/kryne001/ucr-cs100.

**Comment by kryne001** [comment]
how would i do that?

**Comment by bmars003** [comment]
Are you sure the repository on the computer you are using is the clone of YOUR repository and not of the classes?

**Comment by kryne001** [comment]
i did this:

git clone https://github.com/kryne001/ucr-cs100/

but assuming my problem is that i cloned wrong, how would i fix that?
would i do another git init?

**Comment by bmars003** [comment]
In the .git directory look at the config file and make sure the master is showing the URL for your repository.

**Comment by kryne001** [comment]
[remote "origin"]
    url = https://github.com/kryne001/ucr-cs100
    fetch = +refs/heads/_:refs/remotes/origin/_

that's what it says in the config file

**Comment by kryne001** [comment]
oh wow now it works. thank you.
