### ISSUE TITLE
HW3 Test Cases Mistake

### ISSUE THREAD

**Issue by jbarb011** [mikeizbicki/ucr-cs100#1700]
I accidentally didn't push my testcases into my HW3 tag and received a zero on the assignment because of it. I'm sorry for the inconvinience, it was a stupid mistake that I'd hate to fail the class for. The test cases are on my repository and I did not touch the file since last week. I attached a picture of my blame history to prove it. I'd be fine with taking a point deduction or some other penalty. I will soon be reuploading the HW3 tag with the test cases attached.
![screenshot from 2015-06-06 15 08 28](https://cloud.githubusercontent.com/assets/5579068/8021679/f006e8e8-0c5d-11e5-8cdd-2ef89b3ab59e.png)

**Comment by mikeizbicki** [comment]
I will regrade this for you on Tuesday with a penalty.
