### ISSUE TITLE
calcgrade.sh (standard_in) 1: syntax error

### ISSUE THREAD

**Issue by glaceeeee** [mikeizbicki/ucr-cs100#1707]
When I run the calcgrade.sh script, I get the error: `(standard_in) 1: syntax error`. 

I'm not sure exactly what's causing the issue but from what I can tell, the only thing that changed was that the labs/lab names got updated. My only guess to what the error could be is that under the grades file in the grades branch for lab5-rm, there is only a `/`, and no denominator number.

**Comment by ghost** [comment]
That shouldn't be a problem as gitlearn's configs would get the file name from repository and print the name as is on the terminal. If the name was preset on the script then it would be extreme inefficient if a class instructor were to change assignment names or add new assignments/categories.  

First of all:  
Did you try running calcgrade.sh again?
Did you run ''CS100'' before you ran the script?
Are you on hammer?
Have you tried recloning your repository and then run 'calcgrade'?

**Comment by ghost** [comment]
Also another way would be to just add '2> /dev/null/' at the end of calcgrade.sh if you just want to ignore the errors.

**Comment by mikeizbicki** [comment]
@pockymons You were correct about the cause being a malformated `lab5-rm/grade` file.  I've deleted that file, so it should work fine for you now.
