### ISSUE TITLE
Writing Center EC

### ISSUE THREAD

**Issue by kevdev158** [mikeizbicki/ucr-cs100#1717]
Hi,
I got our HW4 draft checked out on June 1st and they said that they would notify you about the visit. I was wondering if you ended up receiving proof that we got it checked out by them.
Thanks

**Comment by mikeizbicki** [comment]
I have not.  How were they planning on notifying me?

**Comment by kevdev158** [comment]
They had me write down my name on this list and the class it was for. They weren't clear on how they were going to notify you though.
