### ISSUE TITLE
HW Grading Question

### ISSUE THREAD

**Issue by jpatu001** [mikeizbicki/ucr-cs100#1725]
Hi, I just have a question with the grades. I got docked off points from the piping hw2 just a few hours ago. I had 100+ pts before but now I have 85. The grade file says that it was from a valgrind memory leak. Now I have been docked points for memory leak on hw3(signals) as well. But I never knew of the valgrind mem leak from hw2 before today. I just want to know if one of the mem leaks - points can be removed since I was not aware of that until tonight. If I have known of the memory leaks from hw2 before I turned in the hw3(signals), then I would have done something to actually fix it instead of having two -25 points. If I remember correctly, Mike said in class before that since some of the hw grades are late, then we should not be docked off points because of errors we had from the previous one that we had no idea until we turned in the current hw. I hope this gets fixed. Thanks.

**Comment by mikeizbicki** [comment]
Sorry, no.  If you had been running valgrind on your code, you would have known about the memory leak.
