### ISSUE TITLE
Regrades tomorrow at 8AM in WCH110

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1727]
Regrades begin tomorrow at 8AM in WCH110.  Please be on time.  If you're late, I can't guarantee I'll have enough time to get to you.

**Comment by htang014** [comment]
For the reshow, all we need to do is create a test script like normal, and show that to you in offices right?

**Comment by mikeizbicki** [comment]
You must have everything prepared and uploaded to github exactly as if it were a normal homework assignment.

**Comment by htang014** [comment]
ok

**Comment by laurenB93** [comment]
Is today the last day we can show you extra credit? I.e. The tor relay?

**Comment by mikeizbicki** [comment]
Yes.  Today was the deadline.

**Comment by jmeji011** [comment]
Hey Mike,
On Tuesday you said I could show you my hw2 for a regrade on Thursday during your last office hours. Do you know what time it will be at because I have a final at 11:30.

**Comment by mikeizbicki** [comment]
Can you meet at 3:30 in WCH 110?

**Comment by jmeji011** [comment]
@mikeizbicki Yeah I will be able to make it at that time

**Comment by mikeizbicki** [comment]
@jmeji011 Sorry, but I can no longer meet you at 3:30.  Does 3 work instead?

**Comment by jmeji011** [comment]
@mikeizbicki Dang, I wish I saw that earlier. I guess it's too late now.

**Comment by mikeizbicki** [comment]
@jmeji011 Sorry for the miscommunication.  That's my fault.  Can you make
it to the office hours I'm having tomorrow?
