### ISSUE TITLE
Lab Grades.

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1754]
I noticed that I have two labs that are duplicates. For example
`10 /  10    |  lab0-vim                       |  Mike Izbicki [signed]`
`10 /  10    |  lab1-git                       |  busrac [signed]`
`10 /  10    |  lab2-fork                      |  busrac [signed]`
`12 /  10    |  lab3-gdb                       |  busrac [signed]`
`--- /  10    |  lab4-cstring                   |  ---`
`--- /  10    |  lab5-cp                        |  ---`
`10 /  10    |  lab5-rm                        |  busrac [signed]`
`10 /  10    |  lab6-signal                    |  busrac [signed]`
`10 /  10    |  lab7-cstring                   |  busrac [signed]`
`--- /  10    |  lab7-rm                        |  ---`
When will this be fixed?

**Comment by mikeizbicki** [comment]
Thanks for pointing this out.  This will be fixed before your grades get entered.

**Comment by mikeizbicki** [comment]
Should be fixed now.
