### ISSUE TITLE
A new record has been set in most extra credit awarded!

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1766]
Adam Veres [discovered a bug in gitlearn](https://github.com/mikeizbicki/gitlearn/pull/31) that let him modify his grade to be whatever he wanted.  He gave himself 2000 extra credit points, setting a new record in highest score yet in a cs100 class.

His pull request fixing the bug is an excellent example of a pull request.  It clearly explains the problem and his solution, and his modified code is very simple to understand.  Great job!

**Comment by avere001** [comment]
Thank you!

**Comment by hgarc014** [comment]
that is pretty awesome.

**Comment by ChannelJuanNews** [comment]
^ I agree
