### ISSUE TITLE
HW4: Webscraping 

### ISSUE THREAD

**Issue by dtran049** [mikeizbicki/ucr-cs100#1779]
We're very close to finishing our script which is the last part of our write up. We only need to fix the some little part of iterate through all of the files and grep the each recipe and make the a file for it in readable format. However we might need a couple of more days as some of us have a final on Thursday and Friday. You told us to turn it in on Thursday at noon but if needed the deadline can be extended to Monday. We think that we can completely finish it and turn it in on Saturday once all of the stress and studying for finals is over. Is this okay?

**Comment by mikeizbicki** [comment]
Sounds good.  Just know that there won't be time for any more feedback
after that.
