### ISSUE TITLE
Final HW4 alterations

### ISSUE THREAD

**Issue by isadoramariamendes** [mikeizbicki/ucr-cs100#1780]
Hello Mike,
I read your feedback from this https://github.com/mikeizbicki/ucr-cs100/pull/1760 right now.
I would like to know if we can make this changes due Friday. I already started my internship and I still have finals... My partner has finals too... Friday would be a great day to finish it up properly.
Thanks,
Isadora

**Comment by mikeizbicki** [comment]
I won't be able to look at it until Monday morning, so you have until Sunday night.
