### ISSUE TITLE
Trying to Rebase

### ISSUE THREAD

**Issue by laurenB93** [mikeizbicki/ucr-cs100#1787]
I am getting some issues when rebasing. My forked repo said it was only 29 commits behind and I was trying to squash the commits. When I rebased them, more than 29 came up, it was more like 50. So i squashed all the commits from the project to the first one from the project but it added other people's commits to it too. Now it says I am 23 commits behind and I don't know what happened. Now I don't know how to fix this issue.

**Comment by ghost** [comment]
Dont forget to fetch updates from the repo.

**Comment by laurenB93** [comment]
Thank you! I figured it out.
