### ISSUE TITLE
git-game-v2 revisions

### ISSUE THREAD

**Issue by ColdNightHour** [mikeizbicki/ucr-cs100#1795]
Here is the revised [git-game-v2](https://github.com/git-game/git-game-v2). This is a final submission, assuming you don't have time to give us more feedback. If you want us to change anything else let @hkwan003 @jruel006 and I know what else to do. We changed the original git-game and added the stuff you wanted us to.

**Comment by mikeizbicki** [comment]
Looks great!  I think you're ready to start publicizing it.  I've given you the full extra credit of 130/100.

**Comment by ChannelJuanNews** [comment]
Awesome, we are going to announce it tomorrow on twitter, Facebook and reddit. We are also thinking of making a website for the organization. The site will also double as a tutorial for git for beginners. At least that's what @hgarc014 @jdixo001 @hkwan003  and I have been discussing. We will also add a badge to be earned at the end of the git-game-v2. Thank you for your help and guidance.

**Comment by ghost** [comment]
Congrats guys!

**Comment by mikeizbicki** [comment]
When you announce the game, please post links here so that we can all support you.

**Comment by ChannelJuanNews** [comment]
Here are the links for some of the announcements

> [The repo for git-game-v2](https://github.com/git-game/git-game-v2)
> [Twitter](https://twitter.com/GitGameUCR)
> [git subreddit](https://www.reddit.com/r/git/comments/3acbbq/test_your_git_skills_with_the_gitgamev2/)
> [Facebook Page](https://www.facebook.com/pages/Git-Game/641945209274969)

There will be more announcements later but these are the ones for now! 
If you could like, share and upvote that would be great! Thank you!

**Comment by mikeizbicki** [comment]
Do you guys have any questions about how to launch?  I doubt very many people will see your tweet or facebook page.  The git subreddit was a good choice, but it's not very highly trafficked.  Hacker News and /r/programming are the places that will send tens of thousands of people to your project.  The key is getting a really nice post title.

If you haven't already, you should check out [the previous /r/programming post](https://github.com/hgarc014/git-game) and the [hacker news discussion](https://news.ycombinator.com/item?id=8855236).  When you submit your own projects to HN, you want to put the text `Show HN:` at the front of your title.  This will get you quite a bit more traffic there.  See [the Show HN page](https://news.ycombinator.com/show) for some examples.

**Comment by ChannelJuanNews** [comment]
We announced the game on the [Hackathon Hackers FB group](https://www.facebook.com/groups/hackathonhackers/) that has over 15,000 members. We got a little attention there. I just submitted a link to HN with the `Show HN:` tag like you recommended. I posted to the /r/programming subreddit as well. [Here is the reddit link](https://www.reddit.com/r/programming/new/) to support us! Please like, share, tag, upvote and all that good social media stuff. Thank you :+1:

**Comment by ChannelJuanNews** [comment]
Also if you have any more recommendations or advice you could give us, we would gladly welcome any input from you @mikeizbicki. We would also welcome any input or advice from other peers if you think you have a better strategy to gain a bigger following or any input in tweaking the git-game-v2 for the future.
