### ISSUE TITLE
Final grades

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#1806]
All of your grades have been entered, with the exception of some people for whom I'm still grading hw4.  That will be finished sometime this afternoon.  Your final grade will be whatever appears in the `overall total` section when you tun the `calcgrade.sh` script.

If there is anything you need to talk to me about regarding grades, I will be available from 10-11AM tomorrow (Tuesday) morning in WCH110.  That will be your last chance to report any mistakes.

**Comment by isadoramariamendes** [comment]
Hello,
I am international student and my transcript is pendent due to my CS100 grade class, which is missing. Could you please verify this for me? I need to transfer this credits with emergency.
Thanks...

**Comment by mikeizbicki** [comment]
I made a mistake when I first entered the grades and didn't enter
extensions students.  I've since contacted the extensions dept and filed a
change of grades request, but these can take some time to process.  That
was several weeks ago.

Your advisor would know the person to contact to get that process sped up.

**Comment by isadoramariamendes** [comment]
Ok thanks. The weird is that my hw4-contributing is without grade. But I am sure that I did, when we talked you said that with the last editions my partner and I could have 110 points :(

**Comment by mikeizbicki** [comment]
Then that was a mistake that needs to be fixed.  Can you send me a link to
where I said that?

**Comment by isadoramariamendes** [comment]
Yes, https://github.com/mikeizbicki/ucr-cs100/pull/1760

**Comment by mikeizbicki** [comment]
My last comment there says you were supposed to resubmit it, then I closed
it.  Since you didn't resubmit it, I never graded it.  If you make the
changes I asked for and resubmit I'll upgrade your grade.

**Comment by isadoramariamendes** [comment]
I don't know what happened cause I did all changes and created a pull request... however some error happened and I did not notice... I pull requested the changes again... as I am in my internship (and using windows) I don't know how to squash the commits, so I pulled all of them... I am sorry about that...

**Comment by isadoramariamendes** [comment]
Hi, I pull requested to submit it... Even tough I did all changes, if you could just submit the wrong grade I would appreciate. As I have full scholarship, have a grade and a transcript right now is more important than the grade, actually, otherwise I may have problems with my visa. Thanks.
