### ISSUE TITLE
piping grade

### ISSUE THREAD

**Issue by htang014** [mikeizbicki/ucr-cs100#1812]
I just noticed that piping is not on my grades.  I know its just past the time that I can ask about this, but I hope you can add the piping assignment grade still.

I don't want my grade to be 100 points off

**Comment by mikeizbicki** [comment]
Your grade was entered, but there was a bug in the `calcgrade.sh` script that prevent it from being displayed.  I've fixed the bug on my machine, so your final grade is 625/675.  It's not fixed yet on hammer, though, so you'll get different results there.
