### ISSUE TITLE
Auto-Indent Solution

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#20]
Hey guys,

I for one like my code to auto indent every line below my first indented line and VIM doesn't do it by default and I've been looking for a solution for a while and finally came across the answer!

type: `echo set autoindent >> .vimrc` in a terminal window. This will add to the default list and once you indent the first line, all lines below it will be indented as well.

Enjoy!

**Comment by bmars003** [comment]
Good find!!!!

**Comment by mikeizbicki** [comment]
Awesome!  Remind me in class to go over why this works and a bit more about configuring vim to your liking.
