### ISSUE TITLE
Having execv read in user input + Lecture 5 Notes

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#23]
Does anyone have any idea how to do read in user input to execl/execv?

The idea I have so far is to parse the user input, then append it onto /bin if appropriate, and then have it be read into execv, but I'm not too sure how to do this.

Also, does anyone have the files that were used in lecture today? I can't seem to find them.

Thanks!

**Comment by mikeizbicki** [comment]
I forgot to upload the lecture notes last night, sorry.  They should be up now though.

Getting the input into `execv` is really just getting the input to be a `char**`.  Focus on just doing that type conversion without worrying about calling the `execv` function, and then `execv` should just work.
