### ISSUE TITLE
HW0 broken link

### ISSUE THREAD

**Issue by tglen002** [mikeizbicki/ucr-cs100#237]
the link to syscalls-tutorial.md in HW0-rshell is broken.

**Comment by tkimva** [comment]
Yes, it is, we will fix it soon

**Comment by tkimva** [comment]
Prof. Izbicki,
The link is supposed to be [this document](https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/tutorials/syscalls) ? Let me know then I'll copy this document into here or change the link.

**Comment by mikeizbicki** [comment]
I've fixed the link.
