### ISSUE TITLE
Syncing Forked Repo

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#240]
I was looking at my forked repository, and was comparing the README.md documents for hw0, and they're slightly different. My forked repo is out of date, so certain links don't work.

Is there a way to sync my repo, or is it supposed to automatically sync?

Thanks!

**Comment by hgarc014** [comment]
Yes, there is. I just created a script to do this... if you run the code below, you shall be up to date. However, I haven't been able to 100% test this... But it seems to work...

git remote add upstream https://github.com/mikeizbicki/ucr-cs100.git
git fetch upstream
git rebase upstream/cs100-2014fall
git push

I THINK: you only need to create the upstream once

**Comment by mikeizbicki** [comment]
The commands Henry suggests are correct.  Github has an official FAQ on this topic where they explain in a little more detail: https://help.github.com/articles/fork-a-repo/#keep-your-fork-synced

(Please don't close this issue as it's a good reference for everyone to see.)

**Comment by tkimva** [comment]
Thanks, Henry,
for someone who is not familiar with `git rebase` command in Henry's suggests:
https://help.github.com/articles/about-git-rebase/

**Comment by tkimva** [comment]
Here is how to check your forked repository is out of date or not

If you see the following message in your forked repository

![screen shot 2014-10-14 at 10 47 30 pm](https://cloud.githubusercontent.com/assets/993376/4641052/3aec7698-5430-11e4-8089-03d3dac00231.png)

Then your repository is out of date.

If the message is the following
"This branch is even with mikeizbicki:cs100-2014fall"
Then, it says your repository is same as original now.
