### ISSUE TITLE
Hw0 explanation 

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#243]
I am still working on Hw0, and quite don't understand what the output should be. 
can you give a simple example of  "cmd         = executable [ argumentList ] [ connecter cmd ]" ?

Thanks you very much!

**Comment by mikeizbicki** [comment]
Can you please be more specific.  The hw gives the examples:

```
$ ls -a
$ echo hello
$ mkdir test
```

```
$ ls -a; echo hello; mkdir test
```

What about these examples doesn't make sense?
