### ISSUE TITLE
HW 0 Test Case: Comments (#)

### ISSUE THREAD

**Issue by ManjunathChet** [mikeizbicki/ucr-cs100#246]
The specs say if parameters come after a comment (#), then they are not passed in. If we have a connector following a comment, does everything following the connector get passed in? Or is that section also ignored?

I ran a test in terminal and it seems that everything is ignored after the comment (including the parameters after the connector). Regardless, I wanted to clarify what we are required to do for rshell.

**Comment by mikeizbicki** [comment]
Everything after a `#` should be ignored.  It doesn't matter what it is.
