### ISSUE TITLE
Script Issues

### ISSUE THREAD

**Issue by holidaylvr** [mikeizbicki/ucr-cs100#247]
Is there a compatibility issue with my pc? The script has large portions of gibberish that are illegible when viewed on my computer. Actually, I just checked the lab machines too and I see the same jargon. Is there a way to resolve this issue?
![screenshot from 2014-10-15 15 42 44](https://cloud.githubusercontent.com/assets/7895290/4654925/9986cb22-54bc-11e4-88dd-ffb174da65bd.png)

**Comment by mikeizbicki** [comment]
`script` records everything that gets typed in.  If you view the raw script file, you'll see all the times where I pressed delete/backspace, the arrow keys, etc.  That's what all those weird looking symbols are.  The easiest way to read the file is by preprocessing it to remove those symbols.  Here are two methods to do that.

### method 1

The command `col -bp < lectureXXX` will remove all of these extra characters from the file `lectureXXX` and print the results to stdout.  The easiest way to read the results is in `vim`.  The following command will make the file readable and then open it in vim:

```
col -bp < lectureXXX | vim -
```

Remember that the `/` command in vim is how you search.  You can use it to quickly find the section of lecture that you want to review.

### method 2

Maybe you're only interested in seeing what the actual commands are that I typed in, and you're less interested in the ouput.  The `grep` command will let us filter all of the output lines away and keep only the input.  Here's an example:

```
col -bp < lectureXXX | grep '^\$'
```

**Comment by holidaylvr** [comment]
I tried the first command to no avail. I typed "col -bp < lecture4 | vim- " and it appears to work but the result is the same as before. I tried the second one as well. I'll keep tinkering though.

**Comment by hgarc014** [comment]
The second command worked great for me. If i remember correctly. It doesn't remove all clutter, but it removes most of it
(even though its not really clutter)

**Comment by mikeizbicki** [comment]
@holidaylvr There is supposed to be a space between `vim` and `-`.  Maybe that's why it didn't work for you?

If the command still doesn't work, I will need to actually see the results to figure out why.  Try pasting a couple dozen lines here.

**Comment by holidaylvr** [comment]
I just ran it again and I guess it does clean it up some. It just takes some will to decipher exactly what we were doing at the moment. Maybe it's normal? I have 3 screenshots to show you the command and how various sections of the code work. 
![screenshot from 2014-10-15 20 33 52](https://cloud.githubusercontent.com/assets/7895290/4657262/16be85fc-54e6-11e4-8701-7f4ad8323c43.png)
![screenshot from 2014-10-15 20 36 34](https://cloud.githubusercontent.com/assets/7895290/4657261/16bbfbc0-54e6-11e4-847b-d41807b1abbd.png)
![screenshot from 2014-10-15 20 37 08](https://cloud.githubusercontent.com/assets/7895290/4657263/16c04d2e-54e6-11e4-98b7-a00c7ba55e16.png)

**Comment by mikeizbicki** [comment]
Ahh... it looks like all the information from the `man` command is getting dumped to the script file.  In the future I'll try to avoid running commands like that that take over the whole terminal to keep things cleaner.  If I forget in class, make sure to remind me.
