### ISSUE TITLE
Request for meeting with instructor for Friday [10/16]

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#252]
Hi. I'd like to schedule an appointment where I can ask additional questions about hw 0.

I am free any time between 11 am and 5 pm. Ideally, I'd prefer the longest duration possible for the meeting, but an hour if possible would be great. Any time allotted will be greatly appreciated.

Thanks!

**Comment by jesuscreyes** [comment]
Sorry, the date I put was confusing. I meant it for today [10/17].

**Comment by mikeizbicki** [comment]
I will be in WCH110 starting at 1PM for anyone who has questions.
