### ISSUE TITLE
quiz due Thursday

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#254]
The quiz I passed out last class is due Thursday.  Focus on your homework for Tuesday.

As a reminder, you may use any resources you want, but you must complete the quiz individually.  You cannot talk about it at all with anyone else.

**Comment by luizlopezm** [comment]
Hi I wasn't able to attend class on Thursday, I was wondering if I could get a copy, or will you have extras on Tuesday?

**Comment by mikeizbicki** [comment]
You can find it in the `quiz3` folder.  You will have to run a program called `pdfatex` on the `tex` file to generate the quiz.
