### ISSUE TITLE
Using strings with execvp

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#257]
I have properly tokenized my input string into multiple strings using the tokenizer from the boost library.

I'm trying to figure out how to use these strings with execvp, but I'm having no luck. Since execvp has the parameter of const char *, I thought of using c_str() to convert my strings to const char *, but that doesn't seem to work.

I was wondering if anyone else encountered, this problem, or knows a solution.

Thanks!

**Comment by mikeizbicki** [comment]
`execvp` takes a `const char **` for the argument list, not a `const char *`.  You will need to allocate the appropriate amount of memory for your `const char **` and use the `strcpy` function to move your `string.c_str()` into it.

**Comment by jesuscreyes** [comment]
Hmm, now I'm more confused. In the man page for execvp, it says:

`int execvp(const char *file, char *const argv[])`.

Are you referring to the `char *const argv[]` when you say `const char **`?

Also, when allocating memory, are you referring to:

`argv[0] = new char[X]`, where X is the appropriate amount of memory? How do I determine the appropriate amount of memory?

**Comment by mikeizbicki** [comment]
1) `char *const argv[]` and `const char **` are the same thing in this case.  There is a _slight_ difference only when you declare the variable.  See this stackoverflow question for more details: http://stackoverflow.com/questions/1335786/c-differences-between-char-pointer-and-array

2) You determine how much memory to allocate based on the length of the command the user typed in.  If they typed in `ls -al`, then the first index to `argv` needs size 3.  One for the command, one for the parameters, and one for the null terminator.  Then `argv[0]` needs size three to store `ls`, `argv[1]` needs size 4 to store `-al`, and `argv[2]` doesn't need any allocation.

**Comment by jesuscreyes** [comment]
Thanks for the reference!

So, just to clarify, in your example `ls` is the command, `-al` is the parameter. Therefore, in addition to the index we need for the null terminator, that's why we need size 3.

And also, `argv[0]` needs size 3 because of the character-length of `ls`? So for example, if I needed to store `echo` into `argv[0]`, it's size would need to be 5 to store it?

**Comment by mikeizbicki** [comment]
Exactly right!
