### ISSUE TITLE
Waiting for multiple child processes

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#259]
How do you wait for all child processes to finish?

With one command it works fine.
But when I try entering ls && pwd, it prints the prompt before outputting the current directory.

I tried 
while(wait(NULL) > 0);
but that doesn't seem to help.

**Comment by mikeizbicki** [comment]
The `wait` syscall will return as soon as _any_ child exits.  The `waitpid` syscall will let you wait on a specific child.  It's possible to correctly use either for this assignment.

**Comment by mikeizbicki** [comment]
I'm leaving this open so that it's easier for other students to find.
