### ISSUE TITLE
What is defined as a fail or success?

### ISSUE THREAD

**Issue by ziyaemanet** [mikeizbicki/ucr-cs100#260]
For hw0 under coding requirements:

_If a command is followed by ;, then the next command is always executed; if a command is followed by &&, then the next command is executed only if the first one succeeds; if a command is followed by ||, then the next command is executed only if the first one fails._

What exactly constitutes a fail or success? Also I wanted to confirm that () and []  will not be required with hw0.

**Comment by mikeizbicki** [comment]
In Unix, a program fails when it has a non-zero exit code.  It succeeds when it has a zero exit code.

You do not have to support any form of parenthesis or quotation marks in the assignment.
