### ISSUE TITLE
Spaces for || and && input?

### ISSUE THREAD

**Issue by luizlopezm** [mikeizbicki/ucr-cs100#261]
Do we there will be spaces when using && and || connectors for example do we assume a valid input would be ls -a || mkdir test

**Comment by mikeizbicki** [comment]
You must be able to handle all possible cases.  A (non-exhaustive) set of examples is:

```
$ ls -a || mkdir test
$ ls -a||mkdir test
$ ls -a ||mkdir test
$ ls -a|| mkdir test
```
