### ISSUE TITLE
Global Constant Variables

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#262]
are we allowed to use global constant variables??
I assume we are.

**Comment by mikeizbicki** [comment]
Yep.  You are allowed to do whatever you want.  Any bad practices you choose to employ will bite you in future assignments.

Global constants (as it happens) are great programming practice and will make your life easier.

**Comment by tkimva** [comment]
Generally, global variables are evil. It's convenience but problem maker. You should be very careful of using the global variables for your big project in the future.

**Comment by hgarc014** [comment]
I agree global variables can be evil. I meant global constants. Those can be really nice if you want to change a constant you use often :)

**Comment by tkimva** [comment]
My bad. I don't know why I couldn't see the word "constants". You're right.
