### ISSUE TITLE
Confusing execvp behavior

### ISSUE THREAD

**Issue by boxcarcoder** [mikeizbicki/ucr-cs100#263]
The behavior of execvp does not seem consistent for some reason. The commands ls and pwd will work properly when prompted individually ($ ls will work and then a second test of $ pwd will work) but echo hello will not work despite it being in the bin folder (I believe). How come ls will work, and then pwd will work, but then echo won't? It will give me the perror when I try executing echo.

**Comment by tkimva** [comment]
The first and second test do not have parameters. Do you think it's `echo hello` problem? Have you ever tried `ls -al` instead of ls in the first step? The parameter passing should be correctly handled in your program.

**Comment by mikeizbicki** [comment]
@bchen022 You haven't given us enough information to help you.  In particular, what is the error message `execvp` is giving?

**Comment by boxcarcoder** [comment]
After typing in echo test on a single line, my perror message for execvp will be displayed, followed by : No such file or directory.

Also, the similar issue will happen if I try to type in multiple commands on a single line. For example, if I type in ls; pwd on a single line, the terminal will print out ls:  pwd: No such file or directory. Hopefully this will provide more information.

**Comment by mikeizbicki** [comment]
You need to print out the input that you're passing into `execvp`.  It can't be what you think it is since those commands exist.  Something like:

```
cerr << "argv[0]=[" << argv[0] << "]" << endl;
cerr << "argv[1]=[" << argv[1] << "]" << endl;
cerr << "argv[2]=[" << argv[2] << "]" << endl;
execvp(argv[0], argv);
```
