### ISSUE TITLE
boost

### ISSUE THREAD

**Issue by attecodes** [mikeizbicki/ucr-cs100#265]
Having some trouble getting the boost library to work on xcode and vim.. so far i followed these steps 

The most reliable way to get a copy of Boost is to download a distribution from SourceForge:
Download boost_1_39_0.tar.bz2.
In the directory where you want to put the Boost installation, execute
tar --bzip2 -xf /path/to/boost_1_39_0.tar.bz2

Then i try doing #include<boost/tokenizer.hpp> but it produces an error

**Comment by tkimva** [comment]
As I know, we are supposed to use Linux for our assignment and lab? Right? Did professor ever allow you to use Xcode? The boost library can be easily installed in Ubuntu, Debian, CentOS, and Fedora from their own repositories. Please remember we run your code in `hammer.cs.ucr.edu` for grading.

**Comment by tkimva** [comment]
As I know, the boost 1.41 has been installed in our class server and you can use this. The following packages have been installed in our class server and `#include <boost/token_iterator.hpp>` in the example is working well. The headers are included in `boost-devel-1.41.0-18.el6.x86_64` package.

boost-filesystem-1.41.0-18.el6.x86_64
boost-date-time-1.41.0-18.el6.x86_64
boost-test-1.41.0-18.el6.x86_64
boost-devel-1.41.0-18.el6.x86_64
boost-graph-1.41.0-18.el6.x86_64
boost-program-options-1.41.0-18.el6.x86_64
boost-python-1.41.0-18.el6.x86_64
boost-1.41.0-18.el6.x86_64
boost-regex-1.41.0-18.el6.x86_64
boost-signals-1.41.0-18.el6.x86_64
boost-serialization-1.41.0-18.el6.x86_64
boost-math-1.41.0-18.el6.x86_64
boost-system-1.41.0-18.el6.x86_64
boost-thread-1.41.0-18.el6.x86_64
boost-iostreams-1.41.0-18.el6.x86_64
boost-wave-1.41.0-18.el6.x86_64

**Comment by jesuscreyes** [comment]
I'm using Ubuntu 14.04 and I was able to get mine to work. I ran this command at the terminal:

`sudo apt-get install libboost-all-dev`

After that, I was able to use it.

**Comment by tkimva** [comment]
@jesuscreyes Thanks, 

For rpm-based distro, Fedora/CentOS,

`yum install boost-*`

**Comment by attecodes** [comment]
I got all the boost files downloaded on my computer but perhaps i placed them into the wrong directory because i cant get tokenizer to work with #include <boost/tokenizer.hpp> 
This path works for tokenizer #include "/Users/attemyllykoski/boost_1_56_0/boost/tokenizer.hpp" but then more errors are produced because you need to include all the other paths that tokenizer.hpp uses

**Comment by 2c2c** [comment]
boost is huge and complex package of stuff. you generally use a package manager to let the maintainers of your distro deal with the baggage related of getting this kind of stuff to work properly.

depending on your distro you can use `apt-cache search boost` or `yum search boost` and it will tell you the name of the package you want to install with `apt-get`/`yum`

last resort is you can login to hammer instead of well and type cs100 which autoloads a newer compiler and boost to work with
