### ISSUE TITLE
perror message after execvp fails

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#266]
I noticed that if I type `chocolate` into the terminal, the error message says "command not found". However, when I type the same thing into my shell program I get the message "No such file or directory". Is this a bug, or is this supposed to happen?

**Comment by mikeizbicki** [comment]
The exact wording of your error message doesn't matter as long as you're displaying good error messages.  `No such file or directory` is a fine error message.  The reason bash doesn't display this exact error is that they're using a custom version of `perror` to display the message.
