### ISSUE TITLE
echo with Comment

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#267]
So, if a person were to write something like
`echo This is a test # you won't see this text`

then bash will print
`This is a test`

as expected. However, if someone were to write
`echo "This is a test #you will see this"`

the output would be
`This is a test #you will see this`

**So, I believe this would be a feature of the quotes, which we do not have to implement, correct?**
which would mean that our echo would still chop everything after the # (pound symbol)?

Example.

```
echo "this is a test#but everything after will be chopped"
"this is a test
```

**Comment by mikeizbicki** [comment]
Correct.  And very nicely asked question btw!

**Comment by aorti017** [comment]
Does that mean commands such as "echo "text" > file" would also be a feature of the quotes?

**Comment by hgarc014** [comment]
That would be redirection. Which is a future hw assignment.
