### ISSUE TITLE
Error when doing git push

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#269]
This is the error I get:
`
 ! [rejected]        exec -> exec (non-fast-forward)
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/jesuscreyes/rshell.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.`

Not sure how to solve this problem. How do I integrate these remote changes?

**Comment by hgarc014** [comment]
this is due to your branch being behind the github branch. You should git pull before you push.

**Comment by mikeizbicki** [comment]
Henry is probably correct here.  If you look through the error message, it has a line saying `hint: 'git pull ...'`.
