### ISSUE TITLE
extra office hours Monday at noon

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#270]
I will be in WCH110 Monday starting at 12:10 for anyone who wants help with the assignment.

EDIT: Sorry, I realized this is during lab time, so I won't be there.  If anyone wants to make a specific appointment, though, let me know.

**Comment by jesuscreyes** [comment]
How long are you planning to stay there?

**Comment by mikeizbicki** [comment]
probably about an hour
