### ISSUE TITLE
pwd and echo errors

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#276]
Every time I run "pwd" and "echo" for the first time in my program I get the error:

There was an error in execvp.: Bad address

However, after that error, running "pwd" and "echo" any time after will produce the normal results of the current directory/empty line. Running "ls", "cat", etc all work fine as well.

**Comment by mikeizbicki** [comment]
A simple google search for `execvp bad address` gives [this stackoverflow question](http://stackoverflow.com/questions/20449182/execvp-bad-address-error) as the first result.

**Comment by DustinPham** [comment]
Yes, I've seen those. However, for my error, it doesn't matter how many commands are run beforehand. The first time "pwd" or "echo" are run, results in an error, but any subsequent calls to those are fine.

**Comment by mikeizbicki** [comment]
The `bad address` error message means that you are not null terminating your array.  The stackoverflow answer gives an example of how to do that.  The fact that it's working in later runs means that you are (probably accidentally) adding a null termination to the end of the array in those later runs.
