### ISSUE TITLE
; && and ||

### ISSUE THREAD

**Issue by ifuka001** [mikeizbicki/ucr-cs100#279]
The rshell should be able to implement all these in one single line correct? 

e.g.: 
ls ; pwd || ls-a
pwd && ls -l || mkdir test

**Comment by hgarc014** [comment]
If i remember correctly, then I think Mike said in class that we do not have to be capable of handling all possibilities in one single line. However, we do have to be capable of handling the same connector a bunch of times in one line.
such as

```
ls; l; pwd; echo test; ls
ls && l && pwd && echo test && ls
ls || l || pwd || echo test || ls
```

**Comment by ifuka001** [comment]
Oh alright thanks!

**Comment by mikeizbicki** [comment]
Basically, I don't care how you define order of operations for the `&&`, `||`, and `;` connectors.  So the command you suggested of: 

```
pwd && ls -l || mkdir test
```

will not necessarily behave the same in everyone's shell.  You may process this statement using whatever order of operations you choose, or you can decide that this will be an error (you might think this latter option is easier, but it's probably harder depending on how you structured your code).

**But whatever you choose, make sure to document it!**

**Comment by hgarc014** [comment]
So, then rshell should be capable of handling combinations of `||` `&&` or  `;` in one line??

**Comment by mikeizbicki** [comment]
@hgarc014 I don't care what you do, but you must document your choice.

**Comment by hgarc014** [comment]
alright, thanks

**Comment by ifuka001** [comment]
Ok thank you
