### ISSUE TITLE
problem with tags

### ISSUE THREAD

**Issue by katherinegallaher** [mikeizbicki/ucr-cs100#28]

**Comment by katherinegallaher** [comment]
I uploaded all of my files and tried to run the commands to check if everything is working but when I try git checkout hw1 it states that I don't have that tag when I'm positive I created it. I tried to create the tag and the git push again but it says everything is up to date. How can I add this tag?

**Comment by mikeizbicki** [comment]
Did your command look like: `git push origin hw1`?  Can you provide the exact messages you are getting from your git command?

**Comment by katherinegallaher** [comment]
Okay i did that and it works! Thank you!

Another question though, I cloned my repository to test everything and when I ran the program for some reason getlogin_r no longer works, the error says "no such process". can you give me any ideas on how to fix this?

**Comment by mikeizbicki** [comment]
Hmm... that's weird.  Try checking the man page for `getlogin` to see if it has any details about that error message.

**Comment by katherinegallaher** [comment]
I checked the man page and it doesn't seem to have any info on that error. 
I also tried changing to the getlogin() function and the error I was given for that was 'no such file or directory'

**Comment by mikeizbicki** [comment]
I can't tell what's going on from what you said.  Can you give the full printout of your test?

**Comment by katherinegallaher** [comment]
I somehow got it working. I am using nomachine to remotely access the well servers, so I logged out and logged back in and it works now. I didn't change any of the code so I'm not sure why it didn't work at first.

**Comment by mikeizbicki** [comment]
Sometimes weird things happen.  It probably means there's a subtle bug somewhere... make sure to document it.

**Comment by katherinegallaher** [comment]
Alright. Is it alright for me to change the readme file here on github or do I have to do it on my machine and the push it onto github?

**Comment by mikeizbicki** [comment]
It's fine to change things directly on github.
