### ISSUE TITLE
Trouble with git push

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#281]
Hi does anyone know what the problem can be here? I'm trying to push my changes onto github

gruiz007@hammer $ git push
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/gbrlrz017/rshell.git/info/refs
fatal: HTTP request failed

**Comment by tkimva** [comment]
type `cs100` then run `git push`
you were using git 1.7.1 so after running `cs100` you will use git 1.8.4

**Comment by tkimva** [comment]
`git --version` and check it yourself

**Comment by gbrlrz017** [comment]
Ahh yes! Forgot to type cs100. Thanks!
