### ISSUE TITLE
trouble exiting

### ISSUE THREAD

**Issue by luizlopezm** [mikeizbicki/ucr-cs100#283]
So I have a continues while loop for the command prompt, if the user types exit, it should break the while loop and terminate the program, the problem is that sometimes it exits, sometimes it doesn't, its not consistent, sometimes it even tries to execute "exit" as a command which it shouldn't even get to that point so I don't know what's causing it.

**Comment by luizlopezm** [comment]
actually, I figured it out, that if I do cin.clear() at the end of the loop, I have no more problems exiting

**Comment by tkimva** [comment]
@reload01 Can I ask who you are? Are you a student?

**Comment by luizlopezm** [comment]
Yeah I'm a student

**Comment by tkimva** [comment]
I know you're Luiz, I was asking to @reload01, he is not in our people directory. So I was wondering who he was. 

Anyway why you were missing lab today? I think you were missing the lab last week as well. Please let me know

**Comment by luizlopezm** [comment]
Yeah, I have a conflicted work schedule which i just sorted out today, I did do the lab, but I know I can't get credit for it.
