### ISSUE TITLE
get user error while running a script

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#284]
The `getlogin()` function works fine on my computer, and on well and hammer, but if I'm running a script I get an error. And then unless I start a new terminal, it continues to give me an error.

How can I fix this?

**Comment by luizlopezm** [comment]
yeah, I'm having the same issue as well, as having other program issues when running rshell on the script vs running it on the regular terminal

**Comment by mikeizbicki** [comment]
If you don't report the error message, then there's no way for us to help you figure out what the problem is.

**Comment by luizlopezm** [comment]
for me I don't get an error, it just doesn't show up on the script, my commands work find, everything works, but it just won't display the user and host name on the script, but it will if I run it on a regular terminal

**Comment by luizlopezm** [comment]
also some of my error statements won't print in the script, for example if I ran la -a && echo hello it would attempt to run la -a and realize its an error and print out the error, but it won't run echo hello like its supposed to but won't print the associating error message but in an actual terminal it would

**Comment by khuan013** [comment]
I get the perror message that checks if getlogin() returns NULL.

`Error getting user name: No such file or directory`

**Comment by mikeizbicki** [comment]
Apparently this is a known issue with `getlogin` and the place in the OS it gets the login info from.  It never happened in previous classes, so I wasn't aware of this.

Anyways, [this stackoverflow question](http://stackoverflow.com/questions/4785126/getlogin-c-function-returns-null-and-error-no-such-file-or-directory) provides a suggested solution.

**Comment by 2c2c** [comment]
the suggested command there is a syscall within a syscall. is your error detection script going to dock points considering it's technically 2 calls with one perr output?

**Comment by mikeizbicki** [comment]
@2c2c It is common for people to write the shortest possible code that gets the job done.  But you must have proper error checking on all syscalls.  So you will have to extend their example code.

**Comment by 2c2c** [comment]
Apparently `getuid` never fails so there's only one check to be made anyways. Shoulda checked both functions before I asked.

**Comment by mikeizbicki** [comment]
You're right!  Forget what I said before.
