### ISSUE TITLE
Exit function misbehaving

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#288]
When the user inputs the word `exit`, I call `exit(1)`.

It works fine when I execute commands that won't produce errors.

But say I try to run a command that produces an error, like `$ lsa`. I get my error message via `perror`. However, when I try to exit immediately after, I need to enter `exit` twice.

I tested this, and ran `$ lsa` 4 times. When I tried to exit right after that, I needed to enter `exit` 4 times to actually exit the function.

I'm guessing that the bug has to do with either `perror` or `execvp` affecting the function call `exit(1)`.

If anyone has any ideas, please let me know. Thanks!

**Comment by hgarc014** [comment]
sounds more like a zombie process to me.

**Comment by jesuscreyes** [comment]
You were right! Thanks so much!

**Comment by mikeizbicki** [comment]
I'm reopenning so that other students are more likely to see this.  It was a great question and answer!
