### ISSUE TITLE
Script and Rshell executable

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#29]
For some reason. as soon as I start script, my rshell executable will not execute. It works fine if script is not running... After I start script exec.script, I call ./rshell, and then it just hangs on a blank line.

**Comment by mikeizbicki** [comment]
If you type a command, does it run?

**Comment by DanTheTingler** [comment]
Oh wow it does, any reason why nothing is suddenly showing in front of it?

**Comment by mikeizbicki** [comment]
I suspect if you copy paste the full output of your program here, we would find the `$` burried in some obscure place.  Like your program prints the `$`, then `script` prints some info, then it starts running normally.

**Comment by DanTheTingler** [comment]
So how do I fix this problem? Not only is it not showing the $ sign, it isn't showing the user info that I usually have as well.

**Comment by mikeizbicki** [comment]
I'm not sure what's going on.  Again, I can't help if you don't copy/paste the output here!

**Comment by DanTheTingler** [comment]
Oops, sorry! Here's the output:

tingles@Tingles:~/rshell/bin$ ./rshell
tingles@Tingles$ script exec.script
Script started, file is exec.script
tingles@Tingles:~/rshell/bin$ ./rshell
ls  
exec.script  rshell
ls -a
.  ..  exec.script  rshell

**Comment by mikeizbicki** [comment]
Is there a reason you are running `rshell` from within `rshell`?

**Comment by DanTheTingler** [comment]
The bin folder is inside my rshell folder, and the bin folder has my executable, which is rshell

**Comment by mikeizbicki** [comment]
Sorry, I wasn't talking about the directories.  I meant you run `rshell`, then you run `script` from within `rshell`, then you run `rshell` from within `script` from within `rshell`.  Why?

Try just running `script` and then `rshell`.

**Comment by DanTheTingler** [comment]
I was trying different things to see if I could get it working. But if i run script, then I run rshell, its still the same thing

**Comment by mikeizbicki** [comment]
Try editing your `main` so that it only prints a single line and does nothing else, then run that within `script` and see if it displays.

**Comment by DanTheTingler** [comment]
Okay, I did that and it printed out the single line.

**Comment by mikeizbicki** [comment]
Now slowly add more of your legit code until you notice the problem occurs.  Then determine what's different about that print statement and your first print statement.

**Comment by DanTheTingler** [comment]
Mike I've been trying to find what's wrong but I can't seem to pinpoint the problem. It prints out fine until I run script.... the commands work fine as well... how many points will I be docked if I can't fix this problem?

**Comment by mikeizbicki** [comment]
I can't say for sure.  Just do your best to document all your test cases.

**Comment by DanTheTingler** [comment]
Okay. I just want to clarify that without script being run, the user's name, followed by the @, and then the user's console, then the $ symbol prints out fine, and that's the only thing missing when I run script. All my commands still run fine and return the correct output. But without script the missing elements below print out just fine.

**Comment by DanTheTingler** [comment]
Okay I think I've pinpointed it to this small block of code, still not sure what's wrong though:

int main(int argc, char *argv[])
{
    while(1) //continue looping
    {
        bool amper = false;
        char str[1024];
        char *user;
        char hostname[256];
        user = getlogin(); //get user's login
        gethostname(hostname, 256); //get user's host name
        cout << user; //user's name
        cout << "@" << hostname; //computer's host name
        cout << "$ "; //bash 
        cin.getline(str, 1024); //get user input

**Comment by DanTheTingler** [comment]
Okay, so I have it halfway fixed. It now displays @Tingles$ instead of the full tingles@Tingles$.

Here's what I have:

while(1) //continue looping
    {
        bool amper = false;
        char str[1024];
        char user[256] = {0};
        char hostname[256] = {0};
        getlogin_r(user, sizeof(user)-1); //get user's login
        gethostname(hostname, sizeof(hostname)-1); //get user's host name
        cout << user; //user's name
        cout << "@" << hostname; //computer's host name
        cout << "$ "; //bash 
        cin.getline(str, 1024); //get user input

**Comment by DanTheTingler** [comment]
Okay here's my latest update, still only halfway fixed:

while(1) //continue looping
    {
        bool amper = false;
        char str[1024] = {0};
        char user[256] = {0};
        char hostname[256] = {0};
        getlogin_r(user, sizeof(user)-1); //get user's login
        gethostname(hostname, sizeof(hostname)-1); //get user's host name
        cout << user; //user's name
        cout << "@" << hostname; //computer's host name
        cout << "$ "; //bash 
        cin.getline(str, 1024); //get user input

**Comment by DanTheTingler** [comment]
Okay I added a perror to the getlogin_r and it says that there is "no such process". However, when I'm not running script, I don't have this perror show up.
