### ISSUE TITLE
Forgotten Test Cases

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#290]
I forgot some test cases in my final submission, should I just remove the `hw0` tag and work on the `exec` branch again? Or just stay on the `master` branch?

**Comment by mikeizbicki** [comment]
You should delete the `hw0` tag, make your changes to the `exec` branch, and when you're done, checkout `master`, merge with `exec`, and recreate the `hw0` tag.  From our perspective, it will look like you never made a mistake.

**Comment by abarb014** [comment]
Okay, thank you!

**Comment by mikeizbicki** [comment]
It was a good question, and I'm reopening it so others are more likely to see it.
