### ISSUE TITLE
Tokenizer Class does not work with hammer.cs.ucr.edu

### ISSUE THREAD

**Issue by ChemicalWonders** [mikeizbicki/ucr-cs100#293]
I would advise people to use the strtok c function instead because the Tokenizer library is not available on hammer.cs.ucr.edu.

**Comment by mikeizbicki** [comment]
The boost tokenizer class is available, I just double checked.  To use it,
you must add:

```
#include <boost/tokenizer.hpp>
```

to your file.

**Comment by tkimva** [comment]
Yes. I also just tested with my simple code and it worked without any problem.

**Comment by tkimva** [comment]
Also don't forget `cs100` before you work.
