### ISSUE TITLE
Script does not display all couts in functions

### ISSUE THREAD

**Issue by hlao002** [mikeizbicki/ucr-cs100#294]
While running the script command and testing my rshell, all couts inside of functions do not print while all the couts in main() print out correctly.

Any ideas as to why this is happening?

**Comment by tkimva** [comment]
Can you come to my office hour now? Let me see more detail. This kind of questioning is really hard to answer.

**Comment by hlao002** [comment]
currently in class, but priorities!!! will be there!

**Comment by tkimva** [comment]
It solved.
