### ISSUE TITLE
vim highlighting

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#295]
My vim just started highlighting the end parentheses throughout my code. Did i accidentally hit a hotkey that did this? I was trying to do the "+p to print from the keyboard when this started happening.

**Comment by 2c2c** [comment]
`/` is search in vim. you typed `/)` on accident. theres an actual command to turn off highlighting permanently or temporarily, but i usually just type `/fklsdjfslkdfj` when i notice it bothering me .

**Comment by DustinPham** [comment]
It worked! Thanks!
