### ISSUE TITLE
Repo Accidentally has Boyfriend's Account as Author

### ISSUE THREAD

**Issue by BridgetBennecke** [mikeizbicki/ucr-cs100#296]
My laptop has been having internet problems today, so I borrowed my boyfriend's computer to finish my assignment, but he forgot that he had already made the default author of git to be himself. So even though I signed in to push my commits to github, it says he's the author of them. What effect will this have on my assignment?

**Comment by tkimva** [comment]
I just checked yours. It's fine, but hereafter be more careful.

**Comment by mikeizbicki** [comment]
You can use the `git rebase` command to rewrite history in git and change the author back to you.  This would be the "correct" way to solve problems like this, but it will take quite a bit of reading the manual to figure it out.  As Taeyoung said, you don't need to worry about it for this assignment.
