### ISSUE TITLE
Practice with memory management

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#297]
After working on hw0, I realized that I'm a little rusty when it comes to handling memory, having to work with pointers, referencing and dereferencing, etc. I was wondering if anyone knew of any good resources that could help me get a better grasp of how to handle memory?

I'm thinking something similar to what we learned in CS 12 or CS 13. Ideally something in C++, and also something that includes example problems that I could practice with.

Thanks!

**Comment by tkimva** [comment]
I also saw someone else was also struggling with C/C++ programming specially for the pointer and dynamic memory allocation in my office hour. Normally I recommend the following website
http://www.cplusplus.com/doc/tutorial/

and also I have found that the previous CS100 reference for c++
http://w11.zetaboards.com/CS_100_UCR_Klefstad/topic/10028969/1/

However, I think professor Izbicki has a better solution for you.
