### ISSUE TITLE
Sizeof Quiz

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#298]
I screwed up and lost the paper, can I rewrite the questions and answers on a regular piece of paper?

**Comment by luizlopezm** [comment]
Its online under quiz3 its a .tex file and there's a way to compile and turn it into a pdf look it up

**Comment by abarb014** [comment]
I know, I just don't have any money to print. So I was hoping I could write it out.

**Comment by mikeizbicki** [comment]
You can print for free in any cs lab.  It cannot be handwritten.

**Comment by ChemicalWonders** [comment]
wait, so we're not allowed to write the answers in?

**Comment by hgarc014** [comment]
I think he meant you are not allowed to write down the questions on a piece of paper.

**Comment by ChemicalWonders** [comment]
okay. thanks henry
