### ISSUE TITLE
Allocation of new/malloc memory

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#30]
Hi guys,
Im redoing my user input into the array since we last learned how to completely use the malloc/new but in office hours, i don't remember what the sizeof(char_) refers to:
int x= how many params;
c = malloc(x \* sizeof(char_));

and for the individual array indexs' we just allocate memory for the size of the word being put in there as well, correct?

Thank you.

**Comment by mikeizbicki** [comment]
When you have a `char**`, this is an array of pointers; `sizeof(char*)` is the size of those pointers; so if `x` is the number of params, then `x*sizeof(char*)` is the number of bytes you need to allocate.

When allocating memory for the actual strings, don't forget to add one for the `\0`.

**Comment by rgosh001** [comment]
Ahhhhh, okay, i assumed that but didn't feel 100% with myself. Thank you Mike!
