### ISSUE TITLE
Can't figure out lab2

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#301]
I wanted to prepare for lab by trying to look at the source code earlier, but I'm confused.

I'm not sure what the exact purpose of the `INSTALL` file is. Are we meant to install the package by following those instructions?

Also, I can't locate the source code file `hbhairy-utils.tar.xz`, assuming that I'm supposed to find it in the `coreutils-8.23.tar.xz`.

Any clarification is greatly appreciated.

**Comment by mikeizbicki** [comment]
I've renamed the file from `coreutils` to `hbhairy-utils`.  Yes, you  must be able to follow the instructions in the `INSTALL` file to build the programs.
