### ISSUE TITLE
Accessing HW0 Grade

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#303]
So I'm a little clueless right now about how to access the break down/comments on our HW 0 grade. Am I supposed to access it using the calcgrade.sh script? 

I ran 
./scripts/calcgrade.sh examplestudent 
with gbrlrz017 replacing examplestudent. But that didn't work for me. 

Thanks in advance.

**Comment by mikeizbicki** [comment]
1. You can also manually check your grade by looking at the grade file on github.
2. Anytime you report an error with a program, you have to report the error messages you're seeing or there's no way you can be helped.
3. You may need to update your local version of ucr-cs100 to have the latest scripts.

**Comment by gbrlrz017** [comment]
1. On github, is the grade file supposed to be under gbrlrz017 / ucr-cs100 / assignments / hw / hw0-rshell / ? If so, is there a reason why there hasn't been any recent commits to that file? If not, where do I find it on github? 
2. ERROR: student gbrlrz017 does not have attribute giturl in their studentinfo file
   ./scripts/config.sh: line 34: kill: (11437) - No such process
3. Updating my local version of ucr-cs100 simply requires git pull, right? If so, I have the same issue with accessing my grade file as (1) on ucr-cs100 / assignments / hw / hw0-rshell / on my computer.

**Comment by tkimva** [comment]
1. not default branch, grade branch
2. ./scripts/calcgrade.sh gruiz007
3. No. you should read previous posting here #240

**Comment by gbrlrz017** [comment]
Nice, thanks!

For 2, is that purposely my ucr net id? Because I had an old github account with gruiz007 as my username, but I never gave write access to the instructors to that one.

For 3, how can I get the grades branch after running #240 's commands on my computer?

**Comment by mikeizbicki** [comment]
You are supposed to use your ucr cs account login when running `calcgrade.sh`.

**Comment by tkimva** [comment]
For 2, you don't need to worry about the id. Github id is defined by /people/students/[ucr cs account]. It is not necessary to be that your github id is same as cur csaccount. calcgrade.sh [ucr cs id] finds the file's definition first and go.
For 3, grading is located another branch, so it's okay

**Comment by gbrlrz017** [comment]
Thank you both very much!
