### ISSUE TITLE
Problem with grade result

### ISSUE THREAD

**Issue by luizlopezm** [mikeizbicki/ucr-cs100#309]
So in my grade file it says my program doesn't exit or run ls -l and I just ran it on my local, hammer, and bell and those commands do work, and it says that multicommands don't work when I try them as well and they do so I'm not really sure whether there's a problem with how the script runs my program or if my program is actually indeed wrong.

**Comment by tkimva** [comment]
I tested your code in hammer with "manually multiple commands typing. I didn't use script for functional checking. There might be possible human error, so come to my office hour and let's check toghether. I already have all cloned your repositories as of homework #0 deadline.

**Comment by luizlopezm** [comment]
well, I don't get off work until 4:30 usually get on campus at 5, can we do it after class?

**Comment by luizlopezm** [comment]
Or if I finish my lab can we do it during lab time.

**Comment by tkimva** [comment]
Okay good

**Comment by tkimva** [comment]
It has been resolved with this student
