### ISSUE TITLE
Question about comment in hw0

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#311]
I have the comment Systemcall misuse (-5) on my hw0. I was wondering what exactly that was referring to.

**Comment by hgarc014** [comment]
This means that you used a system call and did not check if the system call failed.  (if statement with perror, usually)

system calls are functions like, but not limited to:

execvp, fork, wait, etc.

**Comment by tkimva** [comment]
@hgarc014 You're correct. Thanks!

@khuan013 If you want to know more details, please come to office hour on Tuesday

**Comment by khuan013** [comment]
Ok thanks.
