### ISSUE TITLE
hw1-ls

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#315]
For hw1, should commands like 
ls -Rla ./src
already be "mostly" be working with our current rshell program?

I know you'll likely go over this in class today, but where do the readdir and stat syscalls come in to play? 

Thanks!

**Comment by hgarc014** [comment]
I think your question is: Doesn't our rshell already handle `ls`??

Yes, it does. The difference is that we are actually implementing part of `ls` in this assignment. In the last assignment we used `execvp` which basically used the `ls` command already defined on your machine.  

If you look at how the instructors are going to grade this assignment they run your ls file and not your rshell file. Which most likely means, you don't have to have rshell working correctly for this assignment. However, I could be mistaken.

**Comment by gbrlrz017** [comment]
Makes sense. Thanks!
