### ISSUE TITLE
Homework #0 grade 

### ISSUE THREAD

**Issue by tkimva** [mikeizbicki/ucr-cs100#317]
There was someone who got zero on homework #0 only due to github or makefile issue (not c++ code issue). We have decided that we try to grade on your request but with a significant penalty, so please reply here (no email) if you want me to grade your previous submission. Please don't expect too much, but it might be better than zero, but someone will be still 0 in case of coding issue.

**Comment by Adamantly** [comment]
I would like a regrade

**Comment by tkimva** [comment]
@afan004 Adam, unfortunately, your homework had no issue on github/makefile issue. Your homework was code issue itself. You can see this message in your grade file. If you want to discuss with me more, then come to my office hour next week.

**Comment by Adamantly** [comment]
You told me today that I was able to get a regrade because I edited without untagging my code.

**Comment by tkimva** [comment]
@afan004 Oh, I was confused the name, your issue is github issue, right. I'll take a look at it.

**Comment by tkimva** [comment]
@afan004 regraded

**Comment by asand017** [comment]
May I have a regrade?

**Comment by tkimva** [comment]
@asand017 Sure I'll take a look tomorrow morning

**Comment by hfanc001** [comment]
Can I get a regrade please?

**Comment by tkimva** [comment]
@hfanc001 sure, I will do tomorrow morning

**Comment by hfanc001** [comment]
Thank you. Do I need to go anywhere to show you my code or do you prefer to do it yourself?

**Comment by tkimva** [comment]
@hfanc001 I know your problem, tagging issue on github. So it's okay. If there is something, I'll let you know.

**Comment by jmoon018** [comment]
I would like a regrade too, when you get the opportunity. It was a Makefile issue---should I update my repo with the fixed version (so it's easier for you to check), or should I leave it as is? 
Thanks.

**Comment by hfanc001** [comment]
Okay thank you so much.

**Comment by tkimva** [comment]
@jmoon018 I'll use my local repository one which was cloned your repository when it was deadline. I can compile this myself just in case of makefile issue. If it's coding issue(C++), there is no way. So, you don't need to give me new makefile at this time. 
But you should fix your makefile for your second homework.

**Comment by jmoon018** [comment]
Understood. Thanks again

**Comment by vdoan002** [comment]
I would like a regrade too please. I also had a Makefile issue but I fixed it.
Thanks for everything!

**Comment by tkimva** [comment]
@asand017 regraded

**Comment by tkimva** [comment]
@hfanc001 regraded

**Comment by tkimva** [comment]
@jmoon018 regraded

**Comment by tkimva** [comment]
@vdoan002 regraded

**Comment by tkimva** [comment]
If there is no more request, then I will close this issue midnight today.

**Comment by atosti** [comment]
I'd appreciate a regrade if you're still doing them, I do believe mine had a makefile issue. Thanks!

**Comment by tkimva** [comment]
@atost001 regraded
