### ISSUE TITLE
Valgrind possibly lost leak

### ISSUE THREAD

**Issue by yli082** [mikeizbicki/ucr-cs100#320]
When running rshell with valgrind should possibly lost memory leaks due to dynamic allocation within a child process be treated in the same way as a definitely lost memory leak? Or because this is happening within a child process can it be ignored?

**Comment by mikeizbicki** [comment]
I think you might be confused about the assignment.  You're assignment does NOT involve running `rshell` in valgrind, only `ls`.  For this assignment, there is no need to be running `rshell` at all!

To directly answer your question; ALL memory leaks must be fixed, and valgrind should report no warnings or errors.
