### ISSUE TITLE
No office hour next Tuesday (4th Oct)

### ISSUE THREAD

**Issue by tkimva** [mikeizbicki/ucr-cs100#321]
We don't have TA office hour next Tuesday. (4th Oct) Just for next week.

Instead, we'll have office hour next Friday (7th Oct) 9-11am in WCH110.

Thus next week, you will have two office hours on Thursday (Professor) and Friday (TA).

**Comment by 2c2c** [comment]
is there going to be lab

**Comment by tkimva** [comment]
It was about office hour next week. The lab will proceed as planned on Monday.
