### ISSUE TITLE
Alphabetical Order?

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#324]
Does ls.cpp have to output in alphabetical order?

**Comment by nickzoo** [comment]
I was told that the output should look the same as it does on the lab machines.

**Comment by 2c2c** [comment]
i haven't started yet but I would assume it should be trivial. assuming the data is unsorted put it in an STL container and use `std::algorithm` sort. Hope im not wrong.

**Comment by nickzoo** [comment]
With some minor tweaks: the default behavior for sorting strings will put Z before a, since its corresponding ASCII number is lower.

**Comment by 2c2c** [comment]
`tolower()` entire string before comparison! (dont apply on output)

**Comment by tkimva** [comment]
as written in hw1 instruction, you should read `man ls` and see what the reverse order parameter. then what would be original order? As @nickzoo said, the output should be same as hammer default.

**Comment by nickzoo** [comment]
After tolower (or toupper) you have to make sure "name" goes before "Name", and also consider the special case of hidden files (don't know if we'll actually be tested on these).

**Comment by 2c2c** [comment]
im fairly sure there's a boost library that can handle all of the lexicographical corner cases

**Comment by 2c2c** [comment]
the sort is based on your system's current locale apparently. you can set std sort to sort on this
