### ISSUE TITLE
Colors of the Wind

### ISSUE THREAD

**Issue by nickzoo** [mikeizbicki/ucr-cs100#325]
When I tested the ls command on linux using ssh, hidden files did not have a gray background, as specified by the homework page. Am I missing something?

Also, I noticed that well and hammer use different colors (with well being bolder), and after running the cs100 command, no colors (other than black) are used at all. I'd been using the same colors as well, but now I'm not really sure what I should be doing.

(In none of the configurations did hidden files have a gray background.)

**Comment by tkimva** [comment]
@nickzoo  Thanks for letting me us.
with `cs100`, the default has some changes. so if you want to see correctly the color with `ls`, you should put the option llike `ls --color` and `ls -a --color` for hidden.

**Comment by nickzoo** [comment]
So, I guess my questions are: 1) Should I use the colors from hammer or well? I'm guessing hammer, but to be honest I personally prefer the colors from well. 2) Should I use a gray background for hidden files, even though I have not seen them used in any linux configuration I have tested?

**Comment by tkimva** [comment]
1) Hammer and well color are slightly different but please follow hammer.
2) this is for the extra credit. if you follow everything below, you will get the credit, or no extra credit. 

you should print directories in blue; executables in green; and hidden files (with the -a flag only) with a gray background. These effects should be combinable. So if you have a hidden directory, it should be displayed as blue text on top of a gray background.

here is an example

![screen shot 2014-11-01 at 10 52 05 pm](https://cloud.githubusercontent.com/assets/993376/4874416/6f45721e-6254-11e4-8d2c-d9d29a928759.png)
