### ISSUE TITLE
Quick .vimrc Question

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#327]
I'm in the same directory as `ls.cpp` for hw1. I type in the terminal `vim .vimrc` and in the `.vimrc` file, I set all of the settings that I want. However, when I type `vim ls.cpp`, my vim settings aren't set.

It's worked for me before, so I'm really confused as to what I'm doing wrong. I'm thinking that maybe there's a syntax error in my .vimrc file, but not sure how to determine that.

Thanks!

**Comment by 2c2c** [comment]
is `.vimrc` in `~/` or `~/.vim/` ? Put it there.

**Comment by jesuscreyes** [comment]
Got it! I was putting my .vimrc in the wrong folder. I now have it in my `~/` directory and it's working.

Thanks!
