### ISSUE TITLE
Hw#1 ls Long Listing Format Clarification

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#331]
I want to find out which flags to check when I enter the command `ls -l`. But I can't find a straightforward explanation of what each component of the list output represents. Could someone say or refer me to a source that explains the name of each section of the list?

For example, given this output from `ls -l`,

`drwxr-xr-x` `2` `jreyes` `jreyes` `4096` `Oct 30 16:45` `Desktop`.

I broke it up based on how I assumed it's broken down. I know the first section is the flags that shows what type of file it is and it's permissions. And that the `4096` is the size of the file. And that `Desktop` is the name of the file. But I'm not sure what the other sections are.

Thanks in advance!

**Comment by tkimva** [comment]
try to read `info ls` as well as `man ls`

**Comment by tkimva** [comment]
below '-l' section of `info ls`

**Comment by jesuscreyes** [comment]
`info ls` had the information I was looking for. Thanks!
