### ISSUE TITLE
Pseudocode (hw 4)

### ISSUE THREAD

**Issue by tglen002** [mikeizbicki/ucr-cs100#332]
I would like to write a tutorial on pseudocode.

**Comment by mikeizbicki** [comment]
Can you elaborate a little more?  Like we talked about, there is a danger of being too general and vague in this writeup.  How will you avoid this trap?  What examples will you use?

**Comment by ogonz007** [comment]
I will also be working on this topic.

**Comment by tglen002** [comment]
We are going to break down three different kinds of pseudocode. The first is writing your code in english with certain formatting rules (this is the format I most use, I will write down the rules I have come up with which make it easy for communicating your idea to others). The second will be a flow chart pseudocode and the third will be more heavy on the programming. All three will take the same code. Each version has different strengths and weaknesses, we will discuss those and give examples of when each version may be used most successfully.
