### ISSUE TITLE
hw4 Makefile

### ISSUE THREAD

**Issue by nickzoo** [mikeizbicki/ucr-cs100#333]
For a while I've had an irrational fear of Makefiles, and I'd like to write about them.

**Comment by mikeizbicki** [comment]
Sounds good.  Can you be a bit more specific about what aspect of Makefiles?

**Comment by nickzoo** [comment]
I'll start with the minimum of how to create a Makefile that will work for this class, and gradually go into stuff like variables, conventions, the wildcard, conditionals, etc, and maybe also some of the specifics of how the make command actually uses a Makefile.
