### ISSUE TITLE
Lab 5 submission issue

### ISSUE THREAD

**Issue by Dave864** [mikeizbicki/ucr-cs100#337]
On the lab on Monday my partner and I were not able to go through the steps of him forking my repository in order to commit the work we did. I ended up commiting the work to my own repository so that my pertner could later have access to it. However I believe that this will result in a loss of points for my hw1 submission. What do I need to do in order to not lose points?

**Comment by tkimva** [comment]
@mikeizbicki Prof. Izbicki, please answer this.

**Comment by mikeizbicki** [comment]
Your partner should:
1. fork your repo
2. delete your files
3. re-add the cp files
4. issue a pull request

**Comment by atosti** [comment]
Dave, could you merge the cp branch to your master branch so that when I fork your repo I can get all the lab files? Thanks!

**Comment by Dave864** [comment]
I had to make some changes to the assignment because it did not meet specifications and as a result I cannot merge cp with master unless I want to lose the progess I made. Also, it is unclear as how you will be able to add the cp files to the forked repository when the files are under my account.

**Comment by atosti** [comment]
Nevermind my previous comment, I got it to work on my end. Please fork my repo and add the cp files to my src when you get the chance, Dave.
