### ISSUE TITLE
HW4 - GDB Tutorial

### ISSUE THREAD

**Issue by BridgetBennecke** [mikeizbicki/ucr-cs100#342]
I had extreme difficulty understanding how to use GDB going into lab3, and it took a lot of explaining of the TA for me to get it. I would like to write a tutorial for how to use the commands and their significance towards debugging.

**Comment by mikeizbicki** [comment]
Are you thinking about a full tutorial where you walk someone through the debugging process on a specific program, or something more like a gdb cheatsheet?

**Comment by ManjunathChet** [comment]
I also had a hard time understanding GDB. I would like to make an exercise/tutorial that serves as a precursor to Lab 3. It would be a walk-through of GDB where we find bugs like those in lab, but in a smaller software package.

**Comment by mikeizbicki** [comment]
Please also take a look at #356.  I will expect you all to have some basic coordination to make sure your complements each other and doesn't completely overlap.

**Comment by BridgetBennecke** [comment]
I like ManjunathChet's idea. Would you be willing to partner with me to develop that?

**Comment by ManjunathChet** [comment]
Sounds good, let's do it

**Comment by 2c2c** [comment]
just a tip: using gdb's tui made it much more approachable for me and you should definitely go over it! you can toggle it on/off by pressing `C^X` `C^A`
