### ISSUE TITLE
Writing clean, effective test scripts #HW4

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#345]
I would like to focus on something along the lines of how to write a meaningful test script. This topic could show that using # comments in bash could be helpful in explaining what is being done/tested to someone reading the script file. Also, how to avoid unnecessary inputs or outputs could be something to write about.

**Comment by mikeizbicki** [comment]
Sounds good.  My main advice is to make sure to use specific examples, and not just generalities.

**Comment by ghost** [comment]
Thanks @mikeizbicki. I try to drop by your office hours later for any clarification/further ideas.
