### ISSUE TITLE
Hw#1 Input & exiting the program

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#349]
Just to make it clear, when we run our program, we're taking in our input similar to hw0, meaning when we run the program we get this outputted:

`$`

And then we type

`$ls -a`, press [ENTER], or any `ls` command, and then the command is executed. If the command would cause some sort of error when running `ls` normally, do we output an error message and continue taking input?

And do we keep taking input until the user enters `exit`?

**Comment by mikeizbicki** [comment]
This is incorrect.  Your program should behave like the GNU ls program.  GNU ls takes its input as command line parameters (i.e. `argc` and `argv`), not through stdin.

**Comment by atosti** [comment]
I was a bit confused on this as well. Should we be testing our program by doing commands such as "./a.out ls -a" or "./a.out ls -l" then? If so, is it safe to assume that argv[0] will always contain "./a.out", or is there a different way we should be handling input?

**Comment by hgarc014** [comment]
I believe they will be testing it as:
`bin/ls <FLAGS> <FILES/DIR>`
but flags and files can be switched.
Examples:

```
bin/ls -al
bin/ls test.cpp -l
```

but I could be wrong

**Comment by mikeizbicki** [comment]
Henry is correct.

**Comment by jesuscreyes** [comment]
Thanks!
