### ISSUE TITLE
Removing bad commits pushed to GitHub / Reverting to an old commit.

### ISSUE THREAD

**Issue by vdoan002** [mikeizbicki/ucr-cs100#354]
Earlier today I submitted a pull request, only to get it rejected due to spurious commits.

How would I go about removing those commits and pushing it to my fork?

I have tried various methods such as checkout to a good commit and push from there, but get the fastfoward error.

Thanks for the help.

**Comment by mikeizbicki** [comment]
You need your git repo to be in the exact same state as mine before creating the commit.  Going back to a previous commit will mean that your repo is still out of sync with mine.

This stackoverflow question should work you through the steps: http://stackoverflow.com/questions/7244321/how-to-update-github-forked-repository
