### ISSUE TITLE
GDB Cheatsheet HW4

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#356]
@yli082 and I would like to make a GDB cheatsheet for quick reference to the helpful commands that we used and could have used to debug our code.

**Comment by mikeizbicki** [comment]
Sounds good.

Make sure to take another look at the cheatsheet for git that Brenna created over the summer.  That was A quality work from a single student.  Since both of you are working together, I will expect something something considerably more detailed.

**Comment by mikeizbicki** [comment]
Please also take a look at #342.  I will expect you all to have some basic coordination to make sure your work complements each other and doesn't completely overlap.
