### ISSUE TITLE
Expanding on the Syscall Tutorial

### ISSUE THREAD

**Issue by gillianzliu** [mikeizbicki/ucr-cs100#357]
I felt that some of the explanations on the syscalls in the tutorial do not provide enough information, particularly when pertaining to wait and waitpid in their ability to return the exit status of a child process. I would like to expand on this and possibly other syscall explanations.

**Comment by mikeizbicki** [comment]
This sounds great!

You should find 2-3 other syscalls and do those as well.

**Comment by atran046** [comment]
I would also like to do this, more specifically I would like to expand on the open syscall and its flags

**Comment by mikeizbicki** [comment]
@atran046 Sounds good.  If you cover `open`, you'll also need to cover `close`,`read`, and `write`.

**Comment by atran046** [comment]
@mikeizbicki I'll  definitely add those to it.

Thank you.
