### ISSUE TITLE
Expanding exec system call

### ISSUE THREAD

**Issue by luizlopezm** [mikeizbicki/ucr-cs100#358]
Since we use exec a lot I was wondering if I could create a tutorial on using the different variations of the command and when each version would be favorable over another.

**Comment by mikeizbicki** [comment]
I'm having a hard time visualizing what this would look like.  Can you give some quick examples?

**Comment by luizlopezm** [comment]
For example going over:
int execl(const char *path, const char *arg, ...);
int execlp(const char *file, const char *arg, ...);
int execle(const char *path, const char *arg,
.. and so on, writing example code, going over the differences, and advantages and disadvantages to each one.

**Comment by mikeizbicki** [comment]
I seems like there's not very much to talk about.  There are exactly two types of differences.  First, the versions that end in p look up executables in the path, whereas the versions that don't end in p do not.  Second, there are three different ways to pass in the parameters, and that is pretty self evident from the function prototypes.  AFAIK, there are no other differences or (dis)advantages.

If you can give me some concrete examples of how you are going to provide more information than that, or why future students will care about what you've written, then I might approve the topic.  But as is, I don't think it will work.
