### ISSUE TITLE
HW1 late submissions

### ISSUE THREAD

**Issue by bmars003** [mikeizbicki/ucr-cs100#36]
Late submissions for HW 1 will be taken under the following conditions:

i) You needed more time to complete the assignment
ii) You did not follow the specifications and one or more of the following doesn't work for you homework:

```
$ git clone  http://github.com/yourusername/rshell.git
$ cd rshell
$ git checkout hw1
$ make
$ bin/rshell
```

By turning in a late submission you will acknowledge the following conditions:
i)  Your grade for HW 1 will have a **penalty of 25 points**.
ii) Other penalties may occur
ii) Due date is **Sunday August 10th @ 12PM**.
iii) You will need to Notify me before the deadline that you making a late submission by stating so as a comment to this post. Failure to notify by the deadline with result in the grade standing as it was the first time it was graded.
iv) **Late submission is not a reshow**
v) Being able to turn in a late submission is a privilege that can be revoked without any question.

**Comment by willccoates** [comment]
hey i plan on submitting the assignment late because i did not have enough time to finish it

**Comment by brunnaam** [comment]
I will also turn in late to fix my problem with the tag hw1

**Comment by ghost** [comment]
I will turn in late for the tag hw1 problem

**Comment by lwang031** [comment]
I tunred it in please check it.
