### ISSUE TITLE
hw4 Vim cheatsheet

### ISSUE THREAD

**Issue by ifuka001** [mikeizbicki/ucr-cs100#360]
Hi I was thinking about making a vim cheatsheet because even though we went over vimtutor in lab0, it was the beginning of the quarter and since it was first time using vim for me, it was harder to learn how to use it and I think it would be nice for future students to have a write up of vim commands instead of having to go through vimtutor everytime they need to figure out how to use some of the features.

**Comment by mikeizbicki** [comment]
Sounds good!

My recommendation is that you use latex to create the cheatsheet.  This will give you fine grained control over how things get laid out.  There are lots of simple commands in vim (compared to git where there are fewer but longer more complex commands), so layout will be very important.  I think you could make a one page (front and back) cheatsheet that would be very useful.

**Comment by ifuka001** [comment]
Ok!

**Comment by jesuscreyes** [comment]
@ifuka001 I  just talked to Mike and he said that it's possible for the both of us to work on the cheatsheet together. He said one way to make it more comprehensive:

First section: basic commands(movement, basic formatting, etc.)

Second section: advanced commands(changing colorscheme, searching through file, etc.).

If you're interested, I'd like to work on this with you.

**Comment by ifuka001** [comment]
Sure I dont mind at all.

**Comment by jesuscreyes** [comment]
Hi @ifuka001. I'm going to start looking up the different features of VIM today and organizing it. Did you want to compile all of the topics we want to cover and then check that with @mikeizbicki tomorrow to see if we're on the right track? I also have time to meet up with you and prepare something tomorrow morning from 8-11 AM.

 Here's my email so you can contact me: jreye028@ucr.edu

**Comment by ifuka001** [comment]
@jesuscreyes I emailed you. Hopefully you received it
