### ISSUE TITLE
Hw4 Bash commands

### ISSUE THREAD

**Issue by asand017** [mikeizbicki/ucr-cs100#361]
I would like to make a cheat sheet for bash commands for those commands associated with file manipulation.

**Comment by mikeizbicki** [comment]
Sounds good!

**Comment by palvarezz** [comment]
I also wanted to do bash commands but focusing on I/o redirection variables piping and workflow statements

**Comment by tassobarbosa** [comment]
Hey guys, that was my idea too. Let's try to combine them into some levels like:
- show how to use the basics command
- focus in I/o redirection

**Comment by nmlapre** [comment]
Hey guys - 

My guide will primarily cover the way the user can interact with <code>~/.bashrc</code>, the bash config file. This'll include using bash syntax to do function stuff, colors, and other useful scripts. I think we are covering fairly distinct things here, but we'll probably need to be under the same <code>.../tutorials/bash/</code> folder.
