### ISSUE TITLE
Using Sockets for HW4

### ISSUE THREAD

**Issue by luizlopezm** [mikeizbicki/ucr-cs100#362]
I was wondering if I can go over the concept of sockets, and demonstrate by showing example coding on creating simple server-client program because I know it's something previous cs100 students go over.

**Comment by mikeizbicki** [comment]
Sounds good!  I suspect this will be a rather hard topic for three reasons:
1. There's a number of syscalls involved, which would all need an explanation
2. You have to first go over pthreads as well
3. It's really easily to write threaded/networked code that seems like it works, but actually fails in a number of cases.  It's bad to have tutorials like this that don't follow best practices.

(We'll be covering all these topics briefly towards the end of the quarter.)

I would expect that a full version of what your describing would be an appropriate topic for a group of 4-5 people.  So I recommend either finding others to help out or narrowing it down just a bit (e.g. just talk about threads).
