### ISSUE TITLE
HW4 - Recursion

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#364]
I'm a little shaky on the subject of Recursion, but I'd like to research it and write about it for HW4. I'd include information about recursion, examples and explanations of well known recursive functions, and most likely some pictures to help visualize what's going in recursive functions.

**Comment by mikeizbicki** [comment]
I think you should pick just one recursive problem and discuss that.  If you pick a really interesting example, this had a lot of potential to be really good.  Something like explaining how `ls -R` works (you can't use this exmple, though, because it's a homework)  Do you have any ideas?

**Comment by abarb014** [comment]
Factorials, fibonacci, powers, merge sort, quick sort, binary trees, and we talked about Towers of Hanoi a bit in 111. I think the first 3 are too basic, but I'm not sure about the rest.

**Comment by mikeizbicki** [comment]
All of those are pretty basic.  Merge/quicksort or binary trees would be acceptable if you made some ridiculously awesome graphics that explained things visually... but I'm not even sure what those would look like.  Try to find examples of things that aren't covered in cs14 at all.

**Comment by abarb014** [comment]
I found the Ackermann function, I don't really know what it is though. And since I can't do `ls -R`, would `rm -R` or `cp -R` be acceptable?

**Comment by mikeizbicki** [comment]
Ackermann is still too simple. I'd prefer nothing involved with the filesystem.  Why don't you try running the `pstree` command?  It recursively lists all the children of a process.

**Comment by abarb014** [comment]
Okay, I ran it in hammer, and the output looks pretty cool. So I'll do a write up with a small intro about the basics of recursion, then explain the pstree command and what it does, and show how it works according to the source code. I'm not sure how I can add graphics or anything, but I'm sure I can make something so it won't be a huge wall of text. Is that okay?

**Comment by mikeizbicki** [comment]
Sounds good.  Two comments:
1. The actual pstree command is going to do a lot of edge case handling, which might make the code quite a bit harder to understand and explain.  So it might be easier to rewrite it in a simplified version.
2. I expect this will be a relatively hard project to do well because there's a lot of potential pitfalls.  Make sure you're being very specific about everything.  Don't talk in generalities.

**Comment by abarb014** [comment]
I've gotten pretty much nowhere with this topic. Is it too late to change? I'd pretty much rather do anything other than this. Recently, I made a web server with nginx. Maybe a tutorial how to make one of those, with some longer sections on the `nginx.conf` file, some detail into port forwarding, security etc. Or anything else, I'm really stuck with this recursion, and I'll take any suggestions for another topic.

**Comment by mikeizbicki** [comment]
Switching is still fine.  I think nginx is probably too far out of scope for this class.  You could talk about netcat, though, and you might be able to talk about a lot of the same things.  For example, netcat (with some clever piping) makes a good port forwarding service.

**Comment by abarb014** [comment]
So, would a netcat tutorial be okay? I still need to learn about it too, but I can try and explain some things you can do with it like chatting, file transfers, and port forwarding like you said.
