### ISSUE TITLE
Hw 4: How to use strtok to parse through a string

### ISSUE THREAD

**Issue by Dave864** [mikeizbicki/ucr-cs100#365]
Will describe the basics of how to use strtok, giving various examples using one token and using multiple tokens.

**Comment by mikeizbicki** [comment]
What type of string would you want to parse?  It shouldn't be a command line, because then people could just copy/paste your code for the assignment.

**Comment by Dave864** [comment]
The only other type of string I can see is one that is inintialized within the program instead of one being passed via command line. What do you mean by type of string?

**Comment by mikeizbicki** [comment]
Sorry, I mean you shouldn't talk about how to tokenize something like:

```
ls -al | grep ps > test
```

Instead, find some other type of example strings to work with.

**Comment by Dave864** [comment]
Okay, so my topic is acceptable as long as I use examples that are
different from the homework?
