### ISSUE TITLE
HW4: Regular Expressions

### ISSUE THREAD

**Issue by thinkaliker** [mikeizbicki/ucr-cs100#366]
I would like to make an overview of regular expressions. It would contain multiple concrete examples of usages we went over in class (for example, possible uses for \* and additional uses for *). It may include a cheatsheet for regular expressions.

**Comment by Liniarc** [comment]
I am also interested in working on regex. Perhaps we can create sample documents with examples of how to find various strings.

**Comment by mikeizbicki** [comment]
There's definitely enough stuff to talk about with regex for two people to work on it.

**Comment by thinkaliker** [comment]
Here is @Liniarc and I's progress so far. 
https://github.com/thinkaliker/ucr-cs100/tree/cs100-2014fall/tutorials/regex

We will continue to add to it.
