### ISSUE TITLE
HW4: Customizing .bashrc for fun and profit

### ISSUE THREAD

**Issue by nmlapre** [mikeizbicki/ucr-cs100#367]
I'm looking to write a tutorial that covers the basics of customizing the .bashrc file. This will start as low level as fiddling with PS1, but I'm looking to cover some more interesting alias and colorizing shenanigans as well. It's my hope that future CS100 students will use it as a guide to enhance and optimize their terminal use.

**Comment by mikeizbicki** [comment]
Sounds good.  You'll need to coordinate with the other people working on bash (#361).
