### ISSUE TITLE
HW4 Syscalls 4 Dummies

### ISSUE THREAD

**Issue by jbarb011** [mikeizbicki/ucr-cs100#368]
I would like to make a series of videos, running about 1-2 minutes each, that explain how most of the syscalls we use in this class work. The way I will explain them is through fun graphics and simple animations so that the students will have an easier time understanding exactly what the syscalls do. The explanations will be extremely simplified because I hope the students will use these more as a starting point and that they will later delve deeper into nooks and crannies of these functions. I already have the tools such as Photoshop, Flash, and Premiere to do this project and am accustomed to using these programs.

**Comment by mikeizbicki** [comment]
This sounds excellent!
