### ISSUE TITLE
HW4 dynamic memory

### ISSUE THREAD

**Issue by ahsu013** [mikeizbicki/ucr-cs100#369]
Will go over dynamic memory and how it will be use in this class, mainly the new operator and how to use them.

**Comment by mikeizbicki** [comment]
This is something that incoming cs100 students should already be pretty familiar with.  What are you going to talk about that will be different?

**Comment by ahsu013** [comment]
Mainly creating a review sheet so that future student can easily remember. I would also talk about pointers and double char pointers and how it can be use with argv.

**Comment by mikeizbicki** [comment]
Ooohhh... a good "memory management cheat sheet" has a LOT of potential.  You should use latex so that everything can be formatted nicely.
