### ISSUE TITLE
HW2 question

### ISSUE THREAD

**Issue by katherinegallaher** [mikeizbicki/ucr-cs100#37]
I'm trying to make sure I understand all aspects of the assignment so I wanted to clarify some things. 
We are creating the ls.cpp separate from our rshell.cpp file but they will be in the same repository, right? 
How should we set up user input? Can we make it so when the program runs we take one ls command and then the program quits
Or do we have to do something like we continuously take commands until they exit the program?

**Comment by bmars003** [comment]
HW2 is in the same repository as HW1.

**Comment by mikeizbicki** [comment]
Your `ls` should behave exactly like the GNU `ls` command for the `-a`, `-l`, and `-R` commands.  There is no user input from `stdin`.

**Comment by DanTheTingler** [comment]
I'm still a bit confused after reading the answers. So in our ls.cpp, if there isn't supposed to be user input, then how is the user supposed to input the flags and what not? Is the rshell.cpp supposed to call the ls.cpp everytime ls is called?

**Comment by mikeizbicki** [comment]
Your `ls` will take parameters via `argv` and `argc`.  This is different than `stdin`.

**Comment by katherinegallaher** [comment]
Oh okay! That makes sense. Thanks for clarifying
