### ISSUE TITLE
HW4 - Vim Game

### ISSUE THREAD

**Issue by jmoon018** [mikeizbicki/ucr-cs100#370]
I spoke to the professor earlier today at office hours, and we decided it would be a cool idea to make a game that helps teach the vim commands. This would be a great tool for newcomers (future students and anyone else who is interested in learning) and people who want to enhance their vim skills 

It's a nice alternative to the vim-adventures (the extra credit game); unlike vim-adventures, it would be 100% free (vim-adventures cost $20 or so), the gameplay would be different, and additionally I can customize each mini-game to test particular concepts of vim. For example, a mini-game would help improve one's ability to move around (hjkl keys), another minigame would focus on inserting text (o/a/O/A, etc), and so on. The game would be playable on the vim terminal.

I'll enumerate the mini-game ideas a bit later, I just wanted to get my idea on the issue page before I forget. Also, if anyone has a cool idea for a mini-game, post it here and I can try to implement it. 

Thanks

**Comment by rtran012** [comment]
I am also interested in working on vim game. Perhaps we can create different mini-games.

**Comment by mikeizbicki** [comment]
@rtran012 Jamal and I have talked about what this would look like, but you'll have to talk to me if you want to work on this project.

**Comment by jmoon018** [comment]
@mikeizbicki 

I have a question about how you want to be designed.

How do you want the w, W, e, E, b, etc (all the keystrokes that rely on a word) to function? I was thinking that words would spawn randomly in the map and would disappear when the ghosts walk over it, after a time limit, after the player uses it/walks over it, or a combination of these. This would grant the player the opportunity to actually use these keys as if everything were normal. Following this, I'll be able implement more commands from vimtutor; for example, I can spawn two matching brackets randomly in the map, and the player would be given the opportunity to use the '%' key (to swap to the other brace)

Will this work out? If not, how do you want the w, e, b, etc keys to work? Lastly, how do you want the commands with insertion to work (a, i, I, A, o, O..) -- normal function (letting the player type words), disabled, or hybrid (moves cursor but does not let the player insert)?

**Comment by mikeizbicki** [comment]
Do whatever you think makes the best game.

I think something like the following might work:
- letters are like the dots in pacman and the level is over once you've
  deleted them all
- the words you use should be famous somehow, like famous lines from Hamlet
  or something to make it a bit more fun.  Maybe quotes from famous
  programmers.  Or maybe each level has a different theme
- certain letters can't be deleted (the wall looking letters in the ASCII
  table); neither player nor ghost can move through these letters;
  alternatively, set the background of these letters to a different color
- Ignore insert mode for now; maybe on more advanced levels the goal won't
  be to delete everything but to change the text somehow and in those levels
  insert matters.  Maybe as soon as you enter insert mode all the ghosts
  immediately move directly in your direction.  This would give people
  incentive to stay out of insert mode as much as possible and to use the
  fancier insert mode commands.

**Comment by hgarc014** [comment]
I really like Mike's idea, haha. It reminds me of a PacMan game I made a while back.

**Comment by jmoon018** [comment]
Sounds good!
