### ISSUE TITLE
HW4 - tmux/screen

### ISSUE THREAD

**Issue by jhollister** [mikeizbicki/ucr-cs100#371]
I'd like to do my hw4 on either tmux or screen. I would prefer to do it on tmux since that is what I'm used to using but only screen is installed on hammer (tmux is installed on bell though). Is it possible to request tmux be installed on hammer?
I feel that a lot of cs100 students may not know what these programs do or why they are useful but when working on a server through ssh terminal multiplexers make your life a lot easier. I will be covering why you should use it, commands and shortcuts, and basic configuration to get started.

**Comment by mikeizbicki** [comment]
Sounds good.  It should be pretty easy to get tmux installed on hammer.  Can you email systems about it (and cc me)?
