### ISSUE TITLE
Hw#1 Getting username and groupname from userid and groupid

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#372]
I was told in office hours that there's a simple function to convert the userid and group id into actual letters, but I can't seem to find the correct function from google.

I've googled "Getting username from userid" and different variations of that, and I've stumbled on `getlogin()` and `struct passwd`, but they don't seem to be what I'm looking for.

**Comment by mikeizbicki** [comment]
The `getpwnam` and `getgrnam` functions will do what you're looking for.

**Comment by jesuscreyes** [comment]
Thanks!

I looked up the man pages for both of the functions. Those functions didn't work for me, but I was actually able to find the `getpwuid` and `getgrgid` functions, which did what I was looking for.
