### ISSUE TITLE
HW4 - Bash Quiz

### ISSUE THREAD

**Issue by hlao002** [mikeizbicki/ucr-cs100#375]
I would like to create a bash quiz program that examines the student's basic knowledge on simple bash commands and its behaviors. The quiz itself will contain fill in the blank questions and multiple choice questions. The content of the quiz will cover commonly used commands such as (cd, ls, cp, mkdir, man, connectors etc...), I believe this is something that can be implemented into a lab assignment and will help students new to Unix better understand bash.

**Comment by mikeizbicki** [comment]
This sounds like it has potential to be really good, but I'm not sure exactly what you're imagining.  Can you give some more concrete examples?

**Comment by harrychu-git** [comment]
We were planning to work on the same topic together. I was wondering if that would still be possible or would I have to contibute something different such as a bash lab?

**Comment by mikeizbicki** [comment]
You can probably work together, but I'm still not entirely clear on what exactly you want to work on.  Please provide a few _specific_ examples so I can understand better.

**Comment by hlao002** [comment]
An example of a possible question could be : 
Given the command " echo cake &&      &&  echo pie" what would be the expected resulting behavior?"
A. cake

```
 pie
```

B. cake
     pie

C. Bash: syntax error near unexpected token "&&"

D. Cake pie

I can also work together with the bash cheat sheet team so i come up with questions base on their cheatsheets

**Comment by mikeizbicki** [comment]
I suspect this will be hard to do well.

The biggest pitfall will be creating questions that don't actually test anything important.  For example, in the question you proposed, you tested the person's knowledge about bash syntax and whether `&& &&` is allowed.  This knowledge is not very useful in practice.  If ever I need to know this, I'd just try it out.  Knowing this will not prevent me from writing any hard-to-find bugs.

So I'm not going to approve this until you can come up with some better examples that test deep understanding.

**Comment by harrychu-git** [comment]
Would a bash lab be easier to do? Perhaps something that introduces bash to students so that they are more comfortable using a terminal rather than the traditional method of running commands visually (clicking icons on the screen, etc).

There were many times in the beginning of the year when I was working in my hammer and I had to look up a certain command. I think it would be useful to have a lab that introduces these commands.

**Comment by mikeizbicki** [comment]
A lab sounds a bit more promising.  What types of commands would you do in the lab?

One of the important things in designing a lab is that it's not just a jumbled mixed of "here are 20 commands that we'll introduce one at a time".  There should be some kind of "story" behind the lab.  Like you're trying to perform a certain task, and then you naturally introduce the appropriate commands to perform the task.

If you can figure out a good "story", then I think this has a lot of potential.  So I'll go ahead and approve it.
