### ISSUE TITLE
Quiz 3 - sizeof

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#38]
Can someone explain the last part of quiz 3 with the structs or point me to a link that can do so? I have the answers, but especially for the first column (sizeof(s1), sizeof(s2), sizeof(s3), etc) I don't really understand the answers the compiler is giving back. Thanks!

**Comment by bmars003** [comment]
Here is the Wikipedia article on sizeof http://en.wikipedia.org/wiki/Sizeof. I believe that it explains the concept of sizeof fairly well.

**Comment by mikeizbicki** [comment]
In particular, see the section on struct padding: http://en.wikipedia.org/wiki/Sizeof#Structure_padding
