### ISSUE TITLE
HW4 Xomad Tutorial and Cheat Sheet

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#380]
I would like to make to tutorial that covers configuration and use of xmonad (the installation is pretty straight forward), and also demonstrates its power. In the end I would provide a cheat sheet listing a few keyboard combinations that are used the most.

**Comment by mikeizbicki** [comment]
Sounds great!

I think the xmonad community would be very, very happy for someone to do a writeup like this.  You'll probably get a lot of random internet people reading it :)

**Comment by anmolsingh95** [comment]
Consider it done.
