### ISSUE TITLE
hw4-Writing Good Test Cases

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#381]
I would like for the focus of my hw4 to be advice on writing good test cases (part 1), since these are one of the more important things in any program. 

When testing some of my past programs I've wanted to find a way to test code in a more efficient way. I'll look into writing some bash scripts to do this (part 2). But if there is a better alternative then I will go with that. This is similar to the announcement in #344 , and I'll attempt to solve those issues if possible.

**Comment by mikeizbicki** [comment]
You should work with @KenleyArai on unit testing.  One of you could focus on the mechanics of using a testing framework, and the other could focus on how to create good tests.

Also, I'm closing this so that all the discussion about that topic will be in the same issue.
