### ISSUE TITLE
HW4 Valgrind Tutorial

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#382]
I'd like to write a tutorial of how to use the valgrind tool to check for memory leaks. Explain how to use it, what the output means, and some of the options by using examples with simple programs.

**Comment by mikeizbicki** [comment]
How would this be different than the tutorial that's already there?  It's fine if you want to extend that tutorial, but please explain how you will be extending it.

**Comment by khuan013** [comment]
I was thinking about a video tutorial, but I don't think that will improve the existing one. I'll work on something else.
