### ISSUE TITLE
ls -l Symlinks

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#383]
When I run `ls -l` and I have a symlink in the current directory, I get an arrow pointing to what the link points to. Ex. `link -> file`. My question is do we have to implement this?

I've tried using the `lstat()` function along with `readlink()`, but when it comes to the output, all I get is the path to the current directory, then it completely stops any output after that. I read that `readlink()` does not null terminate the string, could that possibly be what is stopping the output?

If that's the case, how would I null terminate a string that I don't know the size of?

**Comment by mikeizbicki** [comment]
I won't require you to show the path of links, but I'll let anyone who implements this feature get 3 points extra credit.  It should be pretty simple.

The return value of `readlink` is the number of bytes.
