### ISSUE TITLE
HW4 Tutorial on Macros

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#384]
Specifically, I'd like to explain how to write an object or function-like macro, how they differ from inline functions and when you might want to use them. I'd also like to include information on macro arguments, and stringification.

**Comment by SparkTesla** [comment]
Hi khuan013, I was thinking of doing a macro functions tutorial for the future CS100 students. Would you like to work together in this assigment.

**Comment by mikeizbicki** [comment]
Good idea.  Macros are pretty complicated, so there's definitely room for two people to do this.
