### ISSUE TITLE
HW4 Templates

### ISSUE THREAD

**Issue by vdoan002** [mikeizbicki/ucr-cs100#385]
I would like to do a tutorial/write-up about templates. It would cover how to write templates, use templates, the usefulness of templates, and the differences between templates and macros.

**Comment by attecodes** [comment]
I would like to work in this as well

**Comment by mikeizbicki** [comment]
Sounds great!

**Comment by jmaw001** [comment]
I was also thinking about working on templates. Would we be able to collaborate 3 ways?

**Comment by mikeizbicki** [comment]
It would need to be a pretty detailed writeup for three people, but yes.
