### ISSUE TITLE
HW4 A Visual Interpretation 

### ISSUE THREAD

**Issue by boxcarcoder** [mikeizbicki/ucr-cs100#387]
@holidaylvr  and I would like to make an extensive series of images(such as maps) and videos that can animate and cover core concepts that should be understood from each assignment. Having most guides being in the form of text, we had difficulty truly grasping and understanding what is going on "under the hood" of what we were coding. For example, from HW0, it was easy to follow the guides on how to utitlize the fork function by following the outline but we feel that providing an animation of how fork works can provide a much more in-depth understanding.

1) We would like to do this with most of the syscalls covered in all the assignments, (provide maps or animations of what is going on as syscalls are called) on a basic level to help future students visualize each call in hopes that would help them see a clear picture of how to piece them together to work on the assignment. 

2) Besides the basics, we'd like to expand on other concepts that are harder to understand (such as in HW0, nested forks, and zombie processes) as well as other miscellaneous topics such as when a syscall is called within another syscall or when a syscall relies on another another syscall. For example HW1, we can create an animation that shows opendir(const char*) creating a directory stream, and then show how readdir grabs a dirent struct from this stream for the student to operate on, to help future students understand the concept of directory access and manipulation.

Of course, these are just a few ideas of what we'd like to draw out or animate since we'd like to do this with all the syscalls required for each assignments. We'd like to further map out or animate other core concepts required to start out in the class, such as using git and how to visualize what is going on "under the hood" when we issue a pull request, when we fork to other directories, how branches are merged, how files are pulled and pushed from git to the local machine, and more ideas we'd like to cover.

**Comment by mikeizbicki** [comment]
This sounds amazing!  Animations would be super helpful to understand these concepts.  If the results turn out really well, you guys could get a lot of extra credit for a project like this.

There's some other people who are going to be reworking some of the info in the syscalls tutorials.  So make sure you talk to them so that your graphics will flow with the changes they make
