### ISSUE TITLE
HW4:  C++ 11 Features

### ISSUE THREAD

**Issue by emullally** [mikeizbicki/ucr-cs100#388]
I would like to do an informative write-up of some new features included in C++ 11 which would be useful for cs100 students to know. Topics could/would include type inference (auto type), new null pointer constant, new object constructor capabilities, uniform initilization syntax, lambda functions and expressions, and range-based for loops. I am willing to expand on this list and work with others if anyone is interested. (I cannot figure out how to add a label to this issue.)

**Comment by mikeizbicki** [comment]
Sounds great!
