### ISSUE TITLE
HW2 ls flags

### ISSUE THREAD

**Issue by katherinegallaher** [mikeizbicki/ucr-cs100#39]
The command line args are supposed to tell us what version of ls we're supposed to do right? So when the program is run it should be something like, "./a.out ls -al" ?
How are we supposed to differentiate between if they were to put -la or -al or any combination of the three possible flags ? I can't think of a way to do it that just isn't checking for each possibility one by one which is way too long.
Can anyone give me some hints?

**Comment by bmars003** [comment]
The 3 different flags `-a` , `-l` , and `-r` each interact with ls in some way.  As for your question regarding how can we distinguish between `-al` and `-la`, does it really matter the order that the flags come in? Don't you just need to know what flags the user inputs? First I would start of by seeing if flags are passed in? How do we know a flag is being passed in as an argument?  Then I would check to see what flags were passed in. From that you should be able to have your program act accordingly to those flags.

Don't forget to test for different combinations of the flags.
