### ISSUE TITLE
Hw#1 Checking if a file is a symbolic link

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#393]
I have a symbolic link in my current directory called `homeLink`, which I created using this command:

`ln -s ~ homeLink`.

So this link takes me to my home directory.

When I try to check if the file is a symbolic link using stat, I use a similar condition that was given to us in the `stat.cpp` file, which showed us how to check if a file is a directory. The only difference is that I use `S_ISLNK` instead of `S_ISDIR`.

`S_ISLNK(statbuf.st_mode)`

If the above condition is true, then I want to output an `l`, otherwise I check to see if it's a directory or a regular file.

However, when I try to use this condition, my symlink `homeLink` is seen as a directory rather than a symbolic link. Does anyone know what might be causing this?

**Comment by tkimva** [comment]
What about doing this. In your conditional logic, check S_ISDIR first and the S_ISLNK last so that if even it's both symbolic link and directory, it will print `l` not `d`.

**Comment by aorti017** [comment]
I had the same problem, I suggest looking into `lstat()`. From the man page; "lstat() is identical to stat(), except that if path is a symbolic link, then the link itself is stat-ed, not the file that it refers to."

**Comment by jesuscreyes** [comment]
@tkimva: That was actually what I did initially, but it doesn't work either.

@aorti017: I tried to use `lstat()` and it worked!

So I think when I was using `stat()`, I was stat-ing my home directory, as opposed to the actual symbolic link.

Thanks so much for the help!
