### ISSUE TITLE
ls output

### ISSUE THREAD

**Issue by attecodes** [mikeizbicki/ucr-cs100#394]
when i run my program it formats nicely into four left aligned columns but if the name of a file is over 14 characters than the formating gets slightly messed up.. Should i try and figure out a way that will always format nicely no matter the file size or can we just assume the directory wont have large file names

**Comment by tkimva** [comment]
Yes, I think, yes, please refer original `ls`. In case of there is any file with long filename, they adjust the listing format.

**Comment by mikeizbicki** [comment]
You may assume a fixed width terminal size (e.g. 72 or 80 characters).  You may not assume a maximum file size.  The number of columns MUST be determined by the file sizes.

**Comment by aorti017** [comment]
Does this mean, assuming you're printing alphabetical from left to right, that the number of columns in a row is based on the amount of characters in those files' names? Or are the number of columns for each row the same?
