### ISSUE TITLE
O_CREAT mode

### ISSUE THREAD

**Issue by aorti017** [mikeizbicki/ucr-cs100#395]
When testing `open()` with the `O_CREAT` flag and no mode I noticed that the file created would output in the color green when I ran `ls`, meaning it was executable. I assumed that this was how `open()` handled the flag when no mode was passed in, but after reading over the man page I found that nothing is mentioned of what happens when nothing is passed in for the mode. So, is this undefined behavior or is this case handled by `open()` but not listed on the man page? Also, what permissions should we set when creating a file for home work 2?

**Comment by mikeizbicki** [comment]
Good question!  I'm giving you +3 points extra credit for it.

The default permissions for a file is determined by the process's umask (see `man umask`) for more details.  The created file should use the umask, which is the default permissions given by the `open` function.
