### ISSUE TITLE
Hw#1 Request for Office hours on Monday

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#399]
I was just wondering if the T.A. or the professor would be available for office hours tomorrow, since I'm assuming there won't be any office hours on Tuesday because of the Holiday.

My schedule is kind of tight on Mondays. The only gaps I have are from 9-11, 2-4, and 5-6. Any available times that either of the instructors can make would be greatly appreciated.

**Comment by mikeizbicki** [comment]
I'm sorry, but I'm not available at all on Mondays.  Is there something specific you have a question about?

**Comment by tkimva** [comment]
I will.
