### ISSUE TITLE
cp forking

### ISSUE THREAD

**Issue by asand017** [mikeizbicki/ucr-cs100#405]
Last week in lab, my inconsiderate partner left lab before I could fork his repository so I had committed the code to my rshell so that I had the code. I issued a pull request and he has still yet to acknowledge it. Is it too late to try to fork the cp file into my rshell or have I already lost the points?

**Comment by mikeizbicki** [comment]
If for whatever reason you can't get your original partner to help you out, you can get a new partner.  You don't have to recode anything with them, just get them to go through the procedure of adding the cp to your repo with you.  You won't lose any points for this.

Does that make sense?

**Comment by npsark** [comment]
Hi, I'm really confused about this part of the assignment. I currently have a working version of cp.cpp that my partner and I wrote in lab. How should I go about adding it to my project such that it follows the assignment requirements? Right now when I run git blame on it, it only shows my name.
