### ISSUE TITLE
Hw 2 clarification 

### ISSUE THREAD

**Issue by rtran012** [mikeizbicki/ucr-cs100#410]
For Hw 2, piping, do we have to write our own stdin and stdout?

**Comment by mikeizbicki** [comment]
I don't understand what you're asking.  Can you elaborate?

**Comment by rtran012** [comment]
In class you were showing us how to open close and duplicate stdin and stdout with the commands close(1) and dup(1), was this so we write our own stdin and stdout or is it for another reason?

**Comment by mikeizbicki** [comment]
I can't figure out what you mean by "write our own stdout"?

**Comment by rtran012** [comment]
I figured it out.  Thank you though.
