### ISSUE TITLE
partner request for cp fork

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#411]
Hi people, i havent heard from my partner at all regarding forking the cp program for hw1. I know izbicki said it doesnt matter who the partner is so if someone can help me out thatd be great. I have my fully completed cp.cpp and i just need to go through the process of pulling it from someone else. So if anyone can give me a hand thatd be really great

thanks

**Comment by hgarc014** [comment]
Sure, send me the code.

either by pull request on my project
or by emailing me the file, hgarc014@ucr.edu

**Comment by npsark** [comment]
thank you so much. ill email it right now!

**Comment by hgarc014** [comment]
since it is in your repository I guess you don't have to email or pull request, but oh well.

**Comment by npsark** [comment]
wait im confused so i see that you have a copy of my rshell on ur account now. do i need to do something with that? it still says mu name on all the changes in cp.cpp

**Comment by hgarc014** [comment]
So, you have your own project called rshell. I also have my own called rshell.

I fork your project onto my github (basically copying your project into my github). After I have a copy of your project, I clone my forked repository. I edit the files, push to my forked repository, and finally issue a pull request to you. You then, inspect my pull request to see if it is fit to be added to your project.

This is useful if you fix a bug for another project on the internet or add a feature, or something else.

**Comment by anmolsingh95** [comment]
hey henry can you help me too coz i missed lab last week. I can email you the file
