### ISSUE TITLE
Gray background for hidden files/directories

### ISSUE THREAD

**Issue by drami025** [mikeizbicki/ucr-cs100#414]
Having a gray background for hidden files and directories makes the text kind of hard to read. Is it okay if we make it a different color?

**Comment by 2c2c** [comment]
bumped into this earlier and just stuck with the grey. might not have jumped out as important to @mikeizbicki because he uses a white terminal (and hence black foreground text) ?

**Comment by hgarc014** [comment]
Yes, I think it just depends on what your terminal color is. Mine is black background with white text, so it doesn't look too bad.

**Comment by tkimva** [comment]
please see #325
