### ISSUE TITLE
Deadline is soon 11:59pm for Homework 1

### ISSUE THREAD

**Issue by tkimva** [mikeizbicki/ucr-cs100#415]
Please finish your homework 1 before the deadline. 
Double check your submission with the following commands before you finalize.
Your code must not generate any warnings on compilation with make on hammer (under "cs100" script).

```
$ git clone  https://github.com/yourusername/rshell.git
$ cd rshell
$ git checkout hw1
$ make
$ bin/ls
```

**Comment by 2c2c** [comment]
clarification: no test cases needed for `cp` right?

**Comment by hgarc014** [comment]
You always need test cases.

https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/assignments/hw/hw1-ls

under test cases...
"Again, the tests you choose will be the most important part of your grade."

**Comment by DustinPham** [comment]
It doesn't say anything about test cases for `cp` though.

**Comment by hgarc014** [comment]
oh, sorry. I miss read the question. Yeah, you are correct.

**Comment by 2c2c** [comment]
the risk's too high boys crank the tests out

**Comment by tkimva** [comment]
No. no test case for `cp` since there was nothing to say about this and I don't think @mikeizbicki mentioned this in the lab last week.
However, for the future, basically, every code you implement needs test cases. I think it's the default.
