### ISSUE TITLE
hw0 grade

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#417]
I pushed two Homework hw0 and hw1. Would you please grade hw0 rshell.
Thank you for your patient.

**Comment by tkimva** [comment]
I don't understand, then why did you make hw1 tag?

**Comment by tkimva** [comment]
Aha.. I heard from professor. Okay. I see what you mean.

**Comment by tkimva** [comment]
Your homework 0 is just graded
