### ISSUE TITLE
char *dirName

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#42]
I'm getting a warning from the code given in assignment two from this line of code:

char *dirName = ".";

The warning is: warning:deprecated conversion from string constant to 'char*'

**Comment by bmars003** [comment]
What is the difference between "" vs '' ?

**Comment by DanTheTingler** [comment]
Both of them gave me a warning, I changed it to char const *dirName = "."; and it got rid of the error.

**Comment by bmars003** [comment]
Hope these helps explain the error http://stackoverflow.com/questions/21529194/c-warning-deprecated-conversion-from-string-constant-to-char-wwrite-stri
http://stackoverflow.com/questions/7468286/warning-deprecated-conversion-from-string-constant-to-char
