### ISSUE TITLE
Hw#2 Understanding output.cpp from lecture

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#423]
I'm looking at `output.cpp` from the lecture folder, and I'm trying to understand the purpose of every line.

`int fdo=open("testfile", O_WRONLY);`

This line is assuming I have a file somewhere in my current directory called `testfile`. When we execute this line, we are opening `testfile` with write permissions, and we return the lowest-numbered file descriptor not currently open for the process. So at this point, `fdo == 3` because the file descriptors `0, 1, 2` are open, corresponding to `stdin`, `stdout`, and `stderr`, respectively.

`int fdi=open("in",O_RDONLY);`

This line is also assuming I have a file somewhere in my current directory called `in`. When we execute this line, we are opening `in` with read permissions, and we return the lowest-numbered file descriptor again. In this case `fdi == 4` because the file descriptor `3` is open in `fdo`. What's the purpose of this `in` file?

`close(0);`
`close(1);`

We close the file descriptor `0` and `1`, meaning that we close the `stdin` and `stdout` processes.

`dup(fdi);`
`dup(fdo);`

So `dup` is creating a copy of the input file-descriptor, and uses the lowest-numbered unused descriptor for the new descriptor. So when I call `dup(fdi)`, a copy of `fdi` is put at file descriptor `0` corresponding to `stdin`. At this point, I'm still not sure what the `in` file is used for, or how it should be used.
Similarly, when I call `dup(fdo)`, a copy of `fdo` is put at file descriptor `1`, corresponding to `stdout`. Is that correct? So at this point, anything that would normally be printed on screen 

`argv[0]="ls";`
`execvp(argv[0],argv);`

Executes `ls` command. But now, instead of outputting it to the terminal, the output now goes to `testfile`. I'm guessing that the reason this happened is due to `dup(fdi);`. So this is a simple example of how someone can implement output redirection.

Thanks for taking the time to read this. If you can answer any of my questions or if you notice an error in my logic or understanding, please let me know. Thanks!

**Comment by atosti** [comment]
As far as I can tell "in" is not needed, since commenting out all lines involving it (9, 10, 12) gives the same result as before with ls's output being printed to "testfile". However, if you wanted to route input from "in" to "testfile" you'd want to use read() and write() by adding the following lines:

```
char buf[80]; //I put a value of 80 here, not sure how you select the proper size to match the input
read(fdi, buf, sizeof(buf));
write(fdo, buf, sizeof(buf));
//And then comment out argv[] lines
//argv[0] = "ls";
//execvp(argv[0], argv);
```

I'm still not sure why "in" was included in the cpp, though, maybe just to demonstrate how to open input files?

**Comment by jesuscreyes** [comment]
Thanks for the response!  That makes sense. So `read()` would read input from the file that correlates with the file descriptor `fdi` and store it in the array `buf`. Then using `write()`, we take what's in the buf, and write it to the file that correlates with the file descriptor `fdo`.

So that would be an example of input redirection and output redirection.

**Comment by mikeizbicki** [comment]
All the explanations so far are correct, with one small correction.  You're both correct that the `fdi` variable is what you would use for input redirection.  In fact, input redirection is fully working in this example.  It's just that the `ls` program doesn't take any input from stdin.  If you instead call `cat`, you'll see the input redirection work.

In particular, there is no need to call `read` and `write` to make input redirection work.
