### ISSUE TITLE
Meeting with an Instructor -- hw1 

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#424]
Hi, I was hoping to have a meeting with any available instructor at his best convenience to discuss my hw1. I'd like to make it to Office hours but I have class at those times.

**Comment by tkimva** [comment]
how about talking after 3:40 Monday?

**Comment by gbrlrz017** [comment]
Yes that works, thank you!

**Comment by tkimva** [comment]
come to WCH110, anyone else TA office hour is a conflict with your class on Tuesday come to Monday 3:40-4:10 WCH100

**Comment by tkimva** [comment]
Did you meet professor today? or will be on Monday?

**Comment by gbrlrz017** [comment]
@tkimva , I went to speak with him on Friday but he said I must talk to you about hw1 grade questions. I just sent you an email to talk about this.

**Comment by tkimva** [comment]
Okay
