### ISSUE TITLE
HW2 - Operator Input

### ISSUE THREAD

**Issue by atosti** [mikeizbicki/ucr-cs100#425]
When we're parsing the input to our rshell program for HW2, do we need to account for operators being passed which aren't surrounded by spaces? For example, this has no spaces around the pipe:

```
ls -l|sed -e "s/[aeio]/u/g"
```

Whereas this surrounds the pipe with spaces:

```
ls -l | sed -e "s/[aeio]/u/g"
```

Do we need to need to handle both of these cases, or can we assume that the user will always enter spaces between the redirection operators and their arguments?

**Comment by 2c2c** [comment]
my assumption is that this is what mike meant at the beginning of class when he said often people have to redo their hw0 to continue through the course. if you designed the way you handle operators really badly (or didn't do them at all), it would mean you're 'redoing' the parsing logic for something that should already be done

**Comment by mikeizbicki** [comment]
A full credit solution is able to parse a `|` operator no matter how much whitespace is on either side, and no matter what characters actually make up that whitespace.

**Comment by jesuscreyes** [comment]
Hi @mikeizbicki. I believe you mislabeled this issue to be `hw1` when it should be `hw2`.

**Comment by mikeizbicki** [comment]
Thanks, fixed.

**Comment by 2c2c** [comment]
closing makes it not show up on the front page (there are likely others who will wonder about this question)

**Comment by atosti** [comment]
Aight, thanks for the heads up; I'll keep it open for a while.
