### ISSUE TITLE
checksyscalls script not working

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#429]
Hello professor
The checksyscalls scipt is not working. It shows up an error message that looks like ./rmcomments.sh : no such file or directory. This is however not the case as the file is there. I also tried running it on one of the lab computers and got the same result.
After a lot of tinkering with the script, I found out that if you remove the line that says source "scriptdir/config.sh" and then run the script, it works fine. 
SO could there be a problem with the config.sh file and why do we even need it in this script?
And also should I submit a pull request for the changes made?

**Comment by hgarc014** [comment]
the checksyscalls function will work if you are in the main directory of the ucr-cs100 file. I was going to look into this and fix it, but if you already found the problem. Be my guest.

**Comment by anmolsingh95** [comment]
Yes, you are right, that will help a lot in the bugspotting.

**Comment by mikeizbicki** [comment]
Thanks.  I've fixed this bug.  If you're looking for something to fix, it would be nice if the checksyscalls script would take multiple files (or directories) as parameters.
