### ISSUE TITLE
hw2 flag input

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#43]
When testing, should we test with "./a.out ls -l -a" or "./a.out -l -a". 

To word my question a little better, should we test with or without the ls, and when you guys do the final check, are you going to be typing in ls or not? And is this the correct way to test it?

**Comment by bmars003** [comment]
Think of it this way when using ls do we want to use  `ls` do we type `ls ls -l` ? NO. Your programs executable should be named `ls`. You program should work like the `ls` command does/
