### ISSUE TITLE
Comments on hw2

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#433]
You are not expected to be able to handle commands that have connectors (`;`,`&&`,and`||`) and pipes (`|`) in the same command.  For example, you are not expected to handle:

```
ls | cat && echo test
```

But you must be able to handle io redirection and pipes in the same command, for example:

```
cat < infile | grep test
```

If you did not get connectors (`;`,`&&`,`||`) working in hw0, you do not have to have them implemented in hw2 to get full credit.  You can still get 100% without them.

**Comment by gbrlrz017** [comment]
Can it be extra credit if we can get connectors and pipes to work together?

**Comment by 2c2c** [comment]
chaining pipes is a requirement right?

**Comment by gbrlrz017** [comment]
@2c2c Should be since the test case in the readme has chained pipes

**Comment by 2c2c** [comment]
Yeah I guess I should have specified can there be forms of redirection between chains of piping. cause that increases the complexity by a lot I think. The test case doesn't display this IIRC

**Comment by hgarc014** [comment]
you should test bash's piping with input redirection and output redirection.

if you have something like:
`cat < filename | grep something | grep somethingElse | cat > newfile`
then it is perfectly fine
if you have something like:
`cat < filename | grep something | cat < anotherfile | grep sup`
then bash will only `grep sup` from anotherfile. (in a way ignoring everything before `cat anotherfile`)
if you have something like:
`cat < filename | grep you| cat | wc -l > newfile | grep doSomething`
then bash will in a way stop after newfile and seem to not execute `grep doSomething`

I didn't give the details of what bash is doing and these don't cover all cases, but think of it like you are piping the output of a program to the next one. So, if your program doesn't do any output its not possible to pipe the output of the program to the next one. I'm not sure if that made sense...
