### ISSUE TITLE
Credit for tor relay not given

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#436]
Hello Mike
The other day after lecture I showed you my laptop running xomand and tor. You then asked me some questions about tor and then checked me. But I have yet to receive those 5 extra points.
Hundal

**Comment by mikeizbicki** [comment]
I just checked your grade file and you have 30/25 points, with +5 for tor.  Maybe you haven't run `git pull`?

**Comment by anmolsingh95** [comment]
I showed a bootable linux +25
xmonad +5
tor +5
so shouldnt that be +35 or is +30 the max?

**Comment by mikeizbicki** [comment]
Oh, I thought you only did tor.  I didn't realize you wanted to be checked off for xmonad as well.  I've updated your grade... I'll believe you have it running :)
