### ISSUE TITLE
Hw#2 Changing file descriptors

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#438]
Say I have this in my command line:

`$ cat < inputFile; ls > outputFile`

When executing `cat < inputFile`, the default file descriptors will be changed.

My question is, after finishing this first command, is it good practice to restore the file descriptors to their default values after finishing every command? Is it absolutely necessary? So before I try to execute `ls > outputFile`, should I restore the default file descriptors to their default values?

**Comment by mikeizbicki** [comment]
You should _never_ be changing the file descriptors in your parent process, only in the children.  Therefore, there is never anything to restore.

Also, as per #433, I'm not requiring you to have the connectors and io redirection working within the same command.  Therefore the command you suggested (`cat < inputFile; ls > outputFile`) is not necessary to have working.

**Comment by jesuscreyes** [comment]
Got it. Thanks!
