### ISSUE TITLE
ls -l column headings

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#44]
Anyone know where we can find good answers on what exactly each part of ls -l is/what part of the struct stat it relates to?

**Comment by DanTheTingler** [comment]
Found the answer myself here, link just in case anyone needs it:

http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/ls.1?query=ls&sec=1

Here's the paragraph as well:

If the -g, -l, or -n options are given, the following information is displayed for each file: mode, number of links, owner (though not for -g), group, size in bytes, time of last modification (“mmm dd HH:MM”), and the pathname. In addition, for each directory whose contents are displayed, the first line displayed is the total number of blocks used by the files in the directory. Blocks are 512 bytes unless overridden by the -k option or BLOCKSIZE environment variable.

**Comment by bmars003** [comment]
See issue @issue41
