### ISSUE TITLE
Calcgrade not working details

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#443]
These are the commands I followed:

1) `ssh ihund001@hammer.cs.ucr.edu`
2) `git clone https://github.com/mikeizbicki/ucr-cs100.git`
3) `cd ucr-cs100/scripts/`
4) `./calcgrade.sh ihund001`
This gives an error 
"finding grade for github account ihund001
awk: cmd. line:1: fatal: cannot open file `people/students/ihund001' for reading (No such file or directory)
 ERROR: student ihund001 does not have attribute giturl in their studentinfo file"

I will put  merge request for the fix and detail it there

**Comment by hgarc014** [comment]
this is possibly due to a change @mikeizbicki  did on the config script.

**Comment by anmolsingh95** [comment]
exactly. He removed the backtrace to the root folder.
