### ISSUE TITLE
Extra credit opportunities

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#445]
The calcgrade script can be made easier to use in two ways: 
1. (easy) There is no reason that it has to take in a single argument which is the student's username.  If no argument is passed in, then we can just use the username of the currently logged in user as the default.  I'll give **20 points** of extra credit to a pull request that fixes this.
2. (harder) Ideally, the calcgrade script (and all the other scripts) could be run from any directory, not just inside the project directory.  This would require some sort of "installation" so that the scripts get added to the path and we can determine where the project directory is installed.  It will take a little bit of research on your part to figure out the best way to handle this.  I'll give between **30-80 points** extra credit to a pull request that fixes this, depending on how robust it is.

If you want to tackle either of these problems, please post here with a rough idea of how you'll solve it and get my approval before getting started.  ( I don't want you going down the wrong track, or having multiple people working on it and so someone ends up wasting their time.)

**Comment by anmolsingh95** [comment]
1) For the first part we can use `git config -l` and do a little bit of parsing to get the user name.

2) For the second path we could use `find  ~/ -type d -name "ucr-cs100"` to get the absolute path of the project directory and then append it with /scripts/. So any script would work from any directory outside the project directory.

**Comment by 2c2c** [comment]
1. Could possibly be even more robust if you have it search for the current git global name. It could 'figure out' who you are even if you aren't launching the script from your ssh account. I cannot into bash though, so I'll just leave the idea on the table.

**Comment by anmolsingh95** [comment]
1) Yes thank you, but the above one works regardless you ssh or not. It uses the current git repo information. ( hopefully the user cloned from his version of the repo ).

**Comment by mikeizbicki** [comment]
@hundal78 
1.  It would be better to get the student's actual username (using `whoami`) since that will always be available even if git isn't set up
2. This solution would be extremely slow and require that the folder exists in the users home directory.  There shouldn't be a need for it to exist in the home directory, though, since it's installed systemwide on hammer.

I want to give someone else a chance at the extra credit since you're grade's already quite good.  If no one else announces they want to do the project before Monday, though, I'll let you do it.

**Comment by 2c2c** [comment]
I think using both(searching username and checking for git info as a fallback) would be pretty bulletproof. Personally, I avoid working/using through ssh because of the uncontrollable limitations it tends to present (old vim version, 8 bit colors, having to use tmux for extra windows...).

**Comment by anmolsingh95** [comment]
Sure @mikeizbicki 
1) The `whoami` would not work for some people including me who do not use their own name as their username, but an alias.
2) I did not know that it is in hammer. Well that would make it even simpler, since it'll always be a fixed path

**Comment by harrychu-git** [comment]
1. Could the 
   echo "no github account given"
   exit
   commands in calcgrade.sh simply be replaced by
   user=$logname?

**Comment by mikeizbicki** [comment]
@hchu007 Something very similar to that (`$logname` is not a variable though). It would also need to check that the logged in user actually is enrolled in the class and print an error message if not.  

Also, I'd like it to also do the git failback check that @2c2c mentioned.  I'd up the extra credit to 30 points for doing that too.
