### ISSUE TITLE
multiple redirections

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#446]
Do we have to be able to handle multiple redirections??

Examples of bash on my computer:

```
cat < file1 < file2 < file3
cat < file1 < file2 < file3 > newfile
echo 'this is a test' > anotherfile > anotherfile2 >> anotherfile3
```

Example output:

```
prints contents of file3 only
contents of file3 transfered to newfile
'this is a test' is transfered to anotherfile3 only
```

**Comment by mikeizbicki** [comment]
You must be able to correctly handle at least one input and at least one output redirection in the same command.  You are allowed to do anything reasonable if there are multiple input (or multiple output) redirections.  Possible ways to handle this are: 
1. print an error message
2. do only the first
3. do only the last
4. do all of them

I don't care what you choose, but you should document it in the README file.
