### ISSUE TITLE
Input Redirection Test Cases HW2

### ISSUE THREAD

**Issue by DustinPham** [mikeizbicki/ucr-cs100#448]
Hey there, is there any special test cases for input redirection? All I've found to work is `cat < test` where `test` is just a file with `hi` inside of it. But that's basically just the same as `cat test` right? The only other example of input redirection I've found online was something like `mail someone < letter_to_mail` which I don't think we're supposed to do?

**Comment by ahsu013** [comment]
You can use wc command.

**Comment by gbrlrz017** [comment]
It seems to me like `<` is there just to be there, since something like `cat < test` is the same as `cat test`. Of course, I am probably wrong about that. 
Any luck with test cases?

@ahsu013 how would we use `wc`?

**Comment by ahsu013** [comment]
I usually run wc -l < Makefile to count the number of lines in my Makefile. You can add  > output  to make sure both your input and output redirection work on a single command. So something like wc -l < Makefile > output will count the number of lines in Makefile and put the output into a file name output.
