### ISSUE TITLE
Hw#2 Trying to append redirected output ">>"

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#449]
If I enter this line:

`$ echo Hello > outputFile`

I know that I have to change the file descriptor for the output file to `stdout`. So when I execute the `ls` command, the output goes goes to `outputFile`.

But say I want to append the world "world."

`$ echo World >> outputFile`.

Expected contents of `outputFile` would be:

`Hello`
`World`.

I've been trying to figure how to add data to the file without overwriting the whole file. I've tried googling how to do it, but most results that I've found don't involve using file descriptors. So I was wondering if anyone could point me to some resources or give me some tips on how to approach this.

Thanks!

**Comment by 2c2c** [comment]
O_APPEND as one of opens flags

**Comment by jesuscreyes** [comment]
Thank you so much!
