### ISSUE TITLE
Hw#2 Request for Office Hours for today [Mon]

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#450]
I was wondering if either the professor or TA would have any free time today to answer questions about the homework assignment.

**Comment by tkimva** [comment]
I'll have short office hour 3:40-4pm tomorrow for homework 1 grade.
so if you have question and it's good for you to come that time.

**Comment by tkimva** [comment]
I meant Monday 11/17

**Comment by jesuscreyes** [comment]
I have a class that starts at 4, but I'll try to prepare all of my questions in advance.

Thanks!

**Comment by tkimva** [comment]
We already discussed. So if you want to have another question, please come 3:40 WCH110
