### ISSUE TITLE
stdin and stdout doesn't work For hw2

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#451]
For HW2, it does work properly  for >, <, | , but it is limit only one time commands. If I tried to renter another command after executing once, the stdin works wired. I can't find the bug, I am thinking if there is something rule after using pipe() or dup() function?
Thank you!

**Comment by tkimva** [comment]
We already met and you need to familiarize with using GDB for debugging. Just come tomorrow office hour

**Comment by jinsongwei** [comment]
OK, thank you.
Actually I found the bug, but still don't understand the reason.

The c = getchar() automatically generate "-1" assign to the c.

Old value = 0 '\000'
New value = 32 ' '
inputCommand () at temp.cpp:88
88      cout << "[rShell_] $";
(gdb) 
90      c = getchar();
(gdb) 
[rShell_] $Hardware watchpoint 3: c

Old value = 32 ' '
New value = -1 '\377'
inputCommand () at temp.cpp:92
92      while(c != EOF)
(gdb) 
108         return temp;
(gdb)

**Comment by tkimva** [comment]
come to my office hour tomorrow
