### ISSUE TITLE
When is hw2 due?

### ISSUE THREAD

**Issue by BridgetBennecke** [mikeizbicki/ucr-cs100#452]
In lab today, Taeyoung said that the due date was moved to Thursday, but I haven't seen an announcement about it.

**Comment by hgarc014** [comment]
I think he was saying that it might be moved to thursday, but it wasn't official. So, until there is an announcement I would assume that it is still due tomorrow.

**Comment by mikeizbicki** [comment]
It's moved to Thursday, see #453

**Comment by tkimva** [comment]
In the lab, I was exactly saying that there might be possibility to extend. It wasn't official. Anyway, it moved now.
