### ISSUE TITLE
Does our rshell need to be able to handle cd?

### ISSUE THREAD

**Issue by khuan013** [mikeizbicki/ucr-cs100#454]
From hw0:

IMPORTANT: Most bash commands are actually executables located in /bin. But some commands are special and are built in to bash. The cd command is the most common example. So while the ls command should "just work" for you, the cd command won't. You'll be adding this feature in a later homework.

Do we need it for this assignment?

**Comment by hgarc014** [comment]
not for hw2, but yes for hw3
https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/assignments/hw/hw3-signals

**Comment by khuan013** [comment]
Alright thanks.
