### ISSUE TITLE
Hw#2 Logic for piping (Simple example)

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#455]
I'm trying to base my piping from the tutorial: https://github.com/mikeizbicki/ucr-cs100/tree/cs100-2014fall/tutorials/syscalls

Say I have a file called `inputFile` which has the line `HELLO WORLD` in it.

Then say I enter this in my command line:

`$ cat < inputFile | tr A-Z a-z`

First I create a pipe.

Then in my first use of `fork()`, when I'm in the child process, I make `stdout` the write end of the pipe by first closing the file descriptor for stdin, `0`, and using `dup2` to create a copy of the file descriptor of the write end of the pipe at `stdin`.

Then I execute my first command, `cat < inputFile`. At this point, the output of this command should be in the pipe.

Then, when I'm in the parent process, I make `stdin` the read end of the pipe.

While I'm in this second parent, I call `fork()` again. When I'm in the second child process, I execute my second command `tr A-Z a-z`. My assumption is that at this point, the command `tr` will take what's in `stdin` as input when I execute it.

Then in my second parent process, I wait until my second child process is done. And once this completes, I'm done.

At this point, I expect to get this output: `hello world`. However I'm running into errors and I think it's because `tr A-Z a-z` is not receiving input from the output from `cat < inputFile`. So nothing actually gets outputted.

Could someone check my logic and see if there's anything obvious that I'm missing, particularly in how I think piping is supposed to work. Thanks!

**Comment by mikeizbicki** [comment]
> Then, when I'm in the parent process, I make stdin the read end of the pipe.

This part is wrong.  You should only be manipulating file descriptors in the children.  Otherwise, everything looks pretty reasonable.

**Comment by jesuscreyes** [comment]
When i wrote that, I was referring to this line in the sample code:

`if(-1 == dup2(fd[0],0))//make stdin the read end of the pipe` 
`perror("There was an error with dup2. ");`

Is this line incorrect? Or am I misinterpreting what this line of code does?

**Comment by mikeizbicki** [comment]
You're correct that that's what the line does.  I'm saying that line should never be called within a parent, but only within a child.

**Comment by jesuscreyes** [comment]
Oh OK. I'm a little more confused now because of the sample code. Could you explain why this line is called in the parent process in the sample code for `pipe()` from the tutorial? I know the sample code is incomplete, so perhaps it's there because it's expecting something else?

**Comment by mikeizbicki** [comment]
It's a bug in the tutorial.

**Comment by jesuscreyes** [comment]
Ahh, OK. Thanks!

**Comment by jesuscreyes** [comment]
@mikeizbicki, did I actually make a typo when I said this:

"Then in my first use of fork(), when I'm in the child process, I make stdout the write end of the pipe by first closing the file descriptor for `stdin`, 0, and using `dup2` to create a copy of the file descriptor of the write end of the pipe at `stdin`."

Should that last word have been `stdout` instead of `stdin`? Because the output of my first command will go to `stdout`, I want that output to go to the write end of the pipe. So I would do something like `dup2(fd[PIPE_WRITE], 1);`. Is this correct? Or was I correct the first time?

**Comment by hfanc001** [comment]
Does that mean the method we are using to implement piping is that we output the result of first command (cat input) in a stdin that we created with dup, so when we go back to execute our next command (tr a-z A-Z) in fork, we will read input from the stdin that we duplicated earlier?

**Comment by 2c2c** [comment]
for 2 processes, the first process uses stdin and writes stdout in the writeend the pipe, 2nd process reads the stdin in the read side of his pipe and lets stdout go. 

for n processes, the pattern is the beginning of the pipe chain needs stdin for initial input and the last process must have open stdout to output the final result. everything imbetween is connected out -> in -> out -> in  ... etc. seamlessly

this stuff is horrible to explain in english. theres a few nicer pseudocode examples on stackoverflow if you googlefu well enough.

**Comment by jesuscreyes** [comment]
Thanks for everyone's input! I think it just took me awhile to reason out the behavior of piping and how to properly utilize it.

If anyone's still confused on the logic, @tkimva showed me this website that explains piping with text, pictures, and pseudo code that was helpful for me: http://hzqtc.github.io/2012/07/linux-ipc-with-pipes.html
