### ISSUE TITLE
Appending to a Script

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#458]
So, it's taken me this long to actually look up the documentation for the script command. It turns out that I didn't have to delete my whole script file and start over every single time I forgot a test case!

Using `script -a <filename>` apparently you can append to the script file, and retain all the prior contents!

I'm just asking to make sure this is okay, because I assume you have to type the `cs100` command again and navigate back to the project directory. I haven't gotten a chance to test it out, but I want to make sure this is okay to do (I hope it is!).

**Comment by hgarc014** [comment]
That's cool. If you mess up you will still have the error i assume. Anyway, what i do is create a script that runs all my test cases. by doing this i don't have to manually type commands.

**Comment by abarb014** [comment]
I feel pretty dumb now, but you saved me some time for future assignments, thank you!
