### ISSUE TITLE
Request for Office Hours from Mike [WED]

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#459]
I was wondering if @mikeizbicki had any free time today to have an office hour. I'm free all day.

**Comment by mikeizbicki** [comment]
Sorry, I'm not going to be at UCR today.

**Comment by jesuscreyes** [comment]
It's OK. Thanks for letting me know! I actually just made some progress on the piping issue I was trying to fix, so I have something to work with now.
