### ISSUE TITLE
Hw2:Help with a bug

### ISSUE THREAD

**Issue by lpeng003** [mikeizbicki/ucr-cs100#460]
I am having trouble fixing this bug which occurs when passing in a command line greater or equal to 2 commands.
If I run the command

```
lpeng003@hammer.cs.ucr.edu$cat info
This is the stuff inside of this file.
lpeng003@hammer.cs.ucr.edu$cat info | tr a-z A-Z
THIS IS THE STUFF INSIDE OF THIS FILE.

```

At this point the program has stopped and no longer responds.
Can anyone provide some insight as to why this is happening?

**Comment by mikeizbicki** [comment]
I'm pretty sure I know what is going on and this is an easy fix.  But first: have you tried walking through your program in gdb and seeing which line it gets stuck on?

**Comment by lpeng003** [comment]
I am currently going through gdb trying to find it.

**Comment by lpeng003** [comment]
So, i think there is a problem with calling wait(), I think I am calling it one extra time, which causes the program to wait for something to stop before continuing.

**Comment by mikeizbicki** [comment]
That's what my guess was.

**Comment by lpeng003** [comment]
Although I decreased the amount of times I call wait() by one, I get the issue of not waiting for the child process to finish first.
Edit: I switched my for loop into a do while loop which has fixed the problem.
