### ISSUE TITLE
HW2 hammer cs100 problem

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#461]
My rshell.cpp works fine in my laptop. However, when I ran it at cs100 hammer, the first run always has 
error like this:

**\* glibc detected **\* bin/rshell: free(): invalid next size (fast): 0x000000000097a080 ***
Segmentation fault
and then exit the program.
but I rerun it, it works fine. So it is hard to debug them, because after first run, it is always working fine.
How can I solve this problem?
Thank you!

**Comment by DustinPham** [comment]
You're probably getting this when you're trying to run a script right? This is most likely because you forgot to exit the last script you made fully.You have to `exit` out of your rshell, `exit` out of cs100, and then `exit` again out of hammer to end the script.

**Comment by jinsongwei** [comment]
Actually, I ran rshell without running script. Simply login to cs100
hammer, git clone , cd rshell, and run. The first try doesn't work.
Is there any other reason?
Thank you.

**Comment by mikeizbicki** [comment]
If you run it from within gdb, it will tell you the exact line the program crashes on.
