### ISSUE TITLE
Request for Office Hours for [Fri]

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#462]
I'm trying to squash some commits using `git rebase`, but I'm running into a lot of issues that I'm not sure how to interpret. I was wondering if one of the instructors would be available to help me figure it out?

I'm free between 9-10 AM and after 3 PM.

**Comment by tkimva** [comment]
I can't make it on Friday. What about on Monday? Is it urgent?

**Comment by jesuscreyes** [comment]
No, it's not urgent. I can wait until Monday. I'm free between 2-4 PM that day.

**Comment by tkimva** [comment]
If it's not urgent, how about meeting normal office hour on Tuesday. I have my class on 2-4pm on Monday.

**Comment by jesuscreyes** [comment]
I understand. That's ok with me.
