### ISSUE TITLE
HW due dates

### ISSUE THREAD

**Issue by tglen002** [mikeizbicki/ucr-cs100#465]
I have been out of town but noticed there have been some changing dates. What homework is due next and when is it due?

**Comment by tkimva** [comment]
What did you notice? I haven't heard anything for changes. 

Did professor mention any due date changes for homework 3 in last class? Anyone know this?
As I know, it's Dec 02 next Tuesday for homework 3 due.

**Comment by hgarc014** [comment]
hw1 was due Tuesday November 11
hw2 was due Thursday November 20
hw3 is due Tuesday Dec 02

there haven't been any changes other than hw1 and hw2

**Comment by tkimva** [comment]
@hgarc014 that's what I know.

**Comment by tglen002** [comment]
Last I had heard hw2 was Nov 18th, but it had been pushed back. I was just checking to see if anything else had changed. Thanks for the update.
