### ISSUE TITLE
HW2 grade question.

### ISSUE THREAD

**Issue by ifuka001** [mikeizbicki/ucr-cs100#467]
I have a question about the hw2 grade. I was deducted some points for missing error check for syscall and I was wondering if this includes missing error check from hw0 as well because if I didn't misunderstand, hw0 should not really affect the grade of hw2. (Though I should of fixed the error checking anyways)

**Comment by mikeizbicki** [comment]
You must have proper error checking on every system call in your repository.  If you had an error in hw0, that error was supposed to be fixed for hw2.

**Comment by ifuka001** [comment]
makes sense. thanks
