### ISSUE TITLE
hw 3 -- General Questions

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#468]
In this new hw, are we creating one separate executable in our shell repo to handle `PATH` , `^C`, `cd`? Or are there none or multiple new executable files we need?

EDIT: 
I see that Taeyoung will run it with `bin/rshell` when grading this. 
As I understand it now, we'd have a separate executable for `cd` (similar to `cp` and `ls`) which we should be able to run from within `bin/rshell`. 
But for `PATH`, if we are not allowed to use execvp, how will you check that we haven't used execvp if we were to modify the old `rschell.cpp`?

**Comment by Dave864** [comment]
I believe we are to replace the use of execvp with the PATH searching method. I would be suprised if the commands that worked when execvp was used didn't work if the PATH searching method was used instead.

**Comment by mikeizbicki** [comment]
1. There should be no executable called `cd`.  `cd` is a built-in bash command, and can only work as a built-in command.  It should be implemented similarly to how you implemented `exit`.
2. With regards to the `PATH` variable, your program should behave EXACTLY as it does now.  The only difference is that you are NOT allowed to use the `execvp` syscall (or any other in the exec family that ends in p).  You must manually search for the executable yourself.  When grading, we will grep your file for execvp, and it shouldn't return any instances outside of the comments.

**Comment by Dave864** [comment]
Mike, I think there might be a typo in the sentence "With regards to the `PATH` variable, your program should behave EXACTLY as it does not". Souldn't the "not" be a "now"?

**Comment by mikeizbicki** [comment]
Yes, fixed.
