### ISSUE TITLE
testing homework to make sure it works

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#47]
when you guys are testing the homework you will not be writing git init right? because when i clone the repo and cd into rshell, when i type git checkout hw1 it only works when i type git init. is this ok? i dont know how else to upload it so i do not have to do this

**Comment by katherinegallaher** [comment]
When i cloned it  I was able to just do 'git checkout hw1' and go into the tag without doing git init. It should work without the git init

**Comment by willccoates** [comment]
do you tag after the merge or before? because ive done both and i still get a message saying there is no path called hw1 known to git

**Comment by katherinegallaher** [comment]
I tagged before the merge, i think. you can try deleting the tag (with 'git tag -d hw1') and retagging it again and the pushing it again. that might work

**Comment by willccoates** [comment]
ok im gonna try to delete the tag, switch to the exec branch, tag it hw1, merge it and the submit, yea?

**Comment by willccoates** [comment]
still doesnt work :/

**Comment by katherinegallaher** [comment]
before you push it onto github can you do git checkout hw1 ?

**Comment by willccoates** [comment]
yes i can and i can do it without git init as well, idk why its not working when i download it

**Comment by bmars003** [comment]
http://git-scm.com/book/en/Git-Basics-Tagging

**Comment by bmars003** [comment]
Looking at your repo there are couple things wrong off the bat. First you have an executable uploaded, more than one main.cpp  and I am not sure what rshell is that is in your repository. Also there is not a tag, are you sure you made a commit after you merged and tagged?

**Comment by willccoates** [comment]
well i was not doing the git push origin hw1, i just did that right now and it worked, il get rid of the extras, what exactly should i delete?

**Comment by bmars003** [comment]
http://stackoverflow.com/questions/19584255/what-does-a-grey-icon-in-remote-github-mean looks like you also have one of these as well.

**Comment by bmars003** [comment]
Look at the specifications as to what needs to be submitted and what not to include.

**Comment by willccoates** [comment]
is a bin ok? because i was reading in other issues and mike said it was fine for this assignment

**Comment by bmars003** [comment]
That is fine

**Comment by bmars003** [comment]
And don't forget to make the changes in the hw tag, that is what I am grading.

**Comment by willccoates** [comment]
ok sounds good
