### ISSUE TITLE
Broken link in Hw4 README.md

### ISSUE THREAD

**Issue by lpeng003** [mikeizbicki/ucr-cs100#470]
The link "international obfuscated C code contest " does not work.

**Comment by 2c2c** [comment]
fix the link -> collect the points! (the error is obvious if you look at the link)

**Comment by lpeng003** [comment]
I see what is wrong, but I do not have the knowledge to repair it.
While mousing over the link, the address is"https://github.com/mikeizbicki/ucr-cs100/blob/cs100-2014fall/assignments/hw/hw4-contributing/ioccc.org" which is clearly wrong.
But looking at the file itself, I am assuming the (ioccc.org) is the supposed link.
