### ISSUE TITLE
Spoofing commit dates vulnerability

### ISSUE THREAD

**Issue by 2c2c** [mikeizbicki/ucr-cs100#478]
The timestamps on git commits are manually editable-- and Github has full faith in whatever information you upload from git to a Github repository.

`git filter-branch` allows you to parse and edit specific commits.

```
git filter-branch --env-filter \
    'if [ $GIT_COMMIT = EXACTCOMMITIDHERE ]
     then
         export GIT_AUTHOR_DATE="SPOOFED_AUTH_DATE"
         export GIT_COMMITTER_DATE="SPOOFED_COMMIT_DATE"
     fi'
```

This says: search through the repository for a specific hash, when you find it change its author and commit date.

You can create a tag that matches your latest commit date by prepending your tag creation with an override of the commit date. 

```
GIT_COMMITTER_DATE="$(git show --format=%aD | head -1)" git tag -a TAGNAMEHERE
-m "totally turned this in on time"
```

The first line of `git show` output is the timestamp we want to copy, hence we pipe it to head. We've seen that a few times in class... 

After applying edits to the dates of any commits you want to change and adding a tag you can push your changes and everything will appear legitimate on Github-- There's no way to tell the difference between doctored commit dates and normal ones (other than that you may be terrible at making up dates).

Anyways, all of this amounts to there basically being no actual due date unless a grader pulls all the repositories of each student at the time the assignment is due. I can attest to this not being done because I tested this through fixing a single perror mistake five days after HW2 was due. If you feel like living on the edge you can try this for yourself on the next hw. Have fun!

**Comment by mikeizbicki** [comment]
Good writeup!  Anyone who feels comfortable enough with git to edit their commit history like this is free to do so.  The only time we've actually checked the timestamps on your submission is on the extra credit for submitting it early in the last assignment.

This is a known vulnerability, and it really impact the integrity of the grade system.  So I'm awarding +25 pts extra credit.
