### ISSUE TITLE
Hw#3 Examples from Lecture

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#480]
I noticed that the `func.cpp`, `sort.cpp`, `signals.cpp`, `map.cpp` and `env.cpp` from lecture are not in the lecture notes. I was wondering if those could be pushed onto the repository.

**Comment by mikeizbicki** [comment]
Sorry, they should be uploaded now.

**Comment by jesuscreyes** [comment]
Thanks!
