### ISSUE TITLE
Hw#3 Clarification on Homework 3 Submission

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#482]
From #477, it says that we don't have to have everything working for our hw3 submission on Tuesday. Is that for everyone, or just people that are planning to get regrades?

So hw#3 is still due on Tuesday by 11:59 PM for people who don't want to get regrades?

**Comment by 2c2c** [comment]
Its still due but wont have an effect on you getting the full regrade points

**Comment by mikeizbicki** [comment]
You must have everything about hw3 working by Tuesday no matter what.  You do not have to have the stuff you missed from hw0-2 working until Thursday.
