### ISSUE TITLE
HW3 Question

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#484]
When I use kill(child_pid, SIGKILL) to kill child process, does it kill parent as well? I catch the child process ID, but it didn't stop. It went into the signal_handle function to kill child_pid again which process child_pid changed to parent ID.

**Comment by mikeizbicki** [comment]
> When I use kill(child_pid, SIGKILL) to kill child process, does it kill parent as well?

The man page or a simple experiment will answer this question.

> I catch the child process ID, but it didn't stop. It went into the signal_handle function to kill child_pid again which process child_pid changed to parent ID. 

I don't understand what you mean by "catch the child process id".  Also, the pid of a process should never change, so I don't understand what you mean by that either.  You will have to provide much more detail in order to get a better answer.

**Comment by jinsongwei** [comment]
I found a way to kill child process not parent. But the confusion still remains. 
I set a global variable int child_pid = 1. inside child process I use child_pid = getpid() and send ^C signal in child process. it goes  into signal_handler which has only kill(child_pid, SIGKILL) function. My confusion is that program call signal_handler twice, first is child_pid = 1 (which kill is not permitted), second time, the child_pid value properly changes to child process id and killed child process. Why does it call twice? Is there a way to stop calling handle_signal first time? 
Thank you !

**Comment by mikeizbicki** [comment]
> Why does it call twice?

If I understand correctly, the signal is being sent once to the child process and once to the parent process.  That is what is supposed to happen.  The child and the parent must behave differently when they get the signals.  So inside your signal handler, you should do something different depending on whether you're in the child or parent process.

**Comment by jinsongwei** [comment]
Thank you!
