### ISSUE TITLE
Hw#3 Clarification for handling ^C

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#485]
The explanation for handling `^C` is that it should interrupt the current foreground job, but it's still unclear to me how I should accomplish this.

My understanding of this feature so far is that at any point my program needs to know when `^C` is entered, and instead of exiting my program, it goes to a specific function that I point to using the `signal()` function. It's THIS function that interrupts the current foreground job.
1. My confusion comes from not knowing what that proposed function should do. Could someone explain the functionality a little more in depth? What does it mean to interrupt the current foreground job?
2. What are some examples of how this feature should work if implemented properly?

Thanks!

**Comment by 2c2c** [comment]
well. when you're using bash and you press ^C all it does is instead of killing the bash process it reprints the  `user@group $` line and behaves as normal. personally I've had issues getting it to output exactly like this, but it's likely they're just looking for your shell not closing while still closing child processes launched from your shell. you could make the function do literally nothing and would work pretty well at not killing your shell.

**Comment by mikeizbicki** [comment]
If you are running rshell, and inside rshell you execute cat, and then press `^C`: it should end the cat process, but rshell should keep running.  Currently, it well end the cat process _and_ your shell.  `^C` should _never_ end your shell.

If no child process is running in rshell when `^C` is pressed, there is no need to print a new prompt like bash does.  This can't be done using iostream.  bash uses a fancier io library called readline to make this happen.

**Comment by gbrlrz017** [comment]
@mikeizbicki in regards to your second point above, 
1. when `^C` is entered, I am able to continue typing on that same prompt. SoI have something like the following in my command prompt: 

`/class/classes/gruiz007/rshell $ ^C` or 
`/class/classes/gruiz007/rshell $ ^C^C^C^C` or
`/class/classes/gruiz007/rshell $ ^C kjkdfjljljal;`

It doesn't print out a new prompt unless I press enter. Based on what you said, this is okay, right?
1. When I have:

`/class/classes/gruiz007/rshell $ ^C kjkdfjljljal;`

My shell interprets `kjkdfjljljal;` as an attempted command so `execv` fails. Is this okay as long as I document it in my README?

**Comment by mikeizbicki** [comment]
@gbrlrz017 Yes, this is the best you can do using the `iostream` library.

**Comment by gbrlrz017** [comment]
Thanks!
