### ISSUE TITLE
Question on the cd command.

### ISSUE THREAD

**Issue by ifuka001** [mikeizbicki/ucr-cs100#487]
I understand how the chdir() syscall works, but I was wondering how I would be able to go to home directory, because in command shell when user inputs just "cd" it will go to their home directory. 

What I had in mind was, using getcwd() to get the current working directory and then comparing each string separated by "/" and if it matches the login name, it means that's where the home directory is so cut the rest of paths off the directory and using chdir() to change the path.
i.e. 
`/home/ifuka001/rshell/src`

will be the current working directory and then search through until separated string matches the login name which is "ifuka001", and then cut off the rest so it'll become

`/home/ifuka001`

I don't know if this is efficient because if getlogin() fails, then with this method cd wont work.

**Comment by mikeizbicki** [comment]
You get the home directory by checking the `HOME` environment variable.  Your method will fail in many circumstances.

I've updated the assigment specs to make it clear, however, that you do NOT have to implement this aspect of the `cd` command.

**Comment by ifuka001** [comment]
Figured that would not work. I didn't think about the `HOME` variable. That would of made things much easier haha. Thanks

edit:
Also we do not have to worry about `cd ~` correct?
