### ISSUE TITLE
hw3-displaing current working directory (part 3)

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#488]
Here is my regular terminal prompt:
    `gruiz007@cs100:~/rshell (hw3) $` (with different colors on specific words)

And here is what my rshell prompt displays when executed:
   `/class/classes/gruiz007/rshell $` (all in one color)
1. Do I need to have the `username@hostname: ~/...` or is the way I have it now sufficient?
2. `hw3` is the branch I am currently working on. Does my rshell prompt need to acknowledge/display my current branch?
3. Is it okay if my prompt is all in one color?

Seems trivial, but I've been marked down for trivial before.

**Comment by mikeizbicki** [comment]
1. Displaying `username@hostname` was the extra credit for assignment 1, and is not required.  You only need to display the working directory.
2. You do not need to show the ~~current working directory~~ branch
3.  You do not need to use other colors.

**Comment by gbrlrz017** [comment]
1. You mean current branch, right? 

Thanks!

**Comment by mikeizbicki** [comment]
Woops!  Fixed.
