### ISSUE TITLE
hw3-cd: optional flags, multiple arguments

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#489]
From running `info cd` in my terminal I see that running this command requires the form:
    `cd [-L|-P] [dir]`
1. Do we need to allow for the options `-P`  `-L` to be passed?
2. Are there any other options or arguments we should account for? For example, `cd dir1 dir2` simply switches to `dir1` (as long as it's a directory) and `dir2` is ignored regardless of if it's a valid directory or not. 

I currently output an error message if there is anything other than `cd dir`.

**Comment by mikeizbicki** [comment]
1.  You do not need to handle any flags.
2.  I don't care how you behave in the case of multiple parameters to `cd`, but this is something that should be documented in your README.
