### ISSUE TITLE
Github problems/issues

### ISSUE THREAD

**Issue by hgarc014** [mikeizbicki/ucr-cs100#491]
@mikeizbicki @tkimva 
Would it be possible to have people in lab tomorrow respond to this post or create issues on my repository (https://github.com/hgarc014/git-game/issues) about problems or things they did not understand about github. This would help me and my contributors add these issues into our hw4 project, if we haven't already thought about them.

**Comment by 2c2c** [comment]
git, github, or both? just curious what your focus is

**Comment by hgarc014** [comment]
Both
