### ISSUE TITLE
signal propagation

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#493]
so im working on the signal handling for hw3 and ive found a pretty major issue. when i run rshell within rshell within rshell(run rshell twice inside of rshell) and hit Ctrl+C, the signal is sent to all of the children of the first rshell. as a result, all of the rshells except the first one are closed. any ideas on how to force the signal to only be sent the the latest child process?

**Comment by mikeizbicki** [comment]
I like the test case you thought up.  But it bothers me that you're asking other people to spend time helping you, when you haven't even put in the effort to capitalize or punctuate your sentences correctly.  This sends the message that you probably haven't put in the time to think about how to solve your question.

**Comment by npsark** [comment]
Sorry about that. By no means did I intend any disrespect by the lack of effort in my grammar. I just, apparently wrongly, saw a general theme of informality in this forum. Furthermore, my lack of grammatical effort is not at all correlated to the amount of time I have put into this topic. I only resort to asking questions here when my research has proven fruitless. I don't want anyone to do my work for me, I just figured someone else has probably run into this issue as well and might want to offer some tips.
Sorry again, no offense intended.

**Comment by aorti017** [comment]
If I am not mistaken, the `^C` signal should never end your shell. So, I would assume that when running multiple instances of rshell within itself the `^C` signal should not close any of the shells.
