### ISSUE TITLE
hw3 access() errorcheck

### ISSUE THREAD

**Issue by attecodes** [mikeizbicki/ucr-cs100#494]
Will we get points taken off if we use the access system call to check and see wether the path exists but do not error check?

**Comment by mikeizbicki** [comment]
It is almost always incorrect to check whether a path exists or not, and I cannot think of a good reason to do that in this assignment.  Performing this check will lead to many subtle bugs.  You should simply try changing directories to that path/executing the file at that path/etc and perform error checking on that syscall.
