### ISSUE TITLE
Hw3 question: implement g++ in rshell

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#497]
I am wondering, if we need to implement `g++` as well in hw3. the command `g++` does work well in calling `execvp()` function, but fail to call `execv()` function. I found `g++` is a linker, so do we need to handle linker as well in `execv()` call?

**Comment by hgarc014** [comment]
I think the answer is yes.
I tested my rshell and `g++` still works.

you can use the `which` command to find out where the command is located.
Ex.
`which g++`

**Comment by jinsongwei** [comment]
thank you!
