### ISSUE TITLE
Running rshell within rshell etc.

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#498]
When I run `rshell` within itself, `getenv("PATH")` only gets one path when it should get just as many paths as the original `rshell`. 

For instance, my first call to `rshell` gives the paths: 
`/usr/csshare/cs100/bin:/opt/rh/devtoolset-2/root/usr/bin:/class/classes/gruiz007/bin:/usr/csshare/bin:/usr/csshare/sbin:/usr/bin/:/bin: ........ (etc)`

But then running `rshell` from within itself gives the following path, only:
`/usr/csshare/cs100/bin`

I originally thought this had something to do with  scope of where I called `getenv`. I tried initializing my array and storing the paths through `getenv` `globally`, within `main` (before my while loop), within the while loop, and finally inside of the `if(pid == 0){...} child` process. 

However, it is my impression that the scope of `getenv` doesn't matter since after `fork` the child and parent processes start from the beginning of the entire program, so `getenv` gets called in each process again, regardless. 

So I know more or less what's going on, but I don't see why this is going on. Why would I have all my paths in the first call to `rshell` and only one when calling `rshell` from within itself?

**Comment by mikeizbicki** [comment]
I like the reasoning process you went through, and everything you said is correct.

A child created with `fork` should inherit all of the environment variables that the parent had.  My hunch is that somewhere you are resetting the environment variables on accident.  The way I would debug this is I would open the program in gdb, and walk through the program, printing the value of `PATH` at each step.  This will narrow down the exact line that is changing the `PATH`.

**Comment by nickzoo** [comment]
I had the same problem, for me it was because I used strtok, I guess it reused the data that strtok already operated on. This problem was fixed when I changed to sstream.

**Comment by lpeng003** [comment]
From what I understand, because `getenv` returns a pointer to the `PATH` string, and im assuming you stored the returned pointer into some `char *`, Using `strtok` on that `char*` will edit the `PATH` string. So, at the end of using `strtok` to parse the `PATH`, it has now become `NULL`.
