### ISSUE TITLE
hw1 not compiling

### ISSUE THREAD

**Issue by kryne001** [mikeizbicki/ucr-cs100#50]
I just saw my grade, which was given because my program did not compile, but I did all five steps shown in the homework, 

git clone (myrepo)
cd rshell
git checkout hw1
make
bin/rshell

I've done it at least four times when I cloned four different repos and they worked each time without me doing anything other than those fives commands.

**Comment by bmars003** [comment]
When I was grading it I got this 

marshb@well $ make 
g++ -Wall -Werror -ansi -pedantic src/hw1.cpp -o bin/rshell
cc1plus: warnings being treated as errors
src/hw1.cpp: In function \u2018int main()\u2019:
src/hw1.cpp:22: warning: comparison between signed and unsigned integer expressions
src/hw1.cpp:35: warning: comparison between signed and unsigned integer expressions
src/hw1.cpp:73: error: no matching function for call to \u2018wait::wait(int)\u2019
/usr/include/bits/waitstatus.h:68: note: candidates are: wait::wait()
/usr/include/bits/waitstatus.h:68: note:                 wait::wait(const wait&)
make: **\* [all] Error 1

**Comment by kryne001** [comment]
![screen shot 2014-08-10 at 12 30 47 pm](https://cloud.githubusercontent.com/assets/8340349/3870250/19a70dca-20c5-11e4-8052-fa973a79fc4b.png)

that's what i get when it runs

**Comment by bmars003** [comment]
Have you tested it on the school's server `well`? I am not quite sure what that picture is showing, but from the looks of it that you were testing it solely on a Mac, which is a different favor of `UNIX` than what what the class is using, which is what is on `well`.

**Comment by kryne001** [comment]
Yeah that's probably the problem, I'm going to Chung today so I'll try it again and see.

**Comment by bmars003** [comment]
You know you can ssh into the schools server anytime remotely by typing `ssh -X username@well.cs.ucr.edu`. Replace `username` with your cs account's username.

**Comment by kryne001** [comment]
Oh wow, okay so I just checked on the school's server and it didn't compile, is it too late to rectify this?

**Comment by rgosh001** [comment]
I just got the same results here due to the difference in the well server. I recognize this is late, but I was wondering the same questions as above.

**Comment by bmars003** [comment]
You will need to ask the professor.
