### ISSUE TITLE
Extra Credit Question: Hackathon attendance?

### ISSUE THREAD

**Issue by ChemicalWonders** [mikeizbicki/ucr-cs100#501]
Since this class is about becoming a hacker, and someone who creates something, would it be okay to count participation to a hackathon for a tiny bit of extra credit?

For example, if you have attended a hackathon AND demonstrated that you built something during that hackathon, you can get x points of extra credit. 

I'm just suggesting this, and I think that this would make the class reach out a bit more to the hacker community for this and future quarters.

**Comment by mikeizbicki** [comment]
Which hackathon and what did you build?

**Comment by ChemicalWonders** [comment]
I've attended several, however, the most recent one I've attended was HackSC, and I built an iOS app that allows you to track how many steps you've walked and link that with your Facebook.

You can check out the github repo under [ChemicalWonders/WalkToTheTop](https://github.com/chemicalwonders/walktothetop)

**Comment by mikeizbicki** [comment]
I've given you 20 pts.
