### ISSUE TITLE
Hw4 question

### ISSUE THREAD

**Issue by ifuka001** [mikeizbicki/ucr-cs100#503]
On the Hw4 assignment page it says Rough Draft is due by Dec 4th midnight. Is this still true or we just need to turn in the final draft on the 13th, while we come to office hour or something to show you the progress as you said in lecture today.

**Comment by mikeizbicki** [comment]
I'm not going to explicitly grade your rough draft.  But I think successful students will have something to show be by that time so I can say whether you're on the right track or not.  Students who do not have anything to show be by that time will probably not do well on the assignment.
