### ISSUE TITLE
having an issue with not being able to squash commits

### ISSUE THREAD

**Issue by ChemicalWonders** [mikeizbicki/ucr-cs100#507]
I was playing around with my github repository, and apparently, I am now 30 commits ahead of the main repository. 

I was wonder how I could fix this, as there's only one commit that's actually changing a single line in the actual repository. 
Is there something that I have to do in order to change everything, because it will say that I posted 30 commits when I try to initate a pull request. I don't want to refork the repository, because my grades on there.

**Comment by hgarc014** [comment]
so, what I would do.
1. checkout the commit before you have a bunch of commits (this will likely remove your changes)
2. force this commit to your main local branch
3. force update your forked repository
4. update your forked repository (if you are behind)
5. make changes
6. push and issue pull request.

that's a rough outline, but if you need more let me know
