### ISSUE TITLE
HW4 Topic Request

### ISSUE THREAD

**Issue by ziyaemanet** [mikeizbicki/ucr-cs100#511]
Hi Mike,

I had two ideas for a HW4 tutorial I hope you could provide some feedback on before I devote my focus to one:
1. Basic game made with SDL library using sprites
   - simple game about a duck flying in not so friendly skies
   - control duck with arrow keys
   - each round would increase hazard
   - add upgrades with rewards
   - perhaps future students could add to it
2. Security tutorial on gaining key to access point secured with WEP
   - Tools used: why they are used and what they do
   - Information regarding wireless networks necessary to understand interactions which take place

I will add the topic to the title once one is chosen.

Thanks
- Ziya Emanet

**Comment by mikeizbicki** [comment]
I think the game is probably too ambitious to do in just a single week, but if you want to gamble and try you're welcome to.

There's already lots of tutorials on how to break WEP encryption.  How would yours be different?  I think this is probably the more realistic option, but you need to have a very good answer to this question.
