### ISSUE TITLE
System Calls: system

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#515]
So we technically could have gamed the system and used the system call `system` in our assignments all this time, since we were never told we couldn't use it. Our assignments could have been only a few lines long if we really wanted to. I believe there is  at least one other syscall out there, and I'm sure a few other ways, to do this as well.

For those who don't know, this syscall has the form `int system(const char *command)` so you could have simply converted your user input to a `const char *`, passed it into to `system`, used error checking of course, and voila! 

Example: `system( "cat < src/ls.cpp | tr a-z A-Z | tee newOutputFile1 | tr a-z A-Z > newOutputFile2 &")`

 You could have been done with your assignment in 10 lines, and maybe just padded your program with some gibberish code in order to not raise any flags (although I am certain whatever cheating detector this code is run through would find this a bit curious). 

@mikeizbicki, is this syscall fair game for our homework? I am guessing it's not, and that this is a potential vulnerability.

**Comment by Liniarc** [comment]
I asked an equivalent question for the first assignment. He said we weren't allowed to do that. I'm not sure how they would have checked though, especially if you obfuscated your code using macros and such.

**Comment by gbrlrz017** [comment]
I added it to `checksyscalls.sh`, and I think that might do the trick. With macros, what would be a way one could get away with using it?

**Comment by hgarc014** [comment]
One could create a macro that ran the system call for you.  The check sys call doesn't find macro defined error checking, which would mean a macro that ran this system call would be in a similar position and not be found by the script.

**Comment by Liniarc** [comment]
I wrote this test program as an example.
This is relatively simple and yet pretty much unreadable. I'm sure you could be more subtle than this too.

<pre><code>
#define define(x) x ## tem
#define while ;
#define if (
#define else )
#define false {
#define goto }
#include &lt;stdlib.h>
int main if else false
const char * define(s) = "echo hello | tr a-z A-Z ; echo goodbye" while
define(sys) if stem else while return 0 while goto
</code></pre>

**Comment by gbrlrz017** [comment]
Ah, yes that makes sense. So pretty much, if one wanted to, it could be done through macros. 

A somewhat tedious way for a grader to make sure that isn't the case might be to have a script check if macros are defined, and have the script say where they are used and try to decipher it by hand that way. That wouldn't be too difficult depending on the macro implementation, but whether or not going to that length is worth it is another issue. (I'm sure there is a simpler way, though). 

And maybe a lack of actual code usage for a recommended syscall would be suspicious in itself.
