### ISSUE TITLE
Hw4 Rough Draft/Check

### ISSUE THREAD

**Issue by asand017** [mikeizbicki/ucr-cs100#517]
https://github.com/asand017/hw4-cs100

I have a good portion of the _sed_ command portion of my project typed up; however, I plan to replace the man page descriptions of the option descriptions and any other relevant information with a more readable form of the same information. I'm also curious if you think I should continue on with the current methodology I've began with for the remaining commands I have listed on my hw4 page or should I focus on _sed_ and do an extensive, thorough write-up of examples when _sed_ may be helpful. Alternatively I've considered focusing on only 2 or 3 commands I feel incoming students may be most inclined to use. Thank you.

**Comment by mikeizbicki** [comment]
It's much better to go deep into something than to go shallow into many things; so just focus on sed.

Also, you should not be writing a reference for sed.  If someone needs to lookup sed's flags, for example, they are going to look at the man page, not what you wrote.  You should be writing a tutorial, which means there will be lots of detailed examples about how to use the most important features.
