### ISSUE TITLE
macros

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#52]
when i define my macros like
# define a 1
# define l 2
# define R 3

it wants me to put semicolons at the end but i know you are not supposed to
what do i do to fix this?

**Comment by willccoates** [comment]
never mind, i believe i fixed it

**Comment by mikeizbicki** [comment]
Note that the values you wrote for `a`, `l`, and `R` are not valid.  Right now, how can you distinguish between `a&l` vs `R`?

**Comment by willccoates** [comment]
What would be correct values?

**Comment by mikeizbicki** [comment]
They must be powers of 2.
