### ISSUE TITLE
calcgrade.sh not showing all grades

### ISSUE THREAD

**Issue by aorti017** [mikeizbicki/ucr-cs100#527]
When I run `./scripts/calcgrade.sh aorti017` the only grade shown is for lab 0, the rest are `---`. When inspecting the grades on my ucr-cs100 repository I noticed that the cs100-2014fall branch has a grade for lab 0, but for nothing else. While the grades branch contains all the grades that it should. Could it be that the script is not checking my grades branch, but instead is checking my cs100-2014fall branch?

**Comment by jesuscreyes** [comment]
I just checked my grades, and I also only have a grade for lab0.

**Comment by hgarc014** [comment]
This happened to me when i first checked my grades, did you try running the script another time?

**Comment by aorti017** [comment]
I have ran the script multiple times, each time producing the same result.

**Comment by hgarc014** [comment]
Interesting ill try it right now

**Comment by hgarc014** [comment]
Well, nothing is wrong when I run the script... If i run it for the first time it will be nothing except lab0, but If I run it again, it grabs all the correct information. So, i'm not sure what's wrong. I assume you guys are using the latest script.

**Comment by anmolsingh95** [comment]
Did you try running the script from the scripts folder. For some reason, some of the scripts do not work if you are not currently in the scripts folder.

**Comment by aorti017** [comment]
Running it from within the scripts folder solved the issue. Thank you.

**Comment by hgarc014** [comment]
that's interesting, because I was running it within the main folder and it worked fine.

**Comment by anmolsingh95** [comment]
maybe calcgrade use some form of a cache mechanism. For the first time, you have to run it from the scripts folder and then you can run it from anywhere. But take for example checksyscalls, which does not run from the main folder. That is an extra credit opportunity right there.

**Comment by hgarc014** [comment]
maybe it does use some sort of cache mechanism... checksyscalls always works running from the main folder for me, haha, but it doesn't work if i run it in the scripts folder.
Well, it does work in the scripts folder if i edit the path, because the script takes you to the main folder, thus assuming your path from there...

**Comment by anmolsingh95** [comment]
really, that strange. But whatever it is, a problem does exist. checksyscalls should be able to run from anywhere.

**Comment by anmolsingh95** [comment]
Well. it seems that the above issue as been fixed and now all the scripts should work from anywhere on the computer. I will initiate a pull request shortly.

**Comment by mikeizbicki** [comment]
The fix by @hundal78 fixes a related problem, but not this problem.

When all of the scripts download grades from github, they stick the downloaded repos in the `gradetmp` folder.  I'm pretty sure the problem is that the right branch is not getting checked out on first download for some reason.  But then when you run the script again, the right branch does get checked out.

**Comment by anmolsingh95** [comment]
Hey @mikeizbicki, the problem with the calcgrade first run bug fix was that the if statement 
`git show-ref --verify --quiet "refs/heads/$branch"` evaluated to false. So git pull on grades branch was never done on the first run, hence causing the bug. I have inititated a pull request for the fix.
Could you please explain what this expression does or means?
