### ISSUE TITLE
Is it necessary to use markdown for hw4?

### ISSUE THREAD

**Issue by nickzoo** [mikeizbicki/ucr-cs100#528]
According to the hw4 assignment page, our submission should include "README.md," does this mean that we are required to use markdown?

P.S. Does anyone know what will happen if you run "rm -rf /"? Will it actually delete all the files on your computer? I don't want to try.

**Comment by mikeizbicki** [comment]
If you have a good reason to not use markdown (for example, you're using latex), that's fine.  But you must run it by me first to see if I think it's a good idea.

`rm -rf /` will not delete all the files on your computer with GNU rm.  It has a special check just for this case; other variants of rm differ.
