### ISSUE TITLE
homework clarification

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#53]
so in assignment 2 we have to take in the commands, for example ls -a, do we need to access each individual file or directory in the directory that we are in and print out each individually? and for -l we need to go in get all neccesary information about the files and print that out correct?

**Comment by willccoates** [comment]
i looked at the man page for readdir and im kind of comfused about what the parameters are, could anyone explain that?

**Comment by katherinegallaher** [comment]
for ls -a it just has to work exactly as it does in terminal

For readdir just look at the code that Mike gave us for this assignment 
https://github.com/mikeizbicki/ucr-cs100/blob/master/assignments/hw/hw2-ls/ls.cpp

**Comment by willccoates** [comment]
I wish I would have seen that earlier lol, thank you :)
