### ISSUE TITLE
HW4 Check: GDB Tutorial

### ISSUE THREAD

**Issue by ManjunathChet** [mikeizbicki/ucr-cs100#532]
https://github.com/ManjunathChet/GDB-Tutorial

So far, I have come up with one example to introduce the GDB commands. I'm currently working on two more that will explain how to find segfaults and why GDB is more efficient that print statements.

**Comment by mikeizbicki** [comment]
1. Take out the first section.  The authors will be recorded in the git history; the license will be creative commons for text and BSD3 for code once you submit it to this repo.
2. You can be less formal; you don't need to say "the user" when you actually mean "you"
3. Don't have a list of the commands you're going to teach at the beginning.  Just introduce them as they come up in the tutorial.  In general, your whole introduction could be a lot more concise.
4. When you refer to ex1.cpp, make this a link we can click on
5. The `strcpy` function is short enough you should put it in the readme
6. Your main function is broken.  What if `strlen(argv[1]) > strlen(argv[2])`?
7. This is a good example, but you need to flesh things out a bit more.  In particular, you should have ALL the text of a complete gdb debugging session in there.  Something like:

```
$ g++ ex1.cpp -g
$ gdb ./a.out
LOT OF TEXT HERE
% run
PROGRAM OUTPUT
% b 12
% run
stopped at break point XXX
% list
source code here
...
```

You take a file like this, then you break it up with your comments.  The idea is that the reader can walk through step by step what you're doing, typing in exactly the commands you typed and then make sure their output matches yours.

Let me know if you have any questions.  This has a lot of potential.
