### ISSUE TITLE
Hw4 first rough draft 

### ISSUE THREAD

**Issue by jinsongwei** [mikeizbicki/ucr-cs100#533]
Professor, I just finished hw4 contribution, the topic about permission of files. Please check if there is anything I should improve or add more information on the topic. 
This is my link below. 
https://github.com/jinsongwei/hw4
Thank you!

**Comment by mikeizbicki** [comment]
1. Overall a good start.
2. There are some minor formatting/typo issues.  For example, the line:

```
*The file "main.cpp" is owned by user "jinsongwei" which is my usrname.
```

should read:

```
* The file `main.cpp` is owned by user `jinsongwei` which is my username.
```
1. I like that you included screenshots of the shell.  But you have screenshots from different shells.  Make them all from the same shell.
2. Those diagrams are nice, but you can't use them unless you can prove to me that they are compatible with a BSD3 license.  This should be left as a comment in the markdown source.
3. There's no need to talk about the `open` syscall.  Stay focused on just the file permissions.
4. You'll need to explain more about the `chmod` command.
5. Talk about the "sticky bit"
6. Take out the Terminology section, and just incorporate the definitions where you cover that material.
7. You should get a native english speaker to proof read before submitting.
