### ISSUE TITLE
Quiz this week?

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#534]
Hi everyone, I had to miss lecture last Thursday and I heard talk in lab today about an upcoming quiz. Just wondering if I missed an announcement. If someone can let me know, that'd be greatly appreciated.
Thanks

**Comment by jesuscreyes** [comment]
Yup, @mikeizbicki told us there would be a quiz tomorrow [Tuesday]. I believe it's supposed to be comprehensive, but he said it shouldn't be too difficult.

**Comment by npsark** [comment]
Ok, thanks a lot!
