### ISSUE TITLE
HW4 Revision

### ISSUE THREAD

**Issue by KenleyArai** [mikeizbicki/ucr-cs100#536]
I mentioned in [issue](https://github.com/mikeizbicki/ucr-cs100/issues/344) that I would be writing a tutorial about test driven development using [Google C++ test framework](https://code.google.com/p/googletest/). 

While writing HW4 I've noticed that I have been writing mostly about how to install, and use the Google framework. I feel like this distracts away from the points I am trying to make about TDD. More or less my HW4 has turned into a how to use google framework.

The contribution I had in mind for this HW was for future students to be:
1. Introduced to [software process development](http://en.wikipedia.org/wiki/Software_development_process)
2. Able to write higher quality code 
3. Create a structured way to develop their own code bases 

I am a transfer student and this is my first quater at UCR, so I have no idea if these topics are already taught. 

Would it be okay to change languages or change libraries so that I can focus more on the process of developing rather than a how to install google test framework?

**Comment by mikeizbicki** [comment]
Yes, feel free to change.  If all you can talk about with google test framework is how to install it, that would not be a good topic.

The danger of talking about software process development in general is that you will be too generic.  You don't really have the experience to write about this well.  I think you should still focus on TDD and how to use a particular testing framework.  If whatever framework you want isn't installed on hammer already, we can get it installed for you.
