### ISSUE TITLE
Make all scripts portable

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#540]
Hey @mikeizbicki, I have an idea to make all the scripts portable, so that they all can be single files without the need of the repository folder. 
Pretty much all the info we need for the scripts is in the students folder, and we can run git clone on the folder in the config file. This way the only two files we would need are the script file and the config file.
To solve this we can run git clone on the config file.
So the script would run on its own.
Should I go on and implement this?

**Comment by mikeizbicki** [comment]
It's a good idea, and that's something I want to do.  Here are some things to consider:
1. Git clone is really slow.  It would take ~5 minutes or so for each script to run.  If it had to clone the whole repo each time.
2. The `config.sh` script has a bunch of class-specific configuration options inside of it.  I want the ability to be able to run different classes besides just cs100 using these scripts.  So you can't just hard code anything.
3. I think the best solution is to use an environment variable to store the directory containing the class info.  Then we can look up the environment variable to get the right files whenever we need it.  All the scripts can then be put in the PATH to work everywhere.

I'd definitely like pull requests that are compatible with all the above.

**Comment by anmolsingh95** [comment]
1) I would be cloning only the config file and the folder people in the entire process. These are mere KBs and wont be any problem unless you live in a really bad place. Moreoever, they would be stored in a temp folder, so future runtimes would be as fast as they can be.

2) I would find a way so that it is not class specific, but specific to the main branch, which will be your current class.

3) This would still require you to have the repo on your hard drive. And if it is on your hard drive, why not just run it like we do now?

**Comment by mikeizbicki** [comment]
1. I don't know of a way to clone individual files.  Even if there is, it's
   not just the file you're downloading; it's the entire history of commits to
   that file.  Many of those commits will affect other files as well and so be
   rather large.  git clone is a lot more complex than just downloading the
   latest version of a file.
2. ok
3. You have to have something installed locally no matter what (otherwise
   what are you running?), so I don't get what you're saying.

**Comment by anmolsingh95** [comment]
1) We cannot clone single files, but we can still download them using wget.
http://stackoverflow.com/questions/4604663/github-download-single-files

3) I meant that the script would run even if you have the script file alone. For e,g calcgrade.sh should be all a student needs to calculate his grade.

But the PATH alternative is still fine.
