### ISSUE TITLE
Please don't delete your git forked repository

### ISSUE THREAD

**Issue by tkimva** [mikeizbicki/ucr-cs100#548]
Please be careful. Your repository `grades` branch has a grade, so if you delete your repository and re-fork to reset, you will lose every grade record.

**Comment by asand017** [comment]
Uh I forgot about this warning and reset my forked repo so I could resubmit my hw4. How can I fix my grade record?

**Comment by mikeizbicki** [comment]
Give us write permission back to your repository and I can upload your
grades from my locally stored version.
