### ISSUE TITLE
readdir error with recursion

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#55]
I'm getting a readdir error ONLY with the -R flag, and only when it's recursing into a directory/folder. The perror that I'm getting is "No such file or directory". I suspect it's because it's trying to read it some files that start with . that are there, but I'm pretty sure I already check for them. Another thing is it still outputs the correct things, just with a whole bunch of readdir errors. Example below.

correct output for recursion:
./tests:
exec.script

my output:
./tests:
Error with readdir: No such file or directory
Error with readdir: No such file or directory
Error with readdir: No such file or directory
exec.script

Any help would be greatly appreciated!

**Comment by mikeizbicki** [comment]
Have you actually printed the value you are passing to `readdir`?  If this is still the same problem as you were  having before, then the problem is that the value you are passing in is not correct.

**Comment by bmars003** [comment]
Do you know what files are causing this issue?

**Comment by DanTheTingler** [comment]
I'm not too sure, although I'd imagine it's some random hidden . file. My opendir doesn't return a perror, and I pass in the result of opendir into my readdir

**Comment by mikeizbicki** [comment]
I know I'm sounding like a broken record, but have you actually printed the file's name to the screen?  `readdir` is telling you that whatever you are passing it does not exist.  So print it to the screen and check if it exists.  In particular, paste here the output of your `ls -R` and the built in `ls -R` side-by-side.  Then look carefully at the name of the file you are trying to access and figure out why that file does not exist.

**Comment by DanTheTingler** [comment]
So this is the portion of my code that calls readdir, and I'm assuming I would check the contents of dirp? The output of my ls -R and the built-in ls -R are identical, expect for the error messages in the recursive calls.

while ((direntp = readdir(dirp)))
{
if(errno != 0)
        {
            perror("Error with readdir");
        }

**Comment by mikeizbicki** [comment]
I can't help you if you don't paste the actual output here.

**Comment by DanTheTingler** [comment]
Here's a snippet of what ls -R outputs and what my code outputs:

correct output for recursion:
./tests:
exec.script

my output:
./tests:
Error with readdir: No such file or directory
Error with readdir: No such file or directory
Error with readdir: No such file or directory
exec.script

**Comment by mikeizbicki** [comment]
Now print out the string you are passing to `opendir`.  I'll bet we'll find that it's not actually a valid directory.

**Comment by DanTheTingler** [comment]
Okay, so what do I do if it isn't?! Should I do a directory check right before my readdir?

**Comment by mikeizbicki** [comment]
One step at a time :)

What is the value of the string you are passing into `opendir`?

**Comment by DanTheTingler** [comment]
Okay this is going to be some pretty confusing output, my apologies in advance!!

So everything that says "testing: _____" is the value of the string I am passing into opendir.

./bin:
testing: rshell
rshell testing: .
Error with readdir: No such file or directory
testing: ..
Error with readdir: No such file or directory

./tests:
testing: .
Error with readdir: No such file or directory
testing: exec.script
Error with readdir: No such file or directory
exec.script testing: ..
Error with readdir: No such file or directory

./src:
testing: .ls.cpp.swp
Error with readdir: No such file or directory
testing: ls.cpp
Error with readdir: No such file or directory
ls.cpp testing: main.cpp
Error with readdir: No such file or directory
main.cpp testing: .
Error with readdir: No such file or directory
testing: a.out
Error with readdir: No such file or directory
a.out testing: ..
Error with readdir: No such file or directory

**Comment by DanTheTingler** [comment]
Now that still contains the correct output. 
bin is supposed to output rshell, which it does.
tests is supposed to output exec.script, which it does.
src is supposed to output everything that comes before testing, which it does.

It just has a bunch of readdir errors. Hopefully I make sense, sorry if what I'm saying is pretty confusing! Thanks for all the help Mike & Bryan!

**Comment by DanTheTingler** [comment]
And this is how I modified my code to test what was going into readdir:

 while ((direntp = readdir(dirp)))
    {
        cout << "testing: " << direntp->d_name << endl;
        if(errno != 0)
        {
            perror("Error with readdir");
        }

**Comment by mikeizbicki** [comment]
That is great error output!  Exactly what I was looking for!  Whenever you're giving debug messages, too much information is always better than too little!  (And if anything you're still on the side of too little.)

So I think you've struggled with this enough, and I'm just going to tell you the error I saw when you showed me in office hours.  I don't remember the exact lines of your code, but you were not always prepending the path correctly to the beginning of your filenames.  This is fine when you don't go into a subfolder because the path is just `./` and so everything happens to work out correctly.  But when you go into a subfolder names `test`, and it has a file named `exec.script`, you have to be applying all your functions to the file `./test/exec.script`.  You are applying some of the functions (again, I forget exactly where this is happening) to just `exec.script` instead of `./test/exec.script` and that is why you are getting an error that says `no such file or directory`.  Said another way, the file `./test/exec.script` exists, but you are asking about file `./exec.script` which does not exist.

The big picture leson to take away from this is that you must have LOTS of debug information.  It is impossible to have too much.  Then, when things don't work like you expect, you must go through that information VERY carefully.  If you actually ran the built in `ls` on one of the file names you printed out after `testing:`, you would have discovered this.  For example, if you would have ran `ls exec.script`, you would have seen that the build in `ls` gives you the same error message because that file doesn't actually exist.  This is what I was trying to get you to do above.

Does that make sense?

**Comment by DanTheTingler** [comment]
What you explained makes perfect sense, but I'm not too sure how to go about implementing it. 

So most importantly, I know I have to add the ./test (or whatever the directory name is) to everything that isn't a directory correct? I'm not too sure how and where I would do it. 

Again, thanks for all the help!

**Comment by mikeizbicki** [comment]
You have to do it EVERYWHERE.  If there's a filename, it MUST also include the path to the file.

**Comment by bmars003** [comment]
As you go down the recursive tree you need to add the path the prev directory's path? Does this make sense?

**Comment by DanTheTingler** [comment]
Hmm, for some reason if it's a filename I don't have this problem. I don't know if you still remember, but I have a while loop that gathers all the directories near the end, and stores them in the vector. Then I have a for loop that recursively calls my rflag function, but appends the dirName and the "/". Is this why my directories are working but my files aren't?

**Comment by DanTheTingler** [comment]
Here's my rflag function, hopefully this will make it easier for you to help me. If I wasn't supposed to post my code here, please delete it asap!!

int rflag(string dirName)
{

```
vector<char*> direc;
if((strcmp(dirName.c_str(), "")) == 0)
{
    dirName = ".";
}

DIR *dirp;

dirent *direntp;

if(!(dirp = opendir(dirName.c_str())))
{
    perror(dirName.c_str());
}


if(strcmp(dirName.c_str(), ".") == 0)
{
    cout << ".:" << endl;
}

else
{
    cout << dirName << ":" << endl;
}

while ((direntp = readdir(dirp)))
{
    cout << "testing: " << direntp->d_name << endl;
    if(errno != 0)
    {
        perror("Error with readdir");
    } 

    struct stat buf;

    char filepath[1024];
    strcpy(filepath, dirName.c_str());
    strcat(filepath, "/");
    strcat(filepath, direntp->d_name);

    if((stat(filepath , &buf)) == -1)
    {
        perror("There is an error with stat: ");
    }

    if ( direntp->d_name[0] == '.' )
    {
        continue;
    }

    cout << direntp->d_name << " ";

    if(stat(direntp->d_name, &buf) != -1)
    {
        if(S_ISDIR(buf.st_mode))
        {
            direc.push_back(direntp->d_name);
        }
    }
```

}
    cout << endl;
    cout << endl;

```
int dsize = direc.size();
for(int d = 0; d < dsize; d++)
{
    rflag(dirName+"/"+ direc.at(d));
}

if((closedir(dirp)) == -1)
{
    perror("Error with closedir: ");
}

return 0;
```

}

**Comment by DanTheTingler** [comment]
I'm just not too sure where to do it exactly in my rflag function, I understand the concept and your previous explanations though!

**Comment by DanTheTingler** [comment]
YES, I fixed it!! Looks like the problem was I was calling stat twice, and I only needed the first stat call. The second stat call (the if statement that comes before me pushing things into my vector) was what was causing the error. Thanks again Mike & Bryan!
