### ISSUE TITLE
hw3-Clarification on failed test cases

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#550]
Hi @tkimva 

I can't make it to office hours today but I am hoping to ask you a few questions about my failed test cases. 

For part 3, you wrote that it fails without parameters. Do you mean when we input `cd` by itself? @mikeizbicki mentioned in #487 and in the `README.md` file for this hw that we do not have to have this working for this assignment. However, I did _accidentally_ exit the entire program when this is inputted. 

For part 3, you also said it crashes with parameters. My `cd` was designed to take only one directory argument, like `cd dir` (see #489). I _accidentally_ exited the entire program again when multiple directories were arguments. 

Was I deducted points because it exited the program? Any chance you can cut me some slack for accidentally exiting?

**Comment by tkimva** [comment]
Yes you deducted the points because you accidentally exited the program when using `cd` with multiple parameters or no parameter. Please discuss with professor about this after class today and then let me know.  Okay?
