### ISSUE TITLE
Transferring file from local computer to hammer

### ISSUE THREAD

**Issue by jesuscreyes** [mikeizbicki/ucr-cs100#551]
I have my hw4 assignment on my local computer and I want to transfer the file to my repository on hammer so that I can create the pull request with it.

I googled a little, and I think the `scp` command is what I need, but the syntax is really confusing.

I was wondering if anyone knew the exact syntax that I need.

**Comment by 2c2c** [comment]
scp localfile remotelogin:directory

**Comment by jesuscreyes** [comment]
Just figured it out, thanks!

`scp testfile <username>@hammer.cs.ucr.edu:~/<directory>`

**Comment by tkimva** [comment]
In addition, you can use `-r` flag with `scp` to copy entire directories.

**Comment by abarb014** [comment]
Personally, I like using `sftp` if you want to look at that
