### ISSUE TITLE
Advice for future cs100 students

### ISSUE THREAD

**Issue by gbrlrz017** [mikeizbicki/ucr-cs100#559]
Everyone, 

In the spirit of hw4, and giving back to future cs100 students, @Tizoc- and I were hoping to write a little advice piece on how to do well in this class. In it we would like to give future students some pointers on what to do and not do based on our experiences. Things we wish we would have done better. Things we did well and so on. But we would also like to create a survey for our current classmates so we can hopefully get a better representation of students' advice.   

Some points we'd address: 
- What we wish we would have known coming into cs100
- What we wish we could have done differently
- What we did well
- What we got out of this class

These are just a few we've thought up, but there is room for a lot of miscellaneous things in between. In a sense this is similar to hw4, only it'd be won't be a tutorial of something specific like syscalls or vim. At the moment, I am thinking this won't be anything too big (since the quarter is almost over). But **if others are interested, we can open source this and create a github repo and we would probably have a much better end product that way.** 

I think this has the potential of being something really beneficial for those that read it to have a compilation of advice from others who have been in their shoes.

**Comment by mikeizbicki** [comment]
Sounds like a great idea to me!  Please do this!

**Comment by jesuscreyes** [comment]
This seems like a cool idea! Definitely something I'd like to have seen as a CS100 student. I'd be down to contribute to this.

**Comment by gbrlrz017** [comment]
@jesuscreyes awesome! We can talk about this more in class later if you'd like.
