### ISSUE TITLE
How to output individual file information like ls -l

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#56]
Im working on my code and i'm stuck in here:
129       while ((direntp = readdir(dirp)))
130       {
131          if (s.st_mode & S_IRUSR){
132             cout << 'r'; 
133          } else{ 
134             cout << '-';
135          }  
136          if (s.st_mode & S_IWUSR){
137             cout << 'w'; 
138          } else{ 
139             cout << '-';
140          }  
141          if (s.st_mode & S_IXUSR){
142             cout << 'x'; 
143          } else{ 
144             cout << '-';
145          }  
146          files.push_back(direntp->d_name);
147       }  

how can i output the individual files information? I removed the other information output, but when i call it, it all outputs it for just the current directory information. How can i make it output the individual files information. I pushed all the file/directory names into a string of vectors incase i could use it for the actual process. Any help will be appreciated!

**Comment by mikeizbicki** [comment]
I'm having trouble figuring out what your actual question is.  Can you please try to clarify it?

**Comment by rgosh001** [comment]
I'm sorry.
So im in the while loop above. I have my stat function's path set to the path provided or the default current directory.
In the original copy of ls.cpp you provided, it outputted the names of the actual files. What I'm trying to do within each while loop before it cout's the file name is cout the other information we need to present as well.
So for above, I'm outputting my usr rights. But when i do that in each iteration of the while loop, it outputs the same thing for all of them which it shouldn't be. Then i realized its outputting the actual directory's information instead of each individual file's information that needs to be presented.

**Comment by mikeizbicki** [comment]
You just need to call `stat` on each file inside the directory.  Is that not working?

**Comment by rgosh001** [comment]
hm, maybe I'm not calling it correctly.
Am i declaring stat right? :
119       stat(directory.back().c_str(), &s); 
120 
121       char const *dirName = directory.back().c_str();
122       DIR *dirp;
123       if (!(dirp  = opendir(dirName)))
124        {
125           cerr << "Error(" << errno << ") opening " << dirName << endl;
126           return errno;
127       }
128       dirent *direntp;
129       while ((direntp = readdir(dirp)))
130       {
etc...and within this loop^ i cout the checks for the user rights and the name of the file

**Comment by mikeizbicki** [comment]
AAAAAAHHHHHHHH!!!!!!!

You are calling a system call (`stat`) without error checking!!!!!!  No, you are not calling that correctly!!!!!!!!!

(Also, in your question you asked if you declared `stat` right, but you don't show any code with a declaration of `stat`.)

**Comment by rgosh001** [comment]
Ahhhh, nooo aha okay, ill do the system check. Let me show my code portion of it:
115    struct stat s;
116    vector<string> files;
117    while(!directory.empty())
118    {
119       stat(directory.back().c_str(), &s);
120 //system check goes here
121       char const *dirName = directory.back().c_str();
122       DIR *dirp;
123       if (!(dirp  = opendir(dirName)))
124        {
125           cerr << "Error(" << errno << ") opening " << dirName << endl;
126           return errno;
127       }
128       dirent *direntp;
129       while ((direntp = readdir(dirp)))
130       {
131          if (s.st_mode & S_IRUSR){
132             cout << 'r';
133          } else{
134             cout << '-';
135          }
136          if (s.st_mode & S_IWUSR){
137             cout << 'w';
138          } else{
139             cout << '-';
140          }
141          if (s.st_mode & S_IXUSR){
142             cout << 'x';
143          } else{
144             cout << '-';
145          }
146          cout << " ";
147          cout << direntp->d_name << endl;
148          files.push_back(direntp->d_name);
149       }
150       closedir(dirp);
151  
152       directory.pop_back();
153       cout << endl;

but the if statements for the usr right is what I'm most concerned about because i checked the man page but I can't get it to output the file's information :(
