### ISSUE TITLE
Things to do differently - extra credit

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#561]
A couple weeks ago I did the extra credit assignment where we had to discuss things we wish we did differently and things we wish the professors did differently. I noticed that the assignment doesn't seem to be anywhere in the github repo. Just wondering if anyone knows where I should see that grade.

**Comment by mikeizbicki** [comment]
I've not yet added the extra credit.  It will be added into the bounty file sometime this week.

**Comment by npsark** [comment]
Hi @mikeizbicki, I just noticed that this extra credit doesn't seem to be accounted for in my grades yet. Don't mean to nag, just want to make sure you're aware.

**Comment by mikeizbicki** [comment]
Thanks for reminding me!  They should be entered now.

**Comment by npsark** [comment]
thanks!
