### ISSUE TITLE
HW4 Draft - Netcat Tutorial

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#563]
It's in it's own repo at this URL https://github.com/abarb014/nctutorial

**Comment by mikeizbicki** [comment]
1. Your writing style and organization is excellent!  I only have some minor technical nitpicks.
2. You wrote: "netcat and telnet both utilize an important part of the computer, and it is called a port".  Technically, a port is not part of the computer, so you should reword this paragraph to make it correct.  The idea of the paragraph is good though.  At the very least, you should provide hyperlinks to wikipedia's ip and tcp articles.
3. "The port can be anything in the range provided earlier (32760 - 61000)"  The available range is much larger than this.  Anything less than 2^16
4. "As a small side note, if you use -l with netcat and you do not specify an IP address, it will default to localhost."  This is not quite correct.  No version of netcat defaults to only accepting connections on 127.0.0.1 AFAIK. Instead, it defaults to your default interface (the things displayed by ifconfig).  The only reason for ever specifying an ip adress is for computers that have multiple ip addresses.  This is a pretty rare setup though.
5.  There's no need to explain the flags in a big section.  Just explain a flag as you use it in the examples and point readers to the man pages for more info.
6. Explain why ctrl-d ends the chat session.
7. (optional) You could pipe the chat session through an encryption program like openssl to get the encrypted chat pretty easily.
8. Port scanning is not the way to check for open ports on your own machine.  The netstat program does that much faster/more accurately.  So you should find a better motivation for port scanning.  And you should probably link to the nmap tool for people who want more in depth port scans.
9. What you're doing looks like port forwarding to me.  I'm not sure what the distinction is you're trying to make.
10. Provide a link to more detailed info on named pipes.
11. You can use a hacking website like phrack.org as a good example of something that might be blocked in one location but you can get around the block with nc.
12. Provide a short conclusion section that has some info on limitations of netcat/related tools/where to learn more.
13. There's a couple spots where your wording could use some minor tweaks.

Overall, very nice!  Make these changes and I'll give you a 100.  Do the encryption change as well and I'll increase it to 110.
