### ISSUE TITLE
HW3 grade

### ISSUE THREAD

**Issue by ogonz007** [mikeizbicki/ucr-cs100#564]
Hi @tkimva 
I saw in the breakdown of my HW3 assignment that you didn't give me credit for part 1 of the assignment. If you look at the code I don't use execvp. I had replaced it with execv. I did however have a block of commented code that had a perror statement with execvp printed in the error statement and so I think the script you ran to check for execvp caught that commented one. Could you please look at the assignment again and correct the grading error? 
Thanks!

**Comment by tkimva** [comment]
regraded
