### ISSUE TITLE
HW 4: Deadline Extension Request for strtok tutorial

### ISSUE THREAD

**Issue by Dave864** [mikeizbicki/ucr-cs100#577]
I am working on a tutorial for how to use the `strtok` function. I have made quite a bit of progress so far but it has become clear that I will not be able to finish the tutorial by Thursday, 12/11/2014, midnight. I would like more time to work on this project. I plan on submitting it no later than Monday, 12/15/2014, at midnight. With the extra time I will be able to implement any suggestions that you have for my assignment and also see if my peers find it informative, since ultimately this will be used by future students. Also I plan on utilizing the writing center.

Here is a link to what I have thus far.
[How to Use Strtok](https://github.com/Dave864/rshell/tree/master/src)
Note: the section discussing parsing multiple strings only contains an outline of what I am going to cover, that is not what will be in the final draft.

**Comment by mikeizbicki** [comment]
I only skimmed your writeup, but it looks very good so far.  You can have the extension, but please reply to the extensions issue so that I have them all in one location.

**Comment by Dave864** [comment]
I finished my first draft on Saturday and posted a comment in the "important dates" issue asking you to review it. I was not sure what issue you referred to when you said to reply to the "extensions" issue so I assumed you meant the "important dates" one. However, my deadline is approaching (and may have passed by the time you read this) and I still have not heard back from you yet. May I have another extension until Friday, 6pm? I will have to use the extra time to study for my finals, which end Thursday morning, in addition to implementing any suggestions you may have.
Here is the link to my first draft:
[How to Use Strtok](https://github.com/Dave864/rshell/tree/master/src)
