### ISSUE TITLE
Problems trying to update fork of the class repo

### ISSUE THREAD

**Issue by abarb014** [mikeizbicki/ucr-cs100#581]
I'm trying to bring my fork up to date with the class one, but when I try and push to my repo, I get this error:

```
Counting objects: 1301, done.
Delta compression using up to 48 threads.
fatal: unable to create thread: Resource temporarily unavailable
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
fatal: write error: Bad file descriptor
```

I read it's because I ran out of memory on the server, so I don't know what to do.

**Comment by hgarc014** [comment]
Well, you could just do everything you are doing on your local computer instead.

**Comment by gbrlrz017** [comment]
Maybe you are trying to push a large file? Try compressing it / them.

To combine multiple files and/or directories into a single file, use:
  `tar -cvf file.tar inputfile1 inputfile2`

To un-tar into separate files later, enter:
  `tar -xvf file.tar`

This happened to me in lab 3 when I tried pushing that big file we were working with.

**Comment by abarb014** [comment]
I ended up cloning my fork my own computer, and doing to changes from there. Thanks anyway!
