### ISSUE TITLE
Assignment 4 on vimrc and plugins 

### ISSUE THREAD

**Issue by hfanc001** [mikeizbicki/ucr-cs100#582]
Me and my partner @atan009 are working on a tutorial on vim, .vimrc, and the plugins in vim for assignment 4. Here is what we have so far https://github.com/atan009/vimrc. We have an appointment at the writing center today at 4 pm to go over our writing in this tutorial. We are planning on adding a few more plugins and reformat our tutorial. Please take a look at what we have so far and give us some advice on how we can do better. Thank you.

**Comment by mikeizbicki** [comment]
This command: `git clone https://github.com/atan009/vimrc.git; mv vimrc/.vim ~/; mv vimrc/.vimrc ~/` isn't actually correct because it leaves unwanted git files on your computer.  Use the `wget` command to download the files.

**Comment by hfanc001** [comment]
Hi Mike, 

Today in office hour you mentioned that in the srcipt that downloads our repo and pre-configured vim, it should create a temp dir and clone our repo into it and then manually move the content afterwards. I am just wondering what should I do if the user who downloads our vim already have .vim and .vimrc? Should I rename theirs to .vim1 and .vimrc1 and then move ours to the place it suppose to be or should I just echo an error message and ask the user to remove their files first before downloading our vim? 

Thank you for your time.

**Comment by mikeizbicki** [comment]
You should rename them to something else.  Make sure to document this in
the readme.
