### ISSUE TITLE
Office hours - finals week

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#585]
Will there be office hours during finals week for me to demonstrate that I have linux working on my computer? Or is today my last chance?

**Comment by tkimva** [comment]
As I know, normally, there is no TA office hour (Tues) on final week at least as the instruction ends tomorrow. Please ask professor, if he's busy, I can do that. But normally Linux working checkoff have been done by professor, please contact professor first as he mentioned in #562

**Comment by mikeizbicki** [comment]
I will have office hours by appointment.
