### ISSUE TITLE
Extension hw4

### ISSUE THREAD

**Issue by drami025** [mikeizbicki/ucr-cs100#589]
Henry and I would like an extension on our hw4 git game to include a hard version for more experienced users. Can we have the deadline extended to next Thursday December 18th?

**Comment by kavj** [comment]
I would like more time. I wanted to fully explore some of the bugs that can affect parsing of repeated commands even if they aren't directly tied to parsing itself.  As an example, when wait did not return immediately or issued an error stating "Wait: interrupted system call", this sometimes caused random issues when calling the next statement that would appear similar to bad input. I also wanted to polish what I have already written. I think it will be done before Tuesday. My most brutal final is Monday.
