### ISSUE TITLE
Question about Email

### ISSUE THREAD

**Issue by ManjunathChet** [mikeizbicki/ucr-cs100#616]
Does anyone remember how Mike modified his email for different services he was signing up for? He covered it in lecture about two weeks ago.

If he was signing up for the web-service "CS100", instead of using his regular email "Mike@Izbicki.me", he would enter something like "Mike@Izbicki.CS100.me". It wouldn't modify his email address, but he used it as a label to know if the service would give out his email later on. That example is probably wrong; I forgot what the syntax was for doing this. Can anyone enlighten me?

**Comment by 2c2c** [comment]
i don't recall his method. the general gmail way to do it is add a + to your username.

e.g. username+nospam@gmail.com

**Comment by gbrlrz017** [comment]
Adding '.' anywhere before that '@' was one way I believe. 

Example: gabriel.ruiz@ucr.edu = ga.b.ri.e.lr.u.iz@ucr.edu = ... = gabrielruiz@ucr.edu

I don't know if there is a limit to the '.' you can have.
