### ISSUE TITLE
hw1 regrading

### ISSUE THREAD

**Issue by kryne001** [mikeizbicki/ucr-cs100#64]
On my grading it says that my homework did not compile again even though I literally can only get it to compile and run on the well server. I was even showing Mike in office hours today how my program runs (albeit improperly) but it still ran. I don't see any possible way it doesn't compile and run.

**Comment by bmars003** [comment]
Come to my OH tomorrow morning or on Monday during lab and I can show exactly the errors I am getting.

**Comment by bmars003** [comment]
~/Desktop/Grading/CS100Summer2014SummerSession2/HW1_late/kryne001
marshb@well $ git checkout hw1
D   bin/rshell
HEAD is now at 9fd82da... finished hw1
~/Desktop/Grading/CS100Summer2014SummerSession2/HW1_late/kryne001
marshb@well $ rm -rf bin/*
~/Desktop/Grading/CS100Summer2014SummerSession2/HW1_late/kryne001
marshb@well $ make
g++ -Wall -Werror -ansi -pedantic -g --debug src/hw1.cpp -o bin/rshell
g++ -Wall -Werror -ansi -pedantic src/ls.cpp -o bin/ls
src/ls.cpp: In function ‘int main()’:
src/ls.cpp:36: error: request for member ‘size’ in ‘commandLine’, which is of non-class type ‘char_’
src/ls.cpp:39: error: expected primary-expression before ‘;’ token
cc1plus: warnings being treated as errors
src/ls.cpp:24: warning: unused variable ‘i’
make: *_\* [ls] Error 1

**Comment by kryne001** [comment]
OH see? homework 2 is not compiling, not homework 1! But homework 2 should compile in the homework 2 tag.

**Comment by bmars003** [comment]
OH = Office hours and HW 1 did not compile.

**Comment by kryne001** [comment]
Wait are you gonna be there after 11? Because by the time I get there park and walk there it'll be past 11.

**Comment by bmars003** [comment]
I might be, but was not planning on it.

**Comment by kryne001** [comment]
Okay I'll try to be there as soon as possible.

**Comment by bmars003** [comment]
Grade should be updated  by later today.

**Comment by bmars003** [comment]
Regraded.
