### ISSUE TITLE
Question regarding calcgrade

### ISSUE THREAD

**Issue by anmolsingh95** [mikeizbicki/ucr-cs100#640]
Hey @mikeizbicki , I had an idea to modify calcgrade to make it faster. the way I did it is that I do not run git clone or git pull, Instead I run wget on individual raw grades files. This makes it much much faster that downloading an entire repo. I had modified the downloadRepo function to my specifics.
I was almost done when I realized that you actually need the original DownloadRepo function while grading our assignments. because you have to download repos to add grades and then push them back.

So, should I go ahead and create a seperate lite version of DownloadRepo that only download Grades files? I will use this lite version with calcgrades. This way calgrade will get faster, and other scripts would work as well.

Also do you have any ideas on how to make uploadGrades faster? Cloning over a hundred repos would a couple hours if you had an internet like mine and that is a lot of time.

**Comment by mikeizbicki** [comment]
Using wget seems like it would be very fragile.  How do you know what files to download?

**Comment by anmolsingh95** [comment]
@mikeizbicki  , I would run `find assignments/ -name grade` on the current repo and it would give me all the paths to grades. I would later append them to the raw github url. Trust me it works, and I would test it under multiple scenarios before issueing a pull request.
