### ISSUE TITLE
Check Request for HW4

### ISSUE THREAD

**Issue by mxu008** [mikeizbicki/ucr-cs100#643]
Hi Mike,

I followed the most of your comments and submitted my assignment. Can you just look more paragraphs and check it again?

 Thank you!

**Comment by mikeizbicki** [comment]
No.  It takes me a long time to carefully read through these writeups. If you didn't put in the time to fix the things at the beginning, then I don't want to waste my time.  You must fix all my comments first.

**Comment by mxu008** [comment]
Ok, is it possible that I get extension until tomorrow so that I can fix
the beginning? Actually I spend much time in this assignment.
