### ISSUE TITLE
Needed to delete my forked repo

### ISSUE THREAD

**Issue by asand017** [mikeizbicki/ucr-cs100#657]
I had to delete my forked repo to resubmit my hw4 in one commit, so I ended up losing my grades branch. I have the screenshot of my grades before I deleted it. How can I go about getting my grade sheet back up to date?
Can we meet either tomorrow after 11am or on Friday after 11am to re-enter my grades? Sorry for the inconvenience.

**Comment by mikeizbicki** [comment]
This should be fixed now.

Just to be clear, you did not _have_ to delete your forked repo like you state.  There were better alternatives for updating your repo.
