### ISSUE TITLE
input for assignment 3

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#66]
since we are running bin/rhsell for this assignment, we have to modify the .cpp file from our assignment 1 correct?

**Comment by bmars003** [comment]
Correct. HW3 is a building on what was completed in HW 1.

**Comment by willccoates** [comment]
so i have a question in reguards to the & for assignment 1, when we see that there is an &, do we fork and not wait? because if we put a wait in there then we still would not be able to input commands in the terminal right?

**Comment by bmars003** [comment]
My question to you would be do you understand what adding the `&` means? Please take a look at stackoverflow.com/questions/13338870/what-does-at-the-end-of-a-linux-command-mean
