### ISSUE TITLE
"Things to do differently" extra credit

### ISSUE THREAD

**Issue by asand017** [mikeizbicki/ucr-cs100#660]
If I recall correctly, we were supposed to receive 10 extra credit points for the 2 things instructors could do differently and 2 things students could do differently sentences, but I only received 5 points for it. Was I missing something when I submitted them? Thank you.

**Comment by mikeizbicki** [comment]
I gave everyone who submitted it 5 points extra credit.

**Comment by asand017** [comment]
Oh ok just making sure. Thank you!
