### ISSUE TITLE
Last office hours Friday

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#665]
The last office hours will be Friday starting at 11 AM in WCH110.  That will be your last chance to talk to me about any issues you have with your grades.

**Comment by hfanc001** [comment]
Hi Mike, would you still be there after 11:30 AM? I have work till 11:30 AM but I still need to talk to you.  Thank you for your time.

**Comment by mikeizbicki** [comment]
@hfanc001 yes.
