### ISSUE TITLE
Makefile Curiosity

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#67]
Just to make sure I don't get marked off points for this but, can i have my makefile remove an existing bin folder if there is one in the current directory? I got tired of having to type the command "make clean" everytime I wanted to re-"make" my file. So now whenever I type "make", it always removes any existing bin folder and creates a new one with the newly compiled executables.

**Comment by bmars003** [comment]
I was allow it, but keep in mind that what if you had other executable in your bin folder that still wanted, but when you compile one of the programs it could delete it.
