### ISSUE TITLE
HW2 grading question

### ISSUE THREAD

**Issue by katherinegallaher** [mikeizbicki/ucr-cs100#68]
I got -10 for not being able to take directories as parameters but I just checked and it can take directories as well as files as parameters

How is this being tested for grading?

Also, I got 10 points off for no perror but i'm pretty sure I have a perror for every sys call, I just double checked...

**Comment by katherinegallaher** [comment]
Also, not really related to this but when I run the script to check my grades the output is really weird and outputting all of the assignments multiple times and it says I have total possible points of 2860. Am I doing something wrong? 
The way I run it is scripts/calcgrade.sh katherinegallaher

**Comment by mikeizbicki** [comment]
If you want to run the grading script yourself, it is `checksyscalls.sh`.  It expects a single parameter that is the filename to grade.  We'll be going over exactly how it works in class on Monday.

When I check your grade, this is the output I get:

```
$ scripts/calcgrade.sh katherinegallaher
finding grade for github account katherinegallaher

===========================================
    grade        |  assignment
===========================================
    --- /   0    |  ec-bounty
    --- /   0    |  ec-online
    --- /   0    |  ec-reading
    100 / 100    |  hw0-vim
    110 / 100    |  hw1-rshell
    105 / 100    |  hw2-ls
    --- / 100    |  hw3-piping
    --- / 100    |  hw4-signals
    --- / 100    |  hw5-oss
     10 /  10    |  lab0-vim
     10 /  10    |  lab1-git
     10 /  10    |  lab2-fork
     10 /  10    |  lab3-debugging1
    --- /  10    |  lab4-cp
    --- /  10    |  lab5-debugging2
    --- /  10    |  lab6-signal
    --- /  10    |  lab7-cstring
    --- /  10    |  lab8-spam
    --- /  10    |  lab9-rm
     25 /  25    |  linux
     10 /  10    |  quiz1
     10 /  10    |  quiz2
     10 /  10    |  quiz3
     10 /  10    |  quiz4
===========================================

running total =  420 /  405 = 103.70
overall total =  420 /  765 = 54.90
```

Can you copy/paste your output here exactly?  Also show the output of `bash --version` and `hostname`.

**Comment by bmars003** [comment]
1) 
`-R`
 Does took a look at it is that when I added a '/' onto the end of the directory path, your program didn't work. Point will be added back. 
`-perror`: 
As for this it looks like there are still 2 calls being missed somewhere. 

2) I was able to get it to work. You might need to have an update of your repo

Here is what I got.
`
~/Desktop/Grading/CS100Summer2014SummerSession2
marshb@well $ ./scripts/calcgrade.sh katherinegallaher
finding grade for github account katherinegallaher

# 

```
grade        |  assignment
```

# 

```
--- /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
100 / 100    |  hw0-vim
110 / 100    |  hw1-rshell
105 / 100    |  hw2-ls
--- / 100    |  hw3-piping
--- / 100    |  hw4-signals
--- / 100    |  hw5-oss
 10 /  10    |  lab0-vim
 10 /  10    |  lab1-git
 10 /  10    |  lab2-fork
 10 /  10    |  lab3-debugging1
--- /  10    |  lab4-cp
--- /  10    |  lab5-debugging2
--- /  10    |  lab6-signal
--- /  10    |  lab7-cstring
--- /  10    |  lab8-spam
--- /  10    |  lab9-rm
 25 /  25    |  linux
 10 /  10    |  quiz1
 10 /  10    |  quiz2
 10 /  10    |  quiz3
 10 /  10    |  quiz4
```

# 

running total =  420 /  405 = 103.70
overall total =  420 /  765 = 54.90
`

**Comment by katherinegallaher** [comment]
Okay I must be missing perror somewhere then. 

Here is the output I get when I try calcgrade:

kgall005@well $ bash --version
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.
~/cs100/ucr-cs100
kgall005@well $ hostname
well.cs.ucr.edu
~/cs100/ucr-cs100
kgall005@well $ scripts/calcgrade.sh katherinegallaher
finding grade for github account katherinegallaher

# 

```
grade        |  assignment
```

# 

```
--- /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
100 / 100    |  hw0-vim
110 / 100    |  hw1-rshell
115 / 100    |  hw2-ls
--- / 100    |  hw3-piping
--- / 100    |  hw4-signals
--- / 100    |  hw5-oss
 10 /  10    |  lab0-vim
 10 /  10    |  lab1-git
 10 /  10    |  lab2-fork
 10 /  10    |  lab3-debugging1
--- /  10    |  lab4-cp
--- /  10    |  lab5-debugging2
--- /  10    |  lab6-signal
--- /  10    |  lab7-cstring
--- /  10    |  lab8-spam
--- /  10    |  lab9-rm
 25 /  25    |  linux
 10 /  10    |  quiz1
 10 /  10    |  quiz2
 10 /  10    |  quiz3
 10 /  10    |  quiz4
  5 /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
--- /   0    |  hw0-vim
 95 / 100    |  hw1-rshell
--- / 100    |  hw2-ls
--- / 100    |  hw3-piping
--- / 100    |  hw4-signals
--- / 100    |  hw5-oss
 10 /  10    |  lab0-vim
 10 /  10    |  lab1-git
 10 /  10    |  lab2-fork
 10 /  10    |  lab3-debugging1
--- /  10    |  lab4-cp
--- /  10    |  lab5-debugging2
--- /  10    |  lab6-signal
--- /  10    |  lab7-cstring
--- /  10    |  lab8-spam
--- /  10    |  lab9-rm
 25 /  25    |  linux
 10 /  10    |  quiz1
  0 /  10    |  quiz2
  0 /  10    |  quiz3
  0 /   0    |  quiz4
--- /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
100 / 100    |  hw0-vim
110 / 100    |  hw1-rshell
--- / 100    |  hw2-ls
--- / 100    |  hw3-piping
--- / 100    |  hw4-signals
--- / 100    |  hw5-oss
 10 /  10    |  lab0-vim
 10 /  10    |  lab1-git
 10 /  10    |  lab2-fork
 10 /  10    |  lab3-debugging1
--- /  10    |  lab4-cp
--- /  10    |  lab5-debugging2
--- /  10    |  lab6-signal
--- /  10    |  lab7-cstring
--- /  10    |  lab8-spam
--- /  10    |  lab9-rm
--- /  25    |  linux
 10 /  10    |  quiz1
 10 /  10    |  quiz2
 10 /  10    |  quiz3
 10 /  10    |  quiz4
--- /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
--- /   0    |  hw0-vim
--- / 100    |  hw1-rshell
--- / 100    |  hw2-ls
--- / 100    |  hw3-piping
--- / 100    |  hw4-signals
--- / 100    |  hw5-oss
 10 /  10    |  lab0-vim
--- /  10    |  lab1-git
--- /  10    |  lab2-fork
--- /  10    |  lab3-debugging1
--- /  10    |  lab4-debugging2
--- /  10    |  lab5-cp
--- /  10    |  lab6-signal
--- /  10    |  lab7-cstring
--- /  10    |  lab8-spam
--- /  10    |  lab9-rm
--- /  25    |  linux
--- /  10    |  quiz1
--- /  20    |  quiz2
  2 /  10    |  kle016
  6 /  10    |  knguy080
```

# 

running total =  913 /  910 = 100.32
overall total =  913 / 2860 = 31.92

**Comment by bmars003** [comment]
Huh that is weird indeed. And you are working with the latest version of your repo from github (online)?

**Comment by bmars003** [comment]
What might be happening actually is the script is grabbing from all your different branches and or tags. Though this is just a hypothesis.

**Comment by katherinegallaher** [comment]
well I recloned the repository and it fixed it a little bit but it's still weird. Here's the output now; 

kgall005@well $ scripts/calcgrade.sh katherinegallaher
finding grade for github account katherinegallaher
error: pathspec 'init' did not match any file(s) known to git.
scripts/config.sh: line 46: 110
-10
number
number
grade
+20

NOTE:

Also: expression recursion level exceeded (error token is "grade
+20

NOTE:

Also")
scripts/config.sh: line 57: 100+100
not
syscalls...
perror.....
-10
credit

forget

to: syntax error: invalid arithmetic operator (error token is "...
perror.....
-10
credit

forget

to")
scripts/config.sh: line 67: 100+100
not
syscalls...
perror.....
-10
credit

forget

to: syntax error: invalid arithmetic operator (error token is "...
perror.....
-10
credit

forget

to")
(standard_in) 1: parse error
(standard_in) 1: parse error

# 

```
grade        |  assignment
```

# 

```
--- /   0    |  ec-bounty
--- /   0    |  ec-online
--- /   0    |  ec-reading
100 / 100    |  hw0-vim
110
```

-10
number
number
grade
+20

NOTE:

Also / 100
not
syscalls...
perror.....
-10
credit

forget

to    |  hw1-rshell
    115

-10pts:
number
number
grade

+25

-10
+10 / 100

syscalls...
perror.....
-10

extra

can't
grading    |  hw2-ls
    --- / 100    |  hw3-piping
    --- / 100    |  hw4-signals
    --- / 100    |  hw5-oss
     10 /  10    |  lab0-vim
     10 /  10    |  lab1-git
     10 /  10    |  lab2-fork
     10 /  10    |  lab3-debugging1
    --- /  10    |  lab4-cp
    --- /  10    |  lab5-debugging2
    --- /  10    |  lab6-signal
    --- /  10    |  lab7-cstring
    --- /  10    |  lab8-spam
    --- /  10    |  lab9-rm
     25 /  25    |  linux
     10 /  10    |  quiz1
     10 /  10    |  quiz2
     10 /  10    |  quiz3

#      10 /  10    |  quiz4

running total =      /      = 0.00
overall total =      /      = 0.00

**Comment by bmars003** [comment]
Oh WOW. I will be honest I have no Idea what is going on.

**Comment by katherinegallaher** [comment]
lol okay, thanks anyways bryan. I guess I can just check it manually on github

**Comment by mikeizbicki** [comment]
The version of bash you are using on well is somehow different than mine.  So the commands are doing something different somehow.  I'll look into why the versions are different and what to do about it.  Thanks for reporting this.

**Comment by mikeizbicki** [comment]
Katherine, can you double check for me that you have the latest copy of the repository?  If you think you do, can you copy your output of `git pull; ./scripts/calcgrade.sh katherinegallaher` here?

**Comment by bmars003** [comment]
I am running it on well as well and here is my bash version:
`
GNU bash, version 3.2.25(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2005 Free Software Foundation, Inc.
`

I believe it is the same as hers.

**Comment by katherinegallaher** [comment]
I guess it was that it wasn't the latest copy of the repository. I recloned and then updated it (according to the instruction here https://github.com/mikeizbicki/ucr-cs100/issues/16) and it works now! Sorry about the trouble. 
So the problem was that I need to keep the repository completely up to date to run the script?

**Comment by bmars003** [comment]
I would assume that is the case.
