### ISSUE TITLE
HW4: Regex program repo fixes

### ISSUE THREAD

**Issue by thinkaliker** [mikeizbicki/ucr-cs100#690]
Hi Mike - I'm not sure when final grades are due, but my partner @Liniarc hasn't responded to my pull request (the changes we went over in office hours today). If final grades are due soon, could you look over [what I did](https://github.com/thinkaliker/regexprogram) and add the grades in? These changes should be the final repository + today's changes.

**Comment by thinkaliker** [comment]
The change has been approved, if you could check out our repo that would be great!
http://github.com/liniarc/regexProgram

**Comment by mikeizbicki** [comment]
Good job!  You guys should submit your repo to places like reddit.
