### ISSUE TITLE
HW4

### ISSUE THREAD

**Issue by jmoon018** [mikeizbicki/ucr-cs100#700]
@mikeizbicki 

<a href="https://github.com/jmoon018/Pac-Vim">Pac-Vim</a>
I need to create a proper .md file, add 2 commands and fix a bug (keystrokes are recorded while the game is loaded, causing weird graphical glitches), but it is fully playable and has the other features (walls, creating custom ghosts in map file, etc). I will post it on Reddit later this week and hopefully get some attention

<a href="https://github.com/jmoon018/rshell-unit-tester">RShell Unit Tester</a>
This still works, but it was far more challenging to make the commands run in proper order without the sleep function (the C++ code continues executing before the bash script finishes if sleep isn't used) than I thought it would be. I do have one more idea to fix this, and I hope to have everything finished by Monday night. 

Thanks,
Jamal

**Comment by mikeizbicki** [comment]
For pacvim, make sure to include a gif showing the actual gameplay. This is what will attract people to the project.

For the tester, this is the bug that most needs to be fixed: "Ensure that you are inside the bin folder, then type ./autograder. It may not work if you run it from ../bin or the root folder"  We simply can't use it at all until it is.
