### ISSUE TITLE
Grade delayed on Growl

### ISSUE THREAD

**Issue by npsark** [mikeizbicki/ucr-cs100#704]
I just saw that my grade on growl says GD. Is this something I need to worry about?

**Comment by hgarc014** [comment]
GD = Grade Delay
This most likely means Mike didn't submit the grades on time. 
So, your final grade is delayed. Mine is also GD.
i had this happen in a previous class and the teacher hadn't submitted grades by the cut off. As soon as he submits grades it should be updated

**Comment by ManjunathChet** [comment]
Henry's right. You guys have absolutely nothing to worry about. Mike has been nice enough to accept submissions past the last day of the quarter. He is probably taking care of the last hw4 submissions and extra credit.

For reference, my biochemistry class has over 300 students. The professor needs to grade all the finals by hand, so we got a GD for that class as well. He said grades won't come out till the new year. Instructors file GDs all the time depending on the workload they have.

**Comment by mikeizbicki** [comment]
See #705
