### ISSUE TITLE
After parsing

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#71]
One obstacle has been surmounted only to be faced by another. 

So say I have this: ls -l > result

Using a for loop, I put the > in a vector of strings, safely recorded for later use, I use strtok to parse out all spaces, >, <, and >>. For my particular example above however, after parsing, how do I know where the > was? Additionally, how can I tell that result is a file name?

**Comment by mikeizbicki** [comment]
If I were parsing that command, I would build a vector that contains four strings: `ls` `-l` `>` and `result`.  Then just loop over the vector deciding what to do at each spot.  It sounds like you build a vector of just the redirection commands, and I'm not sure how that would be helpful.

**Comment by DanTheTingler** [comment]
Hmm okay. So my question is, for that particular example, we would need to fork, open the file first, then close and use dup, and lastly call ls. How would we start with the end of the for loop and work our way back up to the front? And how would we know if result is a file, or just another command that exec needs to run?
