### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#721]
Immediately before the "enrolling in this course" section of Lab 1, there is a link to a "git cheatsheet" that leads to a 404:

"You should check the git cheatsheet to figure out what the git branch -d command does."

(link is: https://github.com/mikeizbicki/ucr-cs100/blob/2015winter/assignments/lab/lab1-git/git-cheatsheet.md)

**Comment by mikeizbicki** [comment]
This should be submitted as a pull request.
