### ISSUE TITLE
No GRADES.md file

### ISSUE THREAD

**Issue by admiralakbar** [mikeizbicki/ucr-cs100#725]
Near the bottom of lab 1(link https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/assignments/lab/lab1-git) it says:
"IMPORTANT: The file GRADES.md in this repo contains detailed information about how your grades will be stored in this repo. Finish completing this lab, then go back and read this file."

The "GRADES.md" link doesnt work and I cannot find this file elsewere either

**Comment by mikeizbicki** [comment]
This file was moved to https://github.com/mikeizbicki/gitlearn

The fix should be submitted as a pull request.

**Comment by mikeizbicki** [comment]
This is a reminder to anyone looking for extra credit that this bug still needs fixing.
