### ISSUE TITLE
Merge conflict image has incorrect branch locations

### ISSUE THREAD

**Issue by svtanthony** [mikeizbicki/ucr-cs100#731]
Image with issue:
https://github.com/mikeizbicki/ucr-cs100/raw/2015winter/assignments/lab/lab1-git/images/11.png

Reading: Basic Merging Section
http://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

Summary:
Based on the link above, a merge will fast-forward(point to the same node) the branch when there is a direct ancestor , if there isn't direct ancestor, git will create a merge commit that has more than 1 parent, thus the branches will not fast-forward.

**Comment by mikeizbicki** [comment]
I don't think the image is correct as-is, but I might not be understanding what you're saying.  It's probably best if you explain this to me in person.
