### ISSUE TITLE
Open & dup2

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#74]
Hey everyone:

I'm having trouble with opening a file of a certain name. For example, if I have a file name stored in a string called filename, this is how I call open

int fd  = open(filename.c_str(), O_RDWR|O_CREAT);
if(fd == -1)
{
perror("Error with opening file:");
exit(1);
}

And im getting the error: No such file or directory.

But since I have O_CREAT, shouldn't it create the file for me?

Also, can we use dup2 instead of dup? That way we won't have to do closing.

**Comment by mikeizbicki** [comment]
Let's say you call `open` on the file `this/is/a/test`.  If the directory `this/is/a` exists, then it will create `test`.  If the directory `this/is/a` does not exist, `open` will NOT create that directory.  This is probably the problem you are encountering.  Have you tried testing how bash works in the same conditions?

**Comment by DanTheTingler** [comment]
Yep, I have. When using bash, I call ls > results, and it creates a results file just fine. However, it doesn't work with my open.

**Comment by DanTheTingler** [comment]
So I'm assuming I cant just have the filename, and that I have to append the directory name onto it as well to call open?

**Comment by examplestudent** [comment]
The path must be either a valid relative or absolute path.  That may or may
not mean appending directory names depending on the circumstances.

**Comment by DanTheTingler** [comment]
So how come if we call open on say ("test", O_RDWR|O_CREAT) it works, but if I call it on a string.c_str() it doesn't work? Doesn't test stand alone without any paths in front of it?

**Comment by examplestudent** [comment]
In that example, `test` is a valid relative path.  That is, all the
directories needed to create the file exist.  If you do:

```
string test="test";
open(test.c_str(),O_RDWR|O_CREAT)
```

that should succeed exactly when what you wrote succeeds.

**Comment by DanTheTingler** [comment]
Okay for some reason when I did what you did it worked, but when I used a string with the c_str, it didn't work.

**Comment by mikeizbicki** [comment]
Well... the only possibility is that you have something different in your string...

**Comment by DanTheTingler** [comment]
The only weird thing I can think of is that my string is constructed from an array of chars. This is how I do it:

```
//split str depending on where the > is.
    for(int p = 0; p < 1024; p++)
    {
        if(str[p] == '>')
        {
            pos = p;
        }
    }


    cout << "the position of p is: " << pos << endl;

    char a1[1024] = {0};
    char a2[1024] = {0};

    for(int d = 0; d < pos; d++)
    {
        a1[d] = str[d];
    }

    for(int d = pos+1; d < 1024; d++)
    {
        a2[d] = str[d];
    }
```

Then, I modify a2[] into a string called filename:
string filename = string(&a2[0], 1024);

Then I pass into open filename.c_str()

**Comment by bmars003** [comment]
Have you tried outputting what is in filename to verify that it is exactly what you are expecting ?

**Comment by mikeizbicki** [comment]
I notice that you haven't printed it out.... anytime the output is not what you expect, check the input!

**Comment by mikeizbicki** [comment]
Also, please surround your code blocks with the backtick characters ``` (top left of the keyboard).  One backtick for inline code, three backticks for code blocks.  This will make it much easier for us to read.

**Comment by DanTheTingler** [comment]
Awesome, I've been wondering how to do that. Okay, so I printed out what I had in filename after changing it into a string, and it prints out tests just fine (my user input was ls > tests).

**Comment by DanTheTingler** [comment]
But like I said, when I did what mike did above, my code worked. So my string has a problem, just not too sure. Could it be with the way I create it? I can post my whole function here as well if need be.

**Comment by DanTheTingler** [comment]
So there are two ways I'm trying to convert my char array to a string. The first method is 
`string filename = string(&a2[0], 1024);`
and the second method is:
`string filename(a2);`

With the first method, when I output filename, it outputs just fine, but open can't find it. With the second method, it compiles just fine, but when I output, nothing shows up, and open also cannot find the file.

**Comment by DanTheTingler** [comment]
Okay so I've tried a bunch of different things and nothing is working. Here's my code for the function:

```bool amper = false;
    int i = 0, d = 0;
    int pos = 0;

```
//split str depending on where the > is.
for(int p = 0; p < 1024; p++)
{
    if(str[p] == '>')
    {
        pos = p;
    }
}
cout << "the position of p is: " << pos << endl;

char a1[1024] = {0};
char a2[1024] = {0};

for(int d = 0; d < pos; d++)
{
    a1[d] = str[d];
}


for(int d = pos+1; d < 1024; d++)
{
    a2[d] = str[d];
}

int alength = sizeof(a2);
a2[alength-1] = '\0';


//convert the file name from char array to a string
//all the different methods i've tried
string filenamet(a2, 1024);
// string filename = chartostring(a2, 1024);
//filename = string(&a2[0], 1024);
//strncpy(filename, a2, 1024);
//filename[1024] = '\0';
cout << "This is the file:" << filenamet << endl;

char **arg;
arg = new char* [1024];

char *token = strtok(a1, " "); //parse input using strtok
while (token != NULL)
{
    arg[i] = token; //put parsed commands into arg
    i++; //incrememnt to the next part of arg
    token = strtok(NULL, " "); //continue parsing
}

arg[i] = NULL; //set the end of arg to NULL to avoid seg fault

//search for the various needed elements
for(int d = 0; d < i; d++)
{
    if(*arg[d] == '&') //if & is found
    {
        amper = true; //set bool to true
    }
}

//for some reason this works, when i pass in test.c_str() to open, it creates the file
//string test = "result";

//tried using a string variable set to what filenamet was, didn't work either
string filename = filenamet;

cout << "This is the second filename:" << filename << endl;
//now we fork
pid_t pid = fork();

if(pid > 0) //parent
{
    if(amper == false) //if there was no &, then wait for child process
    {
        wait(0);
    }
}
else if(pid == 0) //child process, which means we want to run exec
{
    //call open on file
    int fd = open(filename.c_str(),O_RDWR|O_CREAT);

    if(fd == -1)
    {
        perror("Error with opening file");
        exit(1);
    }

    close(1);

    dup2(fd, 1);

    if(execvp(arg[0], arg) < 0 ) //calls the command and its flags
    {
        perror("execvp failed"); //error check/message
    }

    exit(1);
}

else //error check for fork: fork has failed, output error message
{
    perror("fork has failed: ");
    exit(1);
}

delete[] arg;
```

}

**Comment by DanTheTingler** [comment]
Okay after much introspection and carefully going through my code and some soul searching, I have found the error. It is in the for loop where I was setting a2 equal to the latter half of str. a2 needed to start at 0, while str needed to start at pos (position of the >), but I was starting them both at pos. Thanks!
