### ISSUE TITLE
Program exiting after piping

### ISSUE THREAD

**Issue by DanTheTingler** [mikeizbicki/ucr-cs100#80]
Can anyone help me with this problem? I finally got piping to work, but my program exits right after it finishes piping. I've checked all my exit calls, but I don't believe I have any extra ones. As always, I can post my code if need be, or take pointers/tips.

Thanks!

**Comment by bmars003** [comment]
One thought that I had on this issue is that the parent might be waiting on the child process to end. After the enter key is pressed the child ends and the parent is able to precede.
