### ISSUE TITLE
Missed class on Monday

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#803]
Hello professor,
I was in a car accident on Monday and was not able to come to class and lab. I completed the lab on my own and my credentials / accounts are now in the repo. I was hoping I would be able to make up the quiz that I missed. I noticed that your office hours are Tuesday from 11-12. I can make myself available to take it at this time if suitable, or is there another time that I should take it?

**Comment by mikeizbicki** [comment]
You get full credit for the labs.  Please come to office hours for the quiz.
