### ISSUE TITLE
makefile and creating bin

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#81]
i tried adding the code 

all: bin rshell
bin:
    [! -d bin] && mkdir bin

and i got the error

[! -d bin] && mkdir bin
/bin/sh: 1: [!: not found
make: **\* [bin] Error 127

could anyone explain what i need to fix

**Comment by mikeizbicki** [comment]
you need a tab after the bin, so:

```
all: bin rshell
bin:
    [! -d bin] && mkdir bin
```

**Comment by willccoates** [comment]
yea i have that in my Makefile

**Comment by katherinegallaher** [comment]
I had to put a dollar sign before the bin in the brackets
like [ ! -d $bin ] && mkdir bin

**Comment by willccoates** [comment]
i just tried it and i still got the same error :/

**Comment by katherinegallaher** [comment]
maybe you need a space between the bracket and the exclamation point ?

**Comment by willccoates** [comment]
ahh idk whats wrong with it lol

**Comment by katherinegallaher** [comment]
lol well if it helps mine looks like this, idk what could be wrong though :

all: bin rshell ls

bin:
    [ ! -d $bin ] && mkdir bin

**Comment by examplestudent** [comment]
Please paste the exact contents of the file here.  Put it inside of three
backticks so that github displays it as code.  Lookup "github flavored
markdown" if you need a tutorial on how to do this.  Also, put the exact
error message you get when you run `make`.  I mean EVERYTHING, including
the command prompt and the stuff you type in.

**Comment by willccoates** [comment]
```
  1 all: bin rshell
  2 bin:
  3     [ ! -d bin] && mkdir bin
  4 rshell:
  5     g++ -Wall -Werror -ansi -pedantic src/main.cpp -o ./bin/rshell
  6 ls:
  7     g++ -Wall -Werror -ansi -pedantic src/ls.cpp -o ./bin/ls
  8 cp:
  9     g++ -Wall -Werror -ansi -pedantic src/cp.cpp -o ./bin/cp
```

```
william@william-Inspiron-N5110:~/cs100/hw12/rshell$ make
[ ! -d bin] && mkdir bin
/bin/sh: 1: [: missing ]
make: *** [bin] Error 2
william@william-Inspiron-N5110:~/cs100/hw12/rshell$ 
```

**Comment by mikeizbicki** [comment]
You need a space between `bin` and `]`.  The `[` executable expects its last parameter to be `]`, but it's last parameter in your version is `bin]`.

**Comment by willccoates** [comment]
that worked! thank you
