### ISSUE TITLE
Grade checking

### ISSUE THREAD

**Issue by Anthony1234567** [mikeizbicki/ucr-cs100#814]
Im sorry but can you walk me through how to check the grades I think I missed that part of lecture and I cant seem to find anything with specific instructions.

**Comment by tristanzickovich** [comment]
1) ssh into hammer (csusername@hammer.cs.ucr.edu)
2) type: cs100 
3) a menu will pop up with instructions, for grade it is, type : calcgrade.sh

**Comment by Wurmie** [comment]
if your inside Well, then type: ssh -XCY username@hammer. 
if your not inside Well, then go to your terminal and ssh into Well with: ssh -XCY username@Well.cs.ucr.edu. Then ssh into hammer with the above command.

The problem I had was there was no ./calcgrade.sh command. The solution was to type: cs100 into the terminal and then type: calcgrade.sh (without your username)

PS. when ssh into well or hammer, they'll ask you for password. use the password that you log into cs computers with

**Comment by mikeizbicki** [comment]
You can ssh directly into hammer.  There is no need to go through well first.
