### ISSUE TITLE
do not delete your ucr-cs100 forks

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#823]
It looks like a couple people have been deleting your forks of `ucr-cs100`, then reforking this repository.  In the real world, you should NEVER do this because it causes a lot of disruptions.

For this class in particular, when you delete your `ucr-cs100` repo, you delete all the grades we have recorded for you.  From this point on, if you delete your repo, I will NOT reupload your grades.  That means you will get zeros on everything that has already been graded.

The most common reason for students wanting to delete and re-fork is to update your repo's history to include changes that have been made to the main repo (i.e. mine).  If you want to do this, then follow these instructions: https://github.com/mikeizbicki/ucr-cs100/blob/2015winter/textbook/tools/git/managingForkedRepo/README.md

**Comment by MiaoXiao** [comment]
thanks for this!
