### ISSUE TITLE
Hw0 and the ; || and && commands

### ISSUE THREAD

**Issue by jduga002** [mikeizbicki/ucr-cs100#827]
So I was testing some things out in the terminal and I noticed that typing a backslash before one of these symbols makes the terminal treat them like any other char rather than a command. For example, typing:
`echo hello || echo world`
outputs
`hello`
while typing
`echo hello \|\| echo world`
outputs
`hello || echo world`
Do we need to include this functionality in homework zero?

**Comment by mikeizbicki** [comment]
In bash (as in most programming languages) a backslash can be used to escape any special character.  You do not have to implement this feature.

(As an aside, use three backticks when you're putting code on a line of its own for better formatting:

```
echo hello
```

instead of
`echo hello`
)

**Comment by jduga002** [comment]
Okay, great! Thanks!
