### ISSUE TITLE
I cant push to github

### ISSUE THREAD

**Issue by oribix** [mikeizbicki/ucr-cs100#829]
I have been trying for a while now and I can't seem to figure out how to push to github. Whenever I run "git push origin master" I get a 403 error. Someone please tell me what I am doing wrong.

**Comment by tristanzickovich** [comment]
Check what branch you're on: git branch
Odds are you gotta use: git push origin 2015winter

**Comment by oribix** [comment]
I am doing the homework and pushing to my own repo.

**Comment by tristanzickovich** [comment]
http://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

check it out,  same problem

**Comment by oribix** [comment]
I switched it over to ssh://git@github.com/oribix/rshell.git  and it still did not work.

**Comment by busrac** [comment]
You can edit the configuration file

```
./git/config
```

which is under your repo directory. Change the url line to

```
url=https://your_github_username@github.com/your_github_username/your_repo.git
```

and enter your github password when prompted.

**Comment by hermance** [comment]
Hello,
I got the same issue.
With the ssh url (git@github...) it does : ssh: connect to host github.com port 22: Connection timed out
So I switched to the https:// ... and it does the 403 error.
This is for hw0. How should I do ?
Thanks!

**Comment by mikeizbicki** [comment]
@hermance Please post:
1. the contents of your `.git/config` file
2. the exact commands you are running
3. the exact error messages you are receiving

**Comment by hermance** [comment]
Here is my .git/config : 
[core]
  repositoryformatversion = 0
  filemode = true
  bare = false
  logallrefupdates = true
[remote "origin"]
  url = git@github.com:hermance/rshell.git
  fetch = +refs/heads/_:refs/remotes/origin/_

When I type : 
git push -u origin master

I have the output:
"ssh : connect to host github.com port 22: Connection timed out
fatal: The remote end hung up unexpectedly"

same output if i change the url to : ssh://git@github.com/hermance/rshell.git

If I switch the url in .git/config to : https://github.com/hermance/rshell.git

I have this output: "error: The requested URL returned error: 403 Forbidden while accessing https://github.com/hermance/rshell.git/info/refs

fatal: HTTP request failed"

Thanks

**Comment by mikeizbicki** [comment]
In the future, put your verbatim text within backticks to make it display correctly.

Your error is caused by not specifying your username in the `.git/config` file.  See the comment that @busrac left on how to do this.

**Comment by hermance** [comment]
Great, thanks.

**Comment by ghost** [comment]
I ran across the same problem and modified the contents of `.git/config` according to what @busrac has mentioned. I was not prompted to enter my github password. Instead I got the following

```
~/ucr-cs100/rshell
sbala003@hammer $ git push origin exec

(gnome-ssh-askpass:19451): Gtk-WARNING **: cannot open display: 
```

**Comment by mikeizbicki** [comment]
@sbala003 Please see: http://stackoverflow.com/questions/16077971/git-push-produces-gtk-warning
