### ISSUE TITLE
when is hw0 due?

### ISSUE THREAD

**Issue by oribix** [mikeizbicki/ucr-cs100#832]
I checked the repository and it says friday, but I want to make sure since the repository is being recycled.

**Comment by mikeizbicki** [comment]
Hw0 is due Friday at midnight.

**Comment by oribix** [comment]
11:59PM Friday or 12:00AM Friday?

**Comment by mikeizbicki** [comment]
11:59PM Friday

**Comment by oribix** [comment]
thanks
