### ISSUE TITLE
writing the shell

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#837]
How do I run the shell? Is the file a .cpp file if I choose to program in C++? Is there an int main(), or a void main()? How does a shell end?

Thank you for your time. I do plan to come to office hours on Wednesday.
After this, I'd like to ask about test cases too.

**Comment by mikeizbicki** [comment]
I don't understand your question.  `rshell` will be an executable just like any other.  You will compile it with `g++` and run it like normal.  Program execution will begin at the `main()` function and stop when you call the `exit` function.

**Comment by Fire3galaxy** [comment]
Thank you, I did overthink it.

**Comment by mikeizbicki** [comment]
Reopening to make it easier for other students with the same question to find.
