### ISSUE TITLE
C++11 Features

### ISSUE THREAD

**Issue by vgarc018** [mikeizbicki/ucr-cs100#838]
Are we allowed to use the C++11 Features described in our "textbook"? Since we do have to use the flag specified to activate the features, I wanted to make sure if we are allowed or not?

Thanks.

**Comment by mikeizbicki** [comment]
Yes.  You may pass whatever additional flags you want to g++ and use whatever features it supports.

**Comment by vgarc018** [comment]
Perfect Thanks!
