### ISSUE TITLE
How can we tell what a command returns?

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#841]
When we use `exec` or `execvp`, the command that we want to run "takes control" of our program, so unless it fails and `exec` returns -1, we have no idea what's happening. 

As far as I can tell, when I run `false`, it runs successfully, and I can't figure out for the life of me how to tell that the command itself is returning something other than 0, because `execvp` "takes control."

Is there something I'm missing here?

**Comment by mikeizbicki** [comment]
Good question!  You have to use the `wait` function to get this information.  I recommend reading the man pages and syscalls tutorial in the textbook folder.
