### ISSUE TITLE
How do I update my ucr-cs100 git repository?

### ISSUE THREAD

**Issue by plusEight** [mikeizbicki/ucr-cs100#843]
I tried using the method described here, to which it says my repository is already up to date.
https://help.github.com/articles/syncing-a-fork/

EDIT: resolved. Use
git pull https://github.com/mikeizbicki/ucr-cs100.git 2015winter

**Comment by mikeizbicki** [comment]
In the future, you should reply to the thread we were originally talking in or provide a link to that thread.  That way everyone else knows what's going on.
