### ISSUE TITLE
Clarification for hw0,

### ISSUE THREAD

**Issue by ikim025** [mikeizbicki/ucr-cs100#844]
Bascially, we need three files ( README, Makefile, and rshell.cpp ) for the hw 0 correct?
and we have to get rshell.cpp to do whatever the regular shell we use?
Sorry, I wasn't in class the other day and I am somewhat lost for this assignment.

Thank you.

**Comment by mikeizbicki** [comment]
Umm... The specs ask for more files than just those, and they do not require you to implement everything about a shell.  If you have more specific questions about the specs, I can answer in more detail.
