### ISSUE TITLE
Case where command ends in conditional

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#850]
What should we do in the case where a command ends in a condition (`&&` or `||`)?

Bash handles this by realizing the user is missing something and adding an additional prompt on the next line. Should we implement this or can we simply throw an error and not execute anything?

**Comment by mikeizbicki** [comment]
It's not in the specification.  That means I don't care how you handle it as long as it's reasonable.  Basically anything besides segfaulting is reasonable.  Whatever you choose, however, you must document it in the `README` file.
