### ISSUE TITLE
Formatting the makefile?

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#853]
I have no idea how to use a makefile when the .cpp is in another directory. I've tried to interpret the instructions on the hw0 README.md but I'm completely lost. Can I get some guidance please?

**Comment by scohe001** [comment]
Take a look at the make tutorial that's posted in the repo (https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/tools/Makefiles).

Replace something like `g++ main.cpp -o prgm` with `g++ src/main.cpp -o bin/prgm`. You're basically writing bash code, so it's just whatever you'd put if you were on the command line.

**HINT**
Remember that at the time they're running your make file, **there is no `bin` folder**

**Comment by jkinc002** [comment]
Thanks that helped.
