### ISSUE TITLE
Making the hw0 tag.

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#854]
It was a bit too brief in class for me to remember. And google is telling me probably 5 different ways I can do it. How SHOULD I do it for this assignment? I've already merged branches.

**Comment by mikeizbicki** [comment]
I'm not exactly sure what you're trying to do.  Maybe reading the man page on `git tag` will help?

**Comment by scohe001** [comment]
**edit by mikeizbicki**: the follow comment is incorrect

~~I'm pretty sure Mike wants us to make `hw0` a branch, not a tag. To make a new branch and put yourself in it, you can use:~~

```
git checkout -b "hw0"
```

~~Once you've created the `hw0` branch, to throw it up to github and the cloud, you can use:~~

```
git push -u origin hw0
```

~~(This is also what you should've done to initially put your master branch into the cloud)~~

**Comment by jkinc002** [comment]
thanks

**Comment by mikeizbicki** [comment]
**@scohe001's reply is incorrect.** You must create a `hw0` **tag** not a **branch**.  You create tags on commits whenever you "release" a version of your library.  Submitting your assignment is like creating a release.
