### ISSUE TITLE
bin/rshell? How can I get this to work?

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#855]
So the only thing left is to get the command bin/rshell to work, But I just can't figure out how I can make it work. Any tips?

**Comment by scohe001** [comment]
`bin/rshell` is just like doing `./rshell` except instead of being in the local directory, we have to go into `bin` to find your executable. Does this make sense?

**Comment by jkinc002** [comment]
So what do I need to do to emulate exactly what the TA's will be doing when testing my repo? do i clone the repo in my own /bin and do everything there?

**Comment by scohe001** [comment]
The way I did it was by going into `hammer` and running all of the commands (pulling down the repo, checking out `hw0`, calling make, and then running the executable)

The key is that when you pull down the repo and checkout `hw0`, there shouldn't be a `bin` directory. Your make file should create a `bin` directory and place the executable there.

**Comment by jkinc002** [comment]
How do you format a makefile to create  a directory AND place the executable there?

**Comment by scohe001** [comment]
A make file is just running bash code. How do you make a new directory in bash?

**ɹᴉpʞɯ :ɹǝʍsu∀**
