### ISSUE TITLE
About tagging hw0,

### ISSUE THREAD

**Issue by ikim025** [mikeizbicki/ucr-cs100#856]
I see that we have to tag hw0 in our respository as one of the issue stated.
What do we tag the hw0 as exactly?
because I tagged it as hw0 on it and when I download file from it directly
it says rshell-hw0.

Sorry if this is already answered in some way, I am just little lost. 

Thank you

**Comment by scohe001** [comment]
I had this same issue. Be sure your link has `https` instead of `http`

**Comment by mikeizbicki** [comment]
I'm sorry, but I don't understand your question.  You need to provide a lot more information for us to answer.  In particular, you will need to provide: 
1. the full commands that you are running
2. the full output
3. why you think the output is wrong
4. and what output you are expecting

**Comment by ikim025** [comment]
I found out what I was doing wrong. I was just trying out things because git clone was not working clearly.
my mistake was that Scohe said. I put http instead of https.
Sorry
