### ISSUE TITLE
Updating my forked ucr-cs100

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#888]
After syncing the forked ucr-cs100 repo on my computer and getting everything updated, I try to push the repo back to github but I get this error:

$ git push
Password:
Counting objects: 1092, done.
Delta compression using up to 48 threads.
fatal: unable to create thread: Resource temporarily unavailable
error: pack-objects died with strange error

Are there any suggestions on how to go about this?

**Comment by mikeizbicki** [comment]
Is this happening on hammer?

```
 fatal: unable to create thread: Resource temporarily unavailable
```

Means that you've exhausted some of the resource limits.  Maybe you have other programs running in the background, for example.  Try logging out, logging back in, and then running the commands.

**Comment by NisreenFarhoud** [comment]
This is happening through hammer. My cloned repo is in a directory on the hammer server. I have tried logging out and I am still getting the exact error.

**Comment by mikeizbicki** [comment]
Maybe you've used up all your allotted space in your home directory?  Then the "unavailable resource" is that it's trying to write to your home folder but is failing?

I've honestly never seen an error message that looks like this before.  Asking on stackoverflow might get you better answers.

**Comment by NisreenFarhoud** [comment]
It seems that I did run out of memory on the server, due to the repo having lots of large files, which caused the re-packing to take a lot of memory. These commands helped solve the problem for anyone that runs into the same error:
git config --global pack.windowMemory "100m"
git config --global pack.SizeLimit "100m"
git config --global pack.threads "1"

**Comment by mikeizbicki** [comment]
Good work finding the answer!

You can get 20 points of extra credit if you create a short little tutorial explaining the problem and how you fixed it.  You would put it in the `textbook/tools/git` folder with the others.  Don't feel like you have to do this if you don't have time though.
