### ISSUE TITLE
perror

### ISSUE THREAD

**Issue by kryne001** [mikeizbicki/ucr-cs100#89]
The way I implemented my exec function to work with any path is that I would call exec multiple times,  passing in every path that I have until the exec function executes. Obviously, if it doesn't work, exec will return -1, meaning I'd have to run perror. 

My problem is that when I run my program this way, exec will fail and print the error message after every failed call until it does work. Is it possible to get rid of the perror without getting points deducted (in order to avoid printing the error message multiple times), or should I just leave it as is?

**Comment by katherinegallaher** [comment]
You can just put the perror after the for loop you use to call execv so if execv fails for every path you call perror

**Comment by kryne001** [comment]
@katherinegallaher gracias
