### ISSUE TITLE
A major misunderstanding on hw0.

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#890]
After skimming through every option on how I got a 0/100 on hw0, I found that I completely misinterpreted how we were supposed to be handling the exec.script in our /tests directory. For my script I simply wrote  a list of different cases I tested, not at all recording the inputs and terminal response as I apparently was supposed to do. Is there ANY way I could configure my test script properly and demo it to somebody to recieve any kind of credit?

**Comment by mikeizbicki** [comment]
Come to my office hours on Tuesday and we'll work something out.

**Comment by jkinc002** [comment]
Will do.
