### ISSUE TITLE
lab 3, ls command

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#894]
When I think I find something and want to remake the ls binary file, do I 'make' then 'make install', or the other way?

**Comment by Fire3galaxy** [comment]
Also, if we config the make to send the files to a certain folder, does that stay when we ssh later, or do we need to set the path every time.

**Comment by mikeizbicki** [comment]
You never need to run `make install`; you only need to run `make`.
