### ISSUE TITLE
readdir syscall and perror

### ISSUE THREAD

**Issue by jduga002** [mikeizbicki/ucr-cs100#897]
The man page for `readdir` states that if an error occurs, then `readdir` returns `NULL`. However, it also states that if `readdir` reaches the end of the directory stream, then it also returns `NULL`. So how are we to know why it returned `NULL`, i.e. whether we should call `perror` or not? For example, in the sample `ls.cpp` file you gave us, you have the code

```
while ((direntp = readdir(dirp)))
    cout << direntp->d_name << endl;
```

This while loop will exit once readdir returns `NULL`. So how exactly can you tell if this `NULL` was returned because of an error or because it reached the end of the directory stream?

**Comment by mikeizbicki** [comment]
Good question (+3 pts extra credit) ! 

You have two options:
1. Use the alternative `readdir_r` function that has different return values.
2. The man page states that on failure and success, the value of the global variable `errno` will be different.  So you would check `errno` to see whether it succeeded or failed.
