### ISSUE TITLE
Later Office Hours?

### ISSUE THREAD

**Issue by nevarez-emil** [mikeizbicki/ucr-cs100#898]
Hi,

I don't get off of work until 5. Can you host a later session of office hours so I can show you stuff for points?

Thanks!

**Comment by busrac** [comment]
I can't make it after 5pm tomorrow, but if it's for lab3, you can demo after the lab on Monday.

**Comment by oribix** [comment]
what about connectors?

**Comment by mikeizbicki** [comment]
@oribix @eneva see #901
