### ISSUE TITLE
Returning char [] error?

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#90]
Hey guys,
Im having a hard time returning a char [] that'll be holding the directory i need to change to depending on the usr's input. I get a warning message labeled: 
warning: address of stack memory associated with local variable 'returncwd' returned [-Wreturn-stack-address]
   line 29 return (char*) returncwd;

I tried the two ways listed in line 29 below. Thank you

```
18 char *  getPath(string usrin)
 19 {
 20    char cwd[BUFSIZ] ;
 21    char returncwd[BUFSIZ];
 22    int lastslash = 0;
 23 
 24    if(getcwd(cwd, sizeof(cwd)) == 0)
 25    {
 26       perror("getcwd() error");
 27    }
 28 
 29    return returncwd; OR  return (char*) returncwd;
 30 }
```

**Comment by rgosh001** [comment]
Oh wait, I used static to allocate it's memory on the heap, but will that affect my program in any way (such as allocation of memory and possible segmentation faults?)

**Comment by mikeizbicki** [comment]
You did not use `static` anywhere, so I'm not sure what you're talking about.  You did allocate on the stack, however, and you can never return things allocated on the stack.  So you must allocate on the heap.  If you do that, however, you will almost certainly create a memory leak.

My recommendation is to not create a function like this, just use the `getcwd` directly in your code.
