### ISSUE TITLE
A way to cheat about grades?

### ISSUE THREAD

**Issue by Dongdongshe** [mikeizbicki/ucr-cs100#900]
Well, it is not a technical hack...It is just a little trick to grading policy.
I just found out that the grading policy is heavily based on test script we turn in. And I also find we can edit arbitrary any words in test case using VIM.....
Say, if I haven't finish one of tasks in hw0 (i.e the operator), I just edit test case file or add some works like user@host>> ls && ls
file1 file2 
file1 file2
then, it appers that I have finish operators task and get points. (I have finished this part on my own,so I haven't tested this trick, but will this work?)
So, I suggest that maybe grading policy should pay more attendtion to real exectution of our program, to write a script to run our program with some specific cases or something.

**Comment by mikeizbicki** [comment]
Nice thinking!  You could cheat on your homework assignment this way.  Technically, we could look at the log file on hammer to see if this happened or not, but that's not part of the standard grading procedure.  

But this is specifically not allowed in the same way that paying another student to complete the assignment for you is not allowed.  So this is not a way to get extra credit from "hacking" the grading system.
