### ISSUE TITLE
lab3 ex3 make && make install

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#902]
My partner and I have been encountering an error when trying to run Make for lab3.3. We followed the TA instructions and read the directions in the Install file.  We're able to fix the errors but unable to run Make to verify that the corrections. We've tried adding 

```
./configure --prefix=/home/csmajs/santo003/Desktop 
```

afterwards doing the commands 

```
make && make install
```

we encounter an error and cannot run the executables after we've changed the systems.h file and ls.c files. The error we get when making the file is in the attached screen shot:
![image](https://cloud.githubusercontent.com/assets/9372668/5985766/ca7324aa-a89b-11e4-9fc5-901e540be955.png)

**Comment by mikeizbicki** [comment]
You are not installing the program, so you do not need to run `make install`.  You only need to run `make`, which creates all the executables.

Edit: For future reference, it is much easier to read an error message if you copy and paste it into the textbox.
