### ISSUE TITLE
lab 3 "make to bin/executables"

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#903]
After configuring the file and running make, I keep getting the error below in its execution. I've already re-downloaded the zipcodes and ran them again in the terminal without changing the files to check if the issue was from changing the ls.c and system.h files but it still ends up like this.

gperf -m 10 ./lib/iconv_open-osf.gperf > ./lib/iconv_open-osf.h-t
/bin/sh: gperf: command not found
make: **\* [lib/iconv_open-osf.h] Error 127

**Comment by mikeizbicki** [comment]
Are you working on a lab computer or an hammer?  Those should have all the necessary programs installed.  If you're working on your own computer, then you need to install `gperf` like the error message says.

Also, you should put any commands in backticks:

```
gperf -m 10 ./lib/iconv_open-osf.gperf > ./lib/iconv_open-osf.h-t
/bin/sh: gperf: command not found
make: *** [lib/iconv_open-osf.h] Error 127
```

This makes it easier to read.

**Comment by mchu011** [comment]
I'm working on a lab computer in hammer, but I found out that the program doesn't get any errors when files aren't run in the general server
