### ISSUE TITLE
Accessing files on hammer

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#909]
Is there any way to access repositories that are saved on the hammer server while hammer currently isn't working? Hammer keeps giving the "ssh: connect to host hammer.cs.ucr.edu port 22: Operation timed out" error and while systems@cs.ucr.edu takes care of the problem, is there any way to work on files that are only on there such as my labs that I need to work on by tomorrows office hours?

**Comment by mikeizbicki** [comment]
All servers in the cs department use the same home folder.  So whatever was in your home folder on `hammer` will be there in `well` or any other server.
