### ISSUE TITLE
Assignment Due Tomorrow

### ISSUE THREAD

**Issue by rgosh001** [mikeizbicki/ucr-cs100#91]
Here are links to two of my videos produced. The second one has two errors in the audio i need to fix. Other than that, it is just a sample of the whole series we are going to produce.
https://www.youtube.com/watch?v=V5eSFwYpufs
https://www.youtube.com/watch?v=T0mdp6rMPnk

**Comment by mikeizbicki** [comment]
These are excellent!  I think these videos will be very helpful for future students.  I'm very impressed with how professionally done they are---the material is good, you are speaking very clearly throughout, and the videos are structured in a way that's easy to follow.  The only critique I have is that youtube is downgrading your video resolution, which makes the text appear fuzzy and hard to read.  This could be a problem for students trying to read the terminal commands you're typing in.  Maybe if you reduce your computer's resolution before starting the video, youtube won't have to downgrade the quality and everything will stay sharp.

Again, you've done an amazing job!

**Comment by rgosh001** [comment]
Thanks Mike!
Sadly, I've tried doing what you've recommended and these videos were uploaded to 4K quality to youtube and they were the best between 720, 1080, and 4K video quality. I've found that you can only watch it in HD for the quality to be crisp and clear. I'll see what else I can do since I have this week to improve and make the rest of the series.

**Comment by mikeizbicki** [comment]
Ahh... I didn't notice it had multiple resolutions.  Is there a way to make 1080p the default somehow?

**Comment by rgosh001** [comment]
Unfortunately youtube doesn't offer that setting but I can have a pop-up annotation that says to play in HD? That would be the best idea for our problem I presume.
