### ISSUE TITLE
Questions regarding the formating of ls

### ISSUE THREAD

**Issue by plusEight** [mikeizbicki/ucr-cs100#920]
What precisely is considered "easy to read"? Alphabetical order? Spaced formatting similar to the bash ls?

And with the recursive call of ls, -r, is listing everything in alphabetical order enough or do we need to format things by subfolders?

Lastly, it was mentioned in class that there were already libraries used for sorting the outputs of our files. Can anyone list a few?

**Comment by churslic** [comment]
It was mentioned in class that sort from the library algorithm can help alphabetize your files/directories.

**Comment by mikeizbicki** [comment]
> What precisely is considered "easy to read"? Alphabetical order? Spaced formatting similar to the bash ls?

I'm not sure exactly what your question is.  Things need to be in alphabetical order and formatted similar to GNU ls (there is no such thing as bash ls).

> And with the recursive call of ls, -r, is listing everything in alphabetical order enough or do we need to format things by subfolders?

Files need to be grouped into subfolders the same way GNU ls does.

**Comment by MichaelUy** [comment]
Hi plusEight.
this is your classmate MichaelUy627.
If you haven't done the formating part yet, Alex Allain (the creator of our beloved cprogramming.com) wrote a article on  Formatting Cout Output in C++ using iomanip. This guy is a hero, a CS hero.
LINK:
http://www.cprogramming.com/tutorial/iomanip.html
