### ISSUE TITLE
cppcheck script

### ISSUE THREAD

**Issue by SpaceCowboy100** [mikeizbicki/ucr-cs100#921]
@mikeizbicki 
Could you upload the script from Wednesday that went over how to use cppcheck? The only examples from the lectures folder go over Valgrind.

**Comment by svtanthony** [comment]
Run cppcheck and pass the name your cpp file as an argument. Ie. "cppcheck
ls.cpp"

**Comment by mikeizbicki** [comment]
Lecture notes updated, but @svtanthony's answer is also correct.
