### ISSUE TITLE
Valgrind Memory Leak Check

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#922]
In class it was said that to not have points deducted for memory leaks, after running Valgrind we must not have any memory leaks / bytes lost (as well as cppcheck). 

When I run Valgrind on my code, I get <i>"no leaks are possible"</i>, however it gives me some errors.  This is the output Valgrind gives me:

<pre>
        </code>tzick002@cs100:~/Documents/rshell (ls) $ valgrind bin/ls -a
==18627== Memcheck, a memory error detector
==18627== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==18627== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==18627== Command: bin/ls -a
==18627== 
==18627== Mismatched free() / delete / delete []
==18627==    at 0x4A06016: operator delete(void*) (vg_replace_malloc.c:480)
==18627==    by 0x401A2E: printa(char const*, bool) (ls.cpp:96)
==18627==    by 0x404963: main (ls.cpp:676)
==18627==  Address 0x4c330b0 is 0 bytes inside a block of size 2 alloc'd
==18627==    at 0x4A07192: operator new[](unsigned long) (vg_replace_malloc.c:363)
==18627==    by 0x401771: alporder(char const*) (ls.cpp:55)
==18627==    by 0x401853: printa(char const*, bool) (ls.cpp:68)
==18627==    by 0x404963: main (ls.cpp:676)
==18627== 
./  ../  .git/  bin/  LICENSE  Makefile  README.md  src/  tests/  
==18627== 
==18627== HEAP SUMMARY:
==18627==     in use at exit: 0 bytes in 0 blocks
==18627==   total heap usage: 57 allocs, 57 frees, 34,340 bytes allocated
==18627== 
==18627== All heap blocks were freed -- no leaks are possible
==18627== 
==18627== For counts of detected and suppressed errors, rerun with: -v
==18627== ERROR SUMMARY: 9 errors from 1 contexts (suppressed: 6 from 6)
</code>
    </pre>

Will points be deducted for this? This may possibly be happening because I allocate memory in one function call, and delete it in another in order to preserve that data until I can use it.

**Comment by tristanzickovich** [comment]
Fixed: I was forgetting the " [] " after delete's for my char \* 's.

**Comment by mikeizbicki** [comment]
Errors like this would have resulted in points being deducted.

**Comment by monti004** [comment]
how many points would have been deducted per error found in the error summary?
