### ISSUE TITLE
issue with git push

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#925]
I am unable to submit my work due to the error below. How do I fix this? 

mchu011@hammer $ git push -u origin master
Password: 
error: The requested URL returned error: 403 Forbidden while accessing https://mchu011@github.com/mch011/rshell/info/refs

fatal: HTTP request failed

**Comment by mikeizbicki** [comment]
Somehow you don't have your permissions configured correctly or you are using an outdated version of git.  It is possible that you're not using the `cs100` environment, but you haven't given us enough information to tell (based on your prompt, that's what it looks like).  You must fix this problem before the deadline.

Also, in the future, please put code within backticks.

**Comment by admiralakbar** [comment]
Did you ever figure it out? I'm having the same problem.

**Comment by mchu011** [comment]
solved it:
-first double check if both usernames of the url line are typed correctly
-git pull
-git push origin master
