### ISSUE TITLE
Sorting ls output

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#928]
When sorting the files to list, does it matter if everything preceded by a `'.'` (hidden files) are listed alphabetically in their own right before all of the other files? 

e.g.

``` bash
$ bin/ls -a  # my ls
. .. .a .b .c a b c
$ ls -a  # GNU ls
. .. a .a b .b c .c
```

**Comment by mikeizbicki** [comment]
Either way is fine.
