### ISSUE TITLE
A possible project for hw4

### ISSUE THREAD

**Issue by mikeizbicki** [mikeizbicki/ucr-cs100#930]
The scripts in the [gitlearn](https://github.com/mikeizbicki/gitlearn) repo provide a "class management system" similar to ilearn.  In fact, gitlearn supports tons of features that ilearn does not.  The only problem is that gitlearn doesn't have an easy to use interface.  The proposed project is to improve gitlearn to provide this interface (or alternatively any other features you think would be useful).

Last quarter, a number of students built a webserver out of bash commands called [rapache](https://github.com/mikeizbicki/rapache).  You would use this webserver to provide a simple web interface for students to view grades, submit assignments, and instructors to grade assignments.  This will require you to learn a lot of material that we're not directly covering in class, but it's a good opportunity for you to develop code that will actually have real users.

If you're interested in this project, you'll need to talk to me in person about it.

**Comment by jduga002** [comment]
I was thinking about writing a tutorial about template metaprogramming in C++, but this looks interesting. Can I talk with you about this after class tomorrow?

**Comment by mikeizbicki** [comment]
@jduga002 Sure.
