### ISSUE TITLE
HW4 Topic

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#931]
I am willing and able to create a system to replace the current script test-case submission setup. It will be just as easy and more feature-packed as the script system. Furthermore, I'd like to complete it ASAP so I can have others use it.
### Features
- students will create a text file with just their test commands inside
- they can "play" the commands with a provided interface (to run through them and see if they work)
- graders will use the same interface to step through and replay the commands. This eliminates the need to purely rely on past output on quite possibly another system (I think scripts will no longer be needed, personally)
- parameters I'm thinking of to correspond to the features:
  1. delay between running through commands
  2. manual step-through option
  3. executable path
  4. replay file path
  5. generate script option

Do you think this would be sufficient for HW4? Also, are there any more features you think it should contain? 

Thank you,
-Michael Evans

**Comment by mikeizbicki** [comment]
Sounds good.  If you can get a draft of the system ready a week before `hw3` is due, then we could potentially have some students this quarter try it out.

**Comment by M-Evans** [comment]
Where would you like me to put the project? Pull request to gitlearn? My own repo?

**Comment by mikeizbicki** [comment]
I don't really care.  Your own repo sounds best to me, unless you can think
of a reason to put it somewhere else.

**Comment by M-Evans** [comment]
Sweet. I'll put it in my own repo.
