### ISSUE TITLE
HW4 Topic Proposal

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#932]
I would like to research and make a tutorial covering "<i>smart pointers</i>" from the Boost library. 

My tutorial would focus more on the commonly used (and more applicable to programmers at our level) smart pointers; from light research these seem to include scoped_ptr and shared_ptr, and possibly scoped and shared _array. The others would be mentioned and lightly described, with  alternate sources provided for more in depth information.

Memory Management is important, and not always easy to accomplish under certain circumstances.  This would be of use to future students (or anyone seeking an easy to comprehend tutorial on basic smart pointers), considering memory leaks heavily affect one's assignment grade. My tutorial would include:
- an explanation of the pointers use: when to use and what it does
- purpose: how it helps the programmer
- a commentated code example

In the brief research I have done so far, most of the tutorials have been dry.  I would try to make it simple to understand and easy/fun to read.

Would this be sufficient for my HW 4 project?
- Tristan

**Comment by mikeizbicki** [comment]
Sounds great!  What would your code example be of?

**Comment by tristanzickovich** [comment]
The code examples would show how to properly declare these pointers and a basic instance of implementation, showing when they can be used and providing proof that these smart pointers do actually manage their "delete's" as intended.

**Comment by mikeizbicki** [comment]
That's what the example _teaches_, but what is the _subject_ of the example?  Are you making an AVL tree?  Are you implementing the `ls` program?

**Comment by tristanzickovich** [comment]
Oh I see.  I'd like to make the example a linked list.
