### ISSUE TITLE
Hw 4 idea

### ISSUE THREAD

**Issue by mchu011** [mikeizbicki/ucr-cs100#935]
I would like to create some videos for this homework. So far I have these three video ideas in mind:
- documentation that provides a visual display on how forks are processed in coding
- documentation on the issues/errors with git push
- an abridged music video on the either one of the two topics above or the coding process/concept of stacks or some other code procedure (tentative humor attempt)

Is it okay for me to do more than one video, because I know that if I choose just one of these ideas, my draft write up won't meet the requirement of 1000 - 2000 words.

**Comment by mikeizbicki** [comment]
Yes, a video project would require multiple videos.  It would be best, however, if all the videos followed some particular theme.  Your submission would be to add the videos to the [/videos folder](https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/videos).  You can look there for a few examples.

I would prefer a video on concepts covered in this course than on stacks.  As for the other two video ideas, how would your video be different than the ones that have already been made for this class?

**Comment by mchu011** [comment]
I would first give a brief description of the video's topic and then show a sample a code and have a drawn animation of a car on a road that would drive off a cliff, crash into something, or proceed normally depending on whether the code is good or not and then fix the problems one piece at a time until the code runs correctly.

Is it okay if I include a friend to help me out with the narration?

**Comment by mikeizbicki** [comment]
There's already two videos for the `fork()` command, and you didn't point out anything that they are lacking, so I don't want you to do that topic.  It's definitely okay to get anyone else to help out.  If they are in the class and using that as their hw4 topic, then you'd have to create a few more videos.

Please think of some new topics that are related by a common theme.

**Comment by mchu011** [comment]
Then I'll do the videos on implementing the getinfos and the read and write system calls

**Comment by mikeizbicki** [comment]
It should probably be a single video covering `read`,`write`,`open` and
`close` all together.  I'm not sure what you mean by the getinfos syscall.

**Comment by mchu011** [comment]
For the getinfos I meant the getcwd, getpwuid, and getgrid
