### ISSUE TITLE
HW 4 Idea

### ISSUE THREAD

**Issue by Fire3galaxy** [mikeizbicki/ucr-cs100#939]
Syscall cheat sheet document for CS100 users

or (my preferred idea) a doc for surviving cs100 as a java (or ruby) programmer

My preferred idea is ruby because I would like an excuse to go back to learning ruby but java is likely more applicable to other students. Also, java likely has the debugger tools and is more relevant to more people than ruby.

**Comment by mikeizbicki** [comment]
The syscall cheatsheet has potential, but how would it be different than the syscall tutorial that already exists?

I don't understand what you mean by a doc for surviving cs100 as a java programmer?  All cs100 students are required to have a year of C++ classes before taking cs100, so who would benefit from this?

**Comment by Fire3galaxy** [comment]
The syscall cheat sheet would compile all of the include statements, parameters, and 1 sentence description.

I've met with people who code on other languages and other colleges don't always use c++. The survival doc would help transfer students and students who are interested in developing skill in a new language. It would include equivalent syscall commands, debuggers, and ways to execute these files to produce a similar result to the equivalent c++ program.

**Comment by mikeizbicki** [comment]
I'll approve the syscall cheatsheet.  I don't like the idea of the cross-language tutorial though.
