### ISSUE TITLE
vim adventures people!

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#94]
![screenshot from 2014-08-25 19 05 35](https://cloud.githubusercontent.com/assets/8251970/4039183/8fa1cd88-2cc5-11e4-9cb7-2523a6d4ecfe.png)
does anyone know how to add in the tt???

**Comment by katherinegallaher** [comment]
copy a t and then do '2p' and it'll paste it twice

**Comment by willccoates** [comment]
thanks! i was tryingsomething like that and just couldnt get it lol

**Comment by willccoates** [comment]
im stuck on the beginning of level 11, but i read that you can switch buffers from the air to the ground, what command will do this?
thank you!

**Comment by lwang031** [comment]
ls    ( to see different buffers)
:b sky/ground

**Comment by willccoates** [comment]
![screenshot from 2014-08-27 20 12 05](https://cloud.githubusercontent.com/assets/8251970/4070665/20fb0ba4-2e61-11e4-9789-cfb5ab5b7c65.png)
anyone know how? i cant think of anything lol

**Comment by willccoates** [comment]
never mind just user ( and ) :p

**Comment by willccoates** [comment]
sorry to keep buggin everyone but this part is confusing me
![screenshot from 2014-08-27 21 41 15](https://cloud.githubusercontent.com/assets/8251970/4071294/1ce950ae-2e6e-11e4-8366-196b78f6afad.png)
