### ISSUE TITLE
HW4 Topic Proposal

### ISSUE THREAD

**Issue by vgarc018** [mikeizbicki/ucr-cs100#941]
I know I spoke to you about trying to do the server user interface today, but I also want to have a backup project. I would like to do a Boost Library Tokenizer tutorial covering the main ideas on how to use the tokenizer and what you need to include in order to make it work. I ran into a couple bugs during hw0 because of not including specific things that the documentation online for the boost library does not go much into detail.

Please let me know your input.

Thanks,

**Comment by mikeizbicki** [comment]
You shouldn't have a "backup" project.  You should commit completely to one project, whichever you think will be more fun.
