### ISSUE TITLE
HW4 topic

### ISSUE THREAD

**Issue by SpaceCowboy100** [mikeizbicki/ucr-cs100#942]
For hw4 I'd like to make a reference/guide on how to make a proper Makefile. Prior to CS100 i've always been compiling my programs with something like `g++ whatever.cpp -o whatever`. Im sure that this might be the first class in which cs students are using makefiles and a tutorial on this topic will make the lives of future CS100 students easier. 

Team members:
Jonathan Candelaria - solo

**Comment by mikeizbicki** [comment]
There is already a tutorial on Makefiles here: https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/tools/Makefiles.  There's a lot of improvement to be done on this tutorial though.  In particular: the tutorial is excessively terse, it covers too many concepts in each example, the examples don't relate well to the homeworks, and there's no cheatsheet summarizing everything.  Fixing these aspects of the tutorial would be a good project.

This might mean starting completely from scratch and using the material in that tutorial as a guide, or it might mean extending what's already written.  That would be up to you.

How does that sound?

**Comment by mikeizbicki** [comment]
Alternatively, there is a program called Autoconf that generates makefiles automatically.  A tutorial on how to use this tool to generate makefiles for the homework assignments might be nice.

**Comment by SpaceCowboy100** [comment]
I'm not familiar with Autoconf so I don't think I would be able to make a tutorial on that. I'd prefer to start from scratch by making a short, consise tutorial as well as a cheatsheet that summarizes the concepts and relating it to the homework submissions as much as possible.

**Comment by mikeizbicki** [comment]
It's fine to start from scratch, but your tutorial would have to be a
complete replacement of the previous one.  That is, I would be deleting the
previous one and replacing it with yours.  So you would have to include all
the information from the previous one, plus the things I mentioned above.

**Comment by SpaceCowboy100** [comment]
That sounds great! I'm up for the challenge
