### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by yliu075** [mikeizbicki/ucr-cs100#944]
I would like to make animated GIFs for the syscalls. Each syscall GIF will include a step by step walkthrough of what it does and how to use it. The GIFs will probably be added to: https://github.com/mikeizbicki/ucr-cs100/blob/2015winter/textbook/assignment-help/syscalls/README.md , under the description of each syscalls.

**Comment by mikeizbicki** [comment]
I'm having trouble imagining how this would work.  How would you explain the syscall without any audio?

**Comment by yliu075** [comment]
For example, for the fork() syscall the first frame would be something like:

```
pid_t fork()
```

second frame:

```
Return Values:
The pid of the child process is returned in the parent process and 0 is returned in the child.
On failure, -1 is returned in the parent process.
```

The remaining frames I would step through a graphical representation of the fork() call:

```
[Parent Process]
pid_t pid = fork()

[Parent Process pid = (pid of child process)]   [Child Process pid = 0]
```

The part where it step through the program would have arrows pointing and comments at the bottom, and it would span a couple of frames.

**Comment by mikeizbicki** [comment]
If I'm understanding correctly, then your idea is to take a bunch of text and convert it into a gif format.  This is a really bad idea because: text is easy to manipulate and read, gifs are not; I can easily scroll through text to get to the location I want, I can't scroll through gifs; I can version control text with git, but I can't version control gifs ...

**Comment by yliu075** [comment]
Can I change my idea to writing a tutorial on libraries? For this I would list the commonly used libraries for this class. They would each have a section with a basic description of the library and a section on some of the commonly used function of the library.

**Comment by mikeizbicki** [comment]
Pick one library and write about that.  It's always better to do one thing well than to do lots of things mediocre.

**Comment by yliu075** [comment]
I'm going to choose `dirent.h`. I give a description of the `dirent.h`, talk about `struct dirent`, and a description for each of the functions: `opendir`, `readdir`, etc.

**Comment by mikeizbicki** [comment]
Lila has already claimed this topic with issue #955, so you'll have to pick a different one.

**Comment by yliu075** [comment]
I will choose `time.h`, it will be in the same format as described above.

**Comment by mikeizbicki** [comment]
Sounds good.  Just as a warning, time is very tricky.  You should watch the video linked in #914.  I would expect your writeup to cover at least some of these edge cases.
