### ISSUE TITLE
0 on ls assignment

### ISSUE THREAD

**Issue by MiaoXiao** [mikeizbicki/ucr-cs100#945]
I just checked my grade, and I received a 0/100 on the ls assignment. On my grades branch, there were errors with Make.

```
0 / 100

$ make
mkdir -p ./bin
g++ -Wall -Werror -ansi -pedantic ./src/ls.cpp -o ./bin/ls
./src/ls.cpp: In function ‘void displayls(std::vector<std::basic_string<char> >, std::vector<bool>, std::string, std::stack<std::basic_string<char> >&)’:
./src/ls.cpp:114:22: error: the address of ‘userinfo’ will never be NULL [-Werror=address]
./src/ls.cpp:123:23: error: the address of ‘groupinfo’ will never be NULL [-Werror=address]
cc1plus: all warnings being treated as errors
make: *** [ls] Error 1
```

I reran the submission commands again on the lab computers, but I did not receive any errors whatsoever when I ran make. What exactly happened? I submitted before midnight on Sunday.

EDIT: Tomorrow when I can head into the labs, I will post proof that that my source code compiles and runs successfully on the lab computers in the cs100 environment. Sorry that I'm unable to provide proof now.

**Comment by ghost** [comment]
Please come to my office hours so we can resolve this. It's probably due to version differences in GCC.
