### ISSUE TITLE
HW4 - possible topic

### ISSUE THREAD

**Issue by jinhangwang** [mikeizbicki/ucr-cs100#948]
We would like to make up to git cheatsheet or make a tutorial for how to write tutorial.

git cheatsheet:
Develop Brunna Amorim's git cheatsheet to a form in pdf file

tutorial for tutorial:
Tutorial with only text words are boring to read. We found the previous cs100 students had added pictures, tables, links and videos in README.md. We want to give an abstract list with examples on how to implement such things.

collaborate: 
Yuqi Liu ( yliu127 )

**Comment by mikeizbicki** [comment]
I actually prefer the markdown file format to using latex to generate a pdf.  It's easier to edit mistakes and add new information.

I think the tutorial for writing tutorials would be too hard to do.  In general, you have to be a very skilled and experienced writer to give advice to others on how to write, and I doubt that you are both at that level yet.  Also, one of the best ways to do this is by example.  So make you're writeup a great example of easy-to-understand writing.

I want you to try to come up with a new idea.

**Comment by jinhangwang** [comment]
We come up with a new idea of writing a tutorial for git rebasing and git patch.
For git rebasing,  we will introduce the basic usage of rebasing as well as interactive rebasing.
For git patch, we will introduce the usage of 'git diff patch' and 'git format patch' and their differences.

**Comment by mikeizbicki** [comment]
Sounds good.  Since there are two of you, I would expect something pretty polished.  I recommend using a format similar to the git lab.
