### ISSUE TITLE
HW4 Idea

### ISSUE THREAD

**Issue by oribix** [mikeizbicki/ucr-cs100#949]
I want to make written tutorials detailing the Standard template library. I found that understanding the containers helped me a lot in hw0 and hw1. This is likely going to end up being a tutorial that basically reviews the content covered in CS14 plus some, but will show how to actually use these things. I hope to provide practical examples and maybe even (with your permission) give hints on where to use these things in the homeworks. I wont be doing only containers of course. I will probably go into how to use some algoritithms and maybe get into some uncomfortable areas. I hope that by doing this, I will become more proficient in using the STL and help others gain proficiency.

**Comment by mikeizbicki** [comment]
Which containers would you cover, and how would they tie in with specific homeworks?

**Comment by oribix** [comment]
I want to cover as many of them as possible (if not all). I found that queues were helpful for implementing the ';' connector.  Lists also helped me out with hw1 by giving me a way to hold the filenames and alphabetize them. I may also branch off into algorithms if I feel I need to contribute more.

**Comment by mikeizbicki** [comment]
I want a specific list of about 5 containers before I approve this.  I would particularly encourage you to talk about how to use a `map` with keys as `strings` and values as function pointers (something we'll be covering in the next 2 weeks) to implement the special built-in commands like `exit`,`cd`,`fg`,etc.

**Comment by scohe001** [comment]
Don't forget using a set to hold flags!

**Comment by mikeizbicki** [comment]
@scohe001 Using a set to hold flags is actually very inefficient.  The syscalls all use an `int` to hold flags because it is the best solution.

**Comment by oribix** [comment]
I'll probably go with the vector, queue, stack, map and list containers unless there are other containers you think or more worthwhile going through. I especially think that everyone should learn how to use vectors, queues, lists and maybe a few others because they are much simpler to use than arrays.

**Comment by mikeizbicki** [comment]
It is extremely rare that you want to use lists instead of vectors in c++.
Also, how specifically are you going to tie in each of those data
structures to the assignments?

**Comment by oribix** [comment]
vectors were very useful when trying to create the argv by making a vector of char*. I could then use the data() member function to make it usable in exec sys call. Queue was useful for the semicolon connector by allowing me to store a queue of commands. list was useful for ls, because it allowed me to alphabetize the filenames easily (you can insert anywhere in the list and, until you have a working alphabetizing algorithm, sort() is there to weakly sort the list for the meanwhile). I will take your word for map and find a way to make it useful for those commands. I don't know how I can tie stack into the homeworks so I may need your help to choose a different container there. I may look for a use for stack if you think it has potential somewhere. Another  container I think has potential is deque, but like stack, I have no idea where it can be used (off the top of my head at least). Do you mind if i discuss this with you after class if we can't find a good plan?
