### ISSUE TITLE
Office hours tomorrow

### ISSUE THREAD

**Issue by willccoates** [mikeizbicki/ucr-cs100#95]
Bryan are you have office hours at 10 tomorrow? Or mike are you having any?

**Comment by bmars003** [comment]
Sorry for responding so late, but I am unable to have OH tomorrow morning at 10 AM definitively since I  have to take my car into the mechanics. Is there anything in particular I can help you with?

**Comment by willccoates** [comment]
No worries Bryan and no it's cool, thank you tho
