### ISSUE TITLE
HW 4 Topic

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/ucr-cs100#950]
https://docs.google.com/a/ucr.edu/document/d/1yggAijn3GJRiOkwBxjys95-ysCN0_3QfG-_NbCBKiLQ/edit

If this is approved we will put this information in a README on a github repo.

Team Members: Sherina Bala, Rica Feng :D

**Comment by mikeizbicki** [comment]
This sounds fun, and is a great idea!

It's okay to do this as a terminal application, but I'm honestly not sure how popular it will be.  It seems like most people who want to learn to recognize musical scales wouldn't know enough about the terminal environment to download and install this game.  If you make it as a website, though, I think it could be amazingly popular.  You could probably even get the music department to use it in classes.  You would need to use HTML, CSS, and JavaScript to make this happen.  This sounds like a great sort of project to learn these languages.

I'll approve this project either way you want to do it.  By the next deadline, I'll want a very basic prototype done that at least makes sounds and shows the interface.  If you have any questions, please let me know.

**Comment by scohe001** [comment]
I was looking through the hw4 ideas and this one struck me as really really cool and feasable.

If you guys are thinking of expanding this to a web interface and you need some more man power, I'm still looking for a project! (I have a strong background in music, Python and Java)

**Comment by MiaoXiao** [comment]
@scohe001 Hey if you are still interested we could use the extra help for expanding  this project to a web interface. We can try talking before/after class.

@mikeizbicki If we expand this to a web interface, would this project be large enough for 3 people to work on?

**Comment by mikeizbicki** [comment]
Yes, this would be a good project for three people.

**Comment by scohe001** [comment]
@MiaoXiao I'd love to! I'll look for you guys after class.
