### ISSUE TITLE
Hw-4 Sustainable Tech Project

### ISSUE THREAD

**Issue by MichaelUy** [mikeizbicki/ucr-cs100#951]
Alternative food production systems are beginning to catch on as a hobby for gardeners and as a potential method of profitably utilizing sustainable technology. http://en.wikipedia.org/wiki/Aquaponics

I would like to create an open-source project to research and develop a DIY aquaponics system including sensors for water analytics. 

This project will consist of designs and guide on how to:
- understand how an aquaponics system works and how might you go about on making one 
- construct electro-conductivity sensors  which determine the percentage of dissolved salt in water  over time
- install the sensors into a system using an arduino, raspberry pi or something similar
  (stretch goals)
-  access the data wirelessly and automate notifications by email or text
  -give our system a twitter account

I hope projects like this will begin to ford the way toward more accessible more reliable farming which is more data-oriented and semi-automated. Maybe in the future low cost systems like these could find their place in developing countries or in urban/suburban food deserts in our own. 

This system will focus on gathering data and automation of warnings and notifications, but will not include automation of system maintenance. Hopefully our efforts may be utilized as a platform for those endeavors.  

If we manage to get the reading to a arduino/ I’m planning on sending the readings from the sensors to a server which will inform and update you on the status of your aquaponic food production system. This will be especially useful in the initial setup phase where the chemical makeup of the water is the least stable and fish fatality is a problem

TEAM:
Michael Uy muy003(leader) 
Ping Fan cfan002
Leo Li  raveoli22

**Comment by mikeizbicki** [comment]
This has potential to be amazing, but I'll need to talk with you all in person to clarify a few points before I approve it.  Can you meet with me right after class?

**Comment by MichaelUy** [comment]
i missed class. I'll come to your office hours on Tuesday though.
