### ISSUE TITLE
HW4 Topic

### ISSUE THREAD

**Issue by ahvino** [mikeizbicki/ucr-cs100#953]
I'd like to do  video tutorial of using debugging tools (gdb, cppcheck, valgrind). I would have two terminals running the same program side by side and would demonstrate the strengths of using these tools on one of the terminals.
- gdb video
- cppcheck video
- valgrind video
  I'd discuss the various benefits for each tool as well.

**Comment by mikeizbicki** [comment]
Sounds great!  For the next deadline I'll want to see (approximately) one video fully complete, and that you've made some progress on the code and scripts for the other examples.
