### ISSUE TITLE
HW4 Topic,

### ISSUE THREAD

**Issue by ikim025** [mikeizbicki/ucr-cs100#954]
I really would like to make a video of using fork, execvp, and waipid.
I realized previous students and current students had hard time for the hw0 and as we saw the statistics, grades were really low. For future students, I really would like to understand how to use these system calls for easier hw0 assignment. In addition, I would like to add more to the video if I can. I really would like to add system calls from hw1 as well.

**Comment by mikeizbicki** [comment]
There are already two videos on using these syscalls.  How would your video be different?

I'm more likely to approve videos related to syscalls in the later homework assignments, or some aspect of the first homeworks other than syscalls.

**Comment by ikim025** [comment]
Would it be possible for me to make videos of system calls from the later homework assignments?

**Comment by mikeizbicki** [comment]
Definitely!  I won't make you select which ones right now, but by the next deadline I'll expect that you've selected the syscalls and have a good script for your video.

**Comment by shinray** [comment]
hi, i'd like to work together with ian on this one
