### ISSUE TITLE
Hw 4 Topic

### ISSUE THREAD

**Issue by NisreenFarhoud** [mikeizbicki/ucr-cs100#957]
For my topic I will create a bash shell cheatsheet that covers topics such as:
-navigation (such as pwd, cd, etc.)
-manipulating files (such as mv, rm, mkdir, etc.)
-I/O redirection (such as pipes, etc.)
-info about directories and how to use them (such as /bin, etc.)
-permissions (files, how to change permissions, etc.)

This will be a nice clean place for everyone to go to and find how different commands in the BASH shell work and are used.

Team: Nisreen Farhoud

**Comment by mikeizbicki** [comment]
This sounds amazing!  There are two things I want you to pay particular attention to:  
1.  Which features are provided by bash, and which features are provided by other utilities.  For example, `ls` is a stand alone utility, but `cd` is built-in to bash.
2. How portable are all the commands?  There is a standard called POSIX that defines what a unix terminal should support.  Bash supports everything in the POSIX standard plus some additional features.  Furthermore, MacOS and Linux agree on everything in the POSIX standard, but implement different features outside the standard.
