### ISSUE TITLE
HW4 Topic

### ISSUE THREAD

**Issue by Wurmie** [mikeizbicki/ucr-cs100#958]
I have seen a trend among engineeres that alot of us lack proper grammar and english. I would like to make a game( have not thought about which kind of game that would be interseting, but i would assume its something along the lines of shark attack). It would have one part on grammar and another part on proper word usage.

**Comment by Origami-Killer** [comment]
This sounds like a cool idea, but if you're going to make a game designed to improve engineering grammar and English skills, you should probably spell engineers and interesting correctly.

**Comment by mikeizbicki** [comment]
You'll need to flesh this out a lot more before I can approve it.  My initial impression is: I suspect this will be both too much to implement in our time frame and something that people won't want to play.  Although if you explain it in more detail I might change my mind.
