### ISSUE TITLE
Hw 4 topic

### ISSUE THREAD

**Issue by churslic** [mikeizbicki/ucr-cs100#959]
We'd like to do a tutorial on the boost tokenizer library and we were also thinking of tutorials on string related functions (from the string library and/or string.h) as well as c++11 features.

I'm working with Virgilio Garcia, vgarc018.

**Comment by mikeizbicki** [comment]
Sounds good.  Your tokenizer tutorial should follow (as much as possible) the same format as the strtok tutorial that already exists, and you should cover strings and c++ features only by showing how they're useful to make tokenizing easier.
