### ISSUE TITLE
signal handling

### ISSUE THREAD

**Issue by kryne001** [mikeizbicki/ucr-cs100#96]
I don't get how the signal handling is supposed to work. I have a function to catch the `^C` signal but it just kills the program.

**Comment by bmars003** [comment]
Try taking another look at Lab 6: Signal Handling.

**Comment by kryne001** [comment]
that's exactly what I did but idk I don't really see how it's not working. I thought if I catch the signal, I go into a function that kills the process but I doubt that's what should be happening.

**Comment by bmars003** [comment]
You seem to be on the right track. It then comes down to what does the function that gets called doing by catching the interrupt doing.

**Comment by kryne001** [comment]
I just don't get how I'm supposed to restart rshell, seeing how my rshell runs in an infinite loop. I tried putting `continue` in my function, but obviously that won't work because `continue` is in a function separate of the loop

**Comment by bmars003** [comment]
huh? Why would you need to restart rshell?

**Comment by kryne001** [comment]
isn't cntl+c supposed to reset the command line in rshell? instead of stopping the program altogether?

**Comment by bmars003** [comment]
No, 
per the specs.
The shell should not exit when the user types `^C`. Instead, the current foreground job should interrupt.

What this means is when `^C` is pressed you need to have your rshell send the appropriate signal to the current foreground process.

**Comment by kryne001** [comment]
How would I interrupt the current foreground project? I'm trying to google a way to do it, can't find anything so far.

**Comment by mikeizbicki** [comment]
One easy way to do it is run `kill` on the child process.
