### ISSUE TITLE
hw4 topic

### ISSUE THREAD

**Issue by monti004** [mikeizbicki/ucr-cs100#960]
I wanted to make a written tutorial and how to dual boot your windows pc and ubuntu and how to solve possible error messages you may encounter with git(such as pull, push, clone, bad index errors, etc), also how to use the ubuntu terminal(such as coping files, renaming files, downloading and removing programs).

**Comment by mikeizbicki** [comment]
First, you're covering way too much material.  There are literally dozens of books on each of those topics.  It is much better to go into detail on one thing than to be shallow on many things.

Second, I don't want a tutorial about specific linux distributions.  Those distributions already have plenty of tutorials and documentation, so your writeup won't be contributing anything.

It would be possible to write about git, but you'll have to look at the git tutorials that students have already written and tell me _very specifically_ what you will do different.

**Comment by monti004** [comment]
would making a tutorial on how to make a website on your own domain be ok?

**Comment by mikeizbicki** [comment]
No.  This would be vender specific, and those venders already have
tutorials.

**Comment by monti004** [comment]
im not sure if there is already a tutorial on macros... if not i would like to make a written tutorial about using macros, why they are useful, and give some examples of how to implement them

**Comment by mikeizbicki** [comment]
This tutorial already exists:
https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/assignment-help/macros
(and was required reading :) )

**Comment by monti004** [comment]
Im really stuck on finding something to do for hw 4... can you recommend something for a one person team?

**Comment by mikeizbicki** [comment]
There are lots of aspects of shell scripting/using the terminal that aren't
covered by a tutorial yet.  For example, the `awk` command.

**Comment by monti004** [comment]
so could i do a tutorial on using and mastering the find command?

**Comment by mikeizbicki** [comment]
Sure!

**Comment by monti004** [comment]
ok :)
