### ISSUE TITLE
Hwk4 comparison function  in sorting

### ISSUE THREAD

**Issue by jsun031** [mikeizbicki/ucr-cs100#962]
In hw1, we are required to sort our display. It would display names with dots only first, and then other names alphabetically. To use sort function form standard library, we need a compare function to pick one with higher priority from two strings. However, the standard compare function less<string> sort string be their ANSCII order. Thus, we need to write a new one ourselves. I would like to write a tutorial about how to write a compare function to make our sort function work.

In tutorial, I would like to stress two processes. The first one is how to change upper case letters into lower case letter by using addition and subtraction in char type. I would describe how it works. The second one is to sort string ignoring other symbols like bracket. Both processes convert the original char arrays to new ones for comparison. I would like to show the difference between copying them to new arrays and operating by pointers.

**Comment by mikeizbicki** [comment]
Sounds great!  You will probably also need to cover the difference between function pointers (C) and functors (C++) to do this.

**Comment by jsun031** [comment]
Hi Mike,

I have my draft here under my repository forked from our class https://github.com/jsun031/ucr-cs100/tree/hwk4/textbook/assignment-help/sort. Could you give me some advice to improve my work?

Thank you!
