### ISSUE TITLE
HW4 Topic

### ISSUE THREAD

**Issue by abenc** [mikeizbicki/ucr-cs100#963]
The topic of my project is to write a Windows Phone application from scratch, and each step of the application will be explained to be a tutorial of creating a Windows Phone application.

The theme of the application will be a "Walk your dog" community where dog owners will be able to find  walkers :) 

the tuto/application will cover : 

-setting up fastly Windows Phone SDK 8.1
-How to create quick and refined UI using XAML
-How to create a member area using MySQL or develop a small api using JSON 
-How to create a feed

Team members: Anir Ben Chabane , Hermance Dornier

**Comment by mikeizbicki** [comment]
I suspect this will be too much work to do well, and so is not a good project.  If you really want to do this, then talk to me after class.
