### ISSUE TITLE
HW4 Topic

### ISSUE THREAD

**Issue by linuxmotion** [mikeizbicki/ucr-cs100#965]
I would like to expand on using git. Lab1 illustrates usage of basic git commands but lacks depth for advanced usage. I would like to extend the tutorials in https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/tools/git/advanced-git on using git from basic to more advanced uses to specifically include usage of the following commands. These following commands were very crucial to my understanding of git when if first learned how to use it.
- Remotes
  - Extended options
- Reviewing history:
  - log
    - Extended options
  - diff
- Merging:
  - Mergetool
  - stash
- Rewriting history:
  - Rebasing
- Patching:
  - Cherry-picking
  - format-patch
  - apply 
- Workflow:
  - What is a workflow
  - A workflow example

If these sections were given a thorough guide, entry level git users could easily become a more advanced git user able create, maintain, and improve projects across multiple forks.

**Comment by mikeizbicki** [comment]
This sounds awesome!  But please remember that it is better to do a small number of topics in depth than to do a large number of topics shallowly.  If you look at the [advanced git tutorial](https://github.com/mikeizbicki/ucr-cs100/tree/2015winter/textbook/tools/git/advanced-git), it's basically just the output of `--help` for each of the commands, and so I wasn't very happy with it.

The best way to do this is to create something like a lab1 that is interactive and the reader can follow along by typing in the commands themselves.  A good extension to lab1 that is just as detailed and covers all the commands you mentioned above would be worth about 200 points, but you'd have to show me a number of drafts as your working so I can make sure it's on the right track.
