### ISSUE TITLE
HW4 topic

### ISSUE THREAD

**Issue by Wurmie** [mikeizbicki/ucr-cs100#967]
I'm not sure if someone already took the project, but I would like to do a Makefile tutorial. The one already written was very confusing and did not help at all when I was writing my Makefile.

**Comment by mikeizbicki** [comment]
See #942.  I agree the one already written needs a lot of work.  I'd be open to having two people work on this, but I'd have very high expectations for the final result.  

If you do want to work on this, please reply to issue #942 and work it out with @SpaceCowboy100 .
