### ISSUE TITLE
Hw4 Topic

### ISSUE THREAD

**Issue by cyang032** [mikeizbicki/ucr-cs100#969]
We want to make a tutorial on strace to show how it can be used to debug system calls. We thought it'd be helpful since we use system calls a lot, and when used together with perror, it would provide more useful information to the programmer.

Claire Yang(cyang032) and Valerie Chiou(valeriechiou)

**Comment by mikeizbicki** [comment]
This has a lot of potential to be amazing.  Can you say a bit more about the examples you'll be using?  Also, you should definitely look at `ptrace` and `ltrace` as well even if you don't write about them.
