### ISSUE TITLE
HW 4 Topic Proposal

### ISSUE THREAD

**Issue by vhall415** [mikeizbicki/ucr-cs100#970]
I'd like to write a tutorial on the C++14 standards. I noticed there was a tutorial on the C++11 standards and I'd like to discuss the further additions with C++14.

**Comment by mikeizbicki** [comment]
Which specific aspects of C++14?  Remember that it's better to go into detail on a small amount than to be vague about lots of things.

**Comment by vhall415** [comment]
I'd like to cover the expansion of auto (use in return type deduction), the deprecated attribute, binary literals and digit separators, improvements on lambda functions, variable templates, standard user-defined literals, and improvements on the std::tuple type. Some of these items I don't think will need much explanation (like the variable templates and standard user-defined literals) so they will go in their own section so people will know they are available.

**Comment by mikeizbicki** [comment]
There is a major danger in this topic of covering too many things too shallowly.  Try to keep your examples focused on how they specifically can be used to solve problems encountered in the homeworks and labs.

**Comment by Anthony1234567** [comment]
I would like to contribute to this tutorial #970. We can get into detail about more aspects of C++14 specifically I would like to cover how C++14 is intended to be a "small extension" of the C++11 standard by going into how it improves on the standard.

topics including but not limited to:
1. Variable templates
2. Binary literals
3. Digit separators
4. relaxed restrictions on constexpr

I would also like to go into some of the new features
1. Standard user-defined literals
2. Tuple addressing via type

giving a detailed explanation of each of the mentioned topics focusing on the benefits of each providing examples as well. This will be a fun learning experience and an opportunity to add on to the repo

**Comment by vhall415** [comment]
Between the two of us I think we can cover most of the topics but we can start by selecting a few of the topics to research and discuss thoroughly and then include others as we go along if we have the time.
