### ISSUE TITLE
Proposing group effort on HW4

### ISSUE THREAD

**Issue by Anthony1234567** [mikeizbicki/ucr-cs100#971]
I would like to contribute to this tutorial #970. We can get into detail about more aspects of C++14 specifically I would like to cover how C++14 is intended to be a "small extension" of the C++11 standard by going into how it improves on the standard.

topics including but not limited to:
1. Variable templates
2. Binary literals
3. Digit separators
4. relaxed restrictions on constexpr

I would also like to go into some of the new features
1. Standard user-defined literals
2. Tuple addressing via type

giving a detailed explanation of each of the mentioned topics focusing on the benefits of each providing examples as well. This will be a fun earning experience for me and an opportunity to add on to the repo

**Comment by mikeizbicki** [comment]
Sounds good.  Please reply directly to #970 so that all the info is in one place.
