### ISSUE TITLE
HW4 Topic - Manga Tracker

### ISSUE THREAD

**Issue by svtanthony** [mikeizbicki/ucr-cs100#973]
### Purpose

I like to read manga, but dislike that some websites update faster than others which would require that I search multiple sites to find the a new release or wait. The solution is to wait, search various sites or automate that process. I dislike waiting and having limited time, so I'd rather read manga than search for it, leaving automation as a solution. I want to create this automation using the UNIX philosophy where you combine simple tools to create something complicated. As such my implementation will be done in BASH scripting, I would reference the student that is working on the bash shell cheat sheet (issue #957) where appropriate. I also want others to benefit from my work, whether though knowledge or simply by having a useful tool.
### Features
- Track manga series from at least 5 sources with instructions on adding more (wget)
- Receive a text or email when there's an update (mail)
- Command line interface 
- Ability to download chapters 
- Instructions on the following:
  1. Setting up timing features , ie how often to check and when not to check (crontab)
  2. Setting up permissions of scripts (chmod)
  3. Set phone number and an email address ex. (phonenumber@messaging.sprintpcs.com)
  4. Set up mailing client(ssmtp)

**Comment by mikeizbicki** [comment]
Sounds great.  Is there a specific format (e.g. RSS, XML) that Manga sources normally use?  If so, this seems like a straightforward implementation of an RSS reader in bash, which is awesome.  If not, this seems like it could be rather difficult.

**Comment by mikeizbicki** [comment]
By the next deadline, I would expect you to be able to download and parse the contents of at least one source.  The interface and timing features can wait until after that's done.

**Comment by svtanthony** [comment]
The sites I am considering would required html parsing, only one had an RSS
feed. As most sites hosting manga have the latest episode in the top of the
page I could extract it with some regular expressions and piping to head.

**Comment by mikeizbicki** [comment]
Okay.  This will be a relatively hard project since they don't use a standard format.  But if you're confident, then I'll approve it!

**Comment by svtanthony** [comment]
Thanks.

**Comment by svtanthony** [comment]
Here is my github repository with the milestones requested.
https://github.com/svtanthony/manga-tracker.git

download images
download.sh works with mangapanda and is called by giving the url of the first page page to parse
ex "./download http://www.mangapanda.com/fuuka/51"

check for updates
updates.sh works with the files containing links to a website and users, Links and Contact respectively.
this just script just needs to be called and will be set up to run through crontab

**Comment by svtanthony** [comment]
I have incorporated all the suggestions to this project. If there's any further changes required please let me know.

Changes include:
- consolidating scripts
- configurations section in script
- clarity improvements
