### ISSUE TITLE
hw1-grade question

### ISSUE THREAD

**Issue by jinhangwang** [mikeizbicki/ucr-cs100#975]
I got 20 on hw1 with the extra point but no grading detail message yet, which means I may got only 5 points on the basic job. I tested all my testcases on hammer and did cppcheck and valgrind again, there is no error with the result as well se the cppcheck and no leak with valgrind. I was wondering which part took away the points.

**Comment by mikeizbicki** [comment]
The TAs are still in the process of getting the rest of your grade uploaded.
