### ISSUE TITLE
Office hours: do they exist?

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#977]
I feel my HW1 was mis-graded, so I went to the front page of the repo to look for office hours to talk to a TA or Mike, and found that only one of the TA's (Busra) has his hours listed. However, nowhere on the page could I find a location!

Do our TA's/Mike have office hours? If so, where and when?

**Comment by mikeizbicki** [comment]
I'm not sure where you looked, but the main course page has everyone's office hours listed: https://github.com/mikeizbicki/ucr-cs100#instructors

**Comment by scohe001** [comment]
Wow, that's entirely my fault, I was in my un-updated repository. Sorry about this!
