### ISSUE TITLE
hw4 topic

### ISSUE THREAD

**Issue by jkinc002** [mikeizbicki/ucr-cs100#979]
I plan on making a simple game where a player starts of having to manage a single line which is continuously spawing error characters (I'll be using 'X' as error chars). The game would become progressively harder as more strings are added and more X's spawn together, and end if any single line grows to be to big due to it's errors. I'll write this so it utilizes the same system of traversing and deleting code with vim; a sort of practice game for using vim.

**Comment by mikeizbicki** [comment]
This sounds too similar to the pacvim game that already exists.

**Comment by jkinc002** [comment]
did the pacvim game go beyond using the controls "h ,j ,k ,l"? I'm planning to implement a good chunk of available movements. think of the game literally as a piece of code you created suddenly spawning bad characters and you have to efficiently maneuver to them and delete them.

**Comment by mikeizbicki** [comment]
It did support more characters.  One of the hardest parts about doing a
game like this is getting the characters correct.

On second thought, there's a good chance you could implement this entirely
within vim via vimscript.  This would make it so you could play the game on
any document you have open (by typing the command `:JordansGame` in your
current window), and you wouldn't have to reimplement a bunch of vim
features.  I think that would be an amazingly popular game.

So if you're willing to make it a vim plugin using vimscript, then I'll
approve the project.

**Comment by jkinc002** [comment]
alright, I'll do it using vimscript.
