### ISSUE TITLE
HW4 - hypem desktop application

### ISSUE THREAD

**Issue by nevarez-emil** [mikeizbicki/ucr-cs100#980]
For my project, I want to create a desktop application for a music streaming site - www.hypem.com

So far I know of a project that has already done many of the things I would need to implement to get this working (found here: https://github.com/fzakaria). He has already created a python script to scrape the URLs of the songs from the site.

Using the URLs, I would use an audio streaming library like LIVE555 or IceCast to play the music. I'm sure there are other alternatives, but I have to do more research on the topic before I settle on anything.

Once I get music playing, I'll develop a UX for easy desktop accessibility. Ideally, it will be an unobtrusive microplayer that would rest on the dock. I'm not sure about UX development in C++, so if you know of any good way to approach it then I'd welcome the advice.

When everything above is working, I'll tackle the entire other issue of logging into the account on the site to enable favorites and the like.

**Comment by mikeizbicki** [comment]
Remember that in unix, we do not build monolithic programs.  We build small programs and connect them together.  So the first step should be to make it a command line utility that has all the functionality you want.  

For example, you would have a daemon that connects to the website and plays the songs (a daemon is just a program that runs in the background with no direct user interface).  Then you would write a program that sends commands to the daemon.  For example, you might call the program `hypem` and then to play a song, the command would be `hypem play songname` or to pause, it would be `hypem pause`.  Once you have all of that worked out, then you can try to build a gui that sits on top of the command line interface.

If you still want to do this project, my expectation is that by the next deadline your daemon would be able to play sounds on the sound card and you would have a simple program to send commands to the daemon.  Once you have that, the next phase is getting the login stuff working.
