### ISSUE TITLE
HW2 question

### ISSUE THREAD

**Issue by scohe001** [mikeizbicki/ucr-cs100#981]
For Extra Credit 1 where we handle strings for input redirection, do we need to handle escape characters in the string we're passed?

**Comment by mikeizbicki** [comment]
No, you can just pass the string directly.

**Comment by scohe001** [comment]
Thank you.

Also, is it safe to assume for the redirection operators (<, >, >>) that there will always be a space between them and the rest of the user input? (I know bash does this when you specify a file descriptor, but not if there isn't one)

**Comment by mikeizbicki** [comment]
I'm sure how to interpret what you're saying about bash.  But no, it is
never safe to assume anything :)
