### ISSUE TITLE
HW4 - replacement for script

### ISSUE THREAD

**Issue by M-Evans** [mikeizbicki/ucr-cs100#982]
It's not completely finished yet, but I believe my [replacement for script](https://github.com/M-Evans/bashAutotest) is ready to be tried. Please share your impression with me. Is there anything you'd like me to add? take away? fix?

**Comment by mikeizbicki** [comment]
I'll need you to demo this for me in person, but my first impression is
it's pretty close.

**Comment by M-Evans** [comment]
Would it be possible to demo it to you today or tomorrow? I am free until 2pm today, and after 9am on Friday.

**Comment by mikeizbicki** [comment]
I can meet you Friday at noon in WCH110

**Comment by M-Evans** [comment]
Sounds good. See you then!

**Comment by M-Evans** [comment]
It's currently 20 past noon. I'm in WCH 110. Has the meeting been cancelled? I'll wait here until 1:00pm

**Comment by mikeizbicki** [comment]
Hmm... sorry.  I was there at noon and waited for a few minutes, but then I
left.  I'm no longer on campus today, so we can meet during office hours
next week or after class.

**Comment by M-Evans** [comment]
I ran into Mr. Linard about 5 minutes before noon, and he let me into 110. 

I am not free during your Tuesday office hours, but am free from 12-2 on Tuesday. Can I meet with you at 12 on Tuesday?

**Comment by mikeizbicki** [comment]
I see.  I never actually went inside.  I was just waiting outside.

I usually stay quite a bit later on Tuesday, so 12 is definitely fine.

**Comment by M-Evans** [comment]
Is it still possible to have students try it out on the next assignment? 

If not, it can still be wrapped in `script` to create the required submission document.

e.g.

``` bash
script sc.script
bat tests/scTests
[does stuff here]
exit
```
