### ISSUE TITLE
HW4 Extra Credit

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#983]
Extra credit listed for HW4:
"If you visit the writing center, I will give you +5 points of extra credit on this assignment."

How do we prove to you that we visited the writing center? And do you suggest we go there with a draft prepared, or just with a basic outline of what we plan to write?

Thanks!

**Comment by mikeizbicki** [comment]
Just ask the writing center to give you some proof (like one of their cards filled out with your appointment info).  You should go with a complete first draft.  They won't know anything about the computer science parts (so won't be able to see if an outline is reasonable), but they will help you with wording and spelling/grammar issues.

Make sure to make an appointment soon, as they won't have any left near the end of the quarter.

**Comment by tristanzickovich** [comment]
Thanks!

Just called in, there is already roughly a two week delay (in case anyone else is considering making an appointment).
