### ISSUE TITLE
Valgrind and GNU ls (in bash)

### ISSUE THREAD

**Issue by tristanzickovich** [mikeizbicki/ucr-cs100#987]
I ran valgrind on GNU's ls (and ls with any flag) and received the following results: 

<pre>
tzick002@hammer $ valgrind ls
==19159== Memcheck, a memory error detector
==19159== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==19159== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==19159== Command: ls
==19159== 
a.out  bin  LICENSE  Makefile  README.md  src  tests
==19159== 
==19159== HEAP SUMMARY:
==19159==     in use at exit: 20,703 bytes in 13 blocks
==19159==   total heap usage: 48 allocs, 35 frees, 57,908 bytes allocated
==19159== 
==19159== LEAK SUMMARY:
==19159==    definitely lost: 0 bytes in 0 blocks
==19159==    indirectly lost: 0 bytes in 0 blocks
==19159==      possibly lost: 0 bytes in 0 blocks
==19159==    still reachable: 20,703 bytes in 13 blocks
==19159==         suppressed: 0 bytes in 0 blocks
==19159== Rerun with --leak-check=full to see details of leaked memory
==19159== 
==19159== For counts of detected and suppressed errors, rerun with: -v
==19159== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
~/Documents/rshell
</pre>

I found this when testing my HW0 (rshell), finding that the ls from my rshell produced the same results. Thinking it was an error in my code I was trying to find a fix for it.
I decided to run valgrind on GNU's ls to see what it looked like and found out it had the same result (shown above).

I would like to verify, for the upcoming assignments (since they build off of rshell), that these are known results for valgrind on ls, and that we won't be penalized for it. I tested the other commands we used for rshell (echo and pwd) and those were fine.

Thanks!

**Comment by mikeizbicki** [comment]
When running valgrind, I only care that the `definitely lost` section is zero, and that it reports no major errors.  The output you give looks fine.
