### ISSUE TITLE
HW1 Still Not Regraded

### ISSUE THREAD

**Issue by MiaoXiao** [mikeizbicki/ucr-cs100#992]
Hello, last Friday I went to both office hours to talk about why my HW1 assignment had warnings with Make even though it could compile on the lab machines. Busra ran my code to verify that my HW1 assignment indeed ran without any errors. According to both TAs, neither of them graded my assignment so I am unsure what happened.

I was told by Busra to post this as an issue if my HW was not regraded by Saturday, and it still has not been regraded.

**Comment by ghost** [comment]
Hi Rica,

That was my mistake, I was the one that originally graded your assignment. I'll regrade it shortly.

**Comment by busrac** [comment]
Rica, I had already regraded your assignment on Friday. Did you check it before posting?

Edited: My commits are not showing for some reason, that's why you couldn't see it even though I graded it.
