### ISSUE TITLE
calcgrade gives me error 

### ISSUE THREAD

**Issue by yuxli066** [mikeizbicki/ucr-cs100#995]
Running calcgrade in my terminal gives me output that say "syntax errors" and I cannot see my total grade points or my hw1 score.

**Comment by mikeizbicki** [comment]
You can always check your score on individual assignments by looking at the file manually.  

I can't diagnose your problem without seeing both the command you ran and the resulting output.  Maybe you can come to office hours and show me?

**Comment by yuxli066** [comment]
My grade does not show up under my forked repo either. I'll come to your office hours tomorrow to show you. Thanks

**Comment by nevarez-emil** [comment]
I'm having a similar issue, but I won't be able to make it to your regular office hours.

Could we meet up after class to discuss?
